### ISSUE TITLE
Reconcile logs and exception repeated with Brixton Eureka Client and Angel Eureka Server

### ISSUE THREAD

**Issue by seno5979** [spring-cloud/spring-cloud-netflix#1013]
I observed some compatibility issue between them. 
Can someone confirm that :
Eureka Client with Brixton.RC2 does not suppose to talk with Eureka Server with version Angel.SR6 ?

**Comment by spencergibb** [comment]
What issue are you seeing?

**Comment by spencergibb** [comment]
I can confirm it works.

**Comment by seno5979** [comment]
One issue I observed on client side:
1. The service (eureka client) is trying to re-register every 30 seconds
    Posibbly due to below issue :
```
09:57:48.738 [DiscoveryClient-HeartbeatExecutor-0] WARN  com.netflix.discovery.shared.transport.decorator.RetryableEurekaHttpClient - Request execution failure
09:57:48.739 [DiscoveryClient-CacheRefreshExecutor-0] WARN  com.netflix.discovery.DiscoveryClient - The reconcile string is 
09:57:48.739 [DiscoveryClient-CacheRefreshExecutor-0] WARN  com.netflix.discovery.DiscoveryClient - The Reconcile hashcodes after complete sync up, client : STARTING_1_UP_19_, server : STARTING_1_UP_21_.
09:57:48.741 [DiscoveryClient-HeartbeatExecutor-0] ERROR com.netflix.discovery.shared.transport.decorator.RedirectingEurekaHttpClient - Request execution error
javax.ws.rs.WebApplicationException
	at com.netflix.discovery.provider.DiscoveryJerseyProvider.readFrom(DiscoveryJerseyProvider.java:110) ~[eureka-client-1.4.6.jar:1.4.6]
	at com.sun.jersey.api.client.ClientResponse.getEntity(ClientResponse.java:634) ~[jersey-client-1.19.1.jar:1.19.1]
	at com.sun.jersey.api.client.ClientResponse.getEntity(ClientResponse.java:586) ~[jersey-client-1.19.1.jar:1.19.1]
	at com.netflix.discovery.shared.transport.jersey.AbstractJerseyEurekaHttpClient.sendHeartBeat(AbstractJerseyEurekaHttpClient.java:105) ~[eureka-client-1.4.6.jar:1.4.6]
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$3.execute(EurekaHttpClientDecorator.java:92) ~[eureka-client-1.4.6.jar:1.4.6]
	at com.netflix.discovery.shared.transport.decorator.MetricsCollectingEurekaHttpClient.execute(MetricsCollectingEurekaHttpClient.java:73) ~[eureka-client-1.4.6.jar:1.4.6]
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.sendHeartBeat(EurekaHttpClientDecorator.java:89) ~[eureka-client-1.4.6.jar:1.4.6]
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$3.execute(EurekaHttpClientDecorator.java:92) ~[eureka-client-1.4.6.jar:1.4.6]
	at com.netflix.discovery.shared.transport.decorator.RedirectingEurekaHttpClient.executeOnNewServer(RedirectingEurekaHttpClient.java:118) ~[eureka-client-1.4.6.jar:1.4.6]
	at com.netflix.discovery.shared.transport.decorator.RedirectingEurekaHttpClient.execute(RedirectingEurekaHttpClient.java:79) [eureka-client-1.4.6.jar:1.4.6]
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.sendHeartBeat(EurekaHttpClientDecorator.java:89) [eureka-client-1.4.6.jar:1.4.6]
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$3.execute(EurekaHttpClientDecorator.java:92) [eureka-client-1.4.6.jar:1.4.6]
	at com.netflix.discovery.shared.transport.decorator.RetryableEurekaHttpClient.execute(RetryableEurekaHttpClient.java:119) [eureka-client-1.4.6.jar:1.4.6]
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.sendHeartBeat(EurekaHttpClientDecorator.java:89) [eureka-client-1.4.6.jar:1.4.6]
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$3.execute(EurekaHttpClientDecorator.java:92) [eureka-client-1.4.6.jar:1.4.6]
	at com.netflix.discovery.shared.transport.decorator.SessionedEurekaHttpClient.execute(SessionedEurekaHttpClient.java:77) [eureka-client-1.4.6.jar:1.4.6]
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.sendHeartBeat(EurekaHttpClientDecorator.java:89) [eureka-client-1.4.6.jar:1.4.6]
	at com.netflix.discovery.DiscoveryClient.renew(DiscoveryClient.java:827) [eureka-client-1.4.6.jar:1.4.6]
	at com.netflix.discovery.DiscoveryClient$HeartbeatThread.run(DiscoveryClient.java:1383) [eureka-client-1.4.6.jar:1.4.6]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_45]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_45]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_45]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_45]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
```

2.

**Comment by spencergibb** [comment]
Any more to that stacktrace? It's not very helpful. Maybe a project that recreates the problem?

**Comment by seno5979** [comment]
Let me add more information that I dig before ;

I suspect the issue is related to the client detect different amount of UP instances. In my case client detect only 19 UP instances, but server detect 21.

There is one apps in my eureka server which is deployed on the same hostname, but different port:

My suspect is, there is different way on old version and new version to resolved the instanceId value :

The old one is by putting the instanceId under <metadataMap>, the new version is on <InstanceId>
```
<application>
<name>SIMPLE-ORIGIN-SERVICE</name>
<instance>
<hostName>devsand00113.example.com</hostName>
<app>SIMPLE-ORIGIN-SERVICE</app>
<ipAddr>10.51.30.0</ipAddr>
<status>UP</status>
<overriddenstatus>UNKNOWN</overriddenstatus>
<port enabled="true">8092</port>
<securePort enabled="false">443</securePort>
<countryId>1</countryId>
<dataCenterInfo class="com.netflix.appinfo.InstanceInfo$DefaultDataCenterInfo">
<name>MyOwn</name>
</dataCenterInfo>
<leaseInfo>
<renewalIntervalInSecs>5</renewalIntervalInSecs>
<durationInSecs>90</durationInSecs>
<registrationTimestamp>1462473050384</registrationTimestamp>
<lastRenewalTimestamp>1462846077421</lastRenewalTimestamp>
<evictionTimestamp>0</evictionTimestamp>
<serviceUpTimestamp>1462473048668</serviceUpTimestamp>
</leaseInfo>
<metadata>
<httpMethodsSupported>GET</httpMethodsSupported>
<instanceId>simple-origin-service-8092</instanceId>
<zone>dc3</zone>
</metadata>
<homePageUrl>http://devsand00113.example.com:8092/</homePageUrl>
<statusPageUrl>
http://devsand00113.example.com:8092/info
</statusPageUrl>
<healthCheckUrl>
http://devsand00113.example.com:8092/health
</healthCheckUrl>
<vipAddress>simple-origin-service</vipAddress>
<isCoordinatingDiscoveryServer>false</isCoordinatingDiscoveryServer>
<lastUpdatedTimestamp>1462473050384</lastUpdatedTimestamp>
<lastDirtyTimestamp>1462375159888</lastDirtyTimestamp>
<actionType>ADDED</actionType>
</instance>
<instance>
<hostName>devsand00113.example.com</hostName>
<app>SIMPLE-ORIGIN-SERVICE</app>
<ipAddr>10.51.30.0</ipAddr>
<status>UP</status>
<overriddenstatus>UNKNOWN</overriddenstatus>
<port enabled="true">8094</port>
<securePort enabled="false">443</securePort>
<countryId>1</countryId>
<dataCenterInfo class="com.netflix.appinfo.InstanceInfo$DefaultDataCenterInfo">
<name>MyOwn</name>
</dataCenterInfo>
<leaseInfo>
<renewalIntervalInSecs>5</renewalIntervalInSecs>
<durationInSecs>90</durationInSecs>
<registrationTimestamp>1462624611137</registrationTimestamp>
<lastRenewalTimestamp>1462846079435</lastRenewalTimestamp>
<evictionTimestamp>0</evictionTimestamp>
<serviceUpTimestamp>1462624611137</serviceUpTimestamp>
</leaseInfo>
<metadata>
<httpMethodsSupported>GET</httpMethodsSupported>
<instanceId>simple-origin-service-8094</instanceId>
<zone>dc3</zone>
</metadata>
<homePageUrl>http://devsand00113.example.com:8094/</homePageUrl>
<statusPageUrl>
http://devsand00113.example.com:8094/info
</statusPageUrl>
<healthCheckUrl>
http://devsand00113.example.com:8094/health
</healthCheckUrl>
<vipAddress>simple-origin-service</vipAddress>
<isCoordinatingDiscoveryServer>false</isCoordinatingDiscoveryServer>
<lastUpdatedTimestamp>1462624611137</lastUpdatedTimestamp>
<lastDirtyTimestamp>1462375190206</lastDirtyTimestamp>
<actionType>ADDED</actionType>
</instance>
</application>
```

**Comment by seno5979** [comment]
It's not easy to provide you a sample project since the issue is happens on multi nodes registering on the server.

**Comment by spencergibb** [comment]
The angel eureka server only understands instanceId from metadata, so all clients must set `eureka.instance.metadataMap.instanceId` if they are on the same host. If everything was brixton, you could just set ``eureka.instance.instanceId`.

**Comment by seno5979** [comment]
But the issue is not on server side. The client (Brixton.RC2) thought its only 19 UP, but server detect 21 UP, the gap 3 instance caused by the instance is share on the same hostname but put the instanceID on metadataMap

**Comment by spencergibb** [comment]
Are you referring to this line?
```
STARTING_1_UP_19_, server : STARTING_1_UP_21_
```

If so, there is no bug. At some point that client was at 19, next time it reconciled, it received 21. Both of those values come from the server. Besides the exception you saw is there anything actually wrong?

**Comment by seno5979** [comment]
yes. but it reconciled each 30 seconds.

**Comment by spencergibb** [comment]
So your concern is you see the reconciliation log statement every 30 seconds?

**Comment by seno5979** [comment]
yes and below exception is repeatly being print out every 30 second :
```
10:02:48.827 [DiscoveryClient-CacheRefreshExecutor-0] WARN  com.netflix.discovery.DiscoveryClient - The reconcile string is 
10:02:48.827 [DiscoveryClient-CacheRefreshExecutor-0] WARN  com.netflix.discovery.DiscoveryClient - The Reconcile hashcodes after complete sync up, client : STARTING_1_UP_18_, server : STARTING_1_UP_20_.
10:03:18.795 [DiscoveryClient-HeartbeatExecutor-0] ERROR com.netflix.discovery.shared.transport.decorator.RedirectingEurekaHttpClient - Request execution error
javax.ws.rs.WebApplicationException
	at com.netflix.discovery.provider.DiscoveryJerseyProvider.readFrom(DiscoveryJerseyProvider.java:110) ~[eureka-client-1.4.6.jar:1.4.6]
	at com.sun.jersey.api.client.ClientResponse.getEntity(ClientResponse.java:634) ~[jersey-client-1.19.1.jar:1.19.1]
	at com.sun.jersey.api.client.ClientResponse.getEntity(ClientResponse.java:586) ~[jersey-client-1.19.1.jar:1.19.1]
	at com.netflix.discovery.shared.transport.jersey.AbstractJerseyEurekaHttpClient.sendHeartBeat(AbstractJerseyEurekaHttpClient.java:105) ~[eureka-client-1.4.6.jar:1.4.6]
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$3.execute(EurekaHttpClientDecorator.java:92) ~[eureka-client-1.4.6.jar:1.4.6]
	at com.netflix.discovery.shared.transport.decorator.MetricsCollectingEurekaHttpClient.execute(MetricsCollectingEurekaHttpClient.java:73) ~[eureka-client-1.4.6.jar:1.4.6]
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.sendHeartBeat(EurekaHttpClientDecorator.java:89) ~[eureka-client-1.4.6.jar:1.4.6]
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$3.execute(EurekaHttpClientDecorator.java:92) ~[eureka-client-1.4.6.jar:1.4.6]
	at com.netflix.discovery.shared.transport.decorator.RedirectingEurekaHttpClient.executeOnNewServer(RedirectingEurekaHttpClient.java:118) ~[eureka-client-1.4.6.jar:1.4.6]
	at com.netflix.discovery.shared.transport.decorator.RedirectingEurekaHttpClient.execute(RedirectingEurekaHttpClient.java:79) [eureka-client-1.4.6.jar:1.4.6]
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.sendHeartBeat(EurekaHttpClientDecorator.java:89) [eureka-client-1.4.6.jar:1.4.6]
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$3.execute(EurekaHttpClientDecorator.java:92) [eureka-client-1.4.6.jar:1.4.6]
	at com.netflix.discovery.shared.transport.decorator.RetryableEurekaHttpClient.execute(RetryableEurekaHttpClient.java:119) [eureka-client-1.4.6.jar:1.4.6]
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.sendHeartBeat(EurekaHttpClientDecorator.java:89) [eureka-client-1.4.6.jar:1.4.6]
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$3.execute(EurekaHttpClientDecorator.java:92) [eureka-client-1.4.6.jar:1.4.6]
	at com.netflix.discovery.shared.transport.decorator.SessionedEurekaHttpClient.execute(SessionedEurekaHttpClient.java:77) [eureka-client-1.4.6.jar:1.4.6]
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.sendHeartBeat(EurekaHttpClientDecorator.java:89) [eureka-client-1.4.6.jar:1.4.6]
	at com.netflix.discovery.DiscoveryClient.renew(DiscoveryClient.java:827) [eureka-client-1.4.6.jar:1.4.6]
	at com.netflix.discovery.DiscoveryClient$HeartbeatThread.run(DiscoveryClient.java:1383) [eureka-client-1.4.6.jar:1.4.6]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_45]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_45]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_45]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_45]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
10:03:18.795 [DiscoveryClient-HeartbeatExecutor-0] WARN  com.netflix.discovery.shared.transport.decorator.RetryableEurekaHttpClient - Request execution failure
10:03:18.795 [DiscoveryClient-HeartbeatExecutor-0] ERROR com.netflix.discovery.DiscoveryClient - DiscoveryClient_GEOLOCATION-SERVICE/ssetiadi-thinkpad-w540.taipei.digitalriver.com:geolocation-service:8080 - was unable to send heartbeat!
com
```

**Comment by spencergibb** [comment]
I'm unable to replicate that error.

**Comment by spencergibb** [comment]
I see these logs repeated
```
2016-05-09 21:06:38.746  WARN 82146 --- [freshExecutor-0] com.netflix.discovery.DiscoveryClient    : The Reconcile hashcodes do not match, client : UP_1_, server : UP_2_. Getting the full registry
2016-05-09 21:06:38.750  WARN 82146 --- [freshExecutor-0] com.netflix.discovery.DiscoveryClient    : The reconcile string is 
2016-05-09 21:06:38.750  WARN 82146 --- [freshExecutor-0] com.netflix.discovery.DiscoveryClient    : The Reconcile hashcodes after complete sync up, client : UP_1_, server : UP_2_.
```

**Comment by ouaibsky** [comment]
Hi

I'm facing same issues wuth Brixton.RELEASE,
I'm sure that my µServices are not registering/un-registering at this rate in eureka

My setup is a cluster of 2 eureka, but coming with Angel.SR4, I'll do a test by upgrading them to Brixton

each 30s I got

> 2016-05-18 10:18:56.360  WARN [onyx-walkway,,,] 35320 --- [freshExecutor-0] com.netflix.discovery.DiscoveryClient    : The reconcile string is 
>2016-05-18 10:18:56.361  WARN [onyx-walkway,,,] 35320 --- [freshExecutor-0] com.netflix.discovery.DiscoveryClient    : The Reconcile hashcodes after complete sync up, client : UP_27_, server : UP_28_.
> 2016-05-18 10:19:26.446  WARN [onyx-walkway,,,] 35320 --- [freshExecutor-0] com.netflix.discovery.DiscoveryClient    : The Reconcile hashcodes do not match, client : UP_27_, server : UP_28_. Getting the full registry

**Comment by aivans** [comment]
@ouaibsky Please keep us posted.

I guess a lot of people are in the same boat. We also installed Eureka a while ago and did not upgraded it regularly as it just worked.
Spring Cloud project is still relatively new, so we need to adjust along the way.

**Comment by dsyer** [comment]
#978 has some analysis as well (slightly more detail). So this is a duplicate.

**Comment by ouaibsky** [comment]
OK, I'm following #978  now
But before upgrading eureka server to Brixton I need to make sure my other clients (Angel) are still working with eureka server (brixton)
Christophe

**Comment by keyhan** [comment]
I have the same issue, it did not help to upgrade both server and client to latest eureka.

**Comment by dsyer** [comment]
Did you notice this issue is closed (as a duplicate)?
