### ISSUE TITLE
IllegalStateException thrown when ribbonRestClient gets destroyed

### ISSUE THREAD

**Issue by sslavic** [spring-cloud/spring-cloud-netflix#1014]
After upgrade of spring-cloud-netflix from 1.1.0.M5 to 1.1.0.RC1 or 1.1.0.RC2 my test logs got polluted with IllegalStateException being thrown every time context is closed and ribbonRestClient bean destroyed. Here's an example snippet, with DEBUG logging turned on:

```
15:02:04 [DEBUG] [o.s.b.f.s.DisposableBeanAdapter] [] Invoking destroy method 'shutdown' on bean with name 'ribbonRestClient'
15:02:04 [INFO ] [c.n.u.c.ShutdownEnabledTimer] [] Shutdown hook removed for: NFLoadBalancer-PingTimer-foo_service
15:02:04 [INFO ] [c.n.u.c.ShutdownEnabledTimer] [] Exception caught (might be ok if at shutdown)
java.lang.IllegalStateException: Shutdown in progress
	at java.lang.ApplicationShutdownHooks.remove(ApplicationShutdownHooks.java:82)
	at java.lang.Runtime.removeShutdownHook(Runtime.java:239)
	at com.netflix.util.concurrent.ShutdownEnabledTimer.cancel(ShutdownEnabledTimer.java:70)
	at com.netflix.loadbalancer.BaseLoadBalancer.cancelPingTask(BaseLoadBalancer.java:599)
	at com.netflix.loadbalancer.BaseLoadBalancer.shutdown(BaseLoadBalancer.java:897)
	at com.netflix.loadbalancer.DynamicServerListLoadBalancer.shutdown(DynamicServerListLoadBalancer.java:375)
	at com.netflix.niws.client.http.RestClient.shutdown(RestClient.java:725)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.DisposableBeanAdapter.invokeCustomDestroyMethod(DisposableBeanAdapter.java:354)
```

**Comment by sslavic** [comment]
In RC1 and RC2, ribbon dependencies got upgraded (to 2.1.3 and 2.1.5 respectively), but downgrading them to 2.1.0, which was used in M5, did not eliminate the unwanted behavior.

**Comment by sslavic** [comment]
This issue was moved to spring-cloud/spring-cloud-commons#111
