### ISSUE TITLE
RestTemplate HttpMethod.PATCH Invalid

### ISSUE THREAD

**Issue by rbkumar88** [spring-cloud/spring-cloud-netflix#1022]
Hi,

Am having my Zuul/Consul/Ribbon combo running and I have two services. One which sends PATCH request to other(Spring Data Rest)

Code Snippets
```
Config class
@LoadBalanced
	@Bean
	RestTemplate restTemplate() {
		return new RestTemplate();
	}

MyCallingClass

@Autowired
	private RestTemplate restTemplate;

	@PostConstruct
	public void testingOnly() {
//		This is just making sure we have got the restTemplate from Consul/Ribbon LB right
		System.out.println("The RestTemplate request factory is "
				+ restTemplate);
	}

restTemplate
				.exchange("http://"+dataUrl+dataPath, httpMethod, requestEntity, String.class);
```

Am running with spring.aop.proxyTargetClass=true and able to do GET and POST.
Sysout
```
The RestTemplate request factory is org.springframework.web.client.RestTemplate@
cd2cb2
```
Error stack
```
2016-05-11 12:42:26.767  INFO 48564 --- [           main] s.c.a.AnnotationConfig
ApplicationContext : Refreshing org.springframework.context.annotation.Annotatio
nConfigApplicationContext@d28235: startup date [Wed May 11 12:42:26 MST 2016]; p
arent: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebAppl
icationContext@1768776
2016-05-11 12:42:26.840  INFO 48564 --- [           main] f.a.AutowiredAnnotatio
nBeanPostProcessor : JSR-330 'javax.inject.Inject' annotation found and supporte
d for autowiring
2016-05-11 12:42:26.989  INFO 48564 --- [           main] c.netflix.config.Chain
edDynamicProperty  : Flipping property: profiledata.ribbon.ActiveConnectionsLimi
t to use NEXT property: niws.loadbalancer.availabilityFilteringRule.activeConnec
tionsLimit = 2147483647
2016-05-11 12:42:27.045  INFO 48564 --- [           main] c.n.u.concurrent.Shutd
ownEnabledTimer    : Shutdown hook installed for: NFLoadBalancer-PingTimer-profi
ledata
2016-05-11 12:42:27.148  INFO 48564 --- [           main] c.netflix.loadbalancer
.BaseLoadBalancer  : Client:profiledata instantiated a LoadBalancer:DynamicServe
rListLoadBalancer:{NFLoadBalancer:name=profiledata,current list of Servers=[],Lo
ad balancer stats=Zone stats: {},Server stats: []}ServerList:null
2016-05-11 12:42:27.258  INFO 48564 --- [           main] c.netflix.config.Chain
edDynamicProperty  : Flipping property: profiledata.ribbon.ActiveConnectionsLimi
t to use NEXT property: niws.loadbalancer.availabilityFilteringRule.activeConnec
tionsLimit = 2147483647
2016-05-11 12:42:27.262  INFO 48564 --- [           main] c.n.l.DynamicServerLis
tLoadBalancer      : DynamicServerListLoadBalancer for client profiledata initia
lized: DynamicServerListLoadBalancer:{NFLoadBalancer:name=profiledata,current li
st of Servers=[PHXJ05376036.ads.aexp.com:8080],Load balancer stats=Zone stats: {
unknown=[Zone:unknown;  Instance count:1;       Active connections count: 0;
Circuit breaker tripped count: 0;       Active connections per server: 0.0;]
},Server stats: [[Server:PHXJ05376036.ads.aexp.com:8080;        Zone:UNKNOWN;
Total Requests:0;       Successive connection failure:0;        Total blackout s
econds:0;       Last connection made:Wed Dec 31 17:00:00 MST 1969;      First co
nnection made: Wed Dec 31 17:00:00 MST 1969;    Active Connections:0;   total fa
ilure count in last (1000) msecs:0;     average resp time:0.0;  90 percentile re
sp time:0.0;    95 percentile resp time:0.0;    min resp time:0.0;      max resp
 time:0.0;      stddev resp time:0.0]
]}ServerList:ConsulServerList{serviceId='profiledata', tag=null}
2016-05-11 12:42:28.208  INFO 48564 --- [pool-3-thread-1] c.netflix.config.Chain
edDynamicProperty  : Flipping property: profiledata.ribbon.ActiveConnectionsLimi
t to use NEXT property: niws.loadbalancer.availabilityFilteringRule.activeConnec
tionsLimit = 2147483647
org.springframework.web.client.ResourceAccessException: I/O error on PATCH reque
st for "http://profiledata/data/phones": Invalid HTTP method: PATCH; nested exce
ption is java.net.ProtocolException: Invalid HTTP method: PATCH
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.ja
va:607)
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java
:557)
        at org.springframework.web.client.RestTemplate.exchange(RestTemplate.jav
a:475)
        at org.springframework.web.client.RestTemplate$$FastClassBySpringCGLIB$$
aa4e9ed0.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:2
04)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation
.invokeJoinpoint(CglibAopProxy.java:720)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(
ReflectiveMethodInvocation.java:157)
        at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.p
roceed(MethodInvocationProceedingJoinPoint.java:85)
        at org.springframework.cloud.netflix.metrics.RestTemplateUrlTemplateCapt
uringAspect.captureUrlTemplate(RestTemplateUrlTemplateCapturingAspect.java:33)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMet
hodWithGivenArgs(AbstractAspectJAdvice.java:620)
        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMet
hod(AbstractAspectJAdvice.java:609)
        at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAro
undAdvice.java:68)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(
ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invok
e(ExposeInvocationInterceptor.java:92)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(
ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterce
ptor.intercept(CglibAopProxy.java:655)
        at org.springframework.web.client.RestTemplate$$EnhancerBySpringCGLIB$$5
460d769.exchange(<generated>)
        at com.gbt.connectprofile.ssloader.service.ProfileDataService.callProfil
eDataService(ProfileDataService.java:36)
        at com.gbt.connectprofile.ssloader.service.impl.CreateActionServiceImpl.
process(CreateActionServiceImpl.java:86)
        at com.gbt.connectprofile.ssloader.service.impl.SpreadsheetCoreServiceIm
pl.lambda$processUploadedSheet$0(SpreadsheetCoreServiceImpl.java:43)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:18
4)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:
193)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:
193)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:
193)
        at java.util.Iterator.forEachRemaining(Iterator.java:116)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterat
ors.java:1801)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)

        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.ja
va:471)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.j
ava:151)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEac
hOps.java:174)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)

        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418
)
        at com.gbt.connectprofile.ssloader.service.impl.SpreadsheetCoreServiceIm
pl.processUploadedSheet(SpreadsheetCoreServiceImpl.java:40)
        at com.gbt.connectprofile.ssloader.controllers.FileUploadController.file
Upload(FileUploadController.java:28)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvok
e(InvocableHandlerMethod.java:221)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeF
orRequest(InvocableHandlerMethod.java:136)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocabl
eHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingH
andlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:817)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingH
andlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:731)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapt
er.handle(AbstractHandlerMethodAdapter.java:85)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(Dispatch
erServlet.java:959)
        at org.springframework.web.servlet.DispatcherServlet.doService(Dispatche
rServlet.java:893)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(Frame
workServlet.java:968)
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServ
let.java:870)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:648)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkSer
vlet.java:844)
        at org.springframework.test.web.servlet.TestDispatcherServlet.service(Te
stDispatcherServlet.java:65)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
        at org.springframework.mock.web.MockFilterChain$ServletFilterProxy.doFil
ter(MockFilterChain.java:167)
        at org.springframework.mock.web.MockFilterChain.doFilter(MockFilterChain
.java:134)
        at org.springframework.test.web.servlet.MockMvc.perform(MockMvc.java:155
)
        at com.gbt.connectprofile.ssloader.controllers.FileUploadControllerTest.
readString(FileUploadControllerTest.java:49)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(Framework
Method.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCal
lable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMe
thod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMet
hod.java:17)
        at org.springframework.test.context.junit4.statements.RunBeforeTestMetho
dCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
        at org.springframework.test.context.junit4.statements.RunAfterTestMethod
Callbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
        at org.springframework.test.context.junit4.statements.SpringRepeat.evalu
ate(SpringRepeat.java:84)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runCh
ild(SpringJUnit4ClassRunner.java:254)
        at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runCh
ild(SpringJUnit4ClassRunner.java:89)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.springframework.test.context.junit4.statements.RunBeforeTestClass
Callbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
        at org.springframework.test.context.junit4.statements.RunAfterTestClassC
allbacks.evaluate(RunAfterTestClassCallbacks.java:70)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(S
pringJUnit4ClassRunner.java:193)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provide
r.java:283)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUni
t4Provider.java:173)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4
Provider.java:153)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider
.java:128)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameCla
ssLoader(ForkedBooter.java:203)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(Fork
edBooter.java:155)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:
103)
Caused by: java.net.ProtocolException: Invalid HTTP method: PATCH
        at java.net.HttpURLConnection.setRequestMethod(HttpURLConnection.java:44
0)
        at sun.net.www.protocol.http.HttpURLConnection.setRequestMethod(HttpURLC
onnection.java:519)
        at org.springframework.http.client.SimpleClientHttpRequestFactory.prepar
eConnection(SimpleClientHttpRequestFactory.java:217)
        at org.springframework.http.client.SimpleClientHttpRequestFactory.create
Request(SimpleClientHttpRequestFactory.java:138)
        at org.springframework.http.client.InterceptingClientHttpRequest$Interce
ptingRequestExecution.execute(InterceptingClientHttpRequest.java:88)
        at org.springframework.cloud.client.loadbalancer.LoadBalancerInterceptor
$1.apply(LoadBalancerInterceptor.java:54)
        at org.springframework.cloud.client.loadbalancer.LoadBalancerInterceptor
$1.apply(LoadBalancerInterceptor.java:1)
        at org.springframework.cloud.netflix.ribbon.RibbonLoadBalancerClient.exe
cute(RibbonLoadBalancerClient.java:89)
        at org.springframework.cloud.client.loadbalancer.LoadBalancerInterceptor
.intercept(LoadBalancerInterceptor.java:46)
        at org.springframework.http.client.InterceptingClientHttpRequest$Interce
ptingRequestExecution.execute(InterceptingClientHttpRequest.java:85)
        at org.springframework.cloud.netflix.metrics.MetricsClientHttpRequestInt
erceptor.intercept(MetricsClientHttpRequestInterceptor.java:65)
        at org.springframework.http.client.InterceptingClientHttpRequest$Interce
ptingRequestExecution.execute(InterceptingClientHttpRequest.java:85)
        at org.springframework.http.client.InterceptingClientHttpRequest.execute
Internal(InterceptingClientHttpRequest.java:69)
        at org.springframework.http.client.AbstractBufferingClientHttpRequest.ex
ecuteInternal(AbstractBufferingClientHttpRequest.java:48)
        at org.springframework.http.client.AbstractClientHttpRequest.execute(Abs
tractClientHttpRequest.java:53)
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.ja
va:596)

```

Am using Latest Brixton.RELEASE (cloud-dependencies) which pulls spring-cloud-netflix-core-1.1.0.RELEASE.jar .. Anyway I can get this working. Either via some overriding the Rest template  or have LoadBalanced RestTemplate via ApacheClient etc.?

Thanks

**Comment by spencergibb** [comment]
What version of java are you using? That doesn't look like a Spring Cloud error. You can construct a `RestTemplate` with a `ClientHttpRequestFactory` like `HttpComponentsClientHttpRequestFactory` (which uses apache http client.) or `OkHttpClientHttpRequestFactory` (which uses OkHttp).

**Comment by spencergibb** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
