### ISSUE TITLE
@FeignClient annotation is not compatible with org.springframework.core.annotation.AnnotationUtils.findAnnotation()

### ISSUE THREAD

**Issue by tjuchniewicz** [spring-cloud/spring-cloud-netflix#1025]
Current definition of `@FeignClient`:
```
public @interface FeignClient {

    @AliasFor("name")
    String value() default "";

    @Deprecated
    @AliasFor("value")
    String serviceId() default "";

    @AliasFor("value")
    String name() default "";
```

causes `org.springframework.core.annotation.AnnotationUtils.findAnnotation()` to fail during attribute validation with exception:

Attribute [value] in annotation [org.springframework.cloud.netflix.feign.FeignClient] must be declared as an @AliasFor [serviceId], not [name].

Full stacktrace:
```
org.springframework.core.annotation.AnnotationConfigurationException: Attribute [value] in annotation [org.springframework.cloud.netflix.feign.FeignClient] must be declared as an @AliasFor [serviceId], not [name].
        at org.springframework.core.annotation.AnnotationUtils$AliasDescriptor.validate(AnnotationUtils.java:1991)
        at org.springframework.core.annotation.AnnotationUtils$AliasDescriptor.from(AnnotationUtils.java:1937)
        at org.springframework.core.annotation.AnnotationUtils.getAttributeAliasNames(AnnotationUtils.java:1626)
        at org.springframework.core.annotation.AnnotationUtils.getAttributeAliasMap(AnnotationUtils.java:1539)
        at org.springframework.core.annotation.AbstractAliasAwareAnnotationAttributeExtractor.<init>(AbstractAliasAwareAnnotationAttributeExtractor.java:66)
        at org.springframework.core.annotation.DefaultAnnotationAttributeExtractor.<init>(DefaultAnnotationAttributeExtractor.java:46)
        at org.springframework.core.annotation.AnnotationUtils.synthesizeAnnotation(AnnotationUtils.java:1372)
        at org.springframework.core.annotation.AnnotationUtils.findAnnotation(AnnotationUtils.java:685)
        at org.springframework.core.annotation.AnnotationUtils.findAnnotation(AnnotationUtils.java:660)
```

Probably fix in spring-core is the only solution?

**Comment by spencergibb** [comment]
@tjuchniewicz What version are you using? We have unit tests that run where they don't fail like this?

**Comment by tjuchniewicz** [comment]
I use Spring Cloud Brixton.RELEASE. It includes spring-core-4.2.6.RELEASE.jar (AnnotationUtils) and spring-cloud-netflix-core-1.1.0.RELEASE.jar (@FeignClient).

See my test case: https://github.com/tjuchniewicz/tests/tree/master/feign-annotation-test

**Comment by tjuchniewicz** [comment]
It works with Spring 4.1.9.RELEASE.

**Comment by dsyer** [comment]
I don't think the test is very faithful (`@FeignClient` is an interface annotation), and there are no failures in spring-cloud-netflix, which uses Spring 4.2.6 as well. Can you construct a better test case that shows a problem in one library or the other?

P.S. I do wonder why the `@AliasFors` point at each other (it looks circular), but that might be unrelated.

**Comment by tjuchniewicz** [comment]
@dsyer `@FeignClient` uses `@AliasFor` from Spring and is not compatible with verification mechanism of `@AliasFor` used in Spring. In other words uses `@AliasFor` in wrong way. This is not only informational annotation. It is also used at runtime in some cases. Problem here is `@Deprecated` attribute that is not properly used by Spring. I understand intention of `@FeignClient`. This attribute could be omitted by Spring during validation.

About circular dependencies: This is how aliases work. Aliased attributes points each other.

More real life example: I'm using Spring Boot. I want to create some additional health stats. When I invoke standard for Spring method:

```
applicationContext.getBeansWithAnnotation(FeignClient.class);
```
I get an exception:

```
at org.springframework.core.annotation.AnnotationUtils$AliasDescriptor.validate(AnnotationUtils.java:1991)
at org.springframework.core.annotation.AnnotationUtils$AliasDescriptor.from(AnnotationUtils.java:1937)
at org.springframework.core.annotation.AnnotationUtils.getAttributeAliasNames(AnnotationUtils.java:1626)
at org.springframework.core.annotation.AnnotationUtils.getAttributeAliasMap(AnnotationUtils.java:1539)
at org.springframework.core.annotation.AbstractAliasAwareAnnotationAttributeExtractor.<init>(AbstractAliasAwareAnnotationAttributeExtractor.java:66)
at org.springframework.core.annotation.DefaultAnnotationAttributeExtractor.<init>(DefaultAnnotationAttributeExtractor.java:46)
at org.springframework.core.annotation.AnnotationUtils.synthesizeAnnotation(AnnotationUtils.java:1372)
at org.springframework.core.annotation.AnnotationUtils.findAnnotation(AnnotationUtils.java:685)
at org.springframework.core.annotation.AnnotationUtils.findAnnotation(AnnotationUtils.java:660)
at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAnnotationOnBean(DefaultListableBeanFactory.java:597)
at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanNamesForAnnotation(DefaultListableBeanFactory.java:562)
at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeansWithAnnotation(DefaultListableBeanFactory.java:576)
at org.springframework.context.support.AbstractApplicationContext.getBeansWithAnnotation(AbstractApplicationContext.java:1184)
```

**Comment by dsyer** [comment]
Thanks for the clarification. I raised a ticket in Spring: https://jira.spring.io/browse/SPR-14280.
