### ISSUE TITLE
411 Content Length required issue

### ISSUE THREAD

**Issue by beku8** [spring-cloud/spring-cloud-netflix#1042]
For some reason, my home ISP throws ```411 Content length required``` error when I try to post something to the cloud rest endpoint thru locally running zuul proxy. 
So I tried setting ```content-length``` header manually from a custom filter like:
```ctx.addZuulRequestHeader("content-length", ctx.getRequest().getHeader("Content-Length"));```

But it throws 
```
com.netflix.zuul.exception.ZuulException: Forwarding error...
Caused by: org.apache.http.ProtocolException: Content-Length header already present
	at org.apache.http.protocol.RequestContent.process(RequestContent.java:95)
	at org.apache.http.protocol.ImmutableHttpProcessor.process(ImmutableHttpProcessor.java:131)
	at org.apache.http.protocol.HttpRequestExecutor.preProcess(HttpRequestExecutor.java:165)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:485)
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:863)
```

I'm using Zuul 1.0.28. Am I doing anything wrong? I'm not even sure if the original problem would disappear if I manage to set this header manually. Any suggestion, anything would be very much appreciated.

p.s: ISP allows my post request when its done thru Feign.

This issue is originally posted at https://github.com/Netflix/zuul/issues/223.

**Comment by spencergibb** [comment]
I'm unsure what you are saying is happening? You have some kind of proxy at home that requests go through?

**Comment by beku8** [comment]
No. We have our microservices deployed to the cloudfoundry and we connect to it using locally running zuul to develop the UI section. For some weird reason one of the main ISP in our country (Mongolia) throws 411 error.
Anyways I'm just trying to set the Content-Lenght header manually, hoping this will fix the problem. Probably this is more related to apache's http library?

**Comment by beku8** [comment]
Hello @spencergibb, I just investigated the /trace endpoint to see whats going on with this issue. 

Here's the request from browser to the server:
```
info: {
  method: "PUT",
  path: "/api/core/rest/location/amarbayasgalant",
  headers: {
    request: {
      host: "localhost:9000",
      connection: "keep-alive",
      content-length: "663",
      pragma: "no-cache",
      cache-control: "no-cache",
      authorization: "...authorization omitted",
      accept: "application/json, text/plain, */*",
      origin: "http://localhost:9000",
      user-agent: "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.63 Safari/537.36",
      content-type: "application/json;charset=UTF-8",
      referer: "http://localhost:9000/manage/mn/reference/location",
      accept-encoding: "gzip, deflate, sdch",
      accept-language: "en-US,en;q=0.8,bg;q=0.6,ru;q=0.4",
      cookie: "....cookie values omitted..."
    },
    response: {...response omitted...}
  }
}
```
Well it this point browser sends the content-length properly, but from zuul server to the microservice, content-length is not being sent.

```
info: {
  method: "PUT",
  path: "/rest/location/amarbayasgalant",
  query: "?_t=mn",
  remote: true,
  proxy: "api/core",
  headers: {
    request: {
      accept: "application/json, text/plain, */*",
      origin: "http://localhost:9000",
      user-agent: "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.63 Safari/537.36",
      content-type: "application/json;charset=UTF-8",
      referer: "http://localhost:9000/manage/mn/reference/location",
      accept-language: "en-US,en;q=0.8,bg;q=0.6,ru;q=0.4",
      authorization: "...Bearer token omitted",
      x-forwarded-host: "localhost",
      x-forwarded-proto: "http",
      x-forwarded-prefix: "/api/core",
      x-forwarded-port: "9000",
      x-forwarded-for: "127.0.0.1",
      Accept-Encoding: "gzip"
    },
    response: {
      Server: "httppd",
      Date: "Wed, 15 Jun 2016 11:30:35 GMT",
      Content-Type: "text/html",
      Content-Length: "3892",
      Connection: "close",
      status: "411"
    }
  },
  body: "... json body omitted"
}
```
I don't know if this is a problem with the zuul, spring cloud or apache httpd.

**Comment by spencergibb** [comment]
If zuul isn't sending the content-length, then it's not a problem with your ISP. Is there a possibility of sharing a sample project that recreates the problem?

**Comment by beku8** [comment]
I just created a sample app https://github.com/beku8/zuul-411. Which you probably don't need to see, just a spring starter project with zuul enabled, and proxies a post method to httpbin. 
Zuul411Application.java
```
@SpringBootApplication
@EnableZuulProxy
@Controller
public class Zuul411Application {
	public static void main(String[] args) {
		SpringApplication.run(Zuul411Application.class, args);
	}
	@RequestMapping
	public String index(){
		return "index";
	}
}
```
index.html
```
        <form th:action="@{/api/post}" method="post">
            <input type="submit" value="Post to httpbin"/>
        </form>
```
application.yml
```
zuul:
  ignoredServices: '*'
  routes:
    httpbin: 
      path: /api/**
      url: http://httpbin.org
```

with this sample app if we look at the /trace, same problem: content-length is not set when posting to ```httpbin.org/post```.

I think because most of the ISPs don't "require" content-length, this issue was not looked at before.

**Comment by spencergibb** [comment]
In your sample I see `Content-Length` being set
```
2016-06-16 12:33:22.088 DEBUG 13144 --- [nio-8080-exec-1] h.i.c.PoolingHttpClientConnectionManager : Connection request: [route: {}->http://httpbin.org:80][total kept alive: 0; route allocated: 0 of 20; total allocated: 0 of 200]
2016-06-16 12:33:22.099 DEBUG 13144 --- [nio-8080-exec-1] h.i.c.PoolingHttpClientConnectionManager : Connection leased: [id: 0][route: {}->http://httpbin.org:80][total kept alive: 0; route allocated: 1 of 20; total allocated: 1 of 200]
2016-06-16 12:33:22.101 DEBUG 13144 --- [nio-8080-exec-1] o.a.http.impl.execchain.MainClientExec   : Opening connection {}->http://httpbin.org:80
2016-06-16 12:33:22.515 DEBUG 13144 --- [nio-8080-exec-1] .i.c.DefaultHttpClientConnectionOperator : Connecting to httpbin.org/23.22.14.18:80
2016-06-16 12:33:22.585 DEBUG 13144 --- [nio-8080-exec-1] .i.c.DefaultHttpClientConnectionOperator : Connection established 192.168.2.160:54525<->23.22.14.18:80
2016-06-16 12:33:22.586 DEBUG 13144 --- [nio-8080-exec-1] h.i.c.DefaultManagedHttpClientConnection : http-outgoing-0: set socket timeout to 10000
2016-06-16 12:33:22.586 DEBUG 13144 --- [nio-8080-exec-1] o.a.http.impl.execchain.MainClientExec   : Executing request POST /post HTTP/1.1
2016-06-16 12:33:22.586 DEBUG 13144 --- [nio-8080-exec-1] o.a.http.impl.execchain.MainClientExec   : Target auth state: UNCHALLENGED
2016-06-16 12:33:22.587 DEBUG 13144 --- [nio-8080-exec-1] o.a.http.impl.execchain.MainClientExec   : Proxy auth state: UNCHALLENGED
2016-06-16 12:33:22.590 DEBUG 13144 --- [nio-8080-exec-1] org.apache.http.headers                  : http-outgoing-0 >> POST /post HTTP/1.1
2016-06-16 12:33:22.590 DEBUG 13144 --- [nio-8080-exec-1] org.apache.http.headers                  : http-outgoing-0 >> cache-control: max-age=0
2016-06-16 12:33:22.590 DEBUG 13144 --- [nio-8080-exec-1] org.apache.http.headers                  : http-outgoing-0 >> origin: http://localhost:8080
2016-06-16 12:33:22.590 DEBUG 13144 --- [nio-8080-exec-1] org.apache.http.headers                  : http-outgoing-0 >> upgrade-insecure-requests: 1
2016-06-16 12:33:22.590 DEBUG 13144 --- [nio-8080-exec-1] org.apache.http.headers                  : http-outgoing-0 >> user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.33 Safari/537.36
2016-06-16 12:33:22.590 DEBUG 13144 --- [nio-8080-exec-1] org.apache.http.headers                  : http-outgoing-0 >> content-type: application/x-www-form-urlencoded
2016-06-16 12:33:22.590 DEBUG 13144 --- [nio-8080-exec-1] org.apache.http.headers                  : http-outgoing-0 >> accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
2016-06-16 12:33:22.590 DEBUG 13144 --- [nio-8080-exec-1] org.apache.http.headers                  : http-outgoing-0 >> dnt: 1
2016-06-16 12:33:22.590 DEBUG 13144 --- [nio-8080-exec-1] org.apache.http.headers                  : http-outgoing-0 >> referer: http://localhost:8080/
2016-06-16 12:33:22.590 DEBUG 13144 --- [nio-8080-exec-1] org.apache.http.headers                  : http-outgoing-0 >> accept-language: en-US,en;q=0.8
2016-06-16 12:33:22.590 DEBUG 13144 --- [nio-8080-exec-1] org.apache.http.headers                  : http-outgoing-0 >> x-forwarded-host: localhost
2016-06-16 12:33:22.590 DEBUG 13144 --- [nio-8080-exec-1] org.apache.http.headers                  : http-outgoing-0 >> x-forwarded-proto: http
2016-06-16 12:33:22.590 DEBUG 13144 --- [nio-8080-exec-1] org.apache.http.headers                  : http-outgoing-0 >> x-forwarded-prefix: /api
2016-06-16 12:33:22.590 DEBUG 13144 --- [nio-8080-exec-1] org.apache.http.headers                  : http-outgoing-0 >> x-forwarded-port: 8080
2016-06-16 12:33:22.590 DEBUG 13144 --- [nio-8080-exec-1] org.apache.http.headers                  : http-outgoing-0 >> x-forwarded-for: 0:0:0:0:0:0:0:1
2016-06-16 12:33:22.590 DEBUG 13144 --- [nio-8080-exec-1] org.apache.http.headers                  : http-outgoing-0 >> Accept-Encoding: gzip
2016-06-16 12:33:22.590 DEBUG 13144 --- [nio-8080-exec-1] org.apache.http.headers                  : http-outgoing-0 >> Content-Length: 0
2016-06-16 12:33:22.591 DEBUG 13144 --- [nio-8080-exec-1] org.apache.http.headers                  : http-outgoing-0 >> Host: httpbin.org
2016-06-16 12:33:22.591 DEBUG 13144 --- [nio-8080-exec-1] org.apache.http.headers                  : http-outgoing-0 >> Connection: Keep-Alive
2016-06-16 12:33:22.591 DEBUG 13144 --- [nio-8080-exec-1] org.apache.http.wire                     : http-outgoing-0 >> "POST /post HTTP/1.1[\r][\n]"
2016-06-16 12:33:22.591 DEBUG 13144 --- [nio-8080-exec-1] org.apache.http.wire                     : http-outgoing-0 >> "cache-control: max-age=0[\r][\n]"
2016-06-16 12:33:22.591 DEBUG 13144 --- [nio-8080-exec-1] org.apache.http.wire                     : http-outgoing-0 >> "origin: http://localhost:8080[\r][\n]"
2016-06-16 12:33:22.591 DEBUG 13144 --- [nio-8080-exec-1] org.apache.http.wire                     : http-outgoing-0 >> "upgrade-insecure-requests: 1[\r][\n]"
2016-06-16 12:33:22.591 DEBUG 13144 --- [nio-8080-exec-1] org.apache.http.wire                     : http-outgoing-0 >> "user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.33 Safari/537.36[\r][\n]"
2016-06-16 12:33:22.591 DEBUG 13144 --- [nio-8080-exec-1] org.apache.http.wire                     : http-outgoing-0 >> "content-type: application/x-www-form-urlencoded[\r][\n]"
2016-06-16 12:33:22.591 DEBUG 13144 --- [nio-8080-exec-1] org.apache.http.wire                     : http-outgoing-0 >> "accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8[\r][\n]"
2016-06-16 12:33:22.591 DEBUG 13144 --- [nio-8080-exec-1] org.apache.http.wire                     : http-outgoing-0 >> "dnt: 1[\r][\n]"
2016-06-16 12:33:22.591 DEBUG 13144 --- [nio-8080-exec-1] org.apache.http.wire                     : http-outgoing-0 >> "referer: http://localhost:8080/[\r][\n]"
2016-06-16 12:33:22.591 DEBUG 13144 --- [nio-8080-exec-1] org.apache.http.wire                     : http-outgoing-0 >> "accept-language: en-US,en;q=0.8[\r][\n]"
2016-06-16 12:33:22.591 DEBUG 13144 --- [nio-8080-exec-1] org.apache.http.wire                     : http-outgoing-0 >> "x-forwarded-host: localhost[\r][\n]"
2016-06-16 12:33:22.591 DEBUG 13144 --- [nio-8080-exec-1] org.apache.http.wire                     : http-outgoing-0 >> "x-forwarded-proto: http[\r][\n]"
2016-06-16 12:33:22.591 DEBUG 13144 --- [nio-8080-exec-1] org.apache.http.wire                     : http-outgoing-0 >> "x-forwarded-prefix: /api[\r][\n]"
2016-06-16 12:33:22.592 DEBUG 13144 --- [nio-8080-exec-1] org.apache.http.wire                     : http-outgoing-0 >> "x-forwarded-port: 8080[\r][\n]"
2016-06-16 12:33:22.592 DEBUG 13144 --- [nio-8080-exec-1] org.apache.http.wire                     : http-outgoing-0 >> "x-forwarded-for: 0:0:0:0:0:0:0:1[\r][\n]"
2016-06-16 12:33:22.592 DEBUG 13144 --- [nio-8080-exec-1] org.apache.http.wire                     : http-outgoing-0 >> "Accept-Encoding: gzip[\r][\n]"
2016-06-16 12:33:22.592 DEBUG 13144 --- [nio-8080-exec-1] org.apache.http.wire                     : http-outgoing-0 >> "Content-Length: 0[\r][\n]"
2016-06-16 12:33:22.592 DEBUG 13144 --- [nio-8080-exec-1] org.apache.http.wire                     : http-outgoing-0 >> "Host: httpbin.org[\r][\n]"
2016-06-16 12:33:22.592 DEBUG 13144 --- [nio-8080-exec-1] org.apache.http.wire                     : http-outgoing-0 >> "Connection: Keep-Alive[\r][\n]"
2016-06-16 12:33:22.592 DEBUG 13144 --- [nio-8080-exec-1] org.apache.http.wire                     : http-outgoing-0 >> "[\r][\n]"
```

**Comment by spencergibb** [comment]
Found by setting
```
logging:
  level:
    org.apache.http: DEBUG
```

**Comment by beku8** [comment]
@spencergibb Thanks for the info, you were right.
Turns out eureka clients have no Content-Length set, whereas "direct" proxies are working ok.
I have following config on my zuul server:
```
zuul:
  ignoredServices: '*'
  routes:
    rs: /api/rs/**
    httpbin: 
      path: /api/httpbin/**
      url: http://httpbin.org
```
Here's a eureka client ```rs``` log files on posting:
```
2016-06-20 20:40:06.499 DEBUG 27387 --- [io-8080-exec-10] org.apache.http.headers                  : >> POST /post HTTP/1.1
2016-06-20 20:40:06.499 DEBUG 27387 --- [io-8080-exec-10] org.apache.http.headers                  : >> referer: http://localhost:8080/
2016-06-20 20:40:06.499 DEBUG 27387 --- [io-8080-exec-10] org.apache.http.headers                  : >> accept-language: en-US,en;q=0.8,bg;q=0.6,ru;q=0.4
2016-06-20 20:40:06.499 DEBUG 27387 --- [io-8080-exec-10] org.apache.http.headers                  : >> x-forwarded-proto: http
2016-06-20 20:40:06.499 DEBUG 27387 --- [io-8080-exec-10] org.apache.http.headers                  : >> origin: http://localhost:8080
2016-06-20 20:40:06.499 DEBUG 27387 --- [io-8080-exec-10] org.apache.http.headers                  : >> x-forwarded-port: 8080
2016-06-20 20:40:06.499 DEBUG 27387 --- [io-8080-exec-10] org.apache.http.headers                  : >> x-forwarded-for: 127.0.0.1
2016-06-20 20:40:06.499 DEBUG 27387 --- [io-8080-exec-10] org.apache.http.headers                  : >> Accept-Encoding: gzip
2016-06-20 20:40:06.499 DEBUG 27387 --- [io-8080-exec-10] org.apache.http.headers                  : >> pragma: no-cache
2016-06-20 20:40:06.499 DEBUG 27387 --- [io-8080-exec-10] org.apache.http.headers                  : >> accept: */*
2016-06-20 20:40:06.499 DEBUG 27387 --- [io-8080-exec-10] org.apache.http.headers                  : >> x-forwarded-host: localhost
2016-06-20 20:40:06.499 DEBUG 27387 --- [io-8080-exec-10] org.apache.http.headers                  : >> x-forwarded-prefix: /api/rs
2016-06-20 20:40:06.499 DEBUG 27387 --- [io-8080-exec-10] org.apache.http.headers                  : >> x-requested-with: XMLHttpRequest
2016-06-20 20:40:06.499 DEBUG 27387 --- [io-8080-exec-10] org.apache.http.headers                  : >> content-type: application/json
2016-06-20 20:40:06.499 DEBUG 27387 --- [io-8080-exec-10] org.apache.http.headers                  : >> cache-control: no-cache
2016-06-20 20:40:06.499 DEBUG 27387 --- [io-8080-exec-10] org.apache.http.headers                  : >> user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.84 Safari/537.36
2016-06-20 20:40:06.499 DEBUG 27387 --- [io-8080-exec-10] org.apache.http.headers                  : >> Netflix.NFHttpClient.Version: 1.0
2016-06-20 20:40:06.499 DEBUG 27387 --- [io-8080-exec-10] org.apache.http.headers                  : >> X-netflix-httpclientname: rs
2016-06-20 20:40:06.499 DEBUG 27387 --- [io-8080-exec-10] org.apache.http.headers                  : >> Transfer-Encoding: chunked
2016-06-20 20:40:06.499 DEBUG 27387 --- [io-8080-exec-10] org.apache.http.headers                  : >> Host: 192.168.1.5:8081
2016-06-20 20:40:06.499 DEBUG 27387 --- [io-8080-exec-10] org.apache.http.headers                  : >> Connection: Keep-Alive
```
Here, "direct" proxy ```httpbin``` works ok here:
```
2016-06-20 20:40:42.057 DEBUG 27387 --- [nio-8080-exec-1] org.apache.http.headers                  : http-outgoing-0 >> POST /post HTTP/1.1
2016-06-20 20:40:42.057 DEBUG 27387 --- [nio-8080-exec-1] org.apache.http.headers                  : http-outgoing-0 >> pragma: no-cache
2016-06-20 20:40:42.057 DEBUG 27387 --- [nio-8080-exec-1] org.apache.http.headers                  : http-outgoing-0 >> cache-control: no-cache
2016-06-20 20:40:42.057 DEBUG 27387 --- [nio-8080-exec-1] org.apache.http.headers                  : http-outgoing-0 >> accept: */*
2016-06-20 20:40:42.057 DEBUG 27387 --- [nio-8080-exec-1] org.apache.http.headers                  : http-outgoing-0 >> origin: http://localhost:8080
2016-06-20 20:40:42.057 DEBUG 27387 --- [nio-8080-exec-1] org.apache.http.headers                  : http-outgoing-0 >> x-requested-with: XMLHttpRequest
2016-06-20 20:40:42.057 DEBUG 27387 --- [nio-8080-exec-1] org.apache.http.headers                  : http-outgoing-0 >> user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.84 Safari/537.36
2016-06-20 20:40:42.057 DEBUG 27387 --- [nio-8080-exec-1] org.apache.http.headers                  : http-outgoing-0 >> content-type: application/json
2016-06-20 20:40:42.057 DEBUG 27387 --- [nio-8080-exec-1] org.apache.http.headers                  : http-outgoing-0 >> referer: http://localhost:8080/
2016-06-20 20:40:42.057 DEBUG 27387 --- [nio-8080-exec-1] org.apache.http.headers                  : http-outgoing-0 >> accept-language: en-US,en;q=0.8,bg;q=0.6,ru;q=0.4
2016-06-20 20:40:42.057 DEBUG 27387 --- [nio-8080-exec-1] org.apache.http.headers                  : http-outgoing-0 >> x-forwarded-host: localhost
2016-06-20 20:40:42.057 DEBUG 27387 --- [nio-8080-exec-1] org.apache.http.headers                  : http-outgoing-0 >> x-forwarded-proto: http
2016-06-20 20:40:42.057 DEBUG 27387 --- [nio-8080-exec-1] org.apache.http.headers                  : http-outgoing-0 >> x-forwarded-prefix: /api/httpbin
2016-06-20 20:40:42.057 DEBUG 27387 --- [nio-8080-exec-1] org.apache.http.headers                  : http-outgoing-0 >> x-forwarded-port: 8080
2016-06-20 20:40:42.057 DEBUG 27387 --- [nio-8080-exec-1] org.apache.http.headers                  : http-outgoing-0 >> x-forwarded-for: 127.0.0.1
2016-06-20 20:40:42.057 DEBUG 27387 --- [nio-8080-exec-1] org.apache.http.headers                  : http-outgoing-0 >> Accept-Encoding: gzip
2016-06-20 20:40:42.057 DEBUG 27387 --- [nio-8080-exec-1] org.apache.http.headers                  : http-outgoing-0 >> Content-Length: 13
2016-06-20 20:40:42.057 DEBUG 27387 --- [nio-8080-exec-1] org.apache.http.headers                  : http-outgoing-0 >> Host: httpbin.org
2016-06-20 20:40:42.057 DEBUG 27387 --- [nio-8080-exec-1] org.apache.http.headers                  : http-outgoing-0 >> Connection: Keep-Alive
```

I've updated my demo, please help us.

**Comment by spencergibb** [comment]
The problem is that in `com.sun.jersey.core.impl.provider.entity.InputStreamProvider` lines 81-87 below:
```
    @Override
    public long getSize(InputStream t, Class<?> type, Type genericType, Annotation[] annotations, MediaType mediaType) {
        if (t instanceof ByteArrayInputStream)
            return ((ByteArrayInputStream)t).available();
        else 
            return -1;
    }
```

`t` is an instance of `class com.netflix.zuul.http.ServletInputStreamWrapper` not `ByteArrayInputStream`, therefore it returns -1 :-( .

**Comment by spencergibb** [comment]
Trying with
```
	@Bean
	public RibbonCommandFactory<?> ribbonCommandFactory(SpringClientFactory clientFactory) {
		return new HttpClientRibbonCommandFactory(clientFactory);
	}
```
also results in 0 content length, the transfer encoding gets set to chunked, but I think I can fix that.

**Comment by spencergibb** [comment]
@beku8 when the build is complete you can try with `HttpClientRibbonCommandFactory` above and 1.1.3.BUILD-SNAPSHOT

**Comment by spencergibb** [comment]
Yet another reason to have `HttpClientRibbonCommandFactory` be the default.

**Comment by beku8** [comment]
Can't wait to test it, but snapshot is not [updated](https://repo.spring.io/snapshot/org/springframework/cloud/spring-cloud-netflix-core/1.1.3.BUILD-SNAPSHOT/). How long does it usually take?

**Comment by spencergibb** [comment]
@beku8 should be there now. Had to do it manually. @marcingrzejszczak we need to have jenkins build snapshots of certain branches and deploy them.

**Comment by beku8** [comment]
@spencergibb Thanks again! I pulled it and checked it. Now POST, PUT, DELETE methods are working fine. However GET method is getting a 411 error, which used to work before.

I examined the headers against the old headers, found that ```Transfer-Encoding: chunked``` was added. I made sure this was the problem by reverting to the default ```RestClientRibbonCommandFactory``` and added ```Transfer-Encoding: chunked``` via custom filter, and it threw 411 error.

Could we remove ```Transfer-Encoding``` from GET requests? Since GET requests don't have a body, neither ```Transfer-Encoding``` nor ```Content-Length``` should be set, right?

**Comment by spencergibb** [comment]
@beku8 with apache you either get `Transfer-Encoding: chunked` or `Content-Length: 0` according to `RequestContent`

```
            // Must specify a transfer encoding or a content length
            if (entity.isChunked() || entity.getContentLength() < 0) {
                if (ver.lessEquals(HttpVersion.HTTP_1_0)) {
                    throw new ProtocolException(
                            "Chunked transfer encoding not allowed for " + ver);
                }
                request.addHeader(HTTP.TRANSFER_ENCODING, HTTP.CHUNK_CODING);
            } else {
                request.addHeader(HTTP.CONTENT_LEN, Long.toString(entity.getContentLength()));
            }
```

**Comment by spencergibb** [comment]
@beku8 there are new snapshots.

**Comment by marcingrzejszczak** [comment]
The manual deploy is done - check out Jenkins :)

**Comment by beku8** [comment]
I can work from home now and it feels amazing. You are awesome, thanks so much @spencergibb.

One last question. At which stage do yo release a "static" version (like M1 or RC1 etc), and how long do you think it will take to reach that level?. Once I can access non-snapshot release, I would like to use 1.1.3 for a production environment. 

Again thank you so much, the ISP I use is the biggest ISP in Mongolia, which means I'm not gonna be alone from my company to enjoy this fix.

**Comment by spencergibb** [comment]
We're fairly close to a 1.1.3. There won't be any milestones or RC's.

**Comment by nissel** [comment]
@spencergibb there is still a problem with secure upstream connections. The content length is not set in RibbonApacheHttpRequest withNewUri(final URI uri). Should be a simple fix to add the missing parameter.

**Comment by spencergibb** [comment]
@nissel I've since made changes that always propagate content-length: https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/ribbon/support/ContextAwareRequest.java#L45

**Comment by denyska** [comment]
@spencergibb changes in **HttpClientRibbonCommand** that are part of 1.1.4 release cause NPE in this line `String contentLengthHeader = context.getRequest().getHeader("Content-Length");` if Hystrix configured with THREAD isolation strategy`hystrix.default.execution.isolation.strategy: THREAD`.

I know that RestClientRibbonCommand suggests to use SEMAPHORE strategy, but should it still work with the THREAD isolation and all thread-local variables being resolved even before Command created?

I like that THREAD strategy can interrupt threads and I can keep response time upon agreed SLA for all coming requests.

**Comment by spencergibb** [comment]
@denyska please open a new issue if you think there is a bug.

**Comment by denyska** [comment]
@spencergibb moved conversation to open  issue: https://github.com/spring-cloud/spring-cloud-netflix/issues/339

**Comment by kavinduraisamy91** [comment]
@spencergibb The 'GET' method  services call returns the 'getContentLengthLong()' value as '-1' in the below 'RibbonRoutingFilter' code 

`return new RibbonCommandContext(serviceId, verb, uri, retryable, headers, params, requestEntity,
				this.requestCustomizers, Long.valueOf(request.getContentLengthLong()));` 

Since 'request.getContext().getContentLength()' is not null so 'RibbonApacheHttpRequest' set the negative value in the Entity.
And HttpClient sets the Transfer-Encoding as Chunked.  

Could you please help me to disable the 'Chunked' Transfer-Encoding in this scenario ?

Thank you!

**Comment by spencergibb** [comment]
@kavinduraisamy91 please open a new issue if you think there is a bug. Please include steps to reproduce the problem or a sample project that demonstrates it.

**Comment by marcingrzejszczak** [comment]
> @marcingrzejszczak we need to have jenkins build snapshots of certain branches and deploy them

@spencergibb check out our Jenkins. I've pushed the code with deploying from branch yesterday
