### ISSUE TITLE
Optional request body should be supported

### ISSUE THREAD

**Issue by dimw** [spring-cloud/spring-cloud-netflix#1047]
In Spring MVC it is possible to [annotate body parameter as optional](http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/web/bind/annotation/RequestBody.html) using ```@RequestBody(required = false)``` parameter annotation, e.g.:
```java
@FeignClient("foo-service")
public interface FooService {
    @RequestMapping(value = "/foo", method = RequestMethod.POST)
    void doFoo(@RequestBody(required = false) FilterDto filter);
}
```

However, Spring-Feign contract does not consider the optionality flag which leads to an _IllegalStateException_ on proxy bootstrapping in consumer when calling something like:
```java
fooService.doFoo(null);
```
```
java.lang.IllegalArgumentException: Body parameter 0 was null
	at feign.Util.checkArgument(Util.java:102)
	at feign.ReflectiveFeign$BuildEncodedTemplateFromArgs.resolve(ReflectiveFeign.java:323)
	at feign.ReflectiveFeign$BuildTemplateByResolvingArgs.create(ReflectiveFeign.java:213)
	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:72)
	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:103)
```
It is expected that ```null``` can be passed as parameter since it is optional.

Using:
- spring-cloud-starter-feign:1.1.0.RELEASE
- feign-core:8.16.2

**Comment by daniellavoie** [comment]
From the stack trace you should understand that this issue is a pure Feign problem. Spring Cloud Netflix facilitate Netflix OSS component integration into Spring. I would suggest you to open an issue on the [feign project](https://github.com/Netflix/feign).

**Comment by dimw** [comment]
@daniellavoie, thanks for your feedback. Indeed, initially I was about to open this issue on the Feign project (because of the reasons admitted by you) but stack traces should not be always interpreted literally. Basically it seems not like a "a pure Feign problem" for me. Please correct me if I am wrong but:

1. The [Spring MVC-Feign contract](https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/feign/support/SpringMvcContract.java) alongside with [annotation processors](https://github.com/spring-cloud/spring-cloud-netflix/tree/master/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/feign/annotation) (both part of this project) are responsible for proper processing of the producer interface. Thus, they should process the ```@RequestBody``` annotation and translate the ```required``` flag to Feign metadata.
2. Feign does not know anything about Spring MVC annotations (i.e. ```@RequestBody```) so even it can see the annotations provided on the method, it cannot (and should not) understand semantics of these.

In fact, there might be currently no way in Feign to handle optional request bodies. However, this behavior should be at least documented in this project (because of the difference to behavior anticipated in Spring MVC). Further, it might be considered to create a certain _RequestBodyParameterProcessor_ which catches the issue one level higher before letting Feign to throw semi-reasonable exception.

**Comment by daniellavoie** [comment]
You are right. Looks like I had a bad understanding of Spring Cloud Feign. I'll try to have a look and see if I can come up with a trick to handle an optinal parameter. If you have any inspiration, feel free to give some help ;)

**Comment by dimw** [comment]
@spencergibb: Do you think you can drop a line and explain why this issue has been closed without any further comment?

**Comment by spencergibb** [comment]
Sorry about that, it was a mistake.

**Comment by realdammy** [comment]
Hello @spencergibb, any update on this issues?

**Comment by ryanjbaxter** [comment]
@realdammy it is labeled as an enhancement but as far as I know no one is working on it at the moment.  If you want to submit a PR for it that would be more than welcome.

**Comment by dyc87112** [comment]
@ryanjbaxter I try to fix this issue. But feign always check the body, so I have to wait this PR : https://github.com/OpenFeign/feign/pull/583.

```java
@Override
protected RequestTemplate resolve(Object[] argv, RequestTemplate mutable, Map<String, Object> variables) {
  Object body = argv[metadata.bodyIndex()];
  checkArgument(body != null, "Body parameter %s was null", metadata.bodyIndex());
  ...
  return super.resolve(argv, mutable, variables);
}
```

If this PR can be accept. I will create another PR for here. 

@dimw Thanks for  your analysis.

**Comment by sdhery** [comment]
Already have a solution?

**Comment by dyc87112** [comment]
@sdhery https://github.com/OpenFeign/feign/pull/583 has not been accept，so you need compile feign by yourself，then write an `RequestBodyParameterProcessor` implements `AnnotatedParameterProcessor` interface to support this issue
