### ISSUE TITLE
RejectedExecutionException logged on console

### ISSUE THREAD

**Issue by abhijitsarkar** [spring-cloud/spring-cloud-netflix#1060]
```
2016-05-29 01:33:04.566 ERROR 9669 --- [ver-bootstrap-0] c.netflix.discovery.TimedSupervisorTask  : task supervisor rejected the task

java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@7c6cd7ab rejected from java.util.concurrent.ThreadPoolExecutor@72ab3656[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2047) ~[na:1.8.0_66]
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:823) [na:1.8.0_66]
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1369) [na:1.8.0_66]
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112) ~[na:1.8.0_66]
	at com.netflix.discovery.TimedSupervisorTask.run(TimedSupervisorTask.java:62) ~[eureka-client-1.4.6.jar:1.4.6]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_66]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_66]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_66]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_66]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_66]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_66]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_66]
```

It doesn't appear to hamper any functionality that I've tested, but puts Dev Ops on the edge. Using Spring Cloud parent Brixton.RELEASE, Spring Cloud 1.1.0.RELEASE and Spring Boot 1.3.5.RELEASE.

**Comment by daniellavoie** [comment]
Duplicate with #1055. Could you provide a simple project reproducing this error ?

**Comment by haraldsk** [comment]
This is also confirmed in Spring Boot 1.4.0.

**Comment by bobkilla** [comment]
It may be a duplicate of #1055 but this issue has been locked and no progress has been made since then. Do you have more info about it? ping @spencergibb (since you locked the other issue). Thanks

**Comment by spencergibb** [comment]
@bobkilla log an issue upstream? or comment on this one https://github.com/Netflix/eureka/issues/907

Dalston uses eureka 1.6.2 which may help, but I don't see anything we can do.

**Comment by lferna** [comment]
I have the same problem as #1060 and #1055. Last one is locked, so the problem continues.

**Comment by dsyer** [comment]
I have unlocked the conversation at #1055 (the duplicate issue). There's still nothing there that says to me that a) there is a problem we can fix here, or b) if there is how to reproduce it. So please don't bother to comment unless you can move one of those things forward.

**Comment by lferna** [comment]
Thanks @dsyer , I'll put in #1055 how to reproduce the problem.

**Comment by mradulpandey** [comment]
I observed if i set **eureka.client.enabled=true** in my config server and
hit http://localhost:8888/monitor?path=application
i get the following response

```
{
    "timestamp": 1503601813361,
    "status": 500,
    "error": "Internal Server Error",
    "exception": "java.util.concurrent.RejectedExecutionException",
    "message": "Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@7f865c88 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@20ac99dd[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 2]",
    "path": "/monitor"
}
```

**Comment by ryanjbaxter** [comment]
@mradulpandey posting the same content to multiple issues from different GitHub accounts is not helpful, please don't so this.

**Comment by asarkar** [comment]
Reported mradulpandey for abusing GitHub T&C.

**Comment by spencergibb** [comment]
That's a bit harsh
