### ISSUE TITLE
Eureka Peer Server throwing java.lang.NullPointerException: null at com.netflix.eureka.registry.AbstractInstanceRegistry.renew

### ISSUE THREAD

**Issue by codependent** [spring-cloud/spring-cloud-netflix#1065]
I have two Eureka server instances configured with peer awareness. I start the first server and wait for a while, seeing it looking for the second one:
```
2016-05-30 11:04:53.278  WARN 4936 --- [nfoReplicator-0] c.n.d.s.t.d.RetryableEurekaHttpClient    : Request execution failure
2016-05-30 11:04:53.278  WARN 4936 --- [nfoReplicator-0] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_UNKNOWN/EXPRF026.suministrador.local:8761 - registration failed Cannot execute request on any known server

com.netflix.discovery.shared.transport.TransportException: Cannot execute request on any known server
```

Then I launch the second instance, and the first one registers it:
```
INFO 7720 --- [nfoReplicator-0] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_UNKNOWN/clouddev:8761: registering service...
INFO 7720 --- [nfoReplicator-0] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_UNKNOWN/clouddev:8761 - registration status: 204
INFO 7720 --- [nio-8761-exec-3] c.n.e.registry.AbstractInstanceRegistry  : Registered instance UNKNOWN/clouddev:8761 with status UP (replication=true)
```

Looking at the second server I see a NullPointerException in the log, although everything seems to work fine:

```
 INFO 5524 --- [nio-8762-exec-1] o.s.web.servlet.DispatcherServlet        : FrameworkServlet 'dispatcherServlet': initialization completed in 22 ms
DEBUG 5524 --- [nio-8762-exec-1] o.s.web.servlet.DispatcherServlet        : Servlet 'dispatcherServlet' configured successfully
 INFO 5524 --- [nio-8762-exec-1] c.n.e.registry.AbstractInstanceRegistry  : Registered instance UNKNOWN/clouddev:8762 with status UP (replication=true)
 INFO 5524 --- [nio-8762-exec-2] c.n.e.registry.AbstractInstanceRegistry  : Registered instance UNKNOWN/clouddev:8762 with status UP (replication=true)
 WARN 5524 --- [nio-8762-exec-3] c.n.e.registry.AbstractInstanceRegistry  : DS: Registry: lease doesn't exist, registering resource: UNKNOWN - clouddev:8761
 WARN 5524 --- [nio-8762-exec-3] c.n.eureka.resources.InstanceResource    : Not Found (Renew): UNKNOWN - clouddev:8761
 INFO 5524 --- [nio-8762-exec-5] c.n.e.registry.AbstractInstanceRegistry  : Registered instance UNKNOWN/clouddev:8761 with status UP (replication=false)
 INFO 5524 --- [nio-8762-exec-6] c.n.e.registry.AbstractInstanceRegistry  : Registered instance UNKNOWN/clouddev:8761 with status UP (replication=false)
 INFO 5524 --- [freshExecutor-0] com.netflix.discovery.DiscoveryClient    : Disable delta property : false
 INFO 5524 --- [freshExecutor-0] com.netflix.discovery.DiscoveryClient    : Single vip registry refresh property : null
 INFO 5524 --- [freshExecutor-0] com.netflix.discovery.DiscoveryClient    : Force full registry fetch : false
 INFO 5524 --- [freshExecutor-0] com.netflix.discovery.DiscoveryClient    : Application is null : false
 INFO 5524 --- [freshExecutor-0] com.netflix.discovery.DiscoveryClient    : Registered Applications size is zero : true
 INFO 5524 --- [freshExecutor-0] com.netflix.discovery.DiscoveryClient    : Application version is -1: false
 INFO 5524 --- [freshExecutor-0] com.netflix.discovery.DiscoveryClient    : Getting all instance registry info from the eureka server
 INFO 5524 --- [freshExecutor-0] com.netflix.discovery.DiscoveryClient    : The response status is 200
ERROR 5524 --- [nio-8762-exec-7] c.n.e.resources.PeerReplicationResource  : Heartbeat request processing failed for batch item UNKNOWN/clouddev:8762

java.lang.NullPointerException: null
	at com.netflix.eureka.registry.AbstractInstanceRegistry.renew(AbstractInstanceRegistry.java:379) ~[eureka-core-1.4.6.jar:1.4.6]
	at com.netflix.eureka.registry.PeerAwareInstanceRegistryImpl.renew(PeerAwareInstanceRegistryImpl.java:401) ~[eureka-core-1.4.6.jar:1.4.6]
	at org.springframework.cloud.netflix.eureka.server.InstanceRegistry.renew(InstanceRegistry.java:127) ~[spring-cloud-netflix-eureka-server-1.1.0.RELEASE.jar:1.1.0.RELEASE]
	at com.netflix.eureka.resources.InstanceResource.renewLease(InstanceResource.java:112) ~[eureka-core-1.4.6.jar:1.4.6]
	at com.netflix.eureka.resources.PeerReplicationResource.handleHeartbeat(PeerReplicationResource.java:148) ~[eureka-core-1.4.6.jar:1.4.6]
	at com.netflix.eureka.resources.PeerReplicationResource.dispatch(PeerReplicationResource.java:113) ~[eureka-core-1.4.6.jar:1.4.6]
	at com.netflix.eureka.resources.PeerReplicationResource.batchReplication(PeerReplicationResource.java:85) ~[eureka-core-1.4.6.jar:1.4.6]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_74]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_74]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_74]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_74]
```

I found a similar [issue](https://github.com/spring-cloud/spring-cloud-netflix/issues/953) but I checked my dependencies and think are ok.

**pom.xml**:
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>com.codependent.storyteller</groupId>
	<artifactId>archimedes</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<packaging>jar</packaging>

	<name>Archimedes</name>
	<description>Demo project for Spring Boot</description>

	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>1.3.5.RELEASE</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<java.version>1.8</java.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
		</dependency>
	
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-eureka-server</artifactId>
		</dependency>
		
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>
	
	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-dependencies</artifactId>
				<version>Brixton.RELEASE</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>
	
	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>
	
	<repositories>
		<repository>
			<id>spring-snapshots</id>
			<name>Spring Snapshots</name>
			<url>https://repo.spring.io/snapshot</url>
			<snapshots>
				<enabled>true</enabled>
			</snapshots>
		</repository>
		<repository>
			<id>spring-milestones</id>
			<name>Spring Milestones</name>
			<url>https://repo.spring.io/milestone</url>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
		</repository>
	</repositories>

</project>
```

**application.yml**:
```
---
spring:
  profiles: archimedes1

server:
  port: ${PORT:8761}
        
eureka:
  instance:
    hostname: archimedes1
  client:
    serviceUrl:
      defaultZone: http://archimedes2:8762/eureka/

logging:
    level:
        org.springframework.web: 'DEBUG'
---

spring:
  profiles: archimedes2

server:
  port: ${PORT:8762}
        
eureka:
  instance:
    hostname: archimedes2
  client:
    serviceUrl:
      defaultZone: http://archimedes1:8761/eureka/

logging:
    level:
        org.springframework.web: 'DEBUG'
```

**ArchimedesApplication**:
```
package com.codependent.storyteller;

import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.builder.SpringApplicationBuilder;
import org.springframework.cloud.netflix.eureka.server.EnableEurekaServer;

@EnableEurekaServer
@SpringBootApplication
public class ArchimedesApplication {
	
    public static void main(String[] args) {
    	new SpringApplicationBuilder(ArchimedesApplication.class).web(true).run(args);
    }
}
```

**Comment by daniellavoie** [comment]
Hi @codependent 

Just wanted to let you know that I have the same issue with our 2 peer setup. It seems servers takes some times to be able to gossip properly. After a minute or so that both servers are online, the NullPointerException goes away. I didn't took the time to investigate this issue further.

**Comment by codependent** [comment]
@daniellavoie it doesn't seem important, since everything is working, it's just that it raises a false positive error in our monitoring.

**Comment by spencergibb** [comment]
@daniellavoie looks like a simple bug in eureka. A PR or issue there https://github.com/Netflix/eureka would be welcome.

**Comment by seno5979** [comment]
T算是人口參與食用色素人喪生測試欸死欸欸月月欸願望次於王子錯誤我從未為維護😘😀😃😇😆🍝🍜🍞🍍🍆🍤🍝🍥⏩🔼

Daniel Lavoie <notifications@github.com> 於 2016年6月1日 星期三寫道：

> Hi @codependent <https://github.com/codependent>
>
> Just wanted to let you know that I have the same issue with our 2 peer
> setup. It seems servers takes some times to be able to gossip properly.
> After a minute or so that both servers are online, the NullPointerException
> goes away. I didn't took the time to investigate this issue further.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/spring-cloud/spring-cloud-netflix/issues/1065#issuecomment-222872147>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AE3qYmP8m3OsiPPqD3mbO6C9eblmxUaJks5qHOajgaJpZM4IpoLY>
> .
>


-- 
Sent from my phone

**Comment by superxp1412** [comment]
I encountered the same error, while the replicas shows in the "unavailable-replicas".

**Comment by qiangdavidliu** [comment]
Re-posting from the eureka repo:

Looking at the the issue on this thread and in the eureka codebase, I see that the NPE is due to an out of order creation of a metrics counter. This is a harmless NPE that should only happen at init time. We will take a look at a simple PR to address this regardless.

The details: this is caused due to the second server not completing initialization (specifically, the openForTraffic() method on the local registry that creates the metrics counter in question) before having the first server heartbeat to the second server, and trying to log the renew metrics on an as yet non-existent metrics counter.
