### ISSUE TITLE
Eureka client not reading ssl client certificate from keyStore

### ISSUE THREAD

**Issue by Jumpy-Squirrel** [spring-cloud/spring-cloud-netflix#1077]
I am trying to use Eureka with SSL two-way handshake (client certificate authentication).

To that end, I have created a server and client certificate, had them signed, and configured the eureka server (implemented with spring-cloud-starter-eureka-server) to present the server certificate (properties server.ssl.key-store etc.) and to check client certificates (properties server.ssl.trust-store, server.ssl.clientAuth=need). 

The server side works fine, if I write a small standalone client program using apache HttpClient 4.5.2 and fluent-hc 4.5.2, basically doing

            Request.Get("https://localhost:9000/eureka/")
                    .execute()
                    .returnContent();

it successfully performs a two way SSL handshake with my eureka server (and bails out when no content is returned, but that's not the problem). All I needed to do to make the HttpClient find my certificates was set a few java system properties, namely

    javax.net.ssl.trustStore
    javax.net.ssl.trustStorePassword
    javax.net.ssl.keyStore
    javax.net.ssl.keyStorePassword

Now if I instead write a spring boot microservice as a eureka client, setting those very same system properties, it fails to find the certificate in my client side keyStore when it wants to register its services. 

My guess is it doesn't read the keyStore at all when Eureka goes through  com.sun.jersey.client.apache4.ApacheHttpClient4 to make the call.

When enabling SSL debugging on the client, it becomes clear that the client cannot find the certificate. It authenticates the server, then the server asks it to present a certificate, and it sends back an empty key chain.

I cannot find any information in the documentation regarding what properties to set, so I apologize if I just have the wrong properties (system or spring application.yml). If so, please tell me, and if I haven't just overlooked it in the documentation, I would much appreciate a small extension to the documentation of spring-cloud-netflix. 

I am not sure if spring-cloud-netflix can fix this, it might be an upstream problem with eureka-client. I am still hoping it's just a configuration/documentation issue.

Thanks.

_**Some additional information:**_

I have tried setting the system property com.netflix.eureka.shouldSSLConnectionsUseSystemSocketFactory=true, but this does not fix the problem either.

<b>eureka server application.yml:</b>

<pre>server:
  port: 9000
  ssl:
    enabled: true
    key-store: file:xxx.jks
    key-store-password: xxx
    key-alias: tomcat
    key-password: xxx
    trust-store: file:yyy
    trust-store-password: xxx
    clientAuth: need

...

eureka:
  instance:
    hostname: localhost
    securePort: ${server.port}
    securePortEnabled: true
    nonSecurePortEnabled: false
    secureVirtualHostName: localhost
    homePageUrl: https://${eureka.instance.hostname}:${server.port}/
    statusPageUrl: https://${eureka.instance.hostname}:${server.port}/info
    metadataMap:
      hostname : ${eureka.instance.hostname}
      securePort: ${server.port}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: https://${eureka.instance.hostname}:${server.port}/eureka/</pre>

<b>eureka client application.yml:</b>

<pre>server:
  port: 9001

...

eureka:
  client:
    serviceUrl:
      defaultZone: https://localhost:9000/eureka/
    healthcheck:
      enabled: true
  instance:
    hostname: localhost
    preferIpAddress: false
    securePortEnabled: true
    statusPageUrl: https://${eureka.instance.hostname}:${server.port}/info
    healthCheckUrl: https://${eureka.instance.hostname}:${server.port}/health
    homePageUrl: https://${eureka.instance.hostname}:${server.port}/swagger-ui.html</pre>

<b>client system properties:</b>

<pre>-Djavax.net.ssl.trustStore=xxx
-Djavax.net.ssl.trustStorePassword=xxx
-Djavax.net.ssl.keyStore=xxx.jks
-Djavax.net.ssl.keyStorePassword=xxx</pre>

tried both with and without

<pre>-Dcom.netflix.eureka.shouldSSLConnectionsUseSystemSocketFactory=true</pre>

<b>The exception is:</b>

<pre>2016-06-05 00:08:23.684  INFO 16867 --- [nfoReplicator-0] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_XXX/192.168.236.129:xyz:9001: registering service...
2016-06-05 00:08:23.724 ERROR 16867 --- [nfoReplicator-0] c.n.d.s.t.d.RedirectingEurekaHttpClient  : Request execution error

com.sun.jersey.api.client.ClientHandlerException: javax.net.ssl.SSLHandshakeException: Received fatal alert: bad_certificate
        at com.sun.jersey.client.apache4.ApacheHttpClient4Handler.handle(ApacheHttpClient4Handler.java:187)
        at com.sun.jersey.api.client.filter.GZIPContentEncodingFilter.handle(GZIPContentEncodingFilter.java:123)
        at com.netflix.discovery.EurekaIdentityHeaderFilter.handle(EurekaIdentityHeaderFilter.java:27)
        at com.sun.jersey.api.client.Client.handle(Client.java:652)
        at com.sun.jersey.api.client.WebResource.handle(WebResource.java:682)
        at com.sun.jersey.api.client.WebResource.access$200(WebResource.java:74)
        at com.sun.jersey.api.client.WebResource$Builder.post(WebResource.java:570)
        at com.netflix.discovery.shared.transport.jersey.AbstractJerseyEurekaHttpClient.register(AbstractJerseyEurekaHttpClient.java:56)
        at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$1.execute(EurekaHttpClientDecorator.java:59)
        at com.netflix.discovery.shared.transport.decorator.MetricsCollectingEurekaHttpClient.execute(MetricsCollectingEurekaHttpClient.java:73)
        at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.register(EurekaHttpClientDecorator.java:56)
        at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$1.execute(EurekaHttpClientDecorator.java:59)
        at com.netflix.discovery.shared.transport.decorator.RedirectingEurekaHttpClient.executeOnNewServer(RedirectingEurekaHttpClient.java:118)
        at com.netflix.discovery.shared.transport.decorator.RedirectingEurekaHttpClient.execute(RedirectingEurekaHttpClient.java:79)
        at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.register(EurekaHttpClientDecorator.java:56)
        at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$1.execute(EurekaHttpClientDecorator.java:59)
        at com.netflix.discovery.shared.transport.decorator.RetryableEurekaHttpClient.execute(RetryableEurekaHttpClient.java:119)
        at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.register(EurekaHttpClientDecorator.java:56)
        at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$1.execute(EurekaHttpClientDecorator.java:59)
        at com.netflix.discovery.shared.transport.decorator.SessionedEurekaHttpClient.execute(SessionedEurekaHttpClient.java:77)
        at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.register(EurekaHttpClientDecorator.java:56)
        at com.netflix.discovery.DiscoveryClient.register(DiscoveryClient.java:810)
        at com.netflix.discovery.InstanceInfoReplicator.run(InstanceInfoReplicator.java:103)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: javax.net.ssl.SSLHandshakeException: Received fatal alert: bad_certificate
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:154)
        at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:2023)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1125)
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
        at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:553)
        at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:412)
        at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:179)
        at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:144)
        at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:134)
        at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:612)
        at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:447)
        at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:884)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:117)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
        at com.sun.jersey.client.apache4.ApacheHttpClient4Handler.handle(ApacheHttpClient4Handler.java:173)
        ... 29 common frames omitted
</pre>

**Comment by bitsofinfo** [comment]
@Jumpy-Squirrel did you ever find a resolution to this?

**Comment by Jumpy-Squirrel** [comment]
No, unfortunately I have been unable to solve this so far. 

For the time being, I have switched to https + basic auth for access to Eureka, but this is a bit unfortunate when everything else works with client certificates. 

Thank you for linking me to the relevant upstream issue and patch. 

The patch in #234 looks like someone had the same problem I had and made a patch, so it does appear to be a genuine Eureka problem and not just a missing configuration property in spring cloud netflix.

Therefore I am closing this issue.

**Comment by bitsofinfo** [comment]
I think this should remain open as it *should* work no? even though you reverted to BA+ssl, I think this should be open so its on the project owner's radar.

**Comment by spencergibb** [comment]
I agree

**Comment by bitsofinfo** [comment]
https://github.com/Netflix/eureka/pull/813

**Comment by spencergibb** [comment]
This is now part of eureka 1.4.11 which is included in spring-cloud-netflix
