### ISSUE TITLE
Unable to declare "alias" annotation for @FeignClient

### ISSUE THREAD

**Issue by shuraa** [spring-cloud/spring-cloud-netflix#1083]
I try to create custom annotation for all feign client components that must be pre-configured with OAuth2FeignClientConfiguration:
```java
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.TYPE)
@Documented
@FeignClient
public @interface OAuth2FeignClient
{

	@AliasFor(annotation = FeignClient.class, attribute = "value")
	public String value() default "";

	@AliasFor(annotation = FeignClient.class, attribute = "name")
	public String name() default "";

	@AliasFor(annotation = FeignClient.class, attribute = "configuration")
	public Class<?>[] configuration() default {OAuth2FeignClientConfiguration.class};

}
```

But my application is unable to start with the following stack trace:
<pre>
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49) [spring-boot-devtools-1.3.5.RELEASE.jar:1.3.5.RELEASE]
Caused by: org.springframework.core.annotation.AnnotationConfigurationException: Attribute [value] in annotation [org.springframework.cloud.netflix.feign.FeignClient] must be declared as an @AliasFor [serviceId], not [name].
	at org.springframework.core.annotation.AnnotationUtils$AliasDescriptor.validate(AnnotationUtils.java:1991) ~[spring-core-4.2.6.RELEASE.jar:4.2.6.RELEASE]
	at org.springframework.core.annotation.AnnotationUtils$AliasDescriptor.from(AnnotationUtils.java:1937) ~[spring-core-4.2.6.RELEASE.jar:4.2.6.RELEASE]
	at org.springframework.core.annotation.AnnotationUtils.getAttributeAliasNames(AnnotationUtils.java:1626) ~[spring-core-4.2.6.RELEASE.jar:4.2.6.RELEASE]
	at org.springframework.core.annotation.AnnotationUtils.isSynthesizable(AnnotationUtils.java:1585) ~[spring-core-4.2.6.RELEASE.jar:4.2.6.RELEASE]
	at org.springframework.core.annotation.AnnotationUtils.synthesizeAnnotation(AnnotationUtils.java:1368) ~[spring-core-4.2.6.RELEASE.jar:4.2.6.RELEASE]
	at org.springframework.core.annotation.AnnotationUtils.synthesizeAnnotationArray(AnnotationUtils.java:1472) ~[spring-core-4.2.6.RELEASE.jar:4.2.6.RELEASE]
	at org.springframework.core.annotation.AnnotationUtils.getAnnotations(AnnotationUtils.java:229) ~[spring-core-4.2.6.RELEASE.jar:4.2.6.RELEASE]
	at org.springframework.core.type.classreading.AnnotationAttributesReadingVisitor.doVisitEnd(AnnotationAttributesReadingVisitor.java:76) ~[spring-core-4.2.6.RELEASE.jar:4.2.6.RELEASE]
	at org.springframework.core.type.classreading.RecursiveAnnotationAttributesVisitor.visitEnd(RecursiveAnnotationAttributesVisitor.java:48) ~[spring-core-4.2.6.RELEASE.jar:4.2.6.RELEASE]
	at org.springframework.asm.ClassReader.readAnnotationValues(ClassReader.java:1802) ~[spring-core-4.2.6.RELEASE.jar:4.2.6.RELEASE]
	at org.springframework.asm.ClassReader.accept(ClassReader.java:642) ~[spring-core-4.2.6.RELEASE.jar:4.2.6.RELEASE]
	at org.springframework.asm.ClassReader.accept(ClassReader.java:508) ~[spring-core-4.2.6.RELEASE.jar:4.2.6.RELEASE]
	at org.springframework.core.type.classreading.SimpleMetadataReader.<init>(SimpleMetadataReader.java:64) ~[spring-core-4.2.6.RELEASE.jar:4.2.6.RELEASE]
	at org.springframework.core.type.classreading.SimpleMetadataReaderFactory.getMetadataReader(SimpleMetadataReaderFactory.java:98) ~[spring-core-4.2.6.RELEASE.jar:4.2.6.RELEASE]
	at org.springframework.core.type.classreading.CachingMetadataReaderFactory.getMetadataReader(CachingMetadataReaderFactory.java:102) ~[spring-core-4.2.6.RELEASE.jar:4.2.6.RELEASE]
	at org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider.findCandidateComponents(ClassPathScanningCandidateComponentProvider.java:279) ~[spring-context-4.2.6.RELEASE.jar:4.2.6.RELEASE]
</pre>

I'll expect that there is an ability to create "alias" for ``@FeignClient``.

**Comment by spencergibb** [comment]
880efd18431f9299f41829aeda969d665357aa6f fixed a problem others were having with the alias. Can you try with snapshots and see if that fixes your problem?

**Comment by shuraa** [comment]
@spencergibb , thank you! With 1.1.1-SNAPSHOT the issue is gone.
