### ISSUE TITLE
@FeignClient doesn't support object/map arguments in 'RequestMethod.GET' method

### ISSUE THREAD

**Issue by lowzj** [spring-cloud/spring-cloud-netflix#1097]
such as:
```
@FeignClient("testConsulApp")
public interface TestExample {
    @RequestMapping(value = "/hello", method = RequestMethod.GET)
    public String hello(Map<String, String> args);
}
```

it will send a **POST** request(expect **GET**) to the **testConsulApp**, and throw a exception:

```
feign.FeignException: status 405 reading TestExample#hello(Map); content:
{"timestamp":1465866159340,"status":405,"error":"Method Not Allowed","exception":"org.springframework.web.HttpRequestMethodNotSupportedException","message":"Request method &#39;POST&#39; not supported","path":"/hello"}
	at feign.FeignException.errorStatus(FeignException.java:62) ~[feign-core-8.16.2.jar:8.16.2]
	at feign.codec.ErrorDecoder$Default.decode(ErrorDecoder.java:91) ~[feign-core-8.16.2.jar:8.16.2]
	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:134) ~[feign-core-8.16.2.jar:8.16.2]
	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:76) ~[feign-core-8.16.2.jar:8.16.2]
	at feign.hystrix.HystrixInvocationHandler$1.run(HystrixInvocationHandler.java:97) ~[feign-hystrix-8.16.2.jar:8.16.2]
	at com.netflix.hystrix.HystrixCommand$1.call(HystrixCommand.java:293) ~[hystrix-core-1.5.2.jar:1.5.2]
	at com.netflix.hystrix.HystrixCommand$1.call(HystrixCommand.java:288) ~[hystrix-core-1.5.2.jar:1.5.2]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50) ~[rxjava-1.1.5.jar:1.1.5]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) ~[rxjava-1.1.5.jar:1.1.5]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50) ~[rxjava-1.1.5.jar:1.1.5]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) ~[rxjava-1.1.5.jar:1.1.5]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50) ~[rxjava-1.1.5.jar:1.1.5]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) ~[rxjava-1.1.5.jar:1.1.5]
	at rx.Observable.unsafeSubscribe(Observable.java:8460) ~[rxjava-1.1.5.jar:1.1.5]
	at com.netflix.hystrix.AbstractCommand$5.call(AbstractCommand.java:521) ~[hystrix-core-1.5.2.jar:1.5.2]
	at com.netflix.hystrix.AbstractCommand$5.call(AbstractCommand.java:497) ~[hystrix-core-1.5.2.jar:1.5.2]
	at rx.Observable.unsafeSubscribe(Observable.java:8460) ~[rxjava-1.1.5.jar:1.1.5]
	at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94) ~[rxjava-1.1.5.jar:1.1.5]
	at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction$1.call(HystrixContexSchedulerAction.java:56) ~[hystrix-core-1.5.2.jar:1.5.2]
	at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction$1.call(HystrixContexSchedulerAction.java:47) ~[hystrix-core-1.5.2.jar:1.5.2]
	at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction.call(HystrixContexSchedulerAction.java:69) ~[hystrix-core-1.5.2.jar:1.5.2]
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55) ~[rxjava-1.1.5.jar:1.1.5]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_25]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_25]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_25]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_25]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_25]
```

**Comment by lowzj** [comment]
I using annotation `@RequestParam` on the **args**.  I think the request would be : **/hello?a={a}&b={b}**, If the **args** contains keys: **a**, **b**.
```
public String hello(@RequestParam Map<String, String> args);
```

But it  throws an exception:
```
Caused by: java.lang.IllegalStateException: RequestParam.value() was empty on parameter 0
	at feign.Util.checkState(Util.java:128) ~[feign-core-8.16.2.jar:8.16.2]
	at org.springframework.cloud.netflix.feign.annotation.RequestParamParameterProcessor.processArgument(RequestParamParameterProcessor.java:48) ~[spring-cloud-netflix-core-1.1.0.RELEASE.jar:1.1.0.RELEASE]
```

Then I write a bean just like `RequestParamParameterProcessor`, it works.

```
public static class RequestParamParameterProcessor implements AnnotatedParameterProcessor {

    private static final Class<RequestParam> ANNOTATION = RequestParam.class;

    @Override
    public Class<? extends Annotation> getAnnotationType() {
        return ANNOTATION;
    }

    @Override
    public boolean processArgument(AnnotatedParameterContext context, Annotation annotation) {
        String name = ANNOTATION.cast(annotation).value();
        if (emptyToNull(name) != null) {
            context.setParameterName(name);

            MethodMetadata data = context.getMethodMetadata();
            Collection<String> query = context.setTemplateParameter(name, data.template().queries().get(name));
            data.template().query(name, query);
        } else {
            MethodMetadata data = context.getMethodMetadata();
            data.queryMapIndex(context.getParameterIndex());
        }
        return true;
    }
}
```

**Comment by spencergibb** [comment]
Pull requests welcome.

**Comment by lowzj** [comment]
@spencergibb pr #1102
