### ISSUE TITLE
@EnableZuulProxy causes Assertion failure at org.springframework.cloud.netflix.zuul.ZuulProxyConfiguration.ribbonCommandFactory

### ISSUE THREAD

**Issue by RobMcA** [spring-cloud/spring-cloud-netflix#1134]
When trying to use @EnableZuulProxy, the server won't start.

```
Caused by: java.lang.IllegalStateException: Error processing condition on org.springframework.cloud.netflix.zuul.ZuulProxyConfiguration.ribbonCommandFactory
	at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:64)

Caused by: java.lang.IllegalArgumentException: @ConditionalOnMissingBean annotations must specify at least one bean (type, name or annotation)
	at org.springframework.util.Assert.isTrue(Assert.java:68)
	at org.springframework.boot.autoconfigure.condition.OnBeanCondition$BeanSearchSpec.validate(OnBeanCondition.java:279)
```

Here is the java class:

```java
package myapp;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.cloud.netflix.eureka.EnableEurekaClient;
import org.springframework.cloud.netflix.zuul.EnableZuulProxy;

@EnableEurekaClient
@SpringBootApplication
@EnableZuulProxy
public class ZuulProxyApplication {

	public static void main(String[] args) {
		SpringApplication.run(ZuulProxyApplication.class, args);
	}
}
```

And the POM.

```xml
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>myapp</groupId>
	<artifactId>zuul</artifactId>
  <version>0.0.1-SNAPSHOT</version>
<parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>1.3.5.RELEASE</version>
</parent>

<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-dependencies</artifactId>
            <version>Brixton.SR1</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>
    </dependencies>
</dependencyManagement>
<dependencies>
 
    <dependency>
        <groupId>org.springframework.cloud</groupId>
        <artifactId>spring-cloud-starter-eureka</artifactId>
    </dependency>
</dependencies>
</project>
```

**Comment by spencergibb** [comment]
You're missing `spring-cloud-starter-zuul`.

**Comment by RobMcA** [comment]
Thanks. It couldn't find this in the documentation I was reading in the
Spring Netflix Cloud section.

**Comment by pmsriram13** [comment]
Thanks, had the same issue.. Its interesting as the annotation @EnableZuulProxy is another jar, hence it was not caught immediately.

**Comment by spencergibb** [comment]
Reopening to not the starter in the docs
