### ISSUE TITLE
Issue with Feign, Ribbon and Eureka

### ISSUE THREAD

**Issue by santhosh0705** [spring-cloud/spring-cloud-netflix#1177]
I have tried to use Feign, Ribbon and Eureka and facing below issue.

> nested exception is feign.RetryableException: Connection refused: connect executing GET http://ClientService1/greeting] with root cause

Code Implementation:

@FeignClient("ClientService1")
interface StoreClient {
	
	//@RequestLine("GET /greeting")
	@RequestMapping(value = "/greeting", method = RequestMethod.GET)
    Greeting getGreeting();

}
------------------
    @Autowired
    StoreClient sc;
return sc.getGreeting();

Its working if we disable eureka and list the servers for ribbon.

**Comment by spencergibb** [comment]
That's not nearly enough information. S
What are your dependencies and configuration? Maybe you have a project to share.

**Comment by santhosh0705** [comment]
Please find the attachment for client proj, and config file which I used in config server.
[MainServices.zip](https://github.com/spring-cloud/spring-cloud-netflix/files/360749/MainServices.zip)
[MainService.yml.txt](https://github.com/spring-cloud/spring-cloud-netflix/files/360750/MainService.yml.txt)

And I have ClientService1 instance already running and registered in eureka.

Can you please help on it.

**Comment by spencergibb** [comment]
No need to set those ribbon properties for ClientService1, like NIWSServerListClassName

**Comment by santhosh0705** [comment]
I tried without those prop also and getting same error. Below is the error stack trace, which shows that it able to get the loadbalancer highlighted below.

2016-07-13 11:04:16.046  INFO 11812 --- [nio-7701-exec-1] c.netflix.loadbalancer.BaseLoadBalancer  : Client:ClientService1 instantiated a LoadBalancer:DynamicServerListLoadBalancer:{NFLoadBalancer:name=ClientService1,current list of Servers=[],Load balancer stats=Zone stats: {},Server stats: []}ServerList:null
2016-07-13 11:04:16.068  INFO 11812 --- [nio-7701-exec-1] c.netflix.config.ChainedDynamicProperty  : Flipping property: ClientService1.ribbon.ActiveConnectionsLimit to use NEXT property: niws.loadbalancer.availabilityFilteringRule.activeConnectionsLimit = 2147483647
2016-07-13 11:04:16.070  INFO 11812 --- [nio-7701-exec-1] c.n.l.DynamicServerListLoadBalancer      : DynamicServerListLoadBalancer for client ClientService1 initialized: DynamicServerListLoadBalancer:**{NFLoadBalancer:name=ClientService1,current list of Servers=[PC286394:7002]**,Load balancer stats=Zone stats: {defaultzone=[Zone:defaultzone;	Instance count:1;	Active connections count: 0;	Circuit breaker tripped count: 0;	Active connections per server: 0.0;]
},Server stats: [[Server:PC286394:7002;	Zone:defaultZone;	Total Requests:0;	Successive connection failure:0;	Total blackout seconds:0;	Last connection made:Thu Jan 01 05:30:00 IST 1970;	First connection made: Thu Jan 01 05:30:00 IST 1970;	Active Connections:0;	total failure count in last (1000) msecs:0;	average resp time:0.0;	90 percentile resp time:0.0;	95 percentile resp time:0.0;	min resp time:0.0;	max resp time:0.0;	stddev resp time:0.0]
]}ServerList:org.springframework.cloud.netflix.ribbon.eureka.DomainExtractingServerList@1c0cdc3
2016-07-13 11:04:17.051  INFO 11812 --- [pool-6-thread-1] c.netflix.config.ChainedDynamicProperty  : Flipping property: ClientService1.ribbon.ActiveConnectionsLimit to use NEXT property: niws.loadbalancer.availabilityFilteringRule.activeConnectionsLimit = 2147483647
2016-07-13 11:04:22.384 ERROR 11812 --- [nio-7701-exec-1] o.a.c.c.C.[.[.[.[dispatcherServlet]      : Servlet.service() for servlet [dispatcherServlet] in context with path [/mainsvc] threw exception [Request processing failed; nested exception is feign.RetryableException: Connection refused: connect executing GET http://ClientService1/clientsvc1/greeting] with root cause

java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:85)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)

**Comment by santhosh0705** [comment]
Hey Spencer,

I just added below lines in both client and server.

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}

Then its started working, I wonder what wrong, but after it started working I put old code without above snippet still its working. 

Is there any issue with Eureka registering ( I seen in Eureka its registered). do you have any idea on it,

**Comment by spencergibb** [comment]
With angel, you need to do that as outlined in the [docs](http://projects.spring.io/spring-cloud/docs/1.0.3/spring-cloud.html#_eureka_metadata_for_instances_and_clients). You are also mixing Angel and Brixton with `spring-cloud-config:1.1.1.RELEASE`. That will have unknown consequences.
