### ISSUE TITLE
colons in query parameter names causes IllegalArgumentException

### ISSUE THREAD

**Issue by lawley** [spring-cloud/spring-cloud-netflix#1193]
When passing in a url with a parameter called ?name:content=john an `IllegalArgumentException` is thrown (see stacktrace below).

This has been narrowed down to `org.springframework.web.util.HierarchicalUriComponents` when it calls `expandQueryParams` method.

```
java.lang.IllegalArgumentException: Map has no value for 'name'
at org.springframework.web.util.UriComponents$MapTemplateVariables.getValue(UriComponents.java:306) ~[spring-web-4.2.6.RELEASE.jar:4.2.6.RELEASE]
    at org.springframework.web.util.UriComponents.expandUriComponent(UriComponents.java:230) ~[spring-web-4.2.6.RELEASE.jar:4.2.6.RELEASE]
    at org.springframework.web.util.HierarchicalUriComponents.expandQueryParams(HierarchicalUriComponents.java:343) ~[spring-web-4.2.6.RELEASE.jar:4.2.6.RELEASE]
    at org.springframework.web.util.HierarchicalUriComponents.expandInternal(HierarchicalUriComponents.java:329) ~[spring-web-4.2.6.RELEASE.jar:4.2.6.RELEASE]
    at org.springframework.web.util.HierarchicalUriComponents.expandInternal(HierarchicalUriComponents.java:47) ~[spring-web-4.2.6.RELEASE.jar:4.2.6.RELEASE]
    at org.springframework.web.util.UriComponents.expand(UriComponents.java:152) ~[spring-web-4.2.6.RELEASE.jar:4.2.6.RELEASE]
    at org.springframework.web.util.UriTemplate.expand(UriTemplate.java:97) ~[spring-web-4.2.6.RELEASE.jar:4.2.6.RELEASE]
    at org.springframework.cloud.netflix.zuul.filters.ProxyRequestHelper.getQueryString(ProxyRequestHelper.java:274)
```

The bug here is in lines 264 and 266 of `ProxyRequestHelper`:
```java
  singles.put(param + i, value);
  query.append("={");
  query.append(param + i);
```

Since param contains a colon, this is interpreted by `UriTemplate` in the subsequent expansion.

One solution is to replace the colon with a character that won't be interpreted when parsing an processing the `UriTemplate`, in a manner that won't cause a clash with another query parameter.

For example, if we replaced `:` with `!` then there would be the chance that both `name:content=john` and `name!content=jane` appeared in the original query string. To avoid this problem we can first replace all instances of `!` in param with `!!`, and then all instances of `:` with `!`.

Original details are here: http://stackoverflow.com/questions/38421000/colons-in-parameter-names-going-through-zuul-maybe-spring-related/38436895#38436895

**Comment by GGYaX** [comment]
Please fix it.

**Comment by spencergibb** [comment]
@GGYaX Pull requests are welcome
