### ISSUE TITLE
Registry my micros Service with euraka failed. pls i need help i have been on this issue for 2 days

### ISSUE THREAD

**Issue by seyijava** [spring-cloud/spring-cloud-netflix#1198]
```
2016-07-20 10:02:42.165 ERROR 10476 --- [pool-4-thread-1] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_BOOKMARK-SERVICE/192.9.200.176 - was unable to refresh its cache! status = java.net.UnknownHostException: registry @dsyer pls help

com.sun.jersey.api.client.ClientHandlerException: java.net.UnknownHostException: registry
        at com.sun.jersey.client.apache4.ApacheHttpClient4Handler.handle(ApacheHttpClient4Handler.java:184)
        at com.sun.jersey.api.client.filter.GZIPContentEncodingFilter.handle(GZIPContentEncodingFilter.java:120)
        at com.netflix.discovery.EurekaIdentityHeaderFilter.handle(EurekaIdentityHeaderFilter.java:28)
        at com.sun.jersey.api.client.Client.handle(Client.java:648)
        at com.sun.jersey.api.client.WebResource.handle(WebResource.java:680)
        at com.sun.jersey.api.client.WebResource.access$200(WebResource.java:74)
        at com.sun.jersey.api.client.WebResource$Builder.get(WebResource.java:507)
        at com.netflix.discovery.DiscoveryClient.getUrl(DiscoveryClient.java:1567)
        at com.netflix.discovery.DiscoveryClient.makeRemoteCall(DiscoveryClient.java:1113)
        at com.netflix.discovery.DiscoveryClient.makeRemoteCall(DiscoveryClient.java:1060)
        at com.netflix.discovery.DiscoveryClient.getAndStoreFullRegistry(DiscoveryClient.java:835)
        at com.netflix.discovery.DiscoveryClient.fetchRegistry(DiscoveryClient.java:746)
        at com.netflix.discovery.DiscoveryClient.access$1400(DiscoveryClient.java:105)
        at com.netflix.discovery.DiscoveryClient$CacheRefreshThread.run(DiscoveryClient.java:1723)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.net.UnknownHostException: registry
        at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
        at java.net.InetAddress$2.lookupAllHostAddr(Unknown Source)
        at java.net.InetAddress.getAddressesFromNameService(Unknown Source)
        at java.net.InetAddress.getAllByName0(Unknown Source)
        at java.net.InetAddress.getAllByName(Unknown Source)
        at java.net.InetAddress.getAllByName(Unknown Source)
        at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:44)
        at org.apache.http.impl.conn.DefaultClientConnectionOperator.resolveHostname(DefaultClientConnectionOperator.java:259)
        at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:159)
        at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:144)
        at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:131)
        at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:611)
        at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:446)
        at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:863)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:115)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
        at com.sun.jersey.client.apache4.ApacheHttpClient4Handler.handle(ApacheHttpClient4Handler.java:170)
        ... 18 common frames omitted
```

my service Configure

```
server:
  port: ${vcap.application.port:8761}
  
  
spring:
  application:
    name: registry
  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: true
      password: 37c31fd6-6f09-49fb-bb23-6c72ba668f99
      username: user

eureka:
  instance:
    prefer-ip-address: false
    hostname: localhost
    
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
       defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    
  server:
    waitTimeInMsWhenSyncEmpty: 0
  dashboard:
    enabled: true
```

pls i need help i have  been on this issue for 2 days can someone Help.

**Comment by dsyer** [comment]
Sorry, you lost me. You showed the config from your eureka server. Is that where the log comes from too? It looks like the log is from a client trying to connect to a service on a host called "registry". I guess you might have a problem with the client?

**Comment by seyijava** [comment]
Yes the log is from the client that that is try to connect. I keep getting that error.  @dsyer help.

**Comment by dsyer** [comment]
Maybe the config from the client is more relevant then, if that's where the error is?

**Comment by seyijava** [comment]
thanks it is the configuration from the client. i got it working . i appreciate

**Comment by gewure** [comment]
hey @seyijava could you maybe remeber what was it that got you running?
