### ISSUE TITLE
Turbine AMQP aggregator fails to de-serialize messages from Hystrix stream

### ISSUE THREAD

**Issue by ogunheper** [spring-cloud/spring-cloud-netflix#126]
Turbine's new AMQP aggregation feature fails to read messages from queue with JsonParseException.

Deserialization fails since AmqpInboundChannelAdapter uses a SimpleMessageConverter. However, the message is in JSON format with "__TypeId__" being "java.lang.String". Issue can be fixed with using a message converter that supports JSON messages, instead of the simple one...

Full stack trace:

```
2014-12-31 04:01:02.438 ERROR 2732 --- [cTaskExecutor-1] o.s.netflix.turbine.amqp.Aggregator      : Error receiving hystrix stream payload: 34,123,92,34,111,114,105,103,105,110,92,34,58,123,92,34,104,111,115,116,92,34,58,92,34,105,116,45,109,97,99,98,111,111,107,45,112,114,111,92,34,44,92,34,112,111,114,116,92,34,58,56,48,56,49,44,92,34,115,101,114,118,105,99,101,73,100,92,34,58,92,34,105,100,100,97,97,45,99,111,114,101,45,109,111,100,117,108,101,92,34,44,92,34,105,100,92,34,58,92,34,105,100,100,97,97,45,99,111,114,101,45,109,111,100,117,108,101,58,116,101,115,116,92,34,125,44,92,34,100,97,116,97,92,34,58,123,92,34,116,121,112,101,92,34,58,92,34,72,121,115,116,114,105,120,67,111,109,109,97,110,100,92,34,44,92,34,110,97,109,101,92,34,58,92,34,112,108,97,121,67,111,117,112,111,110,92,34,44,92,34,103,114,111,117,112,92,34,58,92,34,73,100,100,97,97,83,101,114,118,105,99,101,92,34,44,92,34,99,117,114,114,101,110,116,84,105,109,101,92,34,58,49,52,49,57,57,57,49,50,54,49,57,51,56,44,92,34,105,115,67,105,114,99,117,105,116,66,114,101,97,107,101,114,79,112,101,110,92,34,58,102,97,108,115,101,44,92,34,101,114,114,111,114,80,101,114,99,101,110,116,97,103,101,92,34,58,48,44,92,34,101,114,114,111,114,67,111,117,110,116,92,34,58,48,44,92,34,114,101,113,117,101,115,116,67,111,117,110,116,92,34,58,48,44,92,34,114,111,108,108,105,110,103,67,111,117,110,116,67,111,108,108,97,112,115,101,100,82,101,113,117,101,115,116,115,92,34,58,48,44,92,34,114,111,108,108,105,110,103,67,111,117,110,116,69,120,99,101,112,116,105,111,110,115,84,104,114,111,119,110,92,34,58,48,44,92,34,114,111,108,108,105,110,103,67,111,117,110,116,70,97,105,108,117,114,101,92,34,58,48,44,92,34,114,111,108,108,105,110,103,67,111,117,110,116,70,97,108,108,98,97,99,107,70,97,105,108,117,114,101,92,34,58,48,44,92,34,114,111,108,108,105,110,103,67,111,117,110,116,70,97,108,108,98,97,99,107,82,101,106,101,99,116,105,111,110,92,34,58,48,44,92,34,114,111,108,108,105,110,103,67,111,117,110,116,70,97,108,108,98,97,99,107,83,117,99,99,101,115,115,92,34,58,48,44,92,34,114,111,108,108,105,110,103,67,111,117,110,116,82,101,115,112,111,110,115,101,115,70,114,111,109,67,97,99,104,101,92,34,58,48,44,92,34,114,111,108,108,105,110,103,67,111,117,110,116,83,101,109,97,112,104,111,114,101,82,101,106,101,99,116,101,100,92,34,58,48,44,92,34,114,111,108,108,105,110,103,67,111,117,110,116,83,104,111,114,116,67,105,114,99,117,105,116,101,100,92,34,58,48,44,92,34,114,111,108,108,105,110,103,67,111,117,110,116,83,117,99,99,101,115,115,92,34,58,48,44,92,34,114,111,108,108,105,110,103,67,111,117,110,116,84,104,114,101,97,100,80,111,111,108,82,101,106,101,99,116,101,100,92,34,58,48,44,92,34,114,111,108,108,105,110,103,67,111,117,110,116,84,105,109,101,111,117,116,92,34,58,48,44,92,34,99,117,114,114,101,110,116,67,111,110,99,117,114,114,101,110,116,69,120,101,99,117,116,105,111,110,67,111,117,110,116,92,34,58,49,44,92,34,108,97,116,101,110,99,121,69,120,101,99,117,116,101,95,109,101,97,110,92,34,58,48,44,92,34,108,97,116,101,110,99,121,69,120,101,99,117,116,101,92,34,58,123,92,34,48,92,34,58,48,44,92,34,50,53,92,34,58,48,44,92,34,53,48,92,34,58,48,44,92,34,55,53,92,34,58,48,44,92,34,57,48,92,34,58,48,44,92,34,57,53,92,34,58,48,44,92,34,57,57,92,34,58,48,44,92,34,57,57,46,53,92,34,58,48,44,92,34,49,48,48,92,34,58,48,125,44,92,34,108,97,116,101,110,99,121,84,111,116,97,108,95,109,101,97,110,92,34,58,48,44,92,34,108,97,116,101,110,99,121,84,111,116,97,108,92,34,58,123,92,34,48,92,34,58,48,44,92,34,50,53,92,34,58,48,44,92,34,53,48,92,34,58,48,44,92,34,55,53,92,34,58,48,44,92,34,57,48,92,34,58,48,44,92,34,57,53,92,34,58,48,44,92,34,57,57,92,34,58,48,44,92,34,57,57,46,53,92,34,58,48,44,92,34,49,48,48,92,34,58,48,125,44,92,34,112,114,111,112,101,114,116,121,86,97,108,117,101,95,99,105,114,99,117,105,116,66,114,101,97,107,101,114,82,101,113,117,101,115,116,86,111,108,117,109,101,84,104,114,101,115,104,111,108,100,92,34,58,50,48,44,92,34,112,114,111,112,101,114,116,121,86,97,108,117,101,95,99,105,114,99,117,105,116,66,114,101,97,107,101,114,83,108,101,101,112,87,105,110,100,111,119,73,110,77,105,108,108,105,115,101,99,111,110,100,115,92,34,58,53,48,48,48,44,92,34,112,114,111,112,101,114,116,121,86,97,108,117,101,95,99,105,114,99,117,105,116,66,114,101,97,107,101,114,69,114,114,111,114,84,104,114,101,115,104,111,108,100,80,101,114,99,101,110,116,97,103,101,92,34,58,53,48,44,92,34,112,114,111,112,101,114,116,121,86,97,108,117,101,95,99,105,114,99,117,105,116,66,114,101,97,107,101,114,70,111,114,99,101,79,112,101,110,92,34,58,102,97,108,115,101,44,92,34,112,114,111,112,101,114,116,121,86,97,108,117,101,95,99,105,114,99,117,105,116,66,114,101,97,107,101,114,70,111,114,99,101,67,108,111,115,101,100,92,34,58,102,97,108,115,101,44,92,34,112,114,111,112,101,114,116,121,86,97,108,117,101,95,99,105,114,99,117,105,116,66,114,101,97,107,101,114,69,110,97,98,108,101,100,92,34,58,116,114,117,101,44,92,34,112,114,111,112,101,114,116,121,86,97,108,117,101,95,101,120,101,99,117,116,105,111,110,73,115,111,108,97,116,105,111,110,83,116,114,97,116,101,103,121,92,34,58,92,34,84,72,82,69,65,68,92,34,44,92,34,112,114,111,112,101,114,116,121,86,97,108,117,101,95,101,120,101,99,117,116,105,111,110,73,115,111,108,97,116,105,111,110,84,104,114,101,97,100,84,105,109,101,111,117,116,73,110,77,105,108,108,105,115,101,99,111,110,100,115,92,34,58,49,48,48,48,44,92,34,112,114,111,112,101,114,116,121,86,97,108,117,101,95,101,120,101,99,117,116,105,111,110,73,115,111,108,97,116,105,111,110,84,104,114,101,97,100,73,110,116,101,114,114,117,112,116,79,110,84,105,109,101,111,117,116,92,34,58,116,114,117,101,44,92,34,112,114,111,112,101,114,116,121,86,97,108,117,101,95,101,120,101,99,117,116,105,111,110,73,115,111,108,97,116,105,111,110,84,104,114,101,97,100,80,111,111,108,75,101,121,79,118,101,114,114,105,100,101,92,34,58,110,117,108,108,44,92,34,112,114,111,112,101,114,116,121,86,97,108,117,101,95,101,120,101,99,117,116,105,111,110,73,115,111,108,97,116,105,111,110,83,101,109,97,112,104,111,114,101,77,97,120,67,111,110,99,117,114,114,101,110,116,82,101,113,117,101,115,116,115,92,34,58,49,48,44,92,34,112,114,111,112,101,114,116,121,86,97,108,117,101,95,102,97,108,108,98,97,99,107,73,115,111,108,97,116,105,111,110,83,101,109,97,112,104,111,114,101,77,97,120,67,111,110,99,117,114,114,101,110,116,82,101,113,117,101,115,116,115,92,34,58,49,48,44,92,34,112,114,111,112,101,114,116,121,86,97,108,117,101,95,109,101,116,114,105,99,115,82,111,108,108,105,110,103,83,116,97,116,105,115,116,105,99,97,108,87,105,110,100,111,119,73,110,77,105,108,108,105,115,101,99,111,110,100,115,92,34,58,49,48,48,48,48,44,92,34,112,114,111,112,101,114,116,121,86,97,108,117,101,95,114,101,113,117,101,115,116,67,97,99,104,101,69,110,97,98,108,101,100,92,34,58,116,114,117,101,44,92,34,112,114,111,112,101,114,116,121,86,97,108,117,101,95,114,101,113,117,101,115,116,76,111,103,69,110,97,98,108,101,100,92,34,58,116,114,117,101,44,92,34,114,101,112,111,114,116,105,110,103,72,111,115,116,115,92,34,58,49,125,125,34

com.fasterxml.jackson.core.JsonParseException: Unexpected character (',' (code 44)): Expected space separating root-level values
 at [Source: 34,123,92,34,111,114,105,103,105,110,92,34,58,123,92,34,104,111,115,116,92,34,58,92,34,105,116,45,109,97,99,98,111,111,107,45,112,114,111,92,34,44,92,34,112,111,114,116,92,34,58,56,48,56,49,44,92,34,115,101,114,118,105,99,101,73,100,92,34,58,92,34,105,100,100,97,97,45,99,111,114,101,45,109,111,100,117,108,101,92,34,44,92,34,105,100,92,34,58,92,34,105,100,100,97,97,45,99,111,114,101,45,109,111,100,117,108,101,58,116,101,115,116,92,34,125,44,92,34,100,97,116,97,92,34,58,123,92,34,116,121,112,101,92,34,58,92,34,72,121,115,116,114,105,120,67,111,109,109,97,110,100,92,34,44,92,34,110,97,109,101,92,34,58,92,34,112,108,97,121,67,111,117,112,111,110,92,34,44,92,34,103,114,111,117,112,92,34,58,92,34,73,100,100,97,97,83,101,114,118,105,99,101,92,34,44,92,34,99,117,114,114,101,110,116,84,105,109,101,92,34,58,49,52,49,57,57,57,49,50,54,49,57,51,56,44,92,34,105,115,67,105,114,99,117,105,116,66,114,101,97,107,101,114,79,112,101,110,92,34,58,102,97,108,115,101,44,92,34,101,114,114,111,114,80,101,114,99,101,110,116,97,103,101,92,34,58,48,44,92,34,101,114,114,111,114,67,111,117,110,116,92,34,58,48,44,92,34,114,101,113,117,101,115,116,67,111,117,110,116,92,34,58,48,44,92,34,114,111,108,108,105,110,103,67,111,117,110,116,67,111,108,108,97,112,115,101,100,82,101,113,117,101,115,116,115,92,34,58,48,44,92,34,114,111,108,108,105,110,103,67,111,117,110,116,69,120,99,101,112,116,105,111,110,115,84,104,114,111,119,110,92,34,58,48,44,92,34,114,111,108,108,105,110,103,67,111,117,110,116,70,97,105,108,117,114,101,92,34,58,48,44,92,34,114,111,108,108,105,110,103,67,111,117,110,116,70,97,108,108,98,97,99,107,70,97,105,108,117,114,101,92,34,58,48,44,92,34,114,111,108,108,105,110,103,67,111,117,110,116,70,97,108,108,98,97,99,107,82,101,106,101,99,116,105,111,110,92,34,58,48,44,92,34,114,111,108,108,105,110,103,67,111,117,110,116,70,97,108,108,98,97,99,107,83,117,99,99,101,115,115,92,34,58,48,44,92,34,114,111,108,108,105,110,103,67,111,117,110,116,82,101,115,112,111,110,115,101,115,70,114,111,109,67,97,99,104,101,92,34,58,48,44,92,34,114,111,108,108,105,110,103,67,111,117,110,116,83,101,109,97,112,104,111,114,101,82,101,106,101,99,116,101,100,92,34,58,48,44,92,34,114,111,108,108,105,110,103,67,111,117,110,116,83,104,111,114,116,67,105,114,99,117,105,116,101,100,92,34,58,48,44,92,34,114,111,108,108,105,110,103,67,111,117,110,116,83,117,99,99,101,115,115,92,34,58,48,44,92,34,114,111,108,108,105,110,103,67,111,117,110,116,84,104,114,101,97,100,80,111,111,108,82,101,106,101,99,116,101,100,92,34,58,48,44,92,34,114,111,108,108,105,110,103,67,111,117,110,116,84,105,109,101,111,117,116,92,34,58,48,44,92,34,99,117,114,114,101,110,116,67,111,110,99,117,114,114,101,110,116,69,120,101,99,117,116,105,111,110,67,111,117,110,116,92,34,58,49,44,92,34,108,97,116,101,110,99,121,69,120,101,99,117,116,101,95,109,101,97,110,92,34,58,48,44,92,34,108,97,116,101,110,99,121,69,120,101,99,117,116,101,92,34,58,123,92,34,48,92,34,58,48,44,92,34,50,53,92,34,58,48,44,92,34,53,48,92,34,58,48,44,92,34,55,53,92,34,58,48,44,92,34,57,48,92,34,58,48,44,92,34,57,53,92,34,58,48,44,92,34,57,57,92,34,58,48,44,92,34,57,57,46,53,92,34,58,48,44,92,34,49,48,48,92,34,58,48,125,44,92,34,108,97,116,101,110,99,121,84,111,116,97,108,95,109,101,97,110,92,34,58,48,44,92,34,108,97,116,101,110,99,121,84,111,116,97,108,92,34,58,123,92,34,48,92,34,58,48,44,92,34,50,53,92,34,58,48,44,92,34,53,48,92,34,58,48,44,92,34,55,53,92,34,58,48,44,92,34,57,48,92,34,58,48,44,92,34,57,53,92,34,58,48,44,92,34,57,57,92,34,58,48,44,92,34,57,57,46,53,92,34,58,48,44,92,34,49,48,48,92,34,58,48,125,44,92,34,112,114,111,112,101,114,116,121,86,97,108,117,101,95,99,105,114,99,117,105,116,66,114,101,97,107,101,114,82,101,113,117,101,115,116,86,111,108,117,109,101,84,104,114,101,115,104,111,108,100,92,34,58,50,48,44,92,34,112,114,111,112,101,114,116,121,86,97,108,117,101,95,99,105,114,99,117,105,116,66,114,101,97,107,101,114,83,108,101,101,112,87,105,110,100,111,119,73,110,77,105,108,108,105,115,101,99,111,110,100,115,92,34,58,53,48,48,48,44,92,34,112,114,111,112,101,114,116,121,86,97,108,117,101,95,99,105,114,99,117,105,116,66,114,101,97,107,101,114,69,114,114,111,114,84,104,114,101,115,104,111,108,100,80,101,114,99,101,110,116,97,103,101,92,34,58,53,48,44,92,34,112,114,111,112,101,114,116,121,86,97,108,117,101,95,99,105,114,99,117,105,116,66,114,101,97,107,101,114,70,111,114,99,101,79,112,101,110,92,34,58,102,97,108,115,101,44,92,34,112,114,111,112,101,114,116,121,86,97,108,117,101,95,99,105,114,99,117,105,116,66,114,101,97,107,101,114,70,111,114,99,101,67,108,111,115,101,100,92,34,58,102,97,108,115,101,44,92,34,112,114,111,112,101,114,116,121,86,97,108,117,101,95,99,105,114,99,117,105,116,66,114,101,97,107,101,114,69,110,97,98,108,101,100,92,34,58,116,114,117,101,44,92,34,112,114,111,112,101,114,116,121,86,97,108,117,101,95,101,120,101,99,117,116,105,111,110,73,115,111,108,97,116,105,111,110,83,116,114,97,116,101,103,121,92,34,58,92,34,84,72,82,69,65,68,92,34,44,92,34,112,114,111,112,101,114,116,121,86,97,108,117,101,95,101,120,101,99,117,116,105,111,110,73,115,111,108,97,116,105,111,110,84,104,114,101,97,100,84,105,109,101,111,117,116,73,110,77,105,108,108,105,115,101,99,111,110,100,115,92,34,58,49,48,48,48,44,92,34,112,114,111,112,101,114,116,121,86,97,108,117,101,95,101,120,101,99,117,116,105,111,110,73,115,111,108,97,116,105,111,110,84,104,114,101,97,100,73,110,116,101,114,114,117,112,116,79,110,84,105,109,101,111,117,116,92,34,58,116,114,117,101,44,92,34,112,114,111,112,101,114,116,121,86,97,108,117,101,95,101,120,101,99,117,116,105,111,110,73,115,111,108,97,116,105,111,110,84,104,114,101,97,100,80,111,111,108,75,101,121,79,118,101,114,114,105,100,101,92,34,58,110,117,108,108,44,92,34,112,114,111,112,101,114,116,121,86,97,108,117,101,95,101,120,101,99,117,116,105,111,110,73,115,111,108,97,116,105,111,110,83,101,109,97,112,104,111,114,101,77,97,120,67,111,110,99,117,114,114,101,110,116,82,101,113,117,101,115,116,115,92,34,58,49,48,44,92,34,112,114,111,112,101,114,116,121,86,97,108,117,101,95,102,97,108,108,98,97,99,107,73,115,111,108,97,116,105,111,110,83,101,109,97,112,104,111,114,101,77,97,120,67,111,110,99,117,114,114,101,110,116,82,101,113,117,101,115,116,115,92,34,58,49,48,44,92,34,112,114,111,112,101,114,116,121,86,97,108,117,101,95,109,101,116,114,105,99,115,82,111,108,108,105,110,103,83,116,97,116,105,115,116,105,99,97,108,87,105,110,100,111,119,73,110,77,105,108,108,105,115,101,99,111,110,100,115,92,34,58,49,48,48,48,48,44,92,34,112,114,111,112,101,114,116,121,86,97,108,117,101,95,114,101,113,117,101,115,116,67,97,99,104,101,69,110,97,98,108,101,100,92,34,58,116,114,117,101,44,92,34,112,114,111,112,101,114,116,121,86,97,108,117,101,95,114,101,113,117,101,115,116,76,111,103,69,110,97,98,108,101,100,92,34,58,116,114,117,101,44,92,34,114,101,112,111,114,116,105,110,103,72,111,115,116,115,92,34,58,49,125,125,34; line: 1, column: 4]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1419)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:508)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:437)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportMissingRootWS(ParserMinimalBase.java:453)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._verifyRootSpace(ReaderBasedJsonParser.java:1236)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._parsePosNumber(ReaderBasedJsonParser.java:886)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:680)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3105)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3051)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2161)
	at org.springframework.netflix.turbine.amqp.Aggregator.handle(Aggregator.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.springframework.expression.spel.support.ReflectiveMethodExecutor.execute(ReflectiveMethodExecutor.java:112)
	at org.springframework.expression.spel.ast.MethodReference.getValueInternal(MethodReference.java:129)
	at org.springframework.expression.spel.ast.MethodReference.access$000(MethodReference.java:49)
	at org.springframework.expression.spel.ast.MethodReference$MethodValueRef.getValue(MethodReference.java:342)
	at org.springframework.expression.spel.ast.CompoundExpression.getValueInternal(CompoundExpression.java:88)
	at org.springframework.expression.spel.ast.SpelNodeImpl.getTypedValue(SpelNodeImpl.java:131)
	at org.springframework.expression.spel.standard.SpelExpression.getValue(SpelExpression.java:330)
	at org.springframework.integration.util.AbstractExpressionEvaluator.evaluateExpression(AbstractExpressionEvaluator.java:164)
	at org.springframework.integration.util.MessagingMethodInvokerHelper.processInternal(MessagingMethodInvokerHelper.java:276)
	at org.springframework.integration.util.MessagingMethodInvokerHelper.process(MessagingMethodInvokerHelper.java:142)
	at org.springframework.integration.handler.MethodInvokingMessageProcessor.processMessage(MethodInvokingMessageProcessor.java:75)
	at org.springframework.integration.handler.ServiceActivatingHandler.handleRequestMessage(ServiceActivatingHandler.java:71)
	at org.springframework.integration.handler.AbstractReplyProducingMessageHandler.handleMessageInternal(AbstractReplyProducingMessageHandler.java:99)
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:78)
	at org.springframework.integration.dispatcher.AbstractDispatcher.tryOptimizedDispatch(AbstractDispatcher.java:116)
	at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:101)
	at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:97)
	at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:77)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:277)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:239)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:115)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:45)
	at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:95)
	at org.springframework.integration.handler.AbstractMessageProducingHandler.sendOutput(AbstractMessageProducingHandler.java:248)
	at org.springframework.integration.handler.AbstractMessageProducingHandler.produceOutput(AbstractMessageProducingHandler.java:171)
	at org.springframework.integration.handler.AbstractMessageProducingHandler.sendOutputs(AbstractMessageProducingHandler.java:119)
	at org.springframework.integration.handler.AbstractReplyProducingMessageHandler.handleMessageInternal(AbstractReplyProducingMessageHandler.java:105)
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:78)
	at org.springframework.integration.dispatcher.AbstractDispatcher.tryOptimizedDispatch(AbstractDispatcher.java:116)
	at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:101)
	at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:97)
	at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:77)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:277)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:239)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:115)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:45)
	at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:95)
	at org.springframework.integration.endpoint.MessageProducerSupport.sendMessage(MessageProducerSupport.java:101)
	at org.springframework.integration.amqp.inbound.AmqpInboundChannelAdapter.access$400(AmqpInboundChannelAdapter.java:45)
	at org.springframework.integration.amqp.inbound.AmqpInboundChannelAdapter$1.onMessage(AmqpInboundChannelAdapter.java:93)
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:694)
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:617)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.access$001(SimpleMessageListenerContainer.java:82)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$1.invokeListener(SimpleMessageListenerContainer.java:167)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.invokeListener(SimpleMessageListenerContainer.java:1196)
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.executeListener(AbstractMessageListenerContainer.java:600)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.doReceiveAndExecute(SimpleMessageListenerContainer.java:960)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.receiveAndExecute(SimpleMessageListenerContainer.java:944)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.access$700(SimpleMessageListenerContainer.java:82)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.run(SimpleMessageListenerContainer.java:1058)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by dsyer** [comment]
I'm not sure why the incoming messages were in JSON. Maybe you were using different versions of the client and server? Anyway I added explicit `MessageConverters` to both sides now and it seems to be working.
