### ISSUE TITLE
DebugFilter throw: java.lang.IllegalStateException: Cannot parse the request!

### ISSUE THREAD

**Issue by WeipingGuo** [spring-cloud/spring-cloud-netflix#1395]
Running on 1.0.7 release, found some exceptions from the log files.  Any suggestions?

```
Caused by: java.lang.IllegalStateException: Cannot parse the request!
        at com.netflix.zuul.http.HttpServletRequestWrapper.getParameter(HttpServletRequestWrapper.java:259)
        at org.springframework.cloud.netflix.zuul.filters.pre.DebugFilter.shouldFilter(DebugFilter.java:52)
        at com.netflix.zuul.ZuulFilter.runFilter(ZuulFilter.java:109)
        at com.netflix.zuul.FilterProcessor.processZuulFilter(FilterProcessor.java:197)
        ... 89 common frames omitted
Caused by: java.io.EOFException: Unexpected EOF read on the socket
        at org.apache.coyote.http11.InternalNioInputBuffer.fill(InternalNioInputBuffer.java:152)
        at org.apache.coyote.http11.InternalNioInputBuffer$SocketInputBuffer.doRead(InternalNioInputBuffer.java:177)
        at org.apache.coyote.http11.filters.IdentityInputFilter.doRead(IdentityInputFilter.java:110)
        at org.apache.coyote.http11.AbstractInputBuffer.doRead(AbstractInputBuffer.java:414)
        at org.apache.coyote.Request.doRead(Request.java:476)
        at org.apache.catalina.connector.InputBuffer.realReadBytes(InputBuffer.java:350)
        at org.apache.tomcat.util.buf.ByteChunk.substract(ByteChunk.java:395)
        at org.apache.catalina.connector.InputBuffer.read(InputBuffer.java:375)
        at org.apache.catalina.connector.CoyoteInputStream.read(CoyoteInputStream.java:156)
        at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1792)
        at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1769)
        at org.apache.commons.io.IOUtils.copy(IOUtils.java:1744)
        at com.netflix.zuul.http.HttpServletRequestWrapper.parseRequest(HttpServletRequestWrapper.java:151)
        at com.netflix.zuul.http.HttpServletRequestWrapper.getParameter(HttpServletRequestWrapper.java:257)
        ... 92 common frames omitted

```

**Comment by spencergibb** [comment]
Google?

I found these. Generally it seems to be an issue with the client.

http://stackoverflow.com/questions/23359727/tomcat-eofexception-unexpected-eof-read-on-the-socket

https://github.com/spring-projects/spring-boot/issues/1223

**Comment by WeipingGuo** [comment]
@spencergibb Thanks! I was focusing on DebugFilter code. Looks like not very much we can do from the server side?

**Comment by spencergibb** [comment]
Not that I can think of.

**Comment by WeipingGuo** [comment]
@spencergibb thanks.
