### ISSUE TITLE
How to increase the connection pool size

### ISSUE THREAD

**Issue by WeipingGuo** [spring-cloud/spring-cloud-netflix#1466]
Hi,

I am getting exception of "Timeout waiting for connection from pool", but not sure how to adjust the pool size. I tried:
```
 ribbon:
      MaxConnectionsPerHost: 100
      MaxTotalConnections: 400
```
but appears no impact. Any suggestions are appreciated!
```
Caused by: com.netflix.client.ClientException: null
 at com.netflix.client.AbstractLoadBalancerAwareClient.executeWithLoadBalancer(AbstractLoadBalancerAwareClient.java:123)
 at com.netflix.client.AbstractLoadBalancerAwareClient.executeWithLoadBalancer(AbstractLoadBalancerAwareClient.java:81)
 at org.springframework.cloud.netflix.zuul.filters.route.RibbonCommand.forward(RibbonCommand.java:132)
 at org.springframework.cloud.netflix.zuul.filters.route.RibbonCommand.run(RibbonCommand.java:106)
 at org.springframework.cloud.netflix.zuul.filters.route.RibbonCommand.run(RibbonCommand.java:1)
 at com.netflix.hystrix.HystrixCommand$1.call(HystrixCommand.java:294) 
... 135 common frames omitted 
 Caused by: org.apache.http.conn.ConnectionPoolTimeoutException: Timeout waiting for connection from pool
 at org.apache.http.impl.conn.tsccm.ConnPoolByRoute.getEntryBlocking(ConnPoolByRoute.java:412)
 at com.netflix.http4.NamedConnectionPool.getEntryBlocking(NamedConnectionPool.java:141)
 at org.apache.http.impl.conn.tsccm.ConnPoolByRoute$1.getPoolEntry(ConnPoolByRoute.java:298)
 at org.apache.http.impl.conn.tsccm.ThreadSafeClientConnManager$1.getConnection(ThreadSafeClientConnManager.java:238)
 at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:423)
 at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:863)
 at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:115)
 at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
 at com.sun.jersey.client.apache4.ApacheHttpClient4Handler.handle(ApacheHttpClient4Handler.java:170)
 at com.sun.jersey.api.client.Client.handle(Client.java:648)
 at com.sun.jersey.api.client.WebResource.handle(WebResource.java:670)
 at com.sun.jersey.api.client.WebResource.access$200(WebResource.java:74)
 at com.sun.jersey.api.client.WebResource$Builder.post(WebResource.java:563)
 at com.netflix.niws.client.http.RestClient.execute(RestClient.java:621)
 at com.netflix.niws.client.http.RestClient.execute(RestClient.java:527)
 at com.netflix.niws.client.http.RestClient.execute(RestClient.java:92)
 at com.netflix.client.AbstractLoadBalancerAwareClient$1.call(AbstractLoadBalancerAwareClient.java:109)
 at com.netflix.loadbalancer.reactive.LoadBalancerCommand$3$1.call(LoadBalancerCommand.java:303)
 at com.netflix.loadbalancer.reactive.LoadBalancerCommand$3$1.call(LoadBalancerCommand.java:287)
 at rx.internal.operators.OperatorMap$1.onNext(OperatorMap.java:55)
 at rx.internal.util.ScalarSynchronousObservable$1.call(ScalarSynchronousObservable.java:43) 
```

Thanks
Weiping

**Comment by spencergibb** [comment]
Have you tried `PoolMaxThreads`?

https://github.com/Netflix/ribbon/blob/master/ribbon-core/src/main/java/com/netflix/client/config/CommonClientConfigKey.java#L69-L71

**Comment by WeipingGuo** [comment]
@spencergibb thanks. Looked through the source, PoolMaxThreads --> https://github.com/Netflix/ribbon/blob/3a707ec518a896053be44266dddc4c4f925f4e60/ribbon-core/src/main/java/com/netflix/client/config/DefaultClientConfigImpl.java#L331 --> DEFAULT_MAX_TOTAL_HTTP_CONNECTIONS = 200.

Seems default value is sufficient.  I will give a try anyway. 

Also does this property also help: zuul.host.maxPerRouteConnections?

Thanks
Weiping

**Comment by WeipingGuo** [comment]
@spencergibb I eventually figured out which properties to use. https://github.com/Netflix/ribbon/blob/master/ribbon-core/src/main/java/com/netflix/client/config/CommonClientConfigKey.java#L83
Even though it is marked as Deprecated, it is actually being used instead of `MaxConnectionsPerHost`. 

```
ribbon:
  listOfServers: my-server:8080  
  MaxHttpConnectionsPerHost: 100 
```
Turned on the debugging, I can see from the log when running 80 concurrent requests:

`com.netflix.http4.NamedConnectionPool    : [{}->http://my-server:8080] total kept alive: 17, total issued: 62, total allocated: 79 out of 200`

By default, running concurrent requests more than 50 will trigger `Timeout waiting for connection from pool`, and log shows:
` com.netflix.http4.NamedConnectionPool    : [{}->http://my-server:8080] total kept alive: 12, total issued: 38, total allocated: 50 out of 200`

I am unable to locate where this property is initialized. Here is the test case:
https://github.com/Netflix/ribbon/blob/5e6066dd63253014599b4fd89713a7b51f19d165/ribbon-httpclient/src/test/java/com/netflix/http4/NamedConnectionPoolTest.java#L77

Looks like this is a bug to me. 

Thanks
Weiping

**Comment by WeipingGuo** [comment]
Opened a bug report against Netflix/ribbon.
