### ISSUE TITLE
Feign bug when use @RequestParam but not have value

### ISSUE THREAD

**Issue by 924060929** [spring-cloud/spring-cloud-netflix#1482]
The jar is spring-cloud-netflix-core-1.2.2.RELEASE-sources.jar

In the code org\springframework\cloud\netflix\feign\annotation\RequestParamParameterProcessor.java, the method "processArgument" treat @RequestParam param as Map when the value is empty, but in spring mvc, when @RequestParam's value is null, reflect the field name as the value. This diffrent action can make misunderstand.

As follows:

	@Override
	public boolean processArgument(AnnotatedParameterContext context,
			Annotation annotation) {
		RequestParam requestParam = ANNOTATION.cast(annotation);
		String name = requestParam.value();
		if (emptyToNull(name) != null) {
			context.setParameterName(name);

			MethodMetadata data = context.getMethodMetadata();
			Collection<String> query = context.setTemplateParameter(name,
					data.template().queries().get(name));
			data.template().query(name, query);
		} else {
			// supports `Map` types
			MethodMetadata data = context.getMethodMetadata();
			data.queryMapIndex(context.getParameterIndex());
		}
		return true;
	}

Please fix it, :)

**Comment by lowzj** [comment]
Spring Cloud Feign supports simple and map request parameter.
It reflects the field name as the value in another method `SpringMvcContract#synthesizeWithMethodParameterNameAsFallbackValue`. And it synthesizes RequestParam's value when RequestParam's value is null and the parameter is a simple property(checked by using `BeanUtils#isSimpleProperty`).

related issue: https://github.com/spring-cloud/spring-cloud-netflix/issues/1097

**Comment by ryanjbaxter** [comment]
@lowzj so if the `@RequestParam` is a `Map` the value will be an empty `Map` but if the `@RequestParam` is a "simple property" the value will be `null`?

**Comment by lowzj** [comment]
@ryanjbaxter I'm sorry for my unclear description. For examples:

* if the parameter is a `Map`, the value of `@RequestParam` will be empty(default value `""`). And we should not set the value.
  ```java
  User getUser(@RequestParam Map<String, String> query);
  ```

* if the parameter is a "simple property" and we don't set the `@RequestParam` value, `SpringMvcContract` will synthesizes with the parameter's name as fallback value, so the value of `@RequestParam` will not be empty.
  ```java
  // the value of @RequestParam will be "name"
  User getUser(@RequestParam String name);
  ```

* if the the parameter is a "simple property" and we give a value , the value of `@RequestParam` will not be empty.
  ```java
  // the value of @RequestParam will be "name"
  User getUser(@RequestParam("name") String name);
  ```

**Comment by ryanjbaxter** [comment]
@lowzj and this is also the same behavior as Spring MVC? It sounds like @924060929 is saying it is not the same behavior.

**Comment by 924060929** [comment]
@ryanjbaxter @lowzj Sorray, forgot to show my code.

Feign client interface code:

    @FeignClient(serviceId="Do-authority")
    public interface IDoAuthorityService {
        @RequestMapping(path = "hasUser", method = RequestMethod.GET)
        LinkedHashMap hasUser(@RequestParam String username);
    }

Program throw exception when startup:

    Caused by: java.lang.IllegalStateException: QueryMap parameter must be a Map: class java.lang.String
	at feign.Util.checkState(Util.java:128) ~[feign-core-9.3.1.jar:na]
	at feign.Contract$BaseContract.parseAndValidateMetadata(Contract.java:126) ~[feign-core-9.3.1.jar:na]
	at org.springframework.cloud.netflix.feign.support.SpringMvcContract.parseAndValidateMetadata(SpringMvcContract.java:133) ~[spring-cloud-netflix-core-1.2.2.RELEASE.jar:1.2.2.RELEASE]
	at feign.Contract$BaseContract.parseAndValidatateMetadata(Contract.java:64) ~[feign-core-9.3.1.jar:na]
	at feign.hystrix.HystrixDelegatingContract.parseAndValidatateMetadata(HystrixDelegatingContract.java:34) ~[feign-hystrix-9.3.1.jar:na]
	at feign.ReflectiveFeign$ParseHandlersByName.apply(ReflectiveFeign.java:146) ~[feign-core-9.3.1.jar:na]
	at feign.ReflectiveFeign.newInstance(ReflectiveFeign.java:53) ~[feign-core-9.3.1.jar:na]
	at feign.Feign$Builder.target(Feign.java:209) ~[feign-core-9.3.1.jar:na]
	at org.springframework.cloud.netflix.feign.HystrixTargeter.target(HystrixTargeter.java:48) ~[spring-cloud-netflix-core-1.2.2.RELEASE.jar:1.2.2.RELEASE]
	at org.springframework.cloud.netflix.feign.FeignClientFactoryBean.loadBalance(FeignClientFactoryBean.java:146) ~[spring-cloud-netflix-core-1.2.2.RELEASE.jar:1.2.2.RELEASE]
	at org.springframework.cloud.netflix.feign.FeignClientFactoryBean.getObject(FeignClientFactoryBean.java:167) ~[spring-cloud-netflix-core-1.2.2.RELEASE.jar:1.2.2.RELEASE]
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:168) ~[spring-beans-4.3.4.RELEASE.jar:4.3.4.RELEASE]
	... 29 common frames omitted

**Comment by ryanjbaxter** [comment]
I think I understand the problem better now.  Correct me if I am wrong...

It seems like Spring MVC allows you to specify query parameters in a `GET` request using `@RequestMapping` and a basic type.  However Feign expects query parameters to be a type `Map`.  Since we are using Spring MVC to create Feign clients Feign is complaining because it is expecting the query parameters in the method signature to be a type `Map`.  Does that basically describe the problem?

**Comment by 924060929** [comment]
Yes, that's what you said

**Comment by ryanjbaxter** [comment]
If that is the case maybe you can open an issue in OpenFeign to see if this is something they can help support.  I don't really see a way to change the behavior from our side.  Maybe in Feign they can do something similar to Spring MVC so that if the method signature contains basic types it takes the parameters and converts them to a Map with keys being the parameter names.

**Comment by lowzj** [comment]
@924060929 I guess that you're using java8 to compile your code. Java8 has a different way to preserve method parameter names and make them available at runtime by using javac compiler argument `-parameters`.

more information may be helpful:
https://github.com/spring-cloud/spring-cloud-netflix/pull/1102
[Obtaining Names of Method Parameters](https://docs.oracle.com/javase/tutorial/reflect/member/methodparameterreflection.html)
