### ISSUE TITLE
Retry on specific http response codes

### ISSUE THREAD

**Issue by jimmi-skaria** [spring-cloud/spring-cloud-netflix#1540]
Hi
 I am trying Ribbon and Hystrix with following configuration property  based on the solution suggested here . 

http://stackoverflow.com/questions/37272996/zuul-ribbon-hystrix-not-retrying-on-different-instance?noredirect=1&lq=1

```
<ServiceId>.ribbon.listOfServers= https://approute1.g1.cloud.mycompany.net/api/v1/status,https://approute2..g2..cloud.mycompany.net/api/v1/status 
<ServiceId>.ribbon.ReadTimeout=800
<ServiceId>.ribbon.ConnectTimeout=250
<ServiceId>.ribbon.OkToRetryOnAllOperations=true
<ServiceId>.ribbon.MaxAutoRetriesNextServer=2
<ServiceId>.ribbon.MaxAutoRetries=0
hystrix.command.<ServiceId>.execution.isolation.strategy=THREAD
hystrix.command.<ServiceId>.execution.isolation.thread.timeoutInMilliseconds=100000

```
List of servers are in  Cloud foundry and in Cloud foundry returns  "404 Not Found: Requested route" when app is down. 
with the Default implementation 404 HTTP response code  does not trigger fallback within ribbon to try the next server in the list . I would like to Customize  Ribbons Response handler to  trigger fallback to the next server in the list on 404 . How can we achieve this !? 

Retry is working fine when one of the server in the list is not reachable (Connection Time out).

I would like to achieve the same in Zuul also .  Once the above question is answered I guess I can apply the same for zuul as well .

**Comment by jimmi-skaria** [comment]
The above configuration is tested  with SPring boot  1.4.2.RELEASE

**Comment by spencergibb** [comment]
Brixton.RELEASE is fairly old. Brixton.SR7 is the latest. Will you try with that?

Zuul in Brixton uses semaphore isolation and it can't be changed (it can in Camden).

**Comment by jimmi-skaria** [comment]
Thanks Spencer for the quick reply .  Tested with Camden.SR3 and  Brixton.SR7 . Behavior remains the same . 404   does not trigger fallback within ribbon to try the next server in the list . But a Custom fallback like this is triggered on 404  
````
@FeignClient(name="notificationstatus.messagereceiver", fallback = NotificationStatusServiceMessagingClient.class)
public interface NotificationStatusServiceClient{

	@RequestMapping(method = RequestMethod.POST, value = "/api/v1/NotificationStatus", consumes = "application/json")
	public void postNotificationStatus(NotificationStatus status);
	
}

```
I lookedat  the comment in the ResponseValidator.java here https://gist.github.com/allenxwang/9f290dc863705bb4903f , Perhaps that explains the behavior . I am looking for a way to Customize this so that Ribbon tries the next next server in the list on 404.

**Comment by spencergibb** [comment]
Would have been nice to mention your use of feign. There is a PR to fix that #1457

**Comment by jimmi-skaria** [comment]
Found a similar question : http://stackoverflow.com/questions/37614202/feign-retry-depending-on-response-status

**Comment by jimmi-skaria** [comment]
@spencergibb  please  take look at this question when you get a chance . 
http://stackoverflow.com/questions/41183120/spring-cloud-netflix-feign-ribbon-hystrix-how-to-identify-if-the-feign-exec

**Comment by ryanjbaxter** [comment]
@jimmi-skaria were you able to verify that PR #1457 fixes the issue?

**Comment by jimmi-skaria** [comment]
@ryanjbaxter  Sorry for a late reply on this . I was on "sick" vacation for last two months. I haven't got a chance verify if the PR #1457 fixes the issue discussed here yet. Now I am back at work I can try  this. Let me see if I can figure out how to include the dependency with this this particular change and test. following is the current pom.xml configuration. or if you could provide quick pointer on  how to change my pom.xml  to get the changes in PR #1457, that would be great! 
  ```<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-dependencies</artifactId>
				<version>Camden.SR3</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>
```

**Comment by ryanjbaxter** [comment]
No problem.  Actually there have been more changes since Dec.  If you could try out `Camden.BUILD-SNAPSHOT` that would get you the latest and greatest changes.

**Comment by jimmi-skaria** [comment]
@ryanjbaxter I tried  <version>Camden.SR3</version> . but somehow , invalid pom.xml files were dowloaded . The pom.xml contained index.html content. Could not figure why this is happening :-( .  any other version I can try ?

**Comment by spencergibb** [comment]
Camden.SR6 is the latest.

**Comment by jimmi-skaria** [comment]
Sorry for the wrong version number in my previous message  ,I wanted to say, I tried 'Camden.BUILD-SNAPSHOT'  which gave me invalid pom.xmls .  not  Camden.SR3. I would like to test the  fix for PR #1457 .   which version I can try for that ? Does Camden.SR6  has the fix for   PR #1457 ? if not please suggest a version where I can test this PR .

**Comment by ryanjbaxter** [comment]
Yes it is in `Camden.SR6`

**Comment by jimmi-skaria** [comment]
Thanks . I will try Camden.SR6 for PR #1457 .

**Comment by jimmi-skaria** [comment]
I tested with Camden.SR6 . I don't see any Difference in the behavior  when response from the  one of the server is 404 . it doesn't  retry with  next server . does the  fix expect any  additional coding  or usage of any other  annotations? 

```
@FeignClient(name="notificationstatus.messagereceiver", configuration = FeignClientConfiguration.class)
public interface NotificationStatusServiceClient{

	@RequestMapping(method = RequestMethod.POST, value = "/api/v1/NotificationStatus", consumes = "application/json")
	public void postNotificationStatus(NotificationStatus status) throws Exception;
	
}
```

**Comment by spencergibb** [comment]
Do you have `spring-retry` on the classpath?

**Comment by jimmi-skaria** [comment]
No. Let me try adding that .

**Comment by spencergibb** [comment]
It is required for the new retry.

**Comment by jimmi-skaria** [comment]
no luck so far . I tried adding @EnableTry annotation as well .  Giving my main config for  you  to point out any  issues . Feign client is part of another jar file , which is included in the pom.xml as a dependency

Also found the documentation here . 
http://cloud.spring.io/spring-cloud-static/spring-cloud-netflix/1.3.0.RC1/#Retrying Failed Requests
Based on that I guess there is nothing else  needs to be done .

main app class
```
@SpringBootApplication
@EnableScheduling
@EnableFeignClients(basePackages = {"notifications.status.collector.messagepublisher"})
@EnableHystrix
//@EnableRetry
@ComponentScan({"com.comcast.emm.aupm.ubb.notifications.status"})
@EnableAutoConfiguration(exclude={OAuth2AutoConfiguration.class,RabbitAutoConfiguration.class })
@EnableJpaRepositories(basePackages = "com.comcast.emm.aupm.ubb.notifications.status.collector.dao")
@EntityScan(basePackages="com.comcast.emm.aupm.ubb.notifications.status.collector.model")
public class MyApp {

	public static void main(String[] args) {
		SpringApplication.run(EMSCollectorApp.class, args);
	}
}
```






Feign client definition
```
@FeignClient(name="notificationstatusmessagereceiver", configuration = FeignClientConfiguration.class)
public interface NotificationStatusServiceClient{

	@RequestMapping(method = RequestMethod.POST, value = "/api/v1/NotificationStatus", consumes = "application/json")
	public void postNotificationStatus(NotificationStatus status) throws Exception;
	
}
```
properties
```
notificationstatusmessagereceiver.ribbon.ReadTimeout=800
notificationstatusmessagereceiver.ribbon.ConnectTimeout=250
notificationstatusmessagereceiver.ribbon.OkToRetryOnAllOperations=true
notificationstatusmessagereceiver.ribbon.MaxAutoRetriesNextServer=5
notificationstatusmessagereceiver.ribbon.MaxAutoRetries=5
#hystrix.command.notificationstatusmessagereceiver.execution.isolation.strategy=THREAD
#hystrix.command.notificationstatusmessagereceiver.execution.isolation.thread.timeoutInMilliseconds=100000
```


Here is the exception thrown on  404 
```

com.netflix.hystrix.exception.HystrixRuntimeException: NotificationStatusServiceClient#postNotificationStatus(NotificationStatus) failed and no fallback available.
	at com.netflix.hystrix.AbstractCommand$22.call(AbstractCommand.java:805)
	at com.netflix.hystrix.AbstractCommand$22.call(AbstractCommand.java:790)
	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$4.onError(OperatorOnErrorResumeNextViaFunction.java:140)
	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
	at com.netflix.hystrix.AbstractCommand$DeprecatedOnFallbackHookApplication$1.onError(AbstractCommand.java:1451)
	at com.netflix.hystrix.AbstractCommand$FallbackHookApplication$1.onError(AbstractCommand.java:1376)
	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
	at rx.observers.Subscribers$5.onError(Subscribers.java:230)
	at rx.internal.operators.OnSubscribeThrow.call(OnSubscribeThrow.java:44)
	at rx.internal.operators.OnSubscribeThrow.call(OnSubscribeThrow.java:28)
	at rx.Observable.unsafeSubscribe(Observable.java:10211)
	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:51)
	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
	at rx.Observable.unsafeSubscribe(Observable.java:10211)
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10211)
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10211)
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10211)
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10211)
	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$4.onError(OperatorOnErrorResumeNextViaFunction.java:142)
	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
	at com.netflix.hystrix.AbstractCommand$HystrixObservableTimeoutOperator$3.onError(AbstractCommand.java:1173)
	at rx.internal.operators.OperatorSubscribeOn$1$1.onError(OperatorSubscribeOn.java:59)
	at rx.observers.Subscribers$5.onError(Subscribers.java:230)
	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
	at rx.observers.Subscribers$5.onError(Subscribers.java:230)
	at com.netflix.hystrix.AbstractCommand$DeprecatedOnRunHookApplication$1.onError(AbstractCommand.java:1410)
	at com.netflix.hystrix.AbstractCommand$ExecutionHookApplication$1.onError(AbstractCommand.java:1341)
	at rx.observers.Subscribers$5.onError(Subscribers.java:230)
	at rx.observers.Subscribers$5.onError(Subscribers.java:230)
	at rx.internal.operators.OnSubscribeThrow.call(OnSubscribeThrow.java:44)
	at rx.internal.operators.OnSubscribeThrow.call(OnSubscribeThrow.java:28)
	at rx.Observable.unsafeSubscribe(Observable.java:10211)
	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:51)
	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10211)
	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:51)
	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
	at rx.Observable.unsafeSubscribe(Observable.java:10211)
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10211)
	at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
	at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction$1.call(HystrixContexSchedulerAction.java:56)
	at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction$1.call(HystrixContexSchedulerAction.java:47)
	at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction.call(HystrixContexSchedulerAction.java:69)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: feign.FeignException: status 404 reading NotificationStatusServiceClient#postNotificationStatus(NotificationStatus); content:
404 Not Found: Requested route ('notificationstatus-messagereceiver-dev.u1.compnay.net') does not exist.

	at feign.FeignException.errorStatus(FeignException.java:62)
	at feign.codec.ErrorDecoder$Default.decode(ErrorDecoder.java:91)
	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:138)
	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:76)
	at feign.hystrix.HystrixInvocationHandler$1.run(HystrixInvocationHandler.java:108)
	at com.netflix.hystrix.HystrixCommand$2.call(HystrixCommand.java:301)
	at com.netflix.hystrix.HystrixCommand$2.call(HystrixCommand.java:297)
	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:46)
	... 26 common frames omitted
```

**Comment by spencergibb** [comment]
I think we need to see a project that recreates the problem

**Comment by ryanjbaxter** [comment]
The problem is that a `404` response is not actually considered an "error" by Spring Retry.  No exception is thrown when a server returns a `404` so no retry will occur.  That said I think that this will be a common scenario for users of Cloud Foundry so it might be something we might want to special case.  I will discuss it more with the team.

**Comment by jimmi-skaria** [comment]
Thanks for  acknowledging the issue. I assume the issue is well understood  now and  perhaps the  sample project for  recreating the issue is no more needed. if you still need a sample project please let  me know. 

Following work around is used for now 
As  Hystirx fallback which persists the messages for later retry which is any way needed for the scenario when all the servers in the lists are down. it has been verified that this  fallback is triggered on 404 error.

```
@FeignClient(name="notificationstatus.messagereceiver", configuration = FeignClientConfiguration.class ,fallback=NotificationStatusPersistForRetry.class)
public interface NotificationStatusServiceClient{

	@RequestMapping(method = RequestMethod.POST, value = "/api/v1/NotificationStatus", consumes = "application/json")
	public void postNotificationStatus(NotificationStatus status) throws Exception;
	
}
```

**Comment by ryanjbaxter** [comment]
While talking about this with my other teammates a question came up about your configuration
`<ServiceId>.ribbon.listOfServers= https://approute1.g1.cloud.mycompany.net/api/v1/status,https://approute2..g2..cloud.mycompany.net/api/v1/status`

Is this two different deployments of the same app mapped to their own routes?  Is it deployed across two different regions or instances of CF?

**Comment by jimmi-skaria** [comment]
my idea is to deploy the  same app in two different instances of CF. both app instances will be active at the same time .  List of servers will ideally  look like this 
```
<ServiceId>.ribbon.listOfServers= https://myapp.g1.cloud.mycompany.net/api/v1/status,https://myapp.g2.cloud.mycompany.net/api/v1/status 
```

**Comment by jimmi-skaria** [comment]
By the way I just wanted mention the spring boot version that I am using ;just to make sure there is no spring boot version dependency on the issue being discussed here. 

```<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>1.4.2.RELEASE</version>
	</parent>
```

**Comment by ezraroi** [comment]
I have an use case for the retry also. Lets say i have service A which calls service B. From some reason service B had an unexpected error and returns 500 error code. I want the feign with spring retry to also retry this kind of failed requests as maybe another instance of service B will be able to answer my requests

**Comment by ezraroi** [comment]
@ryanjbaxter Thanks!

**Comment by jimmi-skaria** [comment]
Thanks @ryanjbaxter and @spencergibb .

**Comment by acorcoran-daon** [comment]
Hi,

Also having issues with retries. My configuration is slightly different - I am using Eureka discovery. However I only seem to get retries on catastrophic failures rather than retries. I have the following configuration:

spring:
  cloud:
    loadbalancer:
      retry:
        enabled: true

doc-processor:
    ribbon: 
      retryableStatusCodes: 404, 503
      MaxAutoRetriesNextServer: 2
      MaxAutoRetries: 2
      OkToRetryOnAllOperations: true
    
My spring boot application is annotated with:
@EnableEurekaClient
@SpringBootApplication
@ComponentScan
@EnableRetry

I am using RestTemplate which is configured to be loadbalanced:
@LoadBalanced
	@Bean
	RestTemplate getRestTemplate() {
		return new RestTemplate();
	}

However I only see the next server being retried if there is a network error or similar. 

I am using Dalston.RELEASE. It appears from the small amount of debugging that the configuration is not being picked up when eureka discovery is in use.

Am I missing something? Thanks

**Comment by ryanjbaxter** [comment]
@acorcoran-daon please open a separate issue.  Also please follow code formatting guidelines https://help.github.com/articles/creating-and-highlighting-code-blocks/

**Comment by acorcoran-daon** [comment]
@ryanjbaxter apologies, new issue created with formatting .. (https://github.com/spring-cloud/spring-cloud-netflix/issues/1938)

**Comment by Netha6571** [comment]
@jimmi-skaria, how do you differentiate cloud foundry 404(service unavailable) and application specific 404(Resource not found) status codes. I am also using cloud foundry and I have the same situation now.
Is there any way to customize the ribbon based on the response messages?

**Comment by jimmi-skaria** [comment]
@Netha6571 
The issue discussed here is fixed  by having a new property where you can list the response codes you would like the Ribbon client to retry . The property was  introduced  in Dalston.SR1 release.
```
<ServiceId>.ribbon.retryableStatusCodes: 404,502
```
Do we really need to differentiate the 404 based on the the source? Ribbon is just going retry in the next server in the list and the app is going to return 404 from there as well.

if you really want to do , perhaps we need to depend upon the error messages (like you are thinking) or response header values . I also noticed that the  CF routing related 404 error responses  contains a header X-Cf-Routererror  which is not present in app specific 404 error responses. 

Looks like I am not helping much here to answer your real question which "Any way to customize Ribbon response handler" . Even though I started this thread looking for ways of customizing the ribbon response handler , I could not find any effective ways of doing that withing the limited time I spent for researching on it.

**Comment by Netha6571** [comment]
Thanks for the reply @jimmi-skaria, @spencergibb @ryanjbaxter is there any way we can customize the ribbon to use response header values or response messages.
This will be a common problem for all the cloud foundry users.

**Comment by Netha6571** [comment]
Can we use any filters to do this operation?

**Comment by ryanjbaxter** [comment]
@Netha6571 please open a separate issue

**Comment by vaishnav-piyush** [comment]
Is this issue fixed in Camden also or do we need to upgrade to Dalston.SR1 or above ?

**Comment by spencergibb** [comment]
Dalston
