### ISSUE TITLE
Irregular ReplicationTaskProcessor error on AWS

### ISSUE THREAD

**Issue by alexander-balashov** [spring-cloud/spring-cloud-netflix#1660]
Hi all,
I use eureka (1.4.2) on AWS in 2 availability zones (us-east-1a & us-east-1b) with DNS & replication. Also, I use Weave subnets in which work all my microservices including eureka.
For some reason I am seeing irregularly the following error in my logs (5-20 per day on both instances). It seems that it is not causing any problems and the retry is always successful but I am a bit concerned what the reason might be as the log is on error level.

```

2017-02-01 02:16:26,907 ERROR --- [.weave.local-13] c.n.e.cluster.ReplicationTaskProcessor   : Network level connection to peer us-east-1a-registry.weave.local; retrying after delay
com.sun.jersey.api.client.ClientHandlerException: java.net.SocketTimeoutException: Read timed out
    at com.sun.jersey.client.apache4.ApacheHttpClient4Handler.handle(ApacheHttpClient4Handler.java:187) ~[jersey-apache-client4-1.19.1.jar!/:1.19.1]
    at com.netflix.eureka.cluster.DynamicGZIPContentEncodingFilter.handle(DynamicGZIPContentEncodingFilter.java:48) ~[eureka-core-1.4.11.jar!/:1.4.11]
    at com.netflix.discovery.EurekaIdentityHeaderFilter.handle(EurekaIdentityHeaderFilter.java:27) ~[eureka-client-1.4.11.jar!/:1.4.11]
    at com.sun.jersey.api.client.Client.handle(Client.java:652) ~[jersey-client-1.19.1.jar!/:1.19.1]
    at com.sun.jersey.api.client.WebResource.handle(WebResource.java:682) ~[jersey-client-1.19.1.jar!/:1.19.1]
    at com.sun.jersey.api.client.WebResource.access$200(WebResource.java:74) ~[jersey-client-1.19.1.jar!/:1.19.1]
    at com.sun.jersey.api.client.WebResource$Builder.post(WebResource.java:570) ~[jersey-client-1.19.1.jar!/:1.19.1]
    at com.netflix.eureka.transport.JerseyReplicationClient.submitBatchUpdates(JerseyReplicationClient.java:116) ~[eureka-core-1.4.11.jar!/:1.4.11]
    at com.netflix.eureka.cluster.ReplicationTaskProcessor.process(ReplicationTaskProcessor.java:71) ~[eureka-core-1.4.11.jar!/:1.4.11]
    at com.netflix.eureka.util.batcher.TaskExecutors$BatchWorkerRunnable.run(TaskExecutors.java:187) [eureka-core-1.4.11.jar!/:1.4.11]
    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111-internal]
Caused by: java.net.SocketTimeoutException: Read timed out
    at java.net.SocketInputStream.socketRead0(Native Method) ~[na:1.8.0_111-internal]
    at java.net.SocketInputStream.socketRead(SocketInputStream.java:116) ~[na:1.8.0_111-internal]
    at java.net.SocketInputStream.read(SocketInputStream.java:170) ~[na:1.8.0_111-internal]
    at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[na:1.8.0_111-internal]
    at org.apache.http.impl.io.AbstractSessionInputBuffer.fillBuffer(AbstractSessionInputBuffer.java:158) ~[httpcore-4.4.5.jar!/:4.4.5]
    at org.apache.http.impl.io.SocketInputBuffer.fillBuffer(SocketInputBuffer.java:82) ~[httpcore-4.4.5.jar!/:4.4.5]
    at org.apache.http.impl.io.AbstractSessionInputBuffer.readLine(AbstractSessionInputBuffer.java:271) ~[httpcore-4.4.5.jar!/:4.4.5]
    at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:140) ~[httpclient-4.5.2.jar!/:4.5.2]
    at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57) ~[httpclient-4.5.2.jar!/:4.5.2]
    at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259) ~[httpcore-4.4.5.jar!/:4.4.5]
    at org.apache.http.impl.AbstractHttpClientConnection.receiveResponseHeader(AbstractHttpClientConnection.java:281) ~[httpcore-4.4.5.jar!/:4.4.5]
    at org.apache.http.impl.conn.DefaultClientConnection.receiveResponseHeader(DefaultClientConnection.java:259) ~[httpclient-4.5.2.jar!/:4.5.2]
    at org.apache.http.impl.conn.AbstractClientConnAdapter.receiveResponseHeader(AbstractClientConnAdapter.java:232) ~[httpclient-4.5.2.jar!/:4.5.2]
    at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273) ~[httpcore-4.4.5.jar!/:4.4.5]
    at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125) ~[httpcore-4.4.5.jar!/:4.4.5]
    at org.apache.http.impl.client.DefaultRequestDirector.tryExecute(DefaultRequestDirector.java:686) ~[httpclient-4.5.2.jar!/:4.5.2]
    at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:488) ~[httpclient-4.5.2.jar!/:4.5.2]
    at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:884) ~[httpclient-4.5.2.jar!/:4.5.2]
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:117) ~[httpclient-4.5.2.jar!/:4.5.2]
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55) ~[httpclient-4.5.2.jar!/:4.5.2]
    at com.sun.jersey.client.apache4.ApacheHttpClient4Handler.handle(ApacheHttpClient4Handler.java:173) ~[jersey-apache-client4-1.19.1.jar!/:1.19.1]
    ... 10 common frames omitted

```

I'm using the following configs in AWS:

```
eureka:
  datacenter: cloud
  environment: Amazon
  server:
    enableSelfPreservation: true
    renewalPercentThreshold: 0.3 
    waitTimeInMsWhenSyncEmpty: 0
  instance:
    preferIpAddress: false
  client:
      registerWithEureka: true
      region: us-east-1
      fetchRegistry: true 
      instanceInfoReplicationIntervalSeconds: 30 
      registryFetchIntervalSeconds: 30 
      availabilityZones:
        us-east-1: us-east-1a,us-east-1b
      service-url:
        us-east-1a: http://us-east-1a-registry.weave.local:8761/eureka/ # for the reason of using full Weave Net DNS names
        us-east-1b: http://us-east-1b-registry.weave.local:8761/eureka/ 
```

Any ideas what the cause might be?

Thanks in advance

**Comment by ryanjbaxter** [comment]
Intermittent network issues?  I am not sure there is anything wrong from a Spring Cloud perspective.

**Comment by alexander-balashov** [comment]
I thought about it.. I have 3 environments (dev, staging, prod) and on each of them we have different network load due different count tenants and microservices respectively. Average Network In is 1 mb/min and Network Out 2-3 mb/min. However on dev environment I get this error each 30 minute and prod environment about 3 errors for all day. 
Besides, I use m4.large instance type and I do not think AWS may have a problem with the network on such machines

**Comment by spencergibb** [comment]
We can't look into your environments to see what is going on when these timeouts occur. Could you find out some more details?

**Comment by alexander-balashov** [comment]
We use Weave v1.8.2. on each EC2 instance. All our microservices are located into Weave subnets. If we have network issues then probably because of Weave. However, we do not feel network issues on the infrastructure in general.

Maybe you can advise on the best practices in Eureka configuration. May have special settings for regulatory delays associated with this error.
I tried to learn the [official documentation](http://cloud.spring.io/spring-cloud-static/Brixton.SR5/#_appendix_compendium_of_configuration_properties) , but `eureka.server` properties are not described.

**Comment by spencergibb** [comment]
All of you settings look good. I'm unsure what suggestion to give.

**Comment by Caratacus** [comment]
The same situation:
```

2018-01-12 10:24:56,267 - (ReplicationTaskProcessor.java:113) - Network level connection to peer 192.168.0.47; retrying after delay
com.sun.jersey.api.client.ClientHandlerException: java.net.ConnectException: Connection refused (Connection refused)
        at com.sun.jersey.client.apache4.ApacheHttpClient4Handler.handle(ApacheHttpClient4Handler.java:187) ~[jersey-apache-client4-1.19.1.jar!/:1.19.1]
        at com.netflix.eureka.cluster.DynamicGZIPContentEncodingFilter.handle(DynamicGZIPContentEncodingFilter.java:48) ~[eureka-core-1.6.2.jar!/:1.6.2]
        at com.netflix.discovery.EurekaIdentityHeaderFilter.handle(EurekaIdentityHeaderFilter.java:27) ~[eureka-client-1.6.2.jar!/:1.6.2]
        at com.sun.jersey.api.client.Client.handle(Client.java:652) ~[jersey-client-1.19.1.jar!/:1.19.1]
        at com.sun.jersey.api.client.WebResource.handle(WebResource.java:682) ~[jersey-client-1.19.1.jar!/:1.19.1]
        at com.sun.jersey.api.client.WebResource.access$200(WebResource.java:74) ~[jersey-client-1.19.1.jar!/:1.19.1]
        at com.sun.jersey.api.client.WebResource$Builder.post(WebResource.java:570) ~[jersey-client-1.19.1.jar!/:1.19.1]
        at com.netflix.eureka.transport.JerseyReplicationClient.submitBatchUpdates(JerseyReplicationClient.java:116) ~[eureka-core-1.6.2.jar!/:1.6.2]
        at com.netflix.eureka.cluster.ReplicationTaskProcessor.process(ReplicationTaskProcessor.java:71) ~[eureka-core-1.6.2.jar!/:1.6.2]
        at com.netflix.eureka.util.batcher.TaskExecutors$BatchWorkerRunnable.run(TaskExecutors.java:187) ~[eureka-core-1.6.2.jar!/:1.6.2]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
Caused by: java.net.ConnectException: Connection refused (Connection refused)
        at java.net.PlainSocketImpl.socketConnect(Native Method) ~[?:1.8.0_112]
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[?:1.8.0_112]
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[?:1.8.0_112]
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[?:1.8.0_112]
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_112]
        at java.net.Socket.connect(Socket.java:589) ~[?:1.8.0_112]
        at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:121) ~[httpclient-4.5.3.jar!/:4.5.3]
        at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:180) ~[httpclient-4.5.3.jar!/:4.5.3]
        at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:144) ~[httpclient-4.5.3.jar!/:4.5.3]
        at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:134) ~[httpclient-4.5.3.jar!/:4.5.3]
        at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:610) ~[httpclient-4.5.3.jar!/:4.5.3]
        at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:445) ~[httpclient-4.5.3.jar!/:4.5.3]
        at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:835) ~[httpclient-4.5.3.jar!/:4.5.3]
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:118) ~[httpclient-4.5.3.jar!/:4.5.3]
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56) ~[httpclient-4.5.3.jar!/:4.5.3]
        at com.sun.jersey.client.apache4.ApacheHttpClient4Handler.handle(ApacheHttpClient4Handler.java:173) ~[jersey-apache-client4-1.19.1.jar!/:1.19.1]
        ... 10 more
```

**Comment by sqzaman** [comment]
this is the solution
eureka.server.maxThreadsForPeerReplication=0

**Comment by spencergibb** [comment]
Closing this due to inactivity. Please re-open if there's more to discuss.
