### ISSUE TITLE
FilterRegistrationBean has been removed in spring-boot v1.5.x, but spring-cloud-netflix still refrences it

### ISSUE THREAD

**Issue by linzhaoming** [spring-cloud/spring-cloud-netflix#1665]
The class **org.springframework.boot.context.embedded.FilterRegistrationBean** has been deprecated at version 1.4.X, in favor of the new location **org.springframework.boot.web.servlet.FilterRegistrationBean**.

In the newest spring-boot's GA version _1.5.1.RELEASE_, **org.springframework.boot.context.embedded.FilterRegistrationBean** has been removed.

But the newest GA version of spring-cloud-netflix still depends on the old class name which has been removed.
Such as 
- org.springframework.cloud.netflix.eureka.server.EurekaServerConfiguration(spring-cloud-netflix-eureka-server-1.2.4.RELEASE.jar)
- org.springframework.cloud.netflix.hystrix.dashboard.HystrixDashboardConfiguration(spring-cloud-netflix-hystrix-dashboard-1.2.4.RELEASE.jar)
- org.springframework.cloud.netflix.turbine.TurbineHttpConfiguration(spring-cloud-netflix-turbine-1.2.4.RELEASE.jar)
- org.springframework.cloud.netflix.zuul.ZuulConfiguration(spring-cloud-netflix-core-1.2.4.RELEASE.jar)

The result is when I use spring-cloud version **Camden.SR4** and spring-boot version **1.4.1.RELEASE** together. **Application starts will fail and throws the following error message**

`
Caused by: java.lang.IllegalStateException: Failed to introspect annotated methods on class org.springframework.cloud.netflix.zuul.ZuulConfiguration
	at org.springframework.core.type.StandardAnnotationMetadata.getAnnotatedMethods(StandardAnnotationMetadata.java:163)
	at org.springframework.context.annotation.ConfigurationClassParser.retrieveBeanMethodMetadata(ConfigurationClassParser.java:360)
	at org.springframework.context.annotation.ConfigurationClassParser.doProcessConfigurationClass(ConfigurationClassParser.java:294)
	at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:230)
	at org.springframework.context.annotation.ConfigurationClassParser.processImports(ConfigurationClassParser.java:570)
	... 20 common frames omitted
Caused by: java.lang.NoClassDefFoundError: org/springframework/boot/context/embedded/ServletRegistrationBean
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.getDeclaredMethods(Class.java:1975)
	at org.springframework.core.type.StandardAnnotationMetadata.getAnnotatedMethods(StandardAnnotationMetadata.java:152)
	... 24 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.springframework.boot.context.embedded.ServletRegistrationBean
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 28 common frames omitted
`

**Comment by spencergibb** [comment]
Closed already via 81959b5ef3e0ec7738a79fdef923caa8e31a51cc and will be part of 1.2.5 and Camden.SR5

**Comment by spencergibb** [comment]
I assume you mean 1.5.1, not 1.4.1 in 
> spring-cloud version Camden.SR4 and spring-boot version 1.4.1.RELEASE

**Comment by linzhaoming** [comment]
Yes, Thank you and waiting for the new release
