### ISSUE TITLE
How to handle api endpoint that contains <index.php?> ?

### ISSUE THREAD

**Issue by MolineroUA** [spring-cloud/spring-cloud-netflix#1727]
I want to write a feign client for TestRail api, and according to documentation http://docs.gurock.com/testrail-api2/start and discussion with support team the endpoints must contain index.php? in the url.

But, when I try to use 
> @RequestMapping(method = GET, value = 'index.php?/api/v2/get_run/{runId}')

an exception appears
> java.lang.IllegalStateException: Body parameters cannot be used with form parameters.
	at feign.Util.checkState(Util.java:128)
	at feign.Contract$BaseContract.parseAndValidateMetadata(Contract.java:112)
	at org.springframework.cloud.netflix.feign.support.SpringMvcContract.parseAndValidateMetadata(SpringMvcContract.java:133)
	at feign.Contract$BaseContract.parseAndValidatateMetadata(Contract.java:64)
	at feign.ReflectiveFeign$ParseHandlersByName.apply(ReflectiveFeign.java:146)
	at feign.ReflectiveFeign.newInstance(ReflectiveFeign.java:53)
	at feign.Feign$Builder.target(Feign.java:198)
	at feign.Feign$Builder.target(Feign.java:194)
	at feign.Feign$Builder$target$5.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:110)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:130)

As I understand the issue is related to symbol '?' in url.
Is it possible to handle this issue?

**Comment by spencergibb** [comment]
that denotes a `@QueryParam`, but you are trying to use it as a path parameter.

**Comment by sifraser** [comment]
I have the same problem:
```
 @RequestLine("GET /index.php?/api/v2/get_section/{section_id}")
    fun getSection(
            @Param("section_id") sectionId: Int
    ): Section
```
Giving:
```
java.lang.NullPointerException
	at feign.RequestTemplate.replaceQueryValues(RequestTemplate.java:605)
	at feign.RequestTemplate.resolve(RequestTemplate.java:210)
	at feign.ReflectiveFeign$BuildTemplateByResolvingArgs.resolve(ReflectiveFeign.java:294)
	at feign.ReflectiveFeign$BuildFormEncodedTemplateFromArgs.resolve(ReflectiveFeign.java:323)
	at feign.ReflectiveFeign$BuildTemplateByResolvingArgs.create(ReflectiveFeign.java:213)
	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:72)
	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:103)
```

Obviously the endpoint is a bit weird, but we don't have control of that; is there a workaround?

@MolineroUA I have followed up on your thread on the TestRail forums

**Comment by MolineroUA** [comment]
@sifraser I use Groovy HttpBuilder for TestRail api, which is a wrapper for HttpClient. 
It looks like we should wait for TestRail api v3 from Gurock team :)

**Comment by vasilievip** [comment]
Reposting to this thread as well.
You can employ RequestInterceptor to rewrite request url:

```

import feign.RequestInterceptor;
import feign.RequestTemplate;
import org.springframework.util.ReflectionUtils;

import static java.util.Optional.ofNullable;
import static org.springframework.util.ReflectionUtils.findField;

...

TestRailFeignClient:

    @PostMapping(value = "/index.php/api/v2/update_case/{caseId}")
    void updateCase(@PathVariable("caseId") String caseId,
                                      @RequestBody UpdateCaseRequest request);

...

TestRailFeignClientContext:

       @Bean
        public RequestInterceptor fixGovnoApiInterceptor() {
            return requestTemplate -> {
                String url = requestTemplate.url();
                if (url.contains("index.php/api/v2")) {
                    url = url.replace("index.php/", "index.php?/");
                    Optional<Field> field = ofNullable(findField(RequestTemplate.class, "url"));
                    if (field.isPresent()) {
                        ReflectionUtils.makeAccessible(field.get());
                        ReflectionUtils.setField(field.get(), requestTemplate, new StringBuilder(url));
                    }
                }
            };
        }
...
```

**Comment by ryanjbaxter** [comment]
Closing since @vasilievip has found a workaround.
