### ISSUE TITLE
Why load balancer routed to another instance host when using FeignClient?

### ISSUE THREAD

**Issue by importsource** [spring-cloud/spring-cloud-netflix#1736]
When I set property as follow:

`ribbon.NFLoadBalancerRuleClassName=com.netflix.loadbalancer.RandomRule`

The rule still  was  feign built-in rule  by  default.

Then I wrote a bean configuration as follow:

```java
@Configuration
@RibbonClient(name = "person", configuration = RibbonConfiguration.RibbonConfig.class)
public class RibbonConfiguration {
    static class RibbonConfig {
        @Bean
        public IRule rule() {
            return new RandomRule();
        }
    }
}
```

Now,the random rule is available! 

But , happened new stories unfortunately as follow:

In my project ,had 3 feign client:

**1.add-service:**
```java
@FeignClient(value = "ADD-SERVICE", fallback = AddClientFallback.class)
public interface AddClient {

	@RequestMapping(method = RequestMethod.GET, value = "/add-service/heartbeat")
	String heartbeat();
}
```
**2.compute-service:**
```java
@FeignClient(value="COMPUTE-SERVICE",fallback = ComputeClientFallback.class)
public interface ComputeClient {
    @RequestMapping(method = RequestMethod.GET,value = "/compute-service/heartbeat")
    String heartbeat();
}
```
**3.mutiple-service:**

```java
@FeignClient(value="MULTIPLE-SERVICE",fallback = MultipleClientFallback.class)
public interface MultipleClient {
	@RequestMapping(method = RequestMethod.GET,value = "/multiple-service/heartbeat")
    String heartbeat();
}
```

# Tell me WHY

At this time, Step-By-Step Invocation.

1.Invoke add-service :all is ok!
2.Invoke compute-service:all is ok!
3.Invoke multiple-service:all is ok!

Now,I re-invoked add-service again, then threw Exception as follow:

```java
2017-02-28 13:58:29.832 DEBUG [hystrix-ADD-SERVICE-10] c.n.l.ZoneAwareLoadBalancer:112- Zone aware logic disabled or there is only one zone
2017-02-28 13:58:29.833 DEBUG [hystrix-ADD-SERVICE-10] c.n.loadbalancer.LoadBalancerContext:477- ADD-SERVICE using LB returned Server: 172.19.11.201:2222 for request http:///add-service/heartbeat
2017-02-28 13:58:29.858 ERROR [http-nio-3333-exec-4] o.a.c.c.C.[.[.[.[dispatcherServlet]:181- Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is com.netflix.hystrix.exception.HystrixBadRequestException: error_code:404] with root cause
com.netflix.hystrix.exception.HystrixBadRequestException: error_code:404
	at com.zbj.cloud.core.config.ErrorDecoderConfiguration$1.decode(ErrorDecoderConfiguration.java:20)
	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:138)
	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:76)
	at feign.hystrix.HystrixInvocationHandler$1.run(HystrixInvocationHandler.java:108)
	at com.netflix.hystrix.HystrixCommand$2.call(HystrixCommand.java:301)
	at com.netflix.hystrix.HystrixCommand$2.call(HystrixCommand.java:297)
	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:46)
	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10211)
	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:51)
	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
	at rx.Observable.unsafeSubscribe(Observable.java:10211)
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10211)
	at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
	at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction$1.call(HystrixContexSchedulerAction.java:56)
	at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction$1.call(HystrixContexSchedulerAction.java:47)
	at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction.call(HystrixContexSchedulerAction.java:69)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2017-02-28 13:58:30.376 DEBUG [NFLoadBalancer-PingTimer-EUREKA-SERVER] c.n.loadbalancer.BaseLoadBalancer:907- LoadBalancer:  PingTask executing [3] servers configured


```

Note that in the console output:

```log
 [hystrix-ADD-SERVICE-10] c.n.loadbalancer.LoadBalancerContext:477- ADD-SERVICE using LB returned Server: 172.19.11.201:2222 for request http:///add-service/heartbeat
```

Why **ADD-SERVICE** routed  to  172.19.11.201:2222 finally. This host(172.19.11.201:2222) is MULTIPLE-SERVICE host.

 Tell me why !  Tell me why ! Thanks everyone!

**Comment by spencergibb** [comment]
I have no idea. What does eureka tell you (ie `<eurkeaserver>/eureka/apps`?

**Comment by spring-issuemaster** [comment]
Closing due to age of the question. If you would like us to look at this issue, please comment and we will look at re-opening the issue.
