### ISSUE TITLE
First request through Zuul/Euruka will always timeout. Subsequent requests then behave as expected (no timeouts).

### ISSUE THREAD

**Issue by trcodestore** [spring-cloud/spring-cloud-netflix#1783]
Hi all,

Hoping to receive some advice about a timeout issue we're repeatedly experiencing. 

We have a number of microservices that are integrated with Eureka and Zuul. Whenever we start up our services (including the Eureka and Zuul services), the first request that hits Zuul will always timeout. This timeout will occur regardless of how long we wait (i.e. the timeout will occur even if we wait 15 mins after starting up). After this first request, Zuul/Eureka then seem to wake up and all subsequent requests will work as expected. Has anyone else experienced this?

[This file](https://github.com/spring-cloud/spring-cloud-netflix/files/848380/stacktrace.txt) contains the full Zuul stack trace  we experience on the first request. The pertinent parts of the stack trace are also pasted below:

```
com.netflix.zuul.exception.ZuulException: Forwarding error
 	at org.springframework.cloud.netflix.zuul.filters.route.RibbonRoutingFilter.handleException(RibbonRoutingFilter.java:170)
 	at org.springframework.cloud.netflix.zuul.filters.route.RibbonRoutingFilter.forward(RibbonRoutingFilter.java:145)
 ....
Caused by: com.netflix.hystrix.exception.HystrixRuntimeException: my-service-id timed-out and no fallback available.
 	at com.netflix.hystrix.AbstractCommand$22.call(AbstractCommand.java:805)
 	at com.netflix.hystrix.AbstractCommand$22.call(AbstractCommand.java:790)
....
Caused by: java.util.concurrent.TimeoutException: null
 	at com.netflix.hystrix.AbstractCommand.handleTimeoutViaFallback(AbstractCommand.java:980)
 	at com.netflix.hystrix.AbstractCommand.access$500(AbstractCommand.java:59)
 	at com.netflix.hystrix.AbstractCommand$12.call(AbstractCommand.java:595)
 	at com.netflix.hystrix.AbstractCommand$12.call(AbstractCommand.java:587)
 	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$4.onError(OperatorOnErrorResumeNextViaFunction.java:140)
```

Thank you.

**Comment by ryanjbaxter** [comment]
Might possibly be related to #1334.  Maybe try out the fix in PR ##1749

**Comment by matt-shaw** [comment]
I'm getting the same issue, did you resolve it?

**Comment by eacdy** [comment]
@trcodestore @matt-shaw Maybe you should try `ribbon.eager-load`.
OR, you May set Hystrix's timeout longer.

**Comment by matt-shaw** [comment]
Hi, I've added the Zuul eager application loading settings as specified here [Zuul Eager loading settings](http://cloud.spring.io/spring-cloud-static/Edgware.RELEASE/single/spring-cloud.html#_zuul_eager_application_context_loading) but don't understand their relationship to the general ribbon eager loading settings listed here [General Eager loading settings](http://cloud.spring.io/spring-cloud-static/Edgware.RELEASE/single/spring-cloud.html#ribbon-child-context-eager-load)?

How would I set the Hystrix timeout longer in Zuul?

**Comment by matt-shaw** [comment]
I get the following stack trace in Zuul.

`com.netflix.zuul.exception.ZuulException: Forwarding error
	at org.springframework.cloud.netflix.zuul.filters.route.RibbonRoutingFilter.handleException(RibbonRoutingFilter.java:189) ~[spring-cloud-netflix-core-1.4.0.RELEASE.jar:1.4.0.RELEASE]
	at org.springframework.cloud.netflix.zuul.filters.route.RibbonRoutingFilter.forward(RibbonRoutingFilter.java:164) ~[spring-cloud-netflix-core-1.4.0.RELEASE.jar:1.4.0.RELEASE]
	at org.springframework.cloud.netflix.zuul.filters.route.RibbonRoutingFilter.run(RibbonRoutingFilter.java:111) ~[spring-cloud-netflix-core-1.4.0.RELEASE.jar:1.4.0.RELEASE]
	at com.netflix.zuul.ZuulFilter.runFilter(ZuulFilter.java:112) ~[zuul-core-1.3.0.jar:1.3.0]
	at com.netflix.zuul.FilterProcessor.processZuulFilter(FilterProcessor.java:193) ~[zuul-core-1.3.0.jar:1.3.0]
	at com.netflix.zuul.FilterProcessor.runFilters(FilterProcessor.java:157) ~[zuul-core-1.3.0.jar:1.3.0]
	at com.netflix.zuul.FilterProcessor.route(FilterProcessor.java:118) ~[zuul-core-1.3.0.jar:1.3.0]
........

Caused by: com.netflix.client.ClientException: Load balancer does not have available server for client: person-app
	at com.netflix.loadbalancer.LoadBalancerContext.getServerFromLoadBalancer(LoadBalancerContext.java:483) ~[ribbon-loadbalancer-2.2.4.jar:2.2.4]
	at com.netflix.loadbalancer.reactive.LoadBalancerCommand$1.call(LoadBalancerCommand.java:184) ~[ribbon-loadbalancer-2.2.4.jar:2.2.4]
	at com.netflix.loadbalancer.reactive.LoadBalancerCommand$1.call(LoadBalancerCommand.java:180) ~[ribbon-loadbalancer-2.2.4.jar:2.2.4]
	at rx.Observable.unsafeSubscribe(Observable.java:10151) ~[rxjava-1.2.0.jar:1.2.0]
	at rx.internal.operators.OnSubscribeConcatMap.call(OnSubscribeConcatMap.java:94) ~[rxjava-1.2.0.jar:1.2.0]
.....
`

**Comment by ryanjbaxter** [comment]
Please learn how to [format code on GitHub](https://help.github.com/articles/creating-and-highlighting-code-blocks/).

The error indicates that Ribbon does not know about an app names `person-app`.

**Comment by matt-shaw** [comment]
Sorry about code formatting.

Thanks, basically we’re using Zuul and Eureka.  How do I configure Zuul/Ribbon to refresh its list of services from Eureka if it doesn’t know about an app, as above, and then if Eureka doesnt have a service registered with it yet back off and retry in X seconds X times?

**Comment by ryanjbaxter** [comment]
By default, the Eureka client will automatically refresh the service registry from the Eureka client every 30 seconds, there is nothing you should have to do but include the Eureka client jar to your classpath and add `@EnableDiscoveryClient`.

**Comment by spencergibb** [comment]
Closing this due to inactivity. Please re-open if there's more to discuss.

**Comment by nestramix** [comment]
I have order and customer service that integrated with zuul, config, eureka, hystrix. Everything went well until i hit an order-service endpoint that requires remote call (with hystrix command) to the customer-service. If i hit that endpoint directly (without going through zuul proxy) I dont get an error. This problem only exists for the first hit. I have followed all the above suggestions but it does not work for me. 

I get the following stack trace in Zuul

```
gateway_1          | Caused by: com.netflix.client.ClientException: null
gateway_1          | 	at com.netflix.client.AbstractLoadBalancerAwareClient.executeWithLoadBalancer(AbstractLoadBalancerAwareClient.java:118) ~[ribbon-loadbalancer-2.2.5.jar!/:2.2.5]
gateway_1          | 	at org.springframework.cloud.netflix.zuul.filters.route.support.AbstractRibbonCommand.run(AbstractRibbonCommand.java:187) ~[spring-cloud-netflix-core-1.4.4.RELEASE.jar!/:1.4.4.RELEASE]
gateway_1          | 	at org.springframework.cloud.netflix.zuul.filters.route.support.AbstractRibbonCommand.run(AbstractRibbonCommand.java:52) ~[spring-cloud-netflix-core-1.4.4.RELEASE.jar!/:1.4.4.RELEASE]
```

My Spring Cloud Version is Edgware.SR3 with Spring Boot 1.5.13.RELEASE.
Thank you.

**Comment by ryanjbaxter** [comment]
@nestramix this is unrelated.  You problem is just a simple read timeout.  http://cloud.spring.io/spring-cloud-static/Finchley.RC2/single/spring-cloud.html#_zuul_timeouts

**Comment by nestramix** [comment]
First of all thank you @ryanjbaxter  @indraneelb1903. I was set [Zuul Timeouts](http://cloud.spring.io/spring-cloud-static/Edgware.SR3/single/spring-cloud.html#_zuul_timeouts) more than my business service timeout and everything work fine.
``
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds= 20000

ribbon.ReadTimeout= 4000
ribbon.ConnectTimeout= 4000
``

**Comment by rodrigoords** [comment]
> @nestramix @ryanjbaxter As he says his problem is only on the first hit, ribbon eager loading should help -
> `ribbon.eager-load.enabled = true`

What service do I need to configure this? Gateway, Eureka or Clients?

**Comment by ryanjbaxter** [comment]
The clients
