### ISSUE TITLE
Reference documentation for AWS setup using EIP

### ISSUE THREAD

**Issue by gmucha** [spring-cloud/spring-cloud-netflix#188]
As currently trying to set up an AWS/EIP Eureka - per standard Eureka docs - I am unable to get the Eureka server to recognize it's running in AWS. Apparently the EIP binding is handled in EurekaBootstrap.initEurekaEnvironment() whis is overridden in EurekaServerInitializerConfiguration - this bypasses EIP registration attempts.

Not sure if I understand correctly, but is dataCenterInfo modifiable in EurekaInstanceConfigBean? Or is there another way to specify that Eureka is running in AWS and should follow the EIP binding scheme?

**Comment by DirkLachowski** [comment]
Maybe a bit late but i've done that with a custom `EurekaInstanceConfigBean`:

```
@SpringBootApplication
@EnableEurekaServer
@EnableDiscoveryClient
public class EurekaServer {

	public static void main(String[] args) {
		SpringApplication.run(EurekaServer.class, args);
	}

	@Bean
	@Autowired
	public EurekaInstanceConfigBean eurekaInstanceConfig(InetUtils inetUtils) {
	  EurekaInstanceConfigBean b = new EurekaInstanceConfigBean(inetUtils);
	  AmazonInfo info = AmazonInfo.Builder.newBuilder().autoBuild("eureka");
	  b.setDataCenterInfo(info);
	  return b;
	}
}
```

This works but may introduces [this](http://stackoverflow.com/questions/36284246/eureka-on-spring-cloud-netflix-with-dns-based-config-all-instances-showing-up-a) problem because the eureka servers then register with their internal VPC ip and not with the EIP.

**Comment by givenm** [comment]
I am using AWS ECS to deploy Eureka in my Cluster to zones inside us-east-1 region. ECS dynamically deploys to any region and I cannot predetermine the IP or domain the EC2 instance will be, hence I use DNS.

I am using DNS as below 

```
eureka:
    instance:
        healthCheckUrlPath: /manage/health
    client:
        region: us-east-1
        availabilityZones:
            us-east-1: us-east-1a,us-east-1c
        eurekaServerPort: 8761
        useDnsForFetchingServiceUrls: true
        eurekaServerDNSName: eureka.mydomain.com
        eurekaServerURLContext: eureka
        registerWithEureka: true
        fetchRegistry: true

cloud:
    aws:
        credentials:
            accessKey: AWS_KEY
            secretKey: AWS_KEY_SECRET
        region:
            static: us-east-1 
```

The user with AWS_KEY has this policy attached:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "ec2:AllocateAddress",
                "ec2:AssociateAddress",
                "ec2:DescribeAddresses",
                "ec2:DisassociateAddress"
            ],
            "Sid": "Stmt1375723773000",
            "Resource": [
                "*"
            ],
            "Effect": "Allow"
        }
    ]
}
```

and configured the EurekaInstanceConfigBean configured as:

```
@Bean
    @Profile("!default")
    public EurekaInstanceConfigBean eurekaInstanceConfig(InetUtils inetUtils) {
        EurekaInstanceConfigBean config = new EurekaInstanceConfigBean(inetUtils);
        AmazonInfo info = AmazonInfo.Builder.newBuilder().autoBuild("eureka");
        info.getMetadata().put(AmazonInfo.MetaDataKey.publicHostname.getName(), info.get(AmazonInfo.MetaDataKey.publicIpv4));
        config.setHostname(info.get(AmazonInfo.MetaDataKey.publicHostname));
        config.setIpAddress(info.get(AmazonInfo.MetaDataKey.publicIpv4));
        config.setNonSecurePort(port);
        config.setDataCenterInfo(info);
        return config;
    }
```

**GOOD THING:** Eureka recognise my Route 53 configured `eureka.mydomain.com`  DNS EIPs as here [https://github.com/Netflix/eureka/wiki/Deploying-Eureka-Servers-in-EC2](https://github.com/Netflix/eureka/wiki/Deploying-Eureka-Servers-in-EC2) and it tries to bind, the (available and unassigned) EIP in zone us-east-1c, to the instance where my first eureka server is deployed 


**PROBLEM**: I get the following logs and Unauthorized error as below when booting my app:

```

...................................
.................................
2017-04-10 16:07:42.141 DEBUG 5 --- [           main] c.n.d.s.r.a.DnsTxtRecordClusterResolver  : Resolved txt.us-east-1.eureka.mydomain.com to [AwsEndpoint{ serviceUrl=
'http://ec2-34.200.47.82.compute-1.amazonaws.com:8761/eureka', region='us-east-1', zone='us-east-1c'}]
2017-04-10 16:07:42.141 DEBUG 5 --- [           main] c.n.d.s.r.a.ZoneAffinityClusterResolver  : Local zone=us-east-1c; resolved to: [AwsEndpoint{ serviceUrl='http://ec2-3
4.200.47.82.compute-1.amazonaws.com:8761/eureka', region='us-east-1', zone='us-east-1c'}]
2017-04-10 16:07:42.204  INFO 5 --- [           main] com.netflix.discovery.DiscoveryClient    : Disable delta property : false
2017-04-10 16:07:42.209  INFO 5 --- [           main] com.netflix.discovery.DiscoveryClient    : Single vip registry refresh property : null
2017-04-10 16:07:42.209  INFO 5 --- [           main] com.netflix.discovery.DiscoveryClient    : Force full registry fetch : false
2017-04-10 16:07:42.209  INFO 5 --- [           main] com.netflix.discovery.DiscoveryClient    : Application is null : false
2017-04-10 16:07:42.209  INFO 5 --- [           main] com.netflix.discovery.DiscoveryClient    : Registered Applications size is zero : true
2017-04-10 16:07:42.209  INFO 5 --- [           main] com.netflix.discovery.DiscoveryClient    : Application version is -1: true
2017-04-10 16:07:42.211  INFO 5 --- [           main] com.netflix.discovery.DiscoveryClient    : Getting all instance registry info from the eureka server
2017-04-10 16:07:42.213 DEBUG 5 --- [           main] c.n.d.s.t.d.SessionedEurekaHttpClient    : Ending a session and starting anew
2017-04-10 16:07:42.222 DEBUG 5 --- [           main] n.d.s.t.j.AbstractJerseyEurekaHttpClient : Created client for url: http://ec2-34.200.47.82.compute-1.amazonaws.com:87
61/eureka
2017-04-10 16:07:42.313 DEBUG 5 --- [           main] c.n.d.shared.MonitoredConnectionManager  : Get connection: {}->http://ec2-34.200.47.82.compute-1.amazonaws.com:8761,
timeout = 5000
2017-04-10 16:07:42.314 DEBUG 5 --- [           main] c.n.d.shared.NamedConnectionPool         : [{}->http://ec2-34.200.47.82.compute-1.amazonaws.com:8761] total kept aliv
e: 0, total issued: 0, total allocated: 0 out of 200
2017-04-10 16:07:42.314 DEBUG 5 --- [           main] c.n.d.shared.NamedConnectionPool         : No free connections [{}->http://ec2-34.200.47.82.compute-1.amazonaws.com:8
761][null]
2017-04-10 16:07:42.314 DEBUG 5 --- [           main] c.n.d.shared.NamedConnectionPool         : Available capacity: 50 out of 50 [{}->http://ec2-34.200.47.82.compute-1.am
azonaws.com:8761][null]
2017-04-10 16:07:42.314 DEBUG 5 --- [           main] c.n.d.shared.NamedConnectionPool         : Creating new connection [{}->http://ec2-34.200.47.82.compute-1.amazonaws.c
om:8761]
2017-04-10 16:07:42.330 DEBUG 5 --- [           main] c.n.d.shared.MonitoredConnectionManager  : Released connection is not reusable.
2017-04-10 16:07:42.331 DEBUG 5 --- [           main] c.n.d.shared.NamedConnectionPool         : Releasing connection [{}->http://ec2-34.200.47.82.compute-1.amazonaws.com:
8761][null]
2017-04-10 16:07:42.331 DEBUG 5 --- [           main] c.n.d.shared.NamedConnectionPool         : Notifying no-one, there are no waiting threads
2017-04-10 16:07:42.331 DEBUG 5 --- [           main] n.d.s.t.j.AbstractJerseyEurekaHttpClient : Jersey HTTP GET http://ec2-34.200.47.82.compute-1.amazonaws.com:8761/eurek
a/apps/?; statusCode=N/A
2017-04-10 16:07:42.345 ERROR 5 --- [           main] c.n.d.s.t.d.RedirectingEurekaHttpClient  : Request execution 
....................
....................
2017-04-10 16:07:49.455 DEBUG 5 --- [      Thread-11] c.n.discovery.endpoint.EndpointUtils     : This client will talk to the following serviceUrls in order : [http://ec2-
34.206.31.211.compute-1.amazonaws.com:8761/eureka/]
2017-04-10 16:07:49.455 DEBUG 5 --- [      Thread-11] c.n.discovery.endpoint.EndpointUtils     : The region url to be looked up is txt.us-east-1.eureka.mydomain.com :
2017-04-10 16:07:49.456 DEBUG 5 --- [      Thread-11] c.n.discovery.endpoint.EndpointUtils     : The zoneName mapped to region us-east-1 is us-east-1c
2017-04-10 16:07:49.456 DEBUG 5 --- [      Thread-11] c.n.discovery.endpoint.EndpointUtils     : Checking if the instance zone us-east-1c is the same as the zone from DNS
us-east-1c
2017-04-10 16:07:49.456 DEBUG 5 --- [      Thread-11] c.n.discovery.endpoint.EndpointUtils     : The zone index from the list [us-east-1c] that matches the instance zone u
s-east-1c is 0
2017-04-10 16:07:49.456 DEBUG 5 --- [      Thread-11] c.n.discovery.endpoint.EndpointUtils     : The zone url to be looked up is txt.us-east-1c.eureka.mydomain.com :
2017-04-10 16:07:49.457 DEBUG 5 --- [      Thread-11] c.n.discovery.endpoint.EndpointUtils     : The eureka url for the dns name txt.us-east-1c.eureka.mydomain.com is e
c2-34.200.47.82.compute-1.amazonaws.com
2017-04-10 16:07:49.457 DEBUG 5 --- [      Thread-11] c.n.discovery.endpoint.EndpointUtils     : The EC2 url is http://ec2-34.200.47.82.compute-1.amazonaws.com:8761/eureka
/
2017-04-10 16:07:49.457 DEBUG 5 --- [      Thread-11] c.n.discovery.endpoint.EndpointUtils     : This client will talk to the following serviceUrls in order : [http://ec2-
34.200.47.82.compute-1.amazonaws.com:8761/eureka/]
**2017-04-10 16:07:49.527 ERROR 5 --- [      Thread-11] com.netflix.eureka.aws.EIPManager        : Failed to bind elastic IP: 34.200.47.82 to i-0bc1018ccdcc69148

com.amazonaws.AmazonServiceException: You are not authorized to perform this operation. (Service: AmazonEC2; Status Code: 403; Error Code: UnauthorizedOperation; Request I
D: f9b2dec4-6d79-4da2-bbac-061416bde000)**
        at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1378) ~[aws-java-sdk-core-1.11.18.jar!/:na]
        at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:924) ~[aws-java-sdk-core-1.11.18.jar!/:na]
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:702) ~[aws-java-sdk-core-1.11.18.jar!/:na]
        at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:454) ~[aws-java-sdk-core-1.11.18.jar!/:na]
        at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:416) ~[aws-java-sdk-core-1.11.18.jar!/:na]
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:365) ~[aws-java-sdk-core-1.11.18.jar!/:na]
        at com.amazonaws.services.ec2.AmazonEC2Client.doInvoke(AmazonEC2Client.java:12003) ~[aws-java-sdk-ec2-1.11.18.jar!/:na]
        at com.amazonaws.services.ec2.AmazonEC2Client.invoke(AmazonEC2Client.java:11973) ~[aws-java-sdk-ec2-1.11.18.jar!/:na]
        at com.amazonaws.services.ec2.AmazonEC2Client.describeAddresses(AmazonEC2Client.java:4716) ~[aws-java-sdk-ec2-1.11.18.jar!/:na]
        at com.netflix.eureka.aws.EIPManager.bindEIP(EIPManager.java:202) [eureka-core-1.4.12.jar!/:1.4.12]
        at com.netflix.eureka.aws.EIPManager.handleEIPBinding(EIPManager.java:136) [eureka-core-1.4.12.jar!/:1.4.12]
        at com.netflix.eureka.aws.EIPManager.start(EIPManager.java:105) [eureka-core-1.4.12.jar!/:1.4.12]
        at com.netflix.eureka.aws.AwsBinderDelegate.start(AwsBinderDelegate.java:42) [eureka-core-1.4.12.jar!/:1.4.12]
        at org.springframework.cloud.netflix.eureka.server.EurekaServerBootstrap.initEurekaServerContext(EurekaServerBootstrap.java:145) [spring-cloud-netflix-eureka-serve
r-1.2.6.RELEASE.jar!/:1.2.6.RELEASE]
        at org.springframework.cloud.netflix.eureka.server.EurekaServerBootstrap.contextInitialized(EurekaServerBootstrap.java:81) [spring-cloud-netflix-eureka-server-1.2.
6.RELEASE.jar!/:1.2.6.RELEASE]
        at org.springframework.cloud.netflix.eureka.server.EurekaServerInitializerConfiguration$1.run(EurekaServerInitializerConfiguration.java:70) [spring-cloud-netflix-e
ureka-server-1.2.6.RELEASE.jar!/:1.2.6.RELEASE]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_121]

2017-04-10 16:07:49.527  INFO 5 --- [      Thread-11] com.netflix.eureka.aws.EIPManager        : No EIP is free to be associated with this instance. Candidate EIPs are: [3
4.200.47.82]
......................................
........................................
........................................

```

**QUESTION**: I have attached the policy to allow Eureka to bind the Elastic IP to the instance where it is deployed but WHY am I getting a `You are not authorized to perform this operation. (Service: AmazonEC2; Status Code: 403; Error Code: UnauthorizedOperation`  and how can I fix this? As it stands, I have spend more than a day Googling and still the same error :(

I tried the netflix way of configuring eureka like below but to no avail :(:

```
eureka:
        awsAccessId: AWS_KEY
        awsSecretKey:AWS_KEY_SECRET
```

**Comment by DirkLachowski** [comment]
@givenm Are you sure the policy is bound to the user? The stacktrace shows that the user is not allowed to execute `describeAddresses`. If you can't get this working you could use an IAM role for your eureka server (also eliminating the need to store access keys somewhere).

Btw., your profile is missing asg permissions, see https://github.com/Netflix/eureka/wiki/Deploying-Eureka-Servers-in-EC2#aws-access-policies

**Comment by spencergibb** [comment]
Try `eureka.server.{aWSAccessId|aWSSecretKey}`.

**Comment by givenm** [comment]
@DirkLachowski I did try that and it didn't work. I am glad to say that @spencergibb 's SOLUTION WORKED. So all I did for it to work was this:

```
eureka:
    server:
        aWSAccessId: AWS_KEY
        aWSSecretKey: AWS_SECRET_KEY
        asgName: EC2ContainerService_AUTO_SCALING_GROUP_CREATED_BY_ECS_FOR_MY_CLUSTER

```

So my eureka servers bid the free EIPs that I put on my TXT DNS records :)

Thanks for your help.

**Comment by bsushant-athena** [comment]
@givenm is it possible for you to share your repo?

**Comment by Sridharc20** [comment]
I'm trying these from past week, couldn't map properly. Could you please share your configuration details.

**Comment by givenm** [comment]
@Sridharc20 Do you have a bit bucket account? What's your username or email?

**Comment by Sridharc20** [comment]
Hi @givenm my bitbucket accunt:  https://bitbucket.org/sridharc20/

**Comment by lucasobsidiam** [comment]
Hi @givenm, would you also mind sharing it to me? Trying to get this working with no luck in ECS.
