### ISSUE TITLE
Hystrix stopped working behind Zuul Proxy 

### ISSUE THREAD

**Issue by NickPadilla** [spring-cloud/spring-cloud-netflix#189]
Hello,

As of yesterday, I am seeing this error when trying to connect to the http://127.0.0.1:8766/hystrix.stream from the Hystrix Dashboard.  It is trying to hit the Zuul management port which is set to not have security with - 
```
management:
  security:
    enabled: false
```

I do have the Zuul Server using `@EnableOAuth2Sso`, so maybe I need to add some more configuration?  However this was working before yesterday.  Any ideas? 

This is the error. 
```

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'scopedTarget.oauth2ClientContext': Scope 'session' is not active for the current thread; consider defining a scoped proxy for this bean if you intend to refer to it from a singleton; nested exception is java.lang.IllegalStateException: No thread-bound request found: Are you referring to request attributes outside of an actual web request, or processing a request outside of the originally receiving thread? If you are actually operating within a web request and still receive this message, your code is probably running outside of DispatcherServlet/DispatcherPortlet: In this case, use RequestContextListener or RequestContextFilter to expose the current request.
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:352)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
        at org.springframework.aop.target.SimpleBeanTargetSource.getTarget(SimpleBeanTargetSource.java:35)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:187)
        at com.sun.proxy.$Proxy105.getAccessToken(Unknown Source)
        at org.springframework.security.oauth2.client.OAuth2RestTemplate.getAccessToken(OAuth2RestTemplate.java:169)
        at org.springframework.security.oauth2.client.filter.OAuth2ClientAuthenticationProcessingFilter.attemptAuthentication(OAuth2ClientAuthenticationProcessingFilter.java:94)
        at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:211)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
        at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:110)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
        at org.springframework.security.web.csrf.CsrfFilter.doFilterInternal(CsrfFilter.java:85)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
        at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:57)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
        at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:87)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
        at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:50)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
        at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:192)
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:160)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:537)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1085)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:658)
        at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:222)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1556)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1513)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: No thread-bound request found: Are you referring to request attributes outside of an actual web request, or processing a request outside of the originally receiving thread? If you are actually operating within a web request and still receive this message, your code is probably running outside of DispatcherServlet/DispatcherPortlet: In this case, use RequestContextListener or RequestContextFilter to expose the current request.
        at org.springframework.web.context.request.RequestContextHolder.currentRequestAttributes(RequestContextHolder.java:131)
        at org.springframework.web.context.request.SessionScope.get(SessionScope.java:91)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:337)
        ... 41 common frames omitted

```

**Comment by dsyer** [comment]
I think this is a side effect of commit 29bee28 (assuming you are on snapshots) because the /hystrix.stream is no longer part of the Spring MVC chain. Maybe we should rethink that (cc @spencergibb)?

**Comment by dsyer** [comment]
#187 was all about Turbine. Maybe we can fix it there instead? It's nice having /hystrix.stream being an `MvcEndpoint` actually (it follows the others in terms of security for instance).

**Comment by spencergibb** [comment]
@dsyer I can revert my commit and put /hystrix.stream back to an `MvcEndpoint`.  It seems like it fits in the "production ready" parts of actuator and security is nice.

**Comment by dsyer** [comment]
It looks like turbine already supports modifying the endpoint name through `turbine.instanceUrlSuffix.<appName>` (and `turbine.instanceUrlSuffix` for the default). So yes, I believe we should revert the change in #187.

**Comment by NickPadilla** [comment]
Hello @dsyer and @spencergibb - I have pulled the new changes, or revert rather, and have found something else off.  I have Zuul set to this
```
zuul:
  routes:
    micloudhystrix:
      path: /micloudhystrix/**
      stripPrefix: false
      retryable: true
```
This is so that the static resources are found from behind Zuul.   This was working as expected.  But this is what the browser console output now shows. 
![screen shot 2015-02-06 at 10 55 20 am](https://cloud.githubusercontent.com/assets/1381015/6084560/328cdd4e-adef-11e4-928b-b6c8f14da9a4.png)

**Comment by NickPadilla** [comment]
This is how hystrix is setup:
```
server:
  contextPath: /${spring.application.name:}
  port: ${SERVER_PORT:7979}
```
When working with Zuul it was serving the static resources correctly.  I did try to remove the `server.contextPath` setting from Hystrix and removed the `stripPrefix` from Zuul.  With this configuration I was never able to even reach the Hystrix Dashboard.  Please advise.

**Comment by spencergibb** [comment]
I reverted 29bee28db5328f7703ca25373c3a956ce141778a and the /hystrix.stream is now an mvc endpoint again.  I'm going to close this because of the confusion that commit caused.  Please open a new issue if you are still having troubles.
