### ISSUE TITLE
Can't set Content-Type in Feign client

### ISSUE THREAD

**Issue by sixcorners** [spring-cloud/spring-cloud-netflix#1902]
I want to set the Content-Type header programatically. When I try this happens:

```
Caused by: feign.codec.EncodeException: Invalid mime type "{Content-Type}": does not contain '/'
	at feign.ReflectiveFeign$BuildEncodedTemplateFromArgs.resolve(ReflectiveFeign.java:346)
	at feign.ReflectiveFeign$BuildTemplateByResolvingArgs.create(ReflectiveFeign.java:213)
	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:72)
	at feign.hystrix.HystrixInvocationHandler$1.run(HystrixInvocationHandler.java:108)
	at com.netflix.hystrix.HystrixCommand$2.call(HystrixCommand.java:301)
	at com.netflix.hystrix.HystrixCommand$2.call(HystrixCommand.java:297)
	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:46)
	... 27 common frames omitted
Caused by: org.springframework.http.InvalidMediaTypeException: Invalid mime type "{Content-Type}": does not contain '/'
	at org.springframework.http.MediaType.parseMediaType(MediaType.java:425)
	at org.springframework.http.MediaType.valueOf(MediaType.java:410)
	at org.springframework.cloud.netflix.feign.support.SpringEncoder.encode(SpringEncoder.java:64)
	at feign.ReflectiveFeign$BuildEncodedTemplateFromArgs.resolve(ReflectiveFeign.java:342)
	... 33 common frames omitted
Caused by: org.springframework.util.InvalidMimeTypeException: Invalid mime type "{Content-Type}": does not contain '/'
	at org.springframework.util.MimeTypeUtils.parseMimeType(MimeTypeUtils.java:239)
	at org.springframework.http.MediaType.parseMediaType(MediaType.java:422)
	... 36 common frames omitted
```

```
@FeignClient("x")
public interface XClient {
	@RequestMapping(value = "/api/something/{id}", method = POST)
	void x(@RequestHeader("Content-Type") String contentType, @PathVariable("id") Integer id,
		@RequestBody InputStream inputStream);
}
```

I ended up having to set a X-Content-Type2 header and setting up one of these:
```
@Bean
public RequestInterceptor contentTypeFilter() {
	return (req) -> {
		req.header("Content-Type", req.headers().get("X-Content-Type2").iterator().next());
	};
}
```
I am using:
spring-cloud-netflix-core-1.2.5.RELEASE.jar

**Comment by ryanjbaxter** [comment]
I dont believe you can set it programmatically using `@RequestHeader`, I believe we only support doing it via the `consumes` property of `@RequestMapping`.

**Comment by sixcorners** [comment]
Is it possible to add support?
Would it be a good idea to feed it to the @RequestMapping annotation using SpEL?

**Comment by thomasharin** [comment]
I have same problem. Can I know some due date for this issue? My FeignClient request need to resend some header param from client application so I need dynamic value of header param. 
Is something other option for this case? Thanks.

**Comment by spencergibb** [comment]
@thomasharin no due date.

**Comment by thorstenfrank** [comment]
This would have to be changed inside Spring MVC, am I right?
