### ISSUE TITLE
RibbonLoadBalancerClient vs RibbonLoadBalancingHttpClient

### ISSUE THREAD

**Issue by asarkar** [spring-cloud/spring-cloud-netflix#1918]
1. I'm trying to understand the difference between `org.springframework.cloud.netflix.ribbon.RibbonLoadBalancerClient` and `org.springframework.cloud.netflix.ribbon.apache.RibbonLoadBalancingHttpClient`. The two are not in the same class hierarchy, although the package name of the later would indicate so. The former is used by Feign clients and Zuul, but I'm not sure what's the purpose of the later.
2. How does Hystrix come into the picture when `RibbonLoadBalancerClient` is used by Zuul to route the request? I'm looking at `AbstractRibbonCommand`, which also happens to be a  `HystrixCommand` but never see it being called.

Edit: Using `Camden.SR6`.

**Comment by ryanjbaxter** [comment]
`RibbonLoadBalancingHttpClient` (and the retryable and OK HTTP implementations) are used by Zuul.  I believe `RibbonLoadBalancerClient` is used with `LoadBalanced` `RestTemplate`s.  Hystrix therefore would not com into play unless the user wraps the call for the `RestTemplate` in a Hystrix command.

**Comment by asarkar** [comment]
@ryanjbaxter That's not what I'm seeing by debugging 😞 . When I shutdown the target service, and put a breakpoint in `RibbonLoadBalancerClient.execute`, I still see it getting called. Following is the stacktrace, although it doesn't show what Ribbon client is used. I'm using `Camden.SR6`, which my edit now shows in the original question as well.
```
org.apache.http.conn.HttpHostConnectException: Connect to xxx:9030 [xxx/127.0.0.1, xxx/0:0:0:0:0:0:0:1, xxx/fe80:0:0:0:0:0:0:1%1] failed: Connection refused
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:159)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:359)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:118)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at org.springframework.cloud.netflix.zuul.filters.route.SimpleHostRoutingFilter.forwardRequest(SimpleHostRoutingFilter.java:364)
	at org.springframework.cloud.netflix.zuul.filters.route.SimpleHostRoutingFilter.forward(SimpleHostRoutingFilter.java:290)
	at org.springframework.cloud.netflix.zuul.filters.route.SimpleHostRoutingFilter.run(SimpleHostRoutingFilter.java:181)
	at com.netflix.zuul.ZuulFilter.runFilter(ZuulFilter.java:112)
	at com.netflix.zuul.FilterProcessor.processZuulFilter(FilterProcessor.java:193)
	at com.netflix.zuul.FilterProcessor.runFilters(FilterProcessor.java:157)
	at com.netflix.zuul.FilterProcessor.route(FilterProcessor.java:118)
	at com.netflix.zuul.ZuulRunner.route(ZuulRunner.java:96)
	at com.netflix.zuul.http.ZuulServlet.route(ZuulServlet.java:116)
	at com.netflix.zuul.http.ZuulServlet.service(ZuulServlet.java:81)
```

**Comment by asarkar** [comment]
@ryanjbaxter That's not what I'm seeing in a  debugging session 😞  See stacktrace below, where there's no Ribbon being used. Zuul is using Apache HTTP client to simply forward the request.
```
at org.springframework.cloud.netflix.zuul.filters.route.SimpleHostRoutingFilter.forwardRequest(SimpleHostRoutingFilter.java:364)
	  at org.springframework.cloud.netflix.zuul.filters.route.SimpleHostRoutingFilter.forward(SimpleHostRoutingFilter.java:290)
	  at org.springframework.cloud.netflix.zuul.filters.route.SimpleHostRoutingFilter.run(SimpleHostRoutingFilter.java:181)
	  at com.netflix.zuul.ZuulFilter.runFilter(ZuulFilter.java:112)
	  at com.netflix.zuul.FilterProcessor.processZuulFilter(FilterProcessor.java:193)
	  at com.netflix.zuul.FilterProcessor.runFilters(FilterProcessor.java:157)
	  at com.netflix.zuul.FilterProcessor.route(FilterProcessor.java:118)
	  at com.netflix.zuul.ZuulRunner.route(ZuulRunner.java:96)
	  at com.netflix.zuul.http.ZuulServlet.route(ZuulServlet.java:116)
	  at com.netflix.zuul.http.ZuulServlet.service(ZuulServlet.java:81)
```

**Comment by spencergibb** [comment]
`SimpleHostRoutingFilter` doesn't use ribbon. you have to set a `serviceId` to use `RibbonRoutingFilter`.

**Comment by asarkar** [comment]
@spencergibb Set a `serviceId` in `RequestContext`? Isn't that supposed to happen automatically if I've setup the routes in `application.yml`?

**Comment by asarkar** [comment]
I think I understand it now. My route looks as follows:
```
prefix: /whatever
  routes:
    abc:
      path: /abc/**
      strip-prefix: false
      url: http://abc:9060
```

`org.springframework.cloud.netflix.zuul.filters.pre.PreDecorationFilter.run` doesn't set a `serviceId` because the `location` starts with `http`. Thus, `RibbonRoutingFilter` is not executed.

So in this flow, Ribbon or Hystrix is not involved.

Is the above explanation correct or would you like to add something?

**Comment by spencergibb** [comment]
That is correct

**Comment by stiyyagura** [comment]
@asarkar when you have URL specified Zuul will use SimpleHostRoutingFilter if not you have to use serviceId to use RibbonRoutingFilter.( serviceId may not require in configuration if your origin services already registered in Eureka and you have right configuration to retrieve serviceId dynamically)

**Comment by asarkar** [comment]
> when you have URL specified Zuul will use SimpleHostRoutingFilter if not you have to use serviceId to use RibbonRoutingFilter

@stiyyagura I don't think that's correct. Acc. to [PreDecorationFilter.run](https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/zuul/filters/pre/PreDecorationFilter.java), if the location doesn't start with `http:`, `https:` or `forward:`, it sets the `serviceId`. Service name resolution is another matter that I've not looked into.

**Comment by stiyyagura** [comment]
Ok all I can say is already explained. Location comes based on routing information. If services are registered to eureka you don't need to configure anything. If not you need to mention URL(simplehost). Later one is what you are referring.
