### ISSUE TITLE
use Feign, Hystrix, and Consul always fails in the first time, I know the reason, but feign client configure about time-out does not work

### ISSUE THREAD

**Issue by jiangchao123** [spring-cloud/spring-cloud-netflix#1921]
Excuse me, I hava see the problem in this [issue](https://github.com/spring-cloud/spring-cloud-netflix/issues/768), and I meet the same problem to him. I know that in the first time, some class lazy initiallize that will need more time. So I try to configure the time of time-out. But it does not work. I configure 12s in time out, but it always enter hystrix in 2s. I dont know the reason, and I have block in the problem a long time. The amazing thing is that if I configure little time, it works. Such as if I configure 10ms, the request will always fails. If I configure 2s, it fails in the first time, and sussceed then. If I configure 12s, it still fails in the first time, it can not reach 12s, it will fails quickly within 2s. I really dont know the reason.Thanks very much if someone knows the reason~
 
This is my feign client:
```
@FeignClient(value = "spring-boot-demo", fallback = HelloClientFallback.class, configuration = FeignConfigure.class)
public interface TestClient {
    @RequestMapping(method = RequestMethod.POST, value = "/test/hello")
    public String getAnswerResult(@RequestParam(value = "param1") String param1,
            @RequestParam(value = "param2") String param2,
            @RequestParam(required = false, value = "param3") String param3);
}
```
This is my feign configure:
```
@Configuration
public class FeignConfigure {
     public static int connectTimeOutMillis = 12000;
     public static int readTimeOutMillis = 12000;
     @Bean
     public Request.Options options() {
            return new Request.Options(connectTimeOutMillis, readTimeOutMillis);
     }
}
```

**Comment by jiangchao123** [comment]
I write a small demo specifically to reproduce the problem, this is the git repository: https://github.com/jiangchao123/feign-test

**Comment by ryanjbaxter** [comment]
Can you provide the stack trace and tell us what version of Spring Cloud you are using?

**Comment by jiangchao123** [comment]
I am very happy for recieving your reply. I use version Camden.SR6. When I use feign client to request in the first time, it will time out. I have known the reason when I use virsual VM, it is because of the class of DynamicServerListLoadBalancer. The stack trace below:
```
2017-05-09 00:06:34.484  INFO 1915 --- [ing-boot-demo-1] s.c.a.AnnotationConfigApplicationContext : Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@4057b31: startup date [Tue May 09 00:06:34 CST 2017]; parent: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@61f05988
2017-05-09 00:06:34.533  INFO 1915 --- [ing-boot-demo-1] f.a.AutowiredAnnotationBeanPostProcessor : JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
2017-05-09 00:06:34.656  INFO 1915 --- [ing-boot-demo-1] c.netflix.config.ChainedDynamicProperty  : Flipping property: spring-boot-demo.ribbon.ActiveConnectionsLimit to use NEXT property: niws.loadbalancer.availabilityFilteringRule.activeConnectionsLimit = 2147483647
2017-05-09 00:06:34.683  INFO 1915 --- [ing-boot-demo-1] c.n.u.concurrent.ShutdownEnabledTimer    : Shutdown hook installed for: NFLoadBalancer-PingTimer-spring-boot-demo
2017-05-09 00:06:34.769  INFO 1915 --- [ing-boot-demo-1] c.netflix.loadbalancer.BaseLoadBalancer  : Client:spring-boot-demo instantiated a LoadBalancer:DynamicServerListLoadBalancer:{NFLoadBalancer:name=spring-boot-demo,current list of Servers=[],Load balancer stats=Zone stats: {},Server stats: []}ServerList:null
2017-05-09 00:06:34.776  INFO 1915 --- [ing-boot-demo-1] c.n.l.DynamicServerListLoadBalancer      : Using serverListUpdater PollingServerListUpdater
2017-05-09 00:06:34.815  INFO 1915 --- [ing-boot-demo-1] c.netflix.config.ChainedDynamicProperty  : Flipping property: spring-boot-demo.ribbon.ActiveConnectionsLimit to use NEXT property: niws.loadbalancer.availabilityFilteringRule.activeConnectionsLimit = 2147483647
2017-05-09 00:06:34.818  INFO 1915 --- [ing-boot-demo-1] c.n.l.DynamicServerListLoadBalancer      : DynamicServerListLoadBalancer for client spring-boot-demo initialized: DynamicServerListLoadBalancer:{NFLoadBalancer:name=spring-boot-demo,current list of Servers=[192.168.1.107:7001],Load balancer stats=Zone stats: {unknown=[Zone:unknown;	Instance count:1;	Active connections count: 0;	Circuit breaker tripped count: 0;	Active connections per server: 0.0;]
},Server stats: [[Server:192.168.1.107:7001;	Zone:UNKNOWN;	Total Requests:0;	Successive connection failure:0;	Total blackout seconds:0;	Last connection made:Thu Jan 01 08:00:00 CST 1970;	First connection made: Thu Jan 01 08:00:00 CST 1970;	Active Connections:0;	total failure count in last (1000) msecs:0;	average resp time:0.0;	90 percentile resp time:0.0;	95 percentile resp time:0.0;	min resp time:0.0;	max resp time:0.0;	stddev resp time:0.0]
]}ServerList:ConsulServerList{serviceId='spring-boot-demo', tag=null}
2017-05-09 00:06:35.046  INFO 1915 --- [nio-7001-exec-9] c.j.feign.controller.HelloController     : response: hello world hello world hello world hello world hello world hello world hello world 
2017-05-09 00:06:35.459 ERROR 1915 --- [nio-7001-exec-8] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is com.netflix.hystrix.exception.HystrixRuntimeException: HelloClient#getAnswerResult() timed-out and no fallback available.] with root cause

java.util.concurrent.TimeoutException: null
	at com.netflix.hystrix.AbstractCommand.handleTimeoutViaFallback(AbstractCommand.java:980) ~[hystrix-core-1.5.6.jar:1.5.6]
	at com.netflix.hystrix.AbstractCommand.access$500(AbstractCommand.java:59) ~[hystrix-core-1.5.6.jar:1.5.6]
	at com.netflix.hystrix.AbstractCommand$12.call(AbstractCommand.java:595) ~[hystrix-core-1.5.6.jar:1.5.6]
	at com.netflix.hystrix.AbstractCommand$12.call(AbstractCommand.java:587) ~[hystrix-core-1.5.6.jar:1.5.6]
	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$4.onError(OperatorOnErrorResumeNextViaFunction.java:140) ~[rxjava-1.1.10.jar:1.1.10]
	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87) ~[rxjava-1.1.10.jar:1.1.10]
	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87) ~[rxjava-1.1.10.jar:1.1.10]
	at com.netflix.hystrix.AbstractCommand$HystrixObservableTimeoutOperator$1.run(AbstractCommand.java:1121) ~[hystrix-core-1.5.6.jar:1.5.6]
	at com.netflix.hystrix.strategy.concurrency.HystrixContextRunnable$1.call(HystrixContextRunnable.java:41) ~[hystrix-core-1.5.6.jar:1.5.6]
	at com.netflix.hystrix.strategy.concurrency.HystrixContextRunnable$1.call(HystrixContextRunnable.java:37) ~[hystrix-core-1.5.6.jar:1.5.6]
	at com.netflix.hystrix.strategy.concurrency.HystrixContextRunnable.run(HystrixContextRunnable.java:57) ~[hystrix-core-1.5.6.jar:1.5.6]
	at com.netflix.hystrix.AbstractCommand$HystrixObservableTimeoutOperator$2.tick(AbstractCommand.java:1138) ~[hystrix-core-1.5.6.jar:1.5.6]
	at com.netflix.hystrix.util.HystrixTimer$1.run(HystrixTimer.java:99) ~[hystrix-core-1.5.6.jar:1.5.6]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_111]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) ~[na:1.8.0_111]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_111]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) ~[na:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_111]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111]

2017-05-09 00:06:35.790  INFO 1915 --- [erListUpdater-0] c.netflix.config.ChainedDynamicProperty  : Flipping property: spring-boot-demo.ribbon.ActiveConnectionsLimit to use NEXT property: niws.loadbalancer.availabilityFilteringRule.activeConnectionsLimit = 2147483647
```
Now, My primary problem is that. When I use the configure of time out of feign client. It does not work. My configure is below:
```
@Configuration
public class FeignConfigure {
     public static int connectTimeOutMillis = 12000;
     public static int readTimeOutMillis = 12000;
     @Bean
     public Request.Options options() {
            return new Request.Options(connectTimeOutMillis, readTimeOutMillis);
     }
}
```
The controller does not have any things except sleeping 500ms, the code is below:
```
@RestController
@RequestMapping(value = "/test")
public class HelloController {

    private static final Logger logger = LoggerFactory.getLogger(HelloController.class);

    @RequestMapping(value = "/hello", method = RequestMethod.POST)
    public String unit() {

        String response = "hello world hello world hello world hello world hello world hello world hello world ";
        logger.info("response: " + response);
        try {
            Thread.sleep(500);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        return response;
    }
}
```
So, the very amazing thing is that when I configure the time out which is very small such as 10ms, it works. Because it will always time out, so it proves that my configure works. The code is below:
```
@Configuration
public class FeignConfigure {

    public static final int connectTimeOutMillis = 10;
    public static final int readTimeOutMillis = 10;

//    public static final int connectTimeOutMillis = 12000;
//    public static final int readTimeOutMillis = 12000;

    @Bean
    public Request.Options options() {
        return new Request.Options(connectTimeOutMillis, readTimeOutMillis);
    }
}
```
But when I configure long time of time out such as 12s, I expect that it will not appear time out. the configure is below:
```
@Configuration
public class FeignConfigure {

//    public static final int connectTimeOutMillis = 10;
//    public static final int readTimeOutMillis = 10;

    public static final int connectTimeOutMillis = 12000;
    public static final int readTimeOutMillis = 12000;

    @Bean
    public Request.Options options() {
        return new Request.Options(connectTimeOutMillis, readTimeOutMillis);
    }
}
```
The result is that, it still fails in the first time, and then OK. I have configured 12s!!! It means the configure  of time out does not work. So I am very confused. Is my configure is wrong?

**Comment by ryanjbaxter** [comment]
Have your tried configuring the timeout via `hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds`?

**Comment by jiangchao123** [comment]
No, I dont try it. Because I am not sure that configure can configure more than one.  I have many API, So different API will configure different hystrix time of time-out. They are in the same application. If I configure via 
```
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds?
```
in the yaml configure file, I think it will be global effective.

**Comment by jiangchao123** [comment]
I try the configure in the yaml file via :
```
hystrix:
  metrics:
    enabled: true
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 12000
```
It works, but as I say above there are some APIs, diffrent API may want to have different time of time-out. So I think that the 
```
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds
```
will be global effective. And I am confused too that what is difference of Request.Options and hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds?

**Comment by eacdy** [comment]
try   `hystrix.command.<hystrixcommandkey>.execution.isolation.thread.timeoutInMilliseconds`

**Comment by jiangchao123** [comment]
Thanks, But I use the mode of feignclient and the hystrix is default enable, I dont use the mode of command. So, what can I get the hystrixcommandkey? Must I use mode of command?

**Comment by ryanjbaxter** [comment]
The `hystrixcommandkey` takes the format of `FeignClassName#methodSignature`.  See #1864.

**Comment by jiangchao123** [comment]
I am very thanks for your reply, now I have some other urgent things to do . I will try it on the weekend, and then feedback.

**Comment by TomVanWemmel** [comment]
I've stumbled upon a similar issue, using Ribbon directly. 
The first request always fails, no matter how high the time-out value is. 

An issue has been logged, but I'm not sure it will get any response. Maybe it helps you figure out where to look. 
https://github.com/Netflix/ribbon/issues/339

**Comment by ryanjbaxter** [comment]
@TomVanWemmel this repo is for issues related to Spring Cloud Netflix.  Any issue related to Ribbon directly needs to be handled in the Ribbon repo.

**Comment by ryanjbaxter** [comment]
I am going to close this issue due to lack of activity.  Please reopen if there is anything else we can do.

**Comment by jiangchao123** [comment]
thanks, I have try it, it works.

**Comment by gdyjdao** [comment]
dear all:
@Configuration
public class FeignRetry2 {
    @Bean
    Retryer feignRetryer() {
        return new Default(1000, 5000, 5);
    }

}

**Comment by khushbuv** [comment]
Hystrix command key takes >>FeignClassName#methodSignature, # is considered the beginning of a comment in application.properties, Then how it is is going to be loaded as Hystrix property?
Please explain...

**Comment by spencergibb** [comment]
Use quotes (single or double) around the key.
