### ISSUE TITLE
Spring Boot Service fails on startup when using custom autoconfiguration class for enabling/disabling eurekaclient

### ISSUE THREAD

**Issue by bsridhar123** [spring-cloud/spring-cloud-netflix#1933]
We were using Spring Boot 1.4.5 and Camden SR6.

We did not want to use @EnableEurekaClient annotation in Spring Boot Application class to register a service as eureka client.
So, we wrote a custom auto-configuration class and added the annotation to it with profile and made a library out of it so that we can refer it in any spring boot service accordingly.

We now upgraded to Spring Boot 1.5.3 and Dalston Release.
We found the below exception on startup of the service class for which we have activated the profile for making it as a Eureka Client. We did not see this when using Spring Boot 1.4.5 with Camden SR6.

Can you please let us know how to resolve the issue.

```
The exception we get is as below,
2017-05-12 02:06:16.174 DEBUG 1220 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   : Application failed to start due to an exception

org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.netflix.discovery.EurekaClient' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoMatchingBeanFound(DefaultListableBeanFactory.java:1486) ~[spring-beans-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1104) ~[spring-beans-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1066) ~[spring-beans-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:835) ~[spring-beans-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:741) ~[spring-beans-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:467) ~[spring-beans-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1173) ~[spring-beans-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1067) ~[spring-beans-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:513) ~[spring-beans-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483) ~[spring-beans-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[spring-beans-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761) ~[spring-beans-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:866) ~[spring-context-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542) ~[spring-context-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) ~[spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:737) [spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:370) [spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:314) [spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1162) [spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1151) [spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at com.demo.services.Application.main(Application.java:13) [classes/:na]

2017-05-12 02:06:16.175 ERROR 1220 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 0 of method eurekaHealthIndicator in org.springframework.cloud.netflix.eureka.EurekaDiscoveryClientConfiguration$EurekaHealthIndicatorConfiguration required a bean of type 'com.netflix.discovery.EurekaClient' that could not be found.
	- Bean method 'eurekaClient' not loaded because Ancestor org.springframework.cloud.netflix.eureka.EurekaClientAutoConfiguration did not match


Action:

Consider revisiting the conditions above or defining a bean of type 'com.netflix.discovery.EurekaClient' in your configuration.

```
I have also shared the code for the service which has this error on startup,, the library and also the eureka service used for reproducing this issue.
https://github.com/bsridhar123/demo-code

**Comment by ryanjbaxter** [comment]
Why do you not want to use `@EnabledEurekaClient`?

Sounds like you just need to create a `EurekaClient` bean to make your configuration work.  Have you looked into doing that.

**Comment by bsridhar123** [comment]
@ryanjbaxter Thanks for your response. The reason being we do not want the developer to be concerned with the fact the service is a eureka client in development mode. It is a  infrastructure concern. We only want to use the service as a eureka client  in higher environments by applying a profile accordingly.

But, the concern now being it worked fine for us when we were using spring boot 1.4.5, probably something has changed in next version of Spring 1.5.3 which has caused this breaking change for us. I was not able to find anything from the release notes.

Do you mean creating a EurekaClient bean would resolve this issue. Not sure how that would do so.

**Comment by ryanjbaxter** [comment]
Its more likely the fact that you upgraded from Camden to Dalston rather than upgrading boot versions.  You can try keeping the boot version the same and switching the Spring Cloud version and see if that makes a difference.

Based on 
```
Parameter 0 of method eurekaHealthIndicator in org.springframework.cloud.netflix.eureka.EurekaDiscoveryClientConfiguration$EurekaHealthIndicatorConfiguration required a bean of type 'com.netflix.discovery.EurekaClient' that could not be found.
	- Bean method 'eurekaClient' not loaded because Ancestor org.springframework.cloud.netflix.eureka.EurekaClientAutoConfiguration did not match
```
It seems like the `EurekaClient` bean is missing.  It might be worth providing a sample app so we can see what you are doing in more detail.

**Comment by bsridhar123** [comment]
I have already shared the repo for the code which I had used to reproduce the issue, in my initial comment.

sharing it again now,
https://github.com/bsridhar123/demo-code

**Comment by ryanjbaxter** [comment]
Sorry missed that, thanks

**Comment by bsridhar123** [comment]
@ryanjbaxter @spencergibb 
I used the  Dalston.SR1. There is no exception this time.

But, still I am not able to register the service as a Eureka Client using the profiles and auto-configuration on startup.

Can you please have a look at on this.

**Comment by bsridhar123** [comment]
Let me know if you need a new issue to be created for this.

**Comment by ryanjbaxter** [comment]
Does it seem like the same issue, or something new.  If the fix did not resolve the issue we can reopen this, if it seems like something new than open a new issue.

**Comment by bsridhar123** [comment]
My original issue still remains. I got an exception at startup and also my service was not registered as a Eureka Client with the profile applied to it via the autoconfiguration class.

Now, the exception is gone. but my issue is the service is still not registered as a Eureka Client with eureka registry.

The updated code using Dalson.SR1 and spring boot 1.5.3 is in the same repo.
https://github.com/bsridhar123/demo-code

**Comment by liweys** [comment]
I got the same error, and resolved it by renaming my class EurekaClient to EurekaClient1. In my case, the class name happened to be the same as a class in the lib.  With Spring Boot 2.0.0.
