### ISSUE TITLE
use spring cloud feign okhttp with sleuth error

### ISSUE THREAD

**Issue by zhanglc** [spring-cloud/spring-cloud-netflix#1936]
Hi :

use spring cloud feign okhttp with sleuth error.  
```
spring cloud version:Dalston.RELEASE
spring-cloud-sleuth:1.2.0.RELEASE 
```
stack:
```
Caused by: org.springframework.aop.framework.AopConfigException: Could not generate CGLIB subclass of class [class org.springframework.cloud.sleuth.instrument.web.client.feign.TraceFeignClient]: Common causes of this problem include using a final class or a non-visible class; nested exception is org.springframework.cglib.core.CodeGenerationException: java.lang.reflect.InvocationTargetException-->null
	at org.springframework.aop.framework.CglibAopProxy.getProxy(CglibAopProxy.java:207)
	at org.springframework.aop.framework.ProxyFactory.getProxy(ProxyFactory.java:109)
	at org.springframework.aop.framework.autoproxy.AbstractAutoProxyCreator.createProxy(AbstractAutoProxyCreator.java:469)
	at org.springframework.aop.framework.autoproxy.AbstractAutoProxyCreator.wrapIfNecessary(AbstractAutoProxyCreator.java:349)
	at org.springframework.aop.framework.autoproxy.AbstractAutoProxyCreator.postProcessAfterInitialization(AbstractAutoProxyCreator.java:298)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsAfterInitialization(AbstractAutowireCapableBeanFactory.java:423)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1633)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
	... 126 common frames omitted
Caused by: org.springframework.cglib.core.CodeGenerationException: java.lang.reflect.InvocationTargetException-->null
	at org.springframework.cglib.core.AbstractClassGenerator.generate(AbstractClassGenerator.java:345)
	at org.springframework.cglib.proxy.Enhancer.generate(Enhancer.java:492)
	at org.springframework.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:93)
	at org.springframework.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:91)
	at org.springframework.cglib.core.internal.LoadingCache$2.call(LoadingCache.java:54)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.springframework.cglib.core.internal.LoadingCache.createEntry(LoadingCache.java:61)
	at org.springframework.cglib.core.internal.LoadingCache.get(LoadingCache.java:34)
	at org.springframework.cglib.core.AbstractClassGenerator$ClassLoaderData.get(AbstractClassGenerator.java:116)
	at org.springframework.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:291)
	at org.springframework.cglib.proxy.Enhancer.createHelper(Enhancer.java:480)
	at org.springframework.cglib.proxy.Enhancer.createClass(Enhancer.java:337)
	at org.springframework.aop.framework.ObjenesisCglibAopProxy.createProxyClassAndInstance(ObjenesisCglibAopProxy.java:55)
	at org.springframework.aop.framework.CglibAopProxy.getProxy(CglibAopProxy.java:203)
	at org.springframework.aop.framework.ProxyFactory.getProxy(ProxyFactory.java:109)
	at org.springframework.aop.framework.autoproxy.AbstractAutoProxyCreator.createProxy(AbstractAutoProxyCreator.java:469)
	at org.springframework.aop.framework.autoproxy.AbstractAutoProxyCreator.wrapIfNecessary(AbstractAutoProxyCreator.java:349)
	at org.springframework.aop.framework.autoproxy.AbstractAutoProxyCreator.postProcessAfterInitialization(AbstractAutoProxyCreator.java:298)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsAfterInitialization(AbstractAutowireCapableBeanFactory.java:423)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1633)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:220)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveNamedBean(DefaultListableBeanFactory.java:1018)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:345)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:340)
	at org.springframework.cloud.sleuth.instrument.web.client.feign.SleuthHystrixFeignBuilder.client(SleuthHystrixFeignBuilder.java:47)
	... 115 common frames omitted
Caused by: java.lang.reflect.InvocationTargetException: null
	at sun.reflect.GeneratedMethodAccessor12.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.cglib.core.ReflectUtils.defineClass(ReflectUtils.java:413)
	at org.springframework.cglib.core.AbstractClassGenerator.generate(AbstractClassGenerator.java:336)
	... 144 common frames omitted
Caused by: java.lang.IllegalAccessError: class org.springframework.cloud.sleuth.instrument.web.client.feign.TraceFeignClient$$EnhancerBySpringCGLIB$$1bb9f630 cannot access its superclass org.springframework.cloud.sleuth.instrument.web.client.feign.TraceFeignClient
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	... 149 common frames omitted
```

**Comment by ryanjbaxter** [comment]
@marcingrzejszczak any thoughts?

**Comment by marcingrzejszczak** [comment]
@zhanglc can you try with latest snapshots to see if the exception still persists?

**Comment by jonathannaguin** [comment]
@marcingrzejszczak I just tried with the following dependencies and this is still an issue:
```
	compile("org.springframework.cloud:spring-cloud-starter-sleuth:2.0.2.RELEASE")
	compile("org.springframework.cloud:spring-cloud-starter:2.0.2.RELEASE")
	compile("org.springframework.boot:spring-boot-starter-aop:2.1.0.RELEASE")
	compile("org.springframework.cloud:spring-cloud-sleuth-core:2.0.2.RELEASE")
	compile group: 'org.springframework.cloud', name: 'spring-cloud-starter-openfeign', version: '2.0.2.RELEASE'
```

It seems to be failing because of lack of visibility of:
```
class LazyClient implements Client
```

**Comment by ryanjbaxter** [comment]
@jonathannaguin can you please use the Spring Cloud BOM and if that does not work can you provide a sample?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by ryanjbaxter** [comment]
Your project is still not using the Spring Cloud BOM.  Please generate a project using start.spring.io.

**Comment by jonathannaguin** [comment]
@ryanjbaxter Sorry, I thought the following block was for that:
```
dependencyManagement {
	imports {
		mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
		mavenBom "org.springframework.cloud:spring-cloud-sleuth:${springCloudSleuthVersion}"
	}
}
```

By the way, I used the Spring Initializr for that project by selecting Sleuth and Cloud Bootstrap, but I had removed one of the dependencies as I thought was not needed. I've just added it back and still getting the same problem at start up.

**Comment by ryanjbaxter** [comment]
This fixes the problem, and I think is the correct way to do this.

```
    @Bean
    public TestService testService(Client client)
    {
        return Feign.builder()
                    .logger(new Slf4jLogger())
                    .client(client)
                    .target(TestService.class, "http://localhost:8081");
    }
```
You are instantiating the bean a second time by doing this
https://github.com/jonathannaguin/spring-sleuth-feign-issue/blob/master/src/main/java/com/example/demo/Config.java#L63

That is causing the exception.

In addition you should use Feign 9.7.0 and you dont need this https://github.com/jonathannaguin/spring-sleuth-feign-issue/blob/master/build.gradle#L42
