### ISSUE TITLE
Zuul does not proxy multipart/form requests 

### ISSUE THREAD

**Issue by vsafin-copart** [spring-cloud/spring-cloud-netflix#197]
Turned on HTTP Client debuging and forwarded request always has empty body. 

In `ProxyRequestHelper.debugRequestEntity`

```
		String entity = IOUtils.toString(inputStream);
```

entity is always = ""

**Comment by vsafin-copart** [comment]
See following in the log - looks like problem is with com.netflix.zuul.http.HttpServletRequestWrapper

2015-02-04 17:34:43.403 DEBUG 11872 --- [io-10080-exec-2] c.n.zuul.http.HttpServletRequestWrapper  : Path = null
2015-02-04 17:34:43.404 DEBUG 11872 --- [io-10080-exec-2] c.n.zuul.http.HttpServletRequestWrapper  : Transfer-Encoding = null
2015-02-04 17:34:43.404 DEBUG 11872 --- [io-10080-exec-2] c.n.zuul.http.HttpServletRequestWrapper  : Content-Encoding = null
2015-02-04 17:34:43.404 DEBUG 11872 --- [io-10080-exec-2] c.n.zuul.http.HttpServletRequestWrapper  : Content-Length header = 781011
2015-02-04 17:34:43.404 DEBUG 11872 --- [io-10080-exec-2] c.n.zuul.http.HttpServletRequestWrapper  : Length of contentData byte array = 0
2015-02-04 17:34:43.404  WARN 11872 --- [io-10080-exec-2] c.n.zuul.http.HttpServletRequestWrapper  : Content-length different from byte array length! cl=781011, array=0

**Comment by dsyer** [comment]
What's the use case where you need to POST a multipart form? Wouldn't it work with a normal one?

**Comment by vsafin-copart** [comment]
Have set of services all registering with Eureka and one of them accepting file uploads. Would like to use Zuul to be front end to all those.

**Comment by dsyer** [comment]
Have a go with that change (it's tested, but not with file uploads).

**Comment by vsafin-copart** [comment]
Will test and let you know

**Comment by vsafin-copart** [comment]
Getting following exception at the destination service:


java.lang.IllegalStateException: Current request is not of type [org.springframework.web.multipart.MultipartHttpServletRequest]: SecurityContextHolderAwareRequestWrapper[ FirewalledRequest[ org.apache.catalina.connector.RequestFacade@5c1f45f9]]
	at org.springframework.web.servlet.mvc.method.annotation.ServletRequestMethodArgumentResolver.resolveArgument(ServletRequestMethodArgumentResolver.java:94)
	at org.springframework.web.method.support.HandlerMethodArgumentResolverComposite.resolveArgument(HandlerMethodArgumentResolverComposite.java:77)

Still digging through the code.

**Comment by dsyer** [comment]
I can reproduce that pretty easily (the wrong header is being sent downstream). Let's have another bash.

**Comment by vsafin-copart** [comment]
Ok seems like it is not correctly proxying requests. One issue is if request is large enough I get ZuulException caused by HystrixCommand read timeout

Caused by: com.netflix.hystrix.exception.HystrixRuntimeException: upload-wsRibbonCommand failed and no fallback available.
	at com.netflix.hystrix.AbstractCommand$20.call(AbstractCommand.java:816)
	at com.netflix.hystrix.AbstractCommand$20.call(AbstractCommand.java:798)
	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$1.onError(OperatorOnErrorResumeNextViaFunction.java:76)
	at rx.internal.operators.OperatorDoOnEach$1.onError(OperatorDoOnEach.java:70)
	at rx.internal.operators.OperatorDoOnEach$1.onError(OperatorDoOnEach.java:70)
	at rx.Observab

I added following to application.yml but it does not seems to help

hystrix: 
  command:
    upload-wsRibbonCommand:
       execution:
         isolation:
           thread:
              timeoutInMilliseconds: 30000

**Comment by vsafin-copart** [comment]
Problem is solved by configuring ribbon timeout:

upload-ws.ribbon.ReadTimeout=30000    

Thank you!

**Comment by EricGenet** [comment]
Hi,

Is multipart/form request really working for you guys?

We are running Zuul as a front end to our services stack and every time we hit it with a multipart/form request the target service throws
```
java.lang.RuntimeException: java.io.IOException: Missing initial multi part boundary
	at org.eclipse.jetty.server.Request.extractMultipartParameters(Request.java:390)
	at org.eclipse.jetty.server.Request.extractContentParameters(Request.java:308)
```
If we send the request straight to the service everything runs fine.

We are currently on the 1.0.3-RELEASE of spring-cloud-starter-zuul

Thanks in advance for your feedback.

**Comment by dsyer** [comment]
Did you send it to the multipart endpoint (http://projects.spring.io/spring-cloud/spring-cloud.html#_uploading_files_through_zuul)? P.S. it's obviously a bad idea to call your service "zuul" if it's registering with Eureka.

**Comment by EricGenet** [comment]
Hi,

Thanks for that, it works when using the multipart endpoint, but, reading through the docs, I was under the impression it was only required for larger file upload.
Is that correct?

**Comment by dsyer** [comment]
There are tests which prove it works both ways (through the /zuul endpoint and directly).

**Comment by EricGenet** [comment]
OK, I'll look into those.

Thanks for your help!
