### ISSUE TITLE
Zuul exposes all Eureka-registered services by default

### ISSUE THREAD

**Issue by digitaljoel** [spring-cloud/spring-cloud-netflix#198]
If Zuul is connected to Eureka then all services registered in Eureka get a handler registered for them in Zuul.  You can ignore services by id using ignored-services.  For security purposes, I would like to disable this auto-registration and only register those services that I have configured explicitly.

As it is, I have to know the name of every service registered so I can add them to the ignored-services list, which makes it too easy for a service to escape into the wild.

**Comment by digitaljoel** [comment]
Sadly, it appears that * is not a valid value in yml.
```
zuul:
  ignored-services: *
  routes:
```
yields
```
org.yaml.snakeyaml.scanner.ScannerException: while scanning an alias
 in 'reader', line 42, column 21:
      ignored-services: *
                        ^
expected alphabetic or numeric character, but found but found 

 in 'reader', line 42, column 22:
      ignored-services: *
                         ^

	at org.yaml.snakeyaml.scanner.ScannerImpl.scanAnchor(ScannerImpl.java:1439)
	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchAlias(ScannerImpl.java:918)
	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:366)
	at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:226)
	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingValue.produce(ParserImpl.java:586)
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158)
	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:143)
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:132)
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:231)
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155)
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:231)
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155)
	at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122)
	at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:84)
	at org.yaml.snakeyaml.constructor.BaseConstructor.getData(BaseConstructor.java:104)
	at org.yaml.snakeyaml.Yaml$1.next(Yaml.java:502)
	at org.springframework.beans.factory.config.YamlProcessor.process(YamlProcessor.java:152)
```

**Comment by dsyer** [comment]
We didn't invent YAML. I imagine you have to quote it (maybe)?

**Comment by digitaljoel** [comment]
I understand you didn't invent YAML.   Sorry, I was going by the documentation on the checkin and the test case.  Setting it to ```  ignored-services: "*"``` worked.

**Comment by dsyer** [comment]
Good catch on the docs, thanks. And thanks for testing.

**Comment by digitaljoel** [comment]
Sure thing. I should have tried the quotes before the comment.
