### ISSUE TITLE
zuul retry not working correctly when connecting timeout

### ISSUE THREAD

**Issue by hsj1606** [spring-cloud/spring-cloud-netflix#2052]
spring cloud version: Dalston.RELEASE
zuul config:
zuul.retryable=true 
ribbon.restclient.enabled=true
ribbon.MaxAutoRetries=0
ribbon.MaxAutoRetriesNextServer=1
ribbon.OkToRetryOnAllOperations=true
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds=10000
ribbon.ConnectTimeout=3000
ribbon.ReadTimeout=3000

I have two backend servers, one works fine, another cannot connect. When I sending a request to zuul, it always pick the down server first, then wait the connect timeout (3s) then redirect to another server. And when I send the request multiple times, following exception happens ：
`Caused by: com.netflix.client.ClientException: Number of retries on next server exceeded max 1 retries, while making a call for: 172.16.48.140:8200
        at com.netflix.loadbalancer.reactive.LoadBalancerCommand$4.call(LoadBalancerCommand.java:352) ~[ribbon-loadbalancer-2.2.2.jar!/:2.2.2]
        at com.netflix.loadbalancer.reactive.LoadBalancerCommand$4.call(LoadBalancerCommand.java:345) ~[ribbon-loadbalancer-2.2.2.jar!/:2.2.2]
        at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$4.onError(OperatorOnErrorResumeNextViaFunction.java:140) ~[rxjava-1.1.10.jar!/:1.1.10]
        at rx.internal.operators.OperatorRetryWithPredicate$SourceSubscriber$1$1.onError(OperatorRetryWithPredicate.java:107) ~[rxjava-1.1.10.jar!/:1.1.10]
        at rx.observers.SerializedObserver.onError(SerializedObserver.java:153) ~[rxjava-1.1.10.jar!/:1.1.10]
        at rx.observers.SerializedSubscriber.onError(SerializedSubscriber.java:78) ~[rxjava-1.1.10.jar!/:1.1.10]
        at rx.internal.operators.OnSubscribeConcatMap$ConcatMapSubscriber.innerError(OnSubscribeConcatMap.java:192) ~[rxjava-1.1.10.jar!/:1.1.10]
        at rx.internal.operators.OnSubscribeConcatMap$ConcatMapInnerSubscriber.onError(OnSubscribeConcatMap.java:340) ~[rxjava-1.1.10.jar!/:1.1.10]
        at rx.observers.Subscribers$5.onError(Subscribers.java:230) ~[rxjava-1.1.10.jar!/:1.1.10]
        at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87) ~[rxjava-1.1.10.jar!/:1.1.10]
        at rx.internal.operators.OnSubscribeThrow.call(OnSubscribeThrow.java:44) ~[rxjava-1.1.10.jar!/:1.1.10]
        at rx.internal.operators.OnSubscribeThrow.call(OnSubscribeThrow.java:28) ~[rxjava-1.1.10.jar!/:1.1.10]`

**Comment by ryanjbaxter** [comment]
So if it tries the next server, why do you think it is not working correctly?

**Comment by hsj1606** [comment]
One question is:
If there's server A and B, B is down. I think this is the correct retry round strategy 
1st request should try server A, works fine
2nd request should try server B which cannot connect, will automatically try server A.
3rd request should try server A.
but the behavior is zuul always pick server B every time.  

Another question is:
even if server B is down, should not make service unavailable, above exception should not be thrown (Number of retries on next server exceeded max 1 retries)

**Comment by hsj1606** [comment]
I included spring-retry on classpath and use default http client, issue still happen

**Comment by ryanjbaxter** [comment]
@hsj1606 yes it should work that way in theory.  However if you are using service discovery (Eureka) the list of servers returned from Eureka is actually a `Set` so the order can vary from time to time.  So if the list is refreshed in between requests the order could change (you might see B requested twice in row for example).  However the retry should work and then try service A.  Can you provide a sample that reproduces the issue?

**Comment by hsj1606** [comment]
zuul sample: https://github.com/hsj1606/sample-gateway.git
need to start your eureka server and two backend server, then make one of the backend server down, will reproduce the issue. I've made a jmeter test case showing that some request was fail

![image](https://user-images.githubusercontent.com/12151317/27315209-de0d8532-55aa-11e7-921b-52cd97aded74.png)

and exception stacktrace: 
`Caused by: org.apache.http.conn.ConnectTimeoutException: Connect to 172.16.48.140:8200 [/172.16.48.140] failed: connect timed out
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:151) ~[httpclient-4.5.3.jar!/:4.5.3]
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:359) ~[httpclient-4.5.3.jar!/:4.5.3]
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381) ~[httpclient-4.5.3.jar!/:4.5.3]
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237) ~[httpclient-4.5.3.jar!/:4.5.3]
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185) ~[httpclient-4.5.3.jar!/:4.5.3]
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) ~[httpclient-4.5.3.jar!/:4.5.3]
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111) ~[httpclient-4.5.3.jar!/:4.5.3]
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[httpclient-4.5.3.jar!/:4.5.3]
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[httpclient-4.5.3.jar!/:4.5.3]
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108) ~[httpclient-4.5.3.jar!/:4.5.3]
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56) ~[httpclient-4.5.3.jar!/:4.5.3]
        at org.springframework.cloud.netflix.ribbon.apache.RetryableRibbonLoadBalancingHttpClient$1.doWithRetry(RetryableRibbonLoadBalancingHttpClient.java:92) ~[spring-cloud-netflix-core-1.3.0.RELEASE.jar!/:1.3.0.RELEASE]
        at org.springframework.cloud.netflix.ribbon.apache.RetryableRibbonLoadBalancingHttpClient$1.doWithRetry(RetryableRibbonLoadBalancingHttpClient.java:70) ~[spring-cloud-netflix-core-1.3.0.RELEASE.jar!/:1.3.0.RELEASE]
        at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:286) ~[spring-retry-1.2.0.RELEASE.jar!/:?]
        at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:163) ~[spring-retry-1.2.0.RELEASE.jar!/:?]
        at org.springframework.cloud.netflix.ribbon.apache.RetryableRibbonLoadBalancingHttpClient.executeWithRetry(RetryableRibbonLoadBalancingHttpClient.java:109) ~[spring-cloud-netflix-core-1.3.0.RELEASE.jar!/:1.3.0.RELEASE]
        at org.springframework.cloud.netflix.ribbon.apache.RetryableRibbonLoadBalancingHttpClient.execute(RetryableRibbonLoadBalancingHttpClient.java:100) ~[spring-cloud-netflix-core-1.3.0.RELEASE.jar!/:1.3.0.RELEASE]
        at org.springframework.cloud.netflix.ribbon.apache.RetryableRibbonLoadBalancingHttpClient.execute(RetryableRibbonLoadBalancingHttpClient.java:49) ~[spring-cloud-netflix-core-1.3.0.RELEASE.jar!/:1.3.0.RELEASE]
        at com.netflix.client.AbstractLoadBalancerAwareClient$1.call(AbstractLoadBalancerAwareClient.java:109) ~[ribbon-loadbalancer-2.2.2.jar!/:2.2.2]
        at com.netflix.loadbalancer.reactive.LoadBalancerCommand$3$1.call(LoadBalancerCommand.java:303) ~[ribbon-loadbalancer-2.2.2.jar!/:2.2.2]
        at com.netflix.loadbalancer.reactive.LoadBalancerCommand$3$1.call(LoadBalancerCommand.java:287) ~[ribbon-loadbalancer-2.2.2.jar!/:2.2.2]
        at rx.internal.util.ScalarSynchronousObservable$3.call(ScalarSynchronousObservable.java:231) ~[rxjava-1.1.10.jar!/:1.1.10]`

**Comment by hsj1606** [comment]
Thanks. It will be much better if the retry target be more accurate(pick the instance without the "down" one). Because I have to increase the `ribbon.MaxAutoRetriesNextServer` to a slightly big value( bigger than instance size) and the service will not be 100% available in theory.

**Comment by ryanjbaxter** [comment]
If the service is really "down" (it has been shutdown or has not sent hearbeat information to the Eureka server) than it will be taken out of the available servers list in Eureka.  A timeout is a different story.  The service is still up as far as Eureka is concerned.  But it could be a network issue for example that is causing the request to fail to the downed service.

**Comment by hsj1606** [comment]
Make sense. Assume that server is really down, client need some time to refresh local server list. It will be better if the retry target is correct during the refresh interval. And the meaning of ribbon.MaxAutoRetriesNextServer is more clear.

**Comment by ryanjbaxter** [comment]
There is nothing we can do on the client until it gets the updated details from the Eureka server.

**Comment by Harshan96** [comment]
hi @ryanjbaxter  I have a problem with zuul. I am using Zuul with Spring boot and my front end is angular. My intention now is to retry whenever i get a 401 response and this is not happening. I have tried the following 

ribbon.eureka.enabled=false
zuul.retryable=true
spring.cloud.loadbalancer.retry.enabled=true
ribbon.OkToRetryOnAllOperations=true
ribbon.MaxAutoRetries=3
ribbon.MaxAutoRetriesNextServer=3

but they r not workin....Pls do help and thanks in advance

**Comment by ryanjbaxter** [comment]
@Harshan96 please open a separate issue

**Comment by Harshan96** [comment]
@ryanjbaxter  sorry I have created a new issue https://github.com/spring-cloud/spring-cloud-netflix/issues/2172
