### ISSUE TITLE
Way to use Zuul to proxy non eureka service

### ISSUE THREAD

**Issue by NickPadilla** [spring-cloud/spring-cloud-netflix#211]
I am wondering if there is a way to have Zuul proxy a backend service that isn't part of the eureka ecosystem.  I have Zuul doing a redirect to another URL as expected but it is a redirect - if the service is only in a private subnet the redirect will not work.  Any ideas?

**Comment by dsyer** [comment]
From the user guide:

> The location of the backend can be specified as either a "serviceId" (for a Eureka service) or a "url" (for a physical location), e.g.

         zuul:
          routes:
            users:
              path: /myusers/**
              url: http://example.com/users_service

**Comment by NickPadilla** [comment]
I do have url set, it does a redirect.  The url in the browser changes. Is it supposed to do the direct?

**Comment by spencergibb** [comment]
No it should not do a redirect.  Is it possible you're service is sending a redirect to the browser?  The zuul filters don't do redirects.

**Comment by dsyer** [comment]
Maybe the redirect is coming from Spring Security in the proxy (or in the backend, as suggested by Spencer). Either way it's unlikely to be anything to do with the proxy itself.

**Comment by ccit-spence** [comment]
I am having the same problem going to a fresh Atlassian Confluence installation.

**Comment by ccit-spence** [comment]
Error being generated

```
2015-03-16 03:07:51.611  WARN 966 --- [http-nio-80-exec-16] o.s.c.n.z.filters.post.SendErrorFilter   : Error during filtering

org.apache.http.client.ClientProtocolException: null
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:867)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:115)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
	at org.springframework.cloud.netflix.zuul.filters.route.SimpleHostRoutingFilter.forwardRequest(SimpleHostRoutingFilter.java:254)
	at org.springframework.cloud.netflix.zuul.filters.route.SimpleHostRoutingFilter.forward(SimpleHostRoutingFilter.java:217)
	at org.springframework.cloud.netflix.zuul.filters.route.SimpleHostRoutingFilter.run(SimpleHostRoutingFilter.java:175)
	at com.netflix.zuul.ZuulFilter.runFilter(ZuulFilter.java:112)
	at com.netflix.zuul.FilterProcessor.processZuulFilter(FilterProcessor.java:197)
	at com.netflix.zuul.FilterProcessor.runFilters(FilterProcessor.java:161)
	at com.netflix.zuul.FilterProcessor.route(FilterProcessor.java:120)
	at com.netflix.zuul.ZuulRunner.route(ZuulRunner.java:84)
	at com.netflix.zuul.http.ZuulServlet.route(ZuulServlet.java:111)
	at com.netflix.zuul.http.ZuulServlet.service(ZuulServlet.java:77)
	at org.springframework.web.servlet.mvc.ServletWrappingController.handleRequestInternal(ServletWrappingController.java:158)
	at org.springframework.cloud.netflix.zuul.web.ZuulController.handleRequestInternal(ZuulController.java:43)
	at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:146)
	at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:50)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:943)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:877)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:966)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:857)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:618)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:842)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:725)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.springframework.boot.actuate.autoconfigure.EndpointWebMvcAutoConfiguration$ApplicationContextHeaderFilter.doFilterInternal(EndpointWebMvcAutoConfiguration.java:291)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at de.codecentric.boot.admin.web.EndpointCorsFilter.doFilterInternal(EndpointCorsFilter.java:63)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:77)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:102)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.springframework.boot.actuate.autoconfigure.MetricFilterAutoConfiguration$MetricsFilter.doFilterInternal(MetricFilterAutoConfiguration.java:90)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:516)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1086)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:659)
	at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:223)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1558)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1515)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.http.ProtocolException: Invalid request URI: //
	at org.apache.http.impl.client.RequestWrapper.<init>(RequestWrapper.java:83)
	at org.apache.http.impl.client.DefaultRequestDirector.wrapRequest(DefaultRequestDirector.java:331)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:379)
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:863)
	... 68 common frames omitted
Caused by: java.net.URISyntaxException: Expected authority at index 2: //
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.failExpecting(URI.java:2854)
	at java.net.URI$Parser.parseHierarchical(URI.java:3102)
	at java.net.URI$Parser.parse(URI.java:3063)
	at java.net.URI.<init>(URI.java:588)
	at org.apache.http.impl.client.RequestWrapper.<init>(RequestWrapper.java:81)
	... 71 common frames omitted
```

**Comment by ccit-spence** [comment]
Ok, should have tried a little more before assuming a problem. I figure Confluence is pretty common so will add what it took to make it work.  In our case Confluence is the backend help documentation for the main system.

1: Configure Zuul Route
```
zuul:
    routes:
        confluence:
            path: /confluence/**
            url: http://hostname:{port}/confluence
            stripPrefix: true
```

2: Confluence: Add `/confluence` to Context path
```
<Context path="/confluence" docBase="../confluence" debug="0" reloadable="false" useHttpOnly="true">
```
3:  Confluence: General Configuration
Update the base URL

**Comment by dsyer** [comment]
I'm not sure that helps anyone (it doesn't help me to think about a documentation change anyway). Why is confluence special? What is the `{port}` placeholder doing in your URL? What is different about the configuration that works for you as opposed to the one that doesn't?

**Comment by ccit-spence** [comment]
The `{port}` is simply saying that Confluence is normally installed on a port and not `80`.  You are right there is not a difference from the example you provided and no need to document my comment anywhere within the docs.  

This is just an example of a configuration for those that want to integrate a third party service.  In the case of Confluence; Zuul is doing what it is supposed to do. Confluence however requires further configuration to make it work behind Zuul.

The point being for those that might assume that adding a route is all that needs to happen to get something behind Zuul.
