### ISSUE TITLE
NullPointer when creating Feign Client

### ISSUE THREAD

**Issue by pochadri** [spring-cloud/spring-cloud-netflix#212]
not able to create feign client getting this error in 1.0.0.RC3

```
Caused by: java.lang.NullPointerException: encoder
	at feign.Util.checkNotNull(Util.java:93)
	at feign.ReflectiveFeign$ParseHandlersByName.<init>(ReflectiveFeign.java:138)
	at feign.ReflectiveFeign$ParseHandlersByName$$InjectAdapter.get(ReflectiveFeign$ParseHandlersByName$$InjectAdapter.java:67)
	at feign.ReflectiveFeign$ParseHandlersByName$$InjectAdapter.get(ReflectiveFeign$ParseHandlersByName$$InjectAdapter.java:19)
	at feign.ReflectiveFeign$$InjectAdapter.get(ReflectiveFeign$$InjectAdapter.java:62)
	at feign.ReflectiveFeign$$InjectAdapter.get(ReflectiveFeign$$InjectAdapter.java:23)
	at feign.ReflectiveFeign$Module$$ModuleAdapter$ProvideFeignProvidesAdapter.get(ReflectiveFeign$Module$$ModuleAdapter.java:114)
	at feign.ReflectiveFeign$Module$$ModuleAdapter$ProvideFeignProvidesAdapter.get(ReflectiveFeign$Module$$ModuleAdapter.java:78)
	at dagger.ObjectGraph$DaggerObjectGraph.get(ObjectGraph.java:272)
	at feign.Feign$Builder.target(Feign.java:265)
	at org.springframework.cloud.netflix.feign.FeignClientFactoryBean.loadBalance(FeignClientFactoryBean.java:126)
	at org.springframework.cloud.netflix.feign.FeignClientFactoryBean.getObject(FeignClientFactoryBean.java:136)
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:168)
	... 29 more-
```

previously was using `FeignConfiguration` and using `loadBalance()` method to create the client.

any idea if i am missing anything?

**Comment by dsyer** [comment]
Can you provide some more steps to repeat? What does your client configuration look like? Is it a fixed URL or a discovered service?

**Comment by pochadri** [comment]
It is a discovered service
this is my configuration

Client  Configuration
--  Main Application
@Configuration
@ComponentScan
@EnableDiscoveryClient
@EnableAutoConfiguration
@EnableFeignClients
public class MainApplication{
}
--
--- Feign Client definition 
@FeignClient("sampleBank")
public interface BankIntegration {

    @RequestMapping(value="/api/int/{bankName}/transfer",method = RequestMethod.POST)
    public TransferResponse transfer(@PathVariable("bankName") String bankName,@RequestBody TransferRequest transferRequest);

}


Yes spring creates the client , i was debugging it and thought that during the client object creation  error is thrown hence said "not able to create feign client"

**Comment by dsyer** [comment]
I don't see anything wrong with that so it must be something tricky behind the scenes. Can you share a project (minimal preferably) that demonstrates the problem?

**Comment by spencergibb** [comment]
closing, if you still see problems, open a new issue please.

**Comment by xxlabaza** [comment]
Hi, problem is still topical

**Comment by dsyer** [comment]
Did you read Spencer's last comment?

**Comment by xxlabaza** [comment]
Which one? About closing this issue or **DefaultListableBeanFactory** in https://github.com/spring-cloud/spring-cloud-netflix/issues/226

**Comment by dsyer** [comment]
This one "open a new issue please."

**Comment by xxlabaza** [comment]
Yep, I've already opened https://github.com/spring-cloud/spring-cloud-netflix/issues/326

**Comment by dududuck** [comment]
how to solve?

**Comment by spencergibb** [comment]
Please open a new issue in the spring cloud openfeign project with a sample that recreates the problem
