### ISSUE TITLE
Netflix dependencies causing Spring Cloud Dalston to use old okhttp (3.6.0)

### ISSUE THREAD

**Issue by nealeu** [spring-cloud/spring-cloud-netflix#2125]
Hi,

I've just added some spring-cloud functionality (not related to Netflix), and had to do some major sleuth-work to find out where the dependency is being dropped back from 3.7.0.

The answer is that spring-cloud-dependencies is pulling in spring-cloud-netflix-dependencies:1.3.1 which via #1752 sets OkHttp to 3.6.0.

This was a real gotcha, not discoverable via mvn dependency:tree.

Could something be done about making this play more nicely, and if not, perhaps update to 3.7.0 to avoid breaking other libraries which rely on that.

**Comment by ryanjbaxter** [comment]
I dont see why we couldnt update to 3.7.0, @spencergibb any objections?

**Comment by spencergibb** [comment]
3.7.0 is a few months old and 3.8.1 is the latest.

**Comment by repos-jmp** [comment]
Working on this, upgrading okhttp to 3.8.1 causes `testProcessAnnotations_ListParamsWithoutName` to fail, with 2 error messages -

`java.lang.IllegalStateException: RequestParam.value() was empty on parameter 0

	at feign.Util.checkState(Util.java:128)
	at org.springframework.cloud.netflix.feign.annotation.RequestParamParameterProcessor.processArgument(RequestParamParameterProcessor.java:63)
	at org.springframework.cloud.netflix.feign.support.SpringMvcContract.processAnnotationsOnParameter(SpringMvcContract.java:238)
	at feign.Contract$BaseContract.parseAndValidateMetadata(Contract.java:107)
	at org.springframework.cloud.netflix.feign.support.SpringMvcContract.parseAndValidateMetadata(SpringMvcContract.java:133)
	at org.springframework.cloud.netflix.feign.support.SpringMvcContractTests.testProcessAnnotations_ListParamsWithoutName(SpringMvcContractTests.java:305)` 

A fix for the missing name issue with a simple property fallback was submitted, but [some](https://github.com/spring-cloud/spring-cloud-netflix/pull/1102/commits/3617991e57637c4a535a0cfc1aef3956356c556e) of that code is not present in master.
REF: https://github.com/spring-cloud/spring-cloud-netflix/pull/1102#issuecomment-240625520

AND

`org.junit.AssumptionViolatedException: does not have java 8 parameter names


	at org.junit.Assume.assumeTrue(Assume.java:59)
	at org.springframework.cloud.netflix.feign.support.SpringMvcContractTests.testProcessAnnotations_Fallback(SpringMvcContractTests.java:343)`
REF: https://github.com/spring-cloud/spring-cloud-netflix/issues/1482#issuecomment-262425945

I double checked, the compiler byte code is set to 1.7 and the maven -parameters plugin is present in the POM file for netflix-core. 

I am new to this and am not able to figure these out, could you please provide some guidance ?

**Comment by ryanjbaxter** [comment]
@repos-jmp did you resolve the above problem?

**Comment by repos-jmp** [comment]
Yes, it is fixed.

**Comment by repos-jmp** [comment]
Committed another fix to PR branch accidentally. Resubmitted
