### ISSUE TITLE
Update to 1.0.0.RC3 causes logback dependency failure

### ISSUE THREAD

**Issue by kurron** [spring-cloud/spring-cloud-netflix#220]
I've upgraded from RC2 to RC3 and now my application won't start. I'm using Gradle 2.2.1 and it appears to me that logging dependencies have changed. In RC2 I see spring-boot-starter-log4j-1.2.1.RELEASE.jar but not in RC3. I think this prevents libraries such as jcl-over-slf4j-1.7.8.jar and jul-to-slf4j-1.7.8.jar from getting pulled in. In our case, this prevents start up of the application. Are we expected to load those jars by hand or is this a defect in the dependencies?

```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
java.lang.reflect.InvocationTargetException
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:483)
at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:53)
at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: org/apache/commons/logging/LogFactory
at org.springframework.boot.SpringApplication.(SpringApplication.java:160)
at org.springframework.boot.builder.SpringApplicationBuilder.createSpringApplication(SpringApplicationBuilder.java:96)
at org.springframework.boot.builder.SpringApplicationBuilder.(SpringApplicationBuilder.java:84)
at com.transparent.asgard.zisa.Application.main(Application.groovy:26)
... 6 more
Caused by: java.lang.ClassNotFoundException: org.apache.commons.logging.LogFactory
at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
at java.security.AccessController.doPrivileged(Native Method)
at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
at org.springframework.boot.loader.LaunchedURLClassLoader.doLoadClass(LaunchedURLClassLoader.java:170)
at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:136)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
... 10 more
```

**Comment by dsyer** [comment]
Well, jcl-over-slf4j is included transitively from spring-boot-starter (and spring-cloud-starter), and one or both of those would be included in almost all Spring Cloud apps. I'd have to see your dependency declarations in full to guess what the problem might be. Check out the samples as well of course.
