### ISSUE TITLE
Dynamically loading/initializing of Zuul filters

### ISSUE THREAD

**Issue by abaculus** [spring-cloud/spring-cloud-netflix#223]
Hi

Is it possible to dynamically initialize Zuul filters as Netflix shows at https://github.com/Netflix/zuul/wiki/zuul-simple-webapp ?

>We then initialize the FilterFileManager to look for Groovy files on the filesystem in the specified pre, routing, and post directories every 5 seconds.

```java
final String scriptRoot = System.getProperty("zuul.filter.root");
try {
    FilterFileManager.setFilenameFilter(new GroovyFileFilter());
    FilterFileManager.init(5,
            scriptRoot + "/pre",
            scriptRoot + "/route",
            scriptRoot + "/post");
} catch (Exception e) {
    throw new RuntimeException(e);
}
```

**Comment by dsyer** [comment]
You can probably do it with reloadable `<lang:groovy>` scripts (standard Spring feature) of type `ZuulFilter`. A `@Bean` of type `ZuulFilter` that was in `@RefreshScope` would work too. But there's nothing so far in Spring Cloud Netflix to directly support dynamic script reloading.

**Comment by spencergibb** [comment]
related to #206

**Comment by aivans** [comment]
Hi guys,

I just watched this presentation: https://www.youtube.com/watch?v=ZfYJHtVL1_w
At 20:48, the presenter is creating a custom routing rule from the UI.

Do you know whether that UI is public?
What does actually happen behind the scenes? A new filter is created and deployed using their Cassandra FilterPoller?

**Comment by abaculus** [comment]
I think it's a "must have" feature, the dynamic loading of new filters, since it (to me) feels like one of the major benefits of using Zuul (except routing to services using service registry).

I'm thinking of load shedding and routing to debug etc in production without having to restart the application.

**Comment by dsyer** [comment]
I'm not so sure I'd want arbitrary scripts to be run completely untested in a production system. And for people that want to try it, there are the two options I mentioned above anyway. Did anyone try that?

We can do more (contributions always welcome) after 1.0 though for sure.

**Comment by aivans** [comment]
@dsyer I hope to try the options in the coming days.

Netflix make a big case about Zuul, but without other tools on top of it I cannot see that many advantages., at least this is my current impression. The big idea I get right now is the routing to origins (services or other apps) and integration with Eureka, but needs tools on top for other features.

**Comment by abaculus** [comment]
@dsyer IMHO, tested or untested scripts should be controlled by the process of the production environment and not the framework. Anyone with access to a production enviroment could be of danger ;-)

I haven't tested your suggested solutions but I will. Though, the polling of configured directories for pre, routing and post- scripts sounds very appealing to me.

Or, if one would like to add a route to another origin without having to re-start the Zuul application or foresee the need for it - how could I accomplish this?

**Comment by dsyer** [comment]
> polling of configured directories for pre, routing and post- scripts

That's exactly what a `<lang:groovy/>` script does (or any other `<lang:*/>`) so you should be perfectly happy with that. Am I missing something?

> add a route to another origin without having to re-start the Zuul application

Do you mean in a `@EnableZuulProxy`? I'm a bit confused because that's what it already does if the routes change (e.g. a new eureka registration). Maybe you mean something else (can you be more specific about the use case, please)?

**Comment by abaculus** [comment]
@dsyer  To my understanding with `<lang:groovy />` you must define a `script-source` (a file) which, from my understanding, forces you to put all your filters in the same script (ok, which might be fair enough)?

Consider a cluster of Zuul applications and I'd like to add in runtime a re-route from "origin-service" to a "debug-service" for certain requests in a smooth transition without the need of restarting the Zuul applications.

One possible solution if I get this with `<lang:groovy/>` correct - one could alter the groovy script the `script-source` points to with a "routing"-filter?

**Comment by aivans** [comment]
@abaculus Netflix seem to use the FilterPoller with a Cassandra storage. 
They say multiple teams send their scripts this way and the scripts get picked up by all their Zuul instances. They have a Filter verifier which checks if the filter is well formatted, compiles, etc, but I don't understand how they have so much trust that filters will not conflict at runtime. I am curios how it works in reality.

**Comment by dsyer** [comment]
@abaculus thanks for the detail, it's useful to frame the discussion this way (concrete use cases). I don't think you are restricted to one `<lang:groovy/>` script per application, so you can put as much as you like in as many files as you like.

However I think `@RefreshScope` and/or a restart might be a better approach anyway. What's wrong with restarting the application?

With your example, you have a proxy routing requests to a backend, so lets assume that you are using `@EnableZuulProxy`. If you want to change a route you just change the `zuul.routes.*` configuration and send a /refresh. Pretty simple and no need for changing the code in the `ZuulFilter` at all. In this example *all* requests are re-routed, and you said you only want "certain requests" to be re-routed. To come up with an alternative implementation you would have to be more precise about the requirement (what does "certain" mean?), but I suspect a similar approach, where the `ZuulFilter` anticipated the change and only needed to be re-configured, not re-compiled, would be quite possible, and arguably preferable.

**Comment by abaculus** [comment]
@dsyer You're right, I could have been much more clear about the use case from the beginning.

To summarize your suggestions:

- `lang:groovy` requires me to come upp with the name of script(s) up-front, correct? 

- Changing a `zuul.routes.*` and call /refresh requires me to use external file as configuration, i.e. not bundled with the JAR, correct?

By "certain request" I mean it could be a client we identify by a header value which we'd like to route to a debug service.

Nothing wrong with restarting applications but the subject application have very high SLA and we try not to restart them more than necessary since it requires us to pull it out from the load-balancing cluster etc.

**Comment by shanman190** [comment]
Netflix's largest use case for dynamic script loading is for actively debugging issues within their internal services. Since they have the ability to increase (lower) the log level on particular service instances, they combine that with Zuul's routing and dynamic loading of filters to gain the ability to route a single user, out of the thousands, whom is experiencing issues with Netflix's services to those internal services with a higher level of logging, thus giving them insight into production issues as they occur, rather than scrapping through billions of log messages in their Hadoop cluster.

**Comment by damnhandy** [comment]
Yeah, I'm not super excited about allowing arbitrary code to run in the system that acts as the front door to your services. My last experience with something like that involved a junior dev calling `System.exit()` in his dynamic plug in code and took out an entire cluster. Thankfully, it was left over test code an ran in the test environment, but it highlighted the then Architects decision to run and trust arbitrary Java code in a cluster. 

I have no idea how Netflix manages this in production. If Zuul used a Java security policy for the dynamic code bits, I might be more inclined to push for this feature. But even then, there's a slight performance hit and the maintenance of the policies. 

Another option would be to have the variable bits of your filter externalized, and be read from a dynamic properties file or data store of some sort. This way, different aspects of the filter can be variable at runtime as opposed running arbitrary code at runtime. If you look at the Netflix [SurgicalDebugFilter](https://github.com/Netflix/zuul/blob/1.x/zuul-core/src/main/groovy/com/netflix/zuul/filters/SurgicalDebugFilter.groovy) that @shanman190 is referring to, it's not inconceivable to refactor that to use dynamic variables instead of using the full power of Groovy or Java.  

You still have to have some means of validating the variables, but it's a lot less overhead than validating code for proper execution.

**Comment by aivans** [comment]
Hi all,

I tested the the setup where routes are stored in Spring Cloud Config and it works nicely.
It is possible to dynamically change routes by updating them in GIT and sending /refresh call to the Spring Cloud Zuul instance.
The routes are pointing to url-s (not to service VIPs)

Question: Since routing to url-s is performed by SimpleHostRoutingFilter (Apache DefaultHttpClient), is it possible to configure setup per downstream route dynamically?
From what I can see there there are some defaults there in terms of default max connections, max connections per route etc. I wonder whether these could be changed dynamically.

**Comment by aivans** [comment]
I cannot remove a route dynamically. The same issue is described here:
https://github.com/spring-cloud/spring-cloud-config/issues/290
Once a route is there, you cannot remove it.

Maybe related, a route configured with <code>url</code> cannot be changed to <code>serviceId</code>. This is the main reason I tried to remove first, than add

**Comment by aivans** [comment]
I created https://github.com/spring-cloud/spring-cloud-netflix/issues/705

**Comment by aivans** [comment]
Also create https://github.com/spring-cloud/spring-cloud-netflix/issues/706

**Comment by szantopeter** [comment]
Hi @dsyer 

I have partial success with filters written in groovy scipts

## Approach 1 

This approach does not work, when, every request ends with a 404

### groovy-filters.xml
```xml
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:lang="http://www.springframework.org/schema/lang"
       xsi:schemaLocation="
        http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans.xsd
        http://www.springframework.org/schema/lang http://www.springframework.org/schema/lang/spring-lang.xsd">

    <lang:groovy id="exampleSurgicalDebugFilter" refresh-check-delay="3000" script-source="classpath:groovy/ExampleSurgicalDebugFilter.groovy">
    </lang:groovy>

</beans>
```
### ExampleSurgicalDebugFilter.groovy
```groovy
import com.netflix.zuul.filters.SurgicalDebugFilter

public class ExampleSurgicalDebugFilter extends SurgicalDebugFilter {

    @Override
    boolean patternMatches() {
        return false
    }

}
```
### SpringCloudZuulExampleApplication.java
```java
@EnableZuulProxy
@SpringBootApplication
@ImportResource(value = "classpath:spring/groovy-filters.xml")
public class SpringCloudZuulExampleApplication {

```

### Result
Every request ends with a 404. The log file contains nothing relevant, but this during startup
```
Returning cached instance of singleton bean 'scriptFactory.exampleSurgicalDebugFilter'
```



## Approach 2

This approach works, I can load filters from groovy, the only limitation that I found no way to reload groovy scripts

### ExampleSurgicalDebugFilterBean.groovy
```groovy
import com.netflix.zuul.context.RequestContext
import com.netflix.zuul.filters.SurgicalDebugFilter

public class ExampleSurgicalDebugFilterBean extends SurgicalDebugFilter {

    @Override
    boolean patternMatches() {
        RequestContext.currentContext.getRequest().getRequestURI().matches("/test[*.]")
    }

}

beans {
    exampleSurgicalDebugFilterBean(ExampleSurgicalDebugFilterBean) {
        new ExampleSurgicalDebugFilterBean();
    }
}
```

### SpringCloudZuulExampleApplication.java
```java
@EnableZuulProxy
@SpringBootApplication
public class SpringCloudZuulExampleApplication {
    public static void main(String[] args) {

        Object[] sources = {SpringCloudZuulExampleApplication.class, new ClassPathResource("groovy/ExampleSurgicalDebugFilterBean.groovy")};
        SpringApplication.run(sources, args);

    }
}
```

> The question is why approach 1 does not work?

**Comment by dsyer** [comment]
@szantopeter you probably need `proxy-target-class="true"` in your groovy bean definition.

**Comment by dsyer** [comment]
No that's not what I meant. Doesn't the `<lang:groovy>` thing have a `proxy-target-class` attribute?

**Comment by szantopeter** [comment]
@dsyer,

According to the xsd that tag is not allowed, but I tried and to my biggest surprise it worked! I did a last test, I modified the groovy while zuul was runing to see if the changes take effect, but sadly that did not happen, instead I got this :

```
java.lang.ClassCastException: ExampleSurgicalDebugFilter cannot be cast to ExampleSurgicalDebugFilter 
	at DinamyicRouting$$FastClassBySpringCGLIB$$76e8ce08.invoke(<generated>) ~[na:na]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.2.6.RELEASE.jar:4.2.6.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:720) ~[spring-aop-4.2.6.RELEASE.jar:4.2.6.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) ~[spring-aop-4.2.6.RELEASE.jar:4.2.6.RELEASE]
	at org.springframework.aop.support.DelegatingIntroductionInterceptor.doProceed(DelegatingIntroductionInterceptor.java:133) ~[spring-aop-4.2.6.RELEASE.jar:4.2.6.RELEASE]
	at org.springframework.aop.support.DelegatingIntroductionInterceptor.invoke(DelegatingIntroductionInterceptor.java:121) ~[spring-aop-4.2.6.RELEASE.jar:4.2.6.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.2.6.RELEASE.jar:4.2.6.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:655) ~[spring-aop-4.2.6.RELEASE.jar:4.2.6.RELEASE]
	at DinamyicRouting$$EnhancerBySpringCGLIB$$338b47c.filterType(<generated>) ~[na:na]
	at com.netflix.zuul.FilterLoader.getFiltersByType(FilterLoader.java:186) ~[zuul-core-1.1.0.jar:1.1.0]
	at com.netflix.zuul.FilterProcessor.runFilters(FilterProcessor.java:157) ~[zuul-core-1.1.0.jar:1.1.0]

```

I added a serialVersionUID like this : 

`	
private long serialVersionUID = 42;
`
but did not help either

**Comment by szantopeter** [comment]
Hi @dsyer have you had a chance to look into the above exception?

**Comment by dsyer** [comment]
No, sorry.

**Comment by freedombird9** [comment]
Why don't just write a customized routing filter that just reads the routing information from file or remote git repo every time it does routing?  So you only need to change the file/git if you want to change the routing on the fly.

**Comment by szantopeter** [comment]
@freedombird9 I was hoping that externalized, reloadable routing logic is built into spring cloud - zuul. Seems like externalized rules are supported, but application restart is needed. Yes a good workaround can be to write a filter that runs a drools or a javascript engine.

**Comment by dsyer** [comment]
I converted this sample to a `<lang:groovy/>` script and it worked fine: https://github.com/spring-cloud-samples/tests/tree/master/zuul. So I don't know what your problem is but maybe a sample project would be a good idea?

Also AFAIK the routing logic that we support in `@EnableZuulProxy` is mostly (if not completely) reloadable at runtime anyway (possibly apart from the issue identified above where deleting routes is problematic). Maybe you could describe your use case a bit more.

IMO dynamic scripts are a smell because there is insufficient control over the code that you put into production. Netflix don't use them much any more, or so I've heard, and certainly not for new features. Responding to config changes is another thing, and should be the way forward for everyone - it's just feature flags and metrics.

**Comment by dsyer** [comment]
@szantopeter your sample works for me as well as far as I can tell. I run the app and `curl localhost:8080/api/test/` and see content from example.com (provided by the Groovy script). Maybe you could help me understand in a bit more detail what the problem is?

**Comment by szantopeter** [comment]
@dsyer thanks for taking the time. Yes, in my sample localhost:8080/api/test/ is redirected to example.com but if I modify the groovy filter to redirect to somewhere else then I need to restart zuul. Of course in my example it is because the groovy file is included in the jar file. When I load it to an external location and modify it then I get the exception 

```
java.lang.ClassCastException: ExampleSurgicalDebugFilter cannot be cast to ExampleSurgicalDebugFilter 
	at DinamyicRouting$$FastClassBySpringCGLIB$$76e8ce08.invoke(<generated>) ~[na:na]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.2.6.RELEASE.jar:4.2.6.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:720) ~[spring-aop-4.2.6.RELEASE.jar:4.2.6.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) ~[spring-aop-4.2.6.RELEASE.jar:4.2.6.RELEASE]
	at org.springframework.aop.support.DelegatingIntroductionInterceptor.doProceed(DelegatingIntroductionInterceptor.java:133) ~[spring-aop-4.2.6.RELEASE.jar:4.2.6.RELEASE]
	at org.springframework.aop.support.DelegatingIntroductionInterceptor.invoke(DelegatingIntroductionInterceptor.java:121) ~[spring-aop-4.2.6.RELEASE.jar:4.2.6.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.2.6.RELEASE.jar:4.2.6.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:655) ~[spring-aop-4.2.6.RELEASE.jar:4.2.6.RELEASE]
	at DinamyicRouting$$EnhancerBySpringCGLIB$$338b47c.filterType(<generated>) ~[na:na]
	at com.netflix.zuul.FilterLoader.getFiltersByType(FilterLoader.java:186) ~[zuul-core-1.1.0.jar:1.1.0]
	at com.netflix.zuul.FilterProcessor.runFilters(FilterProcessor.java:157) ~[zuul-core-1.1.0.jar:1.1.0]

```

mentioned above

**Comment by dsyer** [comment]
OK, I can reproduce that. Seems like maybe a bug in Spring: https://jira.spring.io/browse/SPR-14719.

**Comment by szantopeter** [comment]
@dsyer thanks, for opening a bug, I guess it will take some time until it gets integrated into the latest spring and spring boot releases, but at least there is a hope.

**Comment by eacdy** [comment]
i raised a issue [https://github.com/spring-cloud/spring-cloud-netflix/issues/1502](https://github.com/spring-cloud/spring-cloud-netflix/issues/1502) today,and then @spencergibb said that Spring Cloud does not support  reloading groovy zuul filters dynamicly.

But I found this code:

[https://github.com/spencergibb/halfpipe/blob/master/halfpipe-router/src/main/java/halfpipe/router/FilterIntializer.java](https://github.com/spencergibb/halfpipe/blob/master/halfpipe-router/src/main/java/halfpipe/router/FilterIntializer.java)

And inspired by it, I've made a demo:

[https://github.com/eacdy/spring-cloud-test-for-issue/tree/master/microservice-gateway-zuul-filter-groovy](https://github.com/eacdy/spring-cloud-test-for-issue/tree/master/microservice-gateway-zuul-filter-groovy)

It works. It can reload groovy zuul filters.

So, my question is, Why @spencergibb said that Spring Cloud does not support reloading groovy zuul filters dynamicly?

**Comment by spencergibb** [comment]
You keep asking why, and the answer is still the same, it just hasn't been done yet.

**Comment by eacdy** [comment]
@spencergibb  So do you mean I shouldn't use the code?
What I really care is whether should I use this code rather than whether has it been done.
And I wonder What will supply When it has been done,

**Comment by ryanjbaxter** [comment]
@eacdy maybe you can propose a pull request?

**Comment by eacdy** [comment]
@ryanjbaxter I'd love to, but I don't know what the problem is. I think the zuul groovy filter works, but spencergibb says this feather hasn't been done yet.

**Comment by ryanjbaxter** [comment]
Sorry misunderstood what you were saying

**Comment by spencergibb** [comment]
Yup, `ZuulFilterInitializer` would need to be changed to support it.

**Comment by vtahlani** [comment]
Filters are being loaded dynamically with below code(method initGroovyFilterManager()) and if i change anything in filter that is also being reflected but filter is being used by Zuul even if i move/delete the filters.

@EnableZuulProxy
@SpringBootApplication
public class GatewayApplication {
	

 public static void main(String[] args) {
	  GatewayApplication app = new GatewayApplication();
	  app.initGroovyFilterManager();
    SpringApplication.run(GatewayApplication.class, args);
  }
 
  private void initGroovyFilterManager() {

      //TODO: pluggable filter initialzer
      FilterLoader.getInstance().setCompiler(new GroovyCompiler());

      final String scriptRoot = System.getProperty("zuul.filter.root");
      //LOGGER.info("Using file system script: " + scriptRoot);

      try {
          FilterFileManager.setFilenameFilter(new GroovyFileFilter());
          FilterFileManager.init(5,
                  scriptRoot + "/pre/"
                 // scriptRoot + "/route",
                 // scriptRoot + "/post"
          );
      }
      catch (Exception e) {
          throw new RuntimeException(e);
      }
  }

}

**Comment by vtahlani** [comment]
@eacdy Tried solution provided by you microservice-gateway-zuul-filter-groovy but same issues -

1. if change filterType() to return empty or "no-post" then also filter is in use.
2. if i delete filter file then also it is in use.

**Comment by szantopeter** [comment]
Hi All

As I stated [here](https://github.com/spring-cloud/spring-cloud-netflix/issues/223#issuecomment-245875065) there are two issues

1. Spring-boot refreshable beans as described [here](http://docs.spring.io/spring/docs/current/spring-framework-reference/html/dynamic-language.html#dynamic-language-refreshable-beans
) does not work with groovy filters.
2. loading groovy files with stanard spring boot features don't work either.
3. FilterLoader is never mentioned in [spring cloud documentation] (http://cloud.spring.io/spring-cloud-static/Camden.SR3/) and they don't work with my filters, but maybe it is me defining filters the wrong way. If FilterLoader is the preferred way then would it be possible to update the documentation?

**Comment by vtahlani** [comment]
filterOrder is within the filter category, in other word can i have same filterOrder 1,2,3,4 for pre, route and post?

Example -
filterType :pre , filter order 1, 2,3,and 4 basically 4 pre filter
filterType:route, filter order 1,2,3 and 4 again 4 route filter

Also, if i keep some filters with jar/code and load/create others at run time dynamically then only dynamic filters are being picked up, is it expected behavior?

**Comment by caicaicai** [comment]
I did it.
`filterRegistry.put(dynamicFilter.getId(), zuulFilter);
and clear FilterLoader.hashFiltersByType;
`
