### ISSUE TITLE
@EnableFeignClients - NullPointerException: logger

### ISSUE THREAD

**Issue by leon** [spring-cloud/spring-cloud-netflix#226]
I'm having a hard time getting @EnableFeignClients to work in my existing spring cloud app.

I've got a spring authentication server which is now going to integrate against another micro service.

the app looks like this

```java
@SpringBootApplication
@EnableAuthorizationServer
@EnableDiscoveryClient
@EnableFeignClients
public class AccountsApplication {
    public static void main(String[] args) {
        SpringApplication.run(AccountsApplication.class, args);
    }
}
```

and my build.gradle is a bit more complex

```groovy
buildscript {
    ext {
        springBootVersion = '1.2.1.RELEASE'
    }
    repositories {
        mavenCentral()
        maven { url 'https://repos.zeroturnaround.com/nexus/content/groups/zt-public/' }
    }
    dependencies {
        classpath("org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}")
        classpath('org.zeroturnaround:gradle-jrebel-plugin:1.1.2')
    }
}

apply plugin: 'java'
apply plugin: 'idea'
apply plugin: 'spring-boot'
apply plugin: 'rebel'

jar {
    baseName = 'accounts'
    version = '1.0.0'
}

jar.dependsOn(generateRebel)

sourceCompatibility = 1.8
targetCompatibility = 1.8

idea {
    project {
        jdkName = '1.8'
        languageLevel = '1.8'
        vcs = 'Git'
    }
}

repositories {
    mavenCentral()
    maven { url 'http://repo.spring.io/snapshot' }
    maven { url 'http://repo.spring.io/milestone' }
    maven { url 'http://repo.spring.io/release' }
}

dependencies {
    // Connect to config server
    compile('org.springframework.cloud:spring-cloud-starter:1.0.0.RC3')

    // Rest
    compile('org.springframework.cloud:spring-cloud-starter-feign:1.0.0.RC3')

    // Authorization Server
    compile('org.springframework.boot:spring-boot-starter-security')
    compile('org.springframework.security.oauth:spring-security-oauth2:2.0.6.RELEASE')
    compile('org.springframework.security:spring-security-jwt')

    // Social Security
    compile('org.springframework.social:spring-social-security')
    compile('org.springframework.boot:spring-boot-starter-social-linkedin')
    //compile('org.springframework.boot:spring-boot-starter-social-facebook')
    // Google doesn't exist as a starter
    compile('org.springframework.social:spring-social-google:1.0.0.RELEASE')

    compile('org.springframework.boot:spring-boot-starter-actuator')
    compile('org.springframework.boot:spring-boot-starter-web')
    compile('org.springframework.boot:spring-boot-starter-mail')
    compile('org.springframework.boot:spring-boot-starter-integration')

    // Templating
    compile('org.springframework.boot:spring-boot-starter-thymeleaf')
    compile('org.thymeleaf.extras:thymeleaf-extras-springsecurity3:2.1.1.RELEASE')

    // Data
    compile('org.springframework.boot:spring-boot-starter-data-jpa')
    compile('org.springframework.boot:spring-boot-starter-data-rest')

    // Sql Server Drivers don't exist in maven
    compile files('./src/main/resources/lib/sqljdbc41.jar')

    // Testing
    testCompile('org.springframework.boot:spring-boot-starter-test')
    testCompile('org.apache.httpcomponents:httpclient')
}

task wrapper(type: Wrapper) {
    gradleVersion = '2.3'
}
```

And a dead simple controller to test it out

```java
@Controller
@RequestMapping("/integration/crm")
public class CRMImportController {

	@Autowired
	protected CrmClient crmClient;

	@RequestMapping("/")
	public List<Customer> customers() {
		return crmClient.getCustomers();
	}

}
```

This compiles, but when I start it up it complains that `logger` is null.

```
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'crmClient': FactoryBean threw exception on object creation; nested exception is java.lang.NullPointerException: logger
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:175)
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.getObjectFromFactoryBean(FactoryBeanRegistrySupport.java:103)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getObjectForBeanInstance(AbstractBeanFactory.java:1517)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGAbstractBeanFactory.java:251)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1127)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1051)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:949)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:533)
	... 18 more
Caused by: java.lang.NullPointerException: logger
	at feign.Util.checkNotNull(Util.java:93)
	at feign.SynchronousMethodHandler$Factory.<init>(SynchronousMethodHandler.java:50)
	at feign.SynchronousMethodHandler$Factory$$InjectAdapter.get(SynchronousMethodHandler$Factory$$InjectAdapter.java:64)
	at feign.SynchronousMethodHandler$Factory$$InjectAdapter.get(SynchronousMethodHandler$Factory$$InjectAdapter.java:19)
	at feign.ReflectiveFeign$ParseHandlersByName$$InjectAdapter.get(ReflectiveFeign$ParseHandlersByName$$InjectAdapter.java:67)
	at feign.ReflectiveFeign$ParseHandlersByName$$InjectAdapter.get(ReflectiveFeign$ParseHandlersByName$$InjectAdapter.java:19)
	at feign.ReflectiveFeign$$InjectAdapter.get(ReflectiveFeign$$InjectAdapter.java:62)
	at feign.ReflectiveFeign$$InjectAdapter.get(ReflectiveFeign$$InjectAdapter.java:23)
	at feign.ReflectiveFeign$Module$$ModuleAdapter$ProvideFeignProvidesAdapter.get(ReflectiveFeign$Module$$ModuleAdapter.java:114)
	at feign.ReflectiveFeign$Module$$ModuleAdapter$ProvideFeignProvidesAdapter.get(ReflectiveFeign$Module$$ModuleAdapter.java:78)
	at dagger.ObjectGraph$DaggerObjectGraph.get(ObjectGraph.java:272)
	at feign.Feign$Builder.target(Feign.java:265)
	at feign.Feign$Builder.target(Feign.java:261)
	at org.springframework.cloud.netflix.feign.FeignClientFactoryBean.getObject(FeignClientFean.java:141)
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:168)
	... 26 more

```

This is where it gets strange. If I now comment out the controller it all starts up great.

and If i check the activator /beans endpoint I can see all the right components

```json
{
"bean": "feignEncoder",
"scope": "singleton",
"type": "org.springframework.cloud.netflix.feign.support.SpringEncoder",
"resource": "class org.springframework.cloud.netflix.feign.FeignClientsConfiguration",
"dependencies": []
},
{
"bean": "feignLogger",
"scope": "singleton",
"type": "feign.slf4j.Slf4jLogger",
"resource": "class org.springframework.cloud.netflix.feign.FeignClientsConfiguration",
"dependencies": []
},
{
"bean": "feignContract",
"scope": "singleton",
"type": "org.springframework.cloud.netflix.feign.support.SpringMvcContract",
"resource": "class org.springframework.cloud.netflix.feign.FeignClientsConfiguration",
"dependencies": []
},
{
"bean": "feignDecoder",
"scope": "singleton",
"type": "org.springframework.cloud.netflix.feign.support.SpringDecoder",
"resource": "class org.springframework.cloud.netflix.feign.FeignClientsConfiguration",
"dependencies": []
},
{
"bean": "crmClient",
"scope": "singleton",
"type": "se.cadcraft.accounts.integration.crm.CrmClient",
"resource": "null",
"dependencies": []
},
```

What am I doing wrong?

**Comment by dsyer** [comment]
How do you define your `@FeignClient`? What's happening in `CrmClient` (I assume that's the thing that is precipitating the error)?

**Comment by spencergibb** [comment]
Do you have a bean of type `Slf4jLogger`?  is `com.netflix.feign:feign-slf4j` in your dependency tree?

**Comment by leon** [comment]
This is the client

```java
@FeignClient(url = "https://myservice.mydomain.com")
public interface CrmClient {

	@RequestMapping(method = RequestMethod.GET, value = "/customers")
	public List<Customer> getCustomers();

}
```

And yes feign-slf4j is included

**Comment by spencergibb** [comment]
and the `Slf4jLogger` bean?

**Comment by leon** [comment]
Hmm that's strange, that's not there.
But isn't that included with spring boot?

**Comment by spencergibb** [comment]
it's a feign class

**Comment by dsyer** [comment]
Is #212 related to this one?

**Comment by leon** [comment]
It's there, as I showed above

````json
{
"bean": "feignLogger",
"scope": "singleton",
"type": "feign.slf4j.Slf4jLogger",
"resource": "class org.springframework.cloud.netflix.feign.FeignClientsConfiguration",
"dependencies": []
},
```

It could be related to #212 since both are defined in FeignClientsConfiguration.

**Comment by spencergibb** [comment]
looks similar.  Dagger (used as DI in feign) can't find an instance.  Dagger will be removed in a future version of feign.

**Comment by spencergibb** [comment]
@leon sorry, I missed it when I glanced at it.

**Comment by spencergibb** [comment]
hah, the logger isn't added to the builder

**Comment by leon** [comment]
Does that mean that you found a fix? :)

**Comment by spencergibb** [comment]
no, I spoke too soon

**Comment by dsyer** [comment]
Looks like a race condition. What is triggering your feign client to be used?

**Comment by leon** [comment]
It's used by a `@Autowired` in a spring mvc `@Controller`

**Comment by dsyer** [comment]
So `CrmClient` is a `@FeignClient` interface?

**Comment by leon** [comment]
yes

**Comment by leon** [comment]
Which seems to be generated properly, but as soon as I try to inject it intro the controller it says it cannot find the logger.
But I'm guessing that the client isn't initialized until it is injected.

**Comment by dsyer** [comment]
It would be a bean definition, so it would be initialized at some point, whether you injected it or not. It seems something you did forced it to happen too early. Can you share a minimal project?

**Comment by leon** [comment]
I tried to reproduce the problem in a minimal project earlier today, but was unable to reproduce the error.

An interesting fact is that even though I don't add the `@EnableFeignClients` the beans defined in FeignClientsConfiguration are loaded.

It's far fetched but could a AutoConfiguration be interfering with `@EnableFeignClients`?
since there seems to be one defined that load's the same `@Configuration` if the Feign.class is available?

I Know this is standard spring boot stuff. but maybe together with dagger it's causing problems?

**Comment by leon** [comment]
I can have another go tomorrow creating a minimal app that has the error, if we cannot come up with something today.

Could it be something with duplicate configs.

I found this in the feign starter

https://github.com/spring-cloud/spring-cloud-starters/blob/master/spring-cloud-starter-feign/src/main/resources/META-INF/spring.provides

It refers to that it provides the eureka-client. is this correct?

**Comment by spencergibb** [comment]
`FeignAutoConfiguration` has `@EnableFeignClients`.  Maybe having it twice is a problem?

**Comment by dsyer** [comment]
Can't see how that would be a problem. Maybe it should be optional though (so users can add an explicit base package)?

**Comment by leon** [comment]
The strange this is that, since I'm including the feign starter and that includes the FeignAutoConfiguration, that in turn include the @EnableFeignClients, shouldn't that be enough?

If I remove the @EnableFeignClients everything compiles and runs but then it says that it cannot find CrmClient.

So it seems to be needed anyways!?

**Comment by dsyer** [comment]
> So it seems to be needed anyways!?

Yes, it needs to know a base package to scan (so I think the one in `FeignAutoConfiguration` is redundant).

**Comment by leon** [comment]
I can try to remove it and see if anything changes.
I'm at home at the moment (CET) so tomorrow morning I'll give it a go.

Or maybe if you have the possibility to release a snapshot that would be great :)

**Comment by dsyer** [comment]
I don't expect there is any change, but did the new snapshots help at all? If not can you try and boil it down to a simple project that reproduces the problem?

**Comment by leon** [comment]
If we add the starter which includes Feign the autoconfiguration kicks in.
https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/feign/FeignAutoConfiguration.java#L34

and then we add the @EnableFeignClients to know what package to go through.

Shouldn't we also remove the @Import of `FeignClientsConfiguration.class` since it will already be included by the AutoConfigure?

https://github.com/spring-cloud/spring-cloud-netflix/blob/6dc0bd5f5e121d89b4fa0926517ec42744e8388e/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/feign/EnableFeignClients.java#L40

**Comment by leon** [comment]
Forgot to say that the new snapshot did not work :(

**Comment by dsyer** [comment]
> Shouldn't we also remove the @Import 

I actually do that on purpose, so you can use autoconfig without @FeignClient and vice versa if you should need to (although I don't see any immediate need).

**Comment by leon** [comment]
Since we cannot use @FeignClient without knowing where to look for them, we might as well remove the import from the @EnableFeignClients

It might be that the autoconfig is first creating the loggers / converters and then when we @Import the same config once more, it overwrites the beans causing the old references to be dropped = null pointer.

But I don't know how springs DI / autoconfig works when it comes to importing the same config multiple times. do you?

**Comment by dsyer** [comment]
It's not a problem to import the same config twice. Spring only registers one instance. The problem is more likely to be something in your app, forcing factory beans to instantiate early. If you put a break point in the `FeignClientFactoryBean.getObject()` it would be interesting to see the stack, just before it crashes.

**Comment by leon** [comment]
The FeignClientFactoryBean looks like this when the getObject() is called

```java
FeignClientFactoryBean(
	type=interface se.cadcraft.accounts.integration.crm.CrmClient,
	name=,
	url=https://myservice.mydomain.com,
	decoder=null,
	encoder=null,
	logger=null,
	contract=null,
	logLevel=null,
	retryer=null,
	errorDecoder=null,
	options=null,
	ribbonClient=null,
	requestInterceptors=null
)
```

And I've placed brake points in the FeignClientsConfiguration, but they never get called, so either they don't get called at all, or the crash is happening before they have a chance to get instantiated.

**Comment by leon** [comment]
It could be that the FeignClientFactoryBean is involved in a circular dependency.
In the documentation for the FactoryBean interface it says:

> If this FactoryBean is not fully initialized yet at the time of the call (for example because it is involved in a circular reference), throw a corresponding {@link FactoryBeanNotInitializedException}

We could check in the getObject that the four properties

```java
@Autowired
private Decoder decoder;

@Autowired
private Encoder encoder;

@Autowired
private Logger logger;

@Autowired
private Contract contract;
```

are not null and if they are throw the `FactoryBeanNotInitializedException`

It seems more likely that this is the problem than the autoconfiguration stuff we have been looking at presently. what do you think @dsyer ?

**Comment by dsyer** [comment]
I think it's the stack we need to see, not the state of the factory (we knew those properties were null already).

**Comment by leon** [comment]
I don't know if this is what you mean by stack.
I did a get thread dump from within intellij.

Have you got a better suggestion on how to generate the data you need?

```
"main@1" prio=5 tid=0x1 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at org.springframework.cloud.netflix.feign.FeignClientFactoryBean.getObject(FeignClientFactoryBean.java:141)
	  at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:168)
	  at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.getObjectFromFactoryBean(FactoryBeanRegistrySupport.java:103)
	  - locked <0x20b0> (a java.util.concurrent.ConcurrentHashMap)
	  at org.springframework.beans.factory.support.AbstractBeanFactory.getObjectForBeanInstance(AbstractBeanFactory.java:1517)
	  at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:251)
	  at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
	  at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1127)
	  at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1051)
	  at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:949)
	  at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:533)
	  at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
	  at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:331)
	  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1202)
	  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:537)
	  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476)
	  at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:303)
	  at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	  at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299)
	  at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
	  at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:762)
	  at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:757)
	  at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:480)
	  - locked <0x20b1> (a java.lang.Object)
	  at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
	  at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:691)
	  at org.springframework.boot.SpringApplication.run(SpringApplication.java:321)
	  at org.springframework.boot.SpringApplication.run(SpringApplication.java:961)
	  at org.springframework.boot.SpringApplication.run(SpringApplication.java:950)
	  at se.cadcraft.accounts.AccountsApplication.main(AccountsApplication.java:27)
```

**Comment by leon** [comment]
@dsyer If you want we could do a teamviewer / skype / google hangout to debug the problem together? it might be easier since I've not been successful in isolating the problem into a minimal project.

**Comment by dsyer** [comment]
No need for skype (I have all the information you can give right now unless you have a project you can share). That thread dump looks utterly normal, which is disappointing. I'm going to have to get into the guts of Dagger.

**Comment by leon** [comment]
I'll see if I can try creating a project, but don't count on it.

Good luck! :)

**Comment by leon** [comment]
@dsyer I was finally able to find how to reproduce the problem and put together this project for you

https://github.com/leon/temp-spring-cloud-feign-problem

The problem is @EnableAuthorizationServer as soon as I uncomment it, the app boots as normal.

**Comment by spencergibb** [comment]
@leon thanks!  Really helps to have this.
@dsyer I was toying with a change to `FeignClientFactoryBean` to have its required fields autowired in the constructor.  When I do that it fails with the following:
```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'myClient': Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.cloud.netflix.feign.FeignClientFactoryBean]: No default constructor found; nested exception is java.lang.NoSuchMethodException: org.springframework.cloud.netflix.feign.FeignClientFactoryBean.<init>()
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1093)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1038)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.getSingletonFactoryBeanForTypeCheck(AbstractAutowireCapableBeanFactory.java:860)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.getTypeForFactoryBean(AbstractAutowireCapableBeanFactory.java:790)
	at org.springframework.beans.factory.support.AbstractBeanFactory.isTypeMatch(AbstractBeanFactory.java:542)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doGetBeanNamesForType(DefaultListableBeanFactory.java:436)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanNamesForType(DefaultListableBeanFactory.java:404)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanNamesForType(DefaultListableBeanFactory.java:398)
	at org.springframework.beans.factory.BeanFactoryUtils.beanNamesForTypeIncludingAncestors(BeanFactoryUtils.java:144)
	at org.springframework.security.oauth2.config.annotation.web.configuration.AuthorizationServerEndpointsConfiguration$TokenKeyEndpointRegistrar.postProcessBeanFactory(AuthorizationServerEndpointsConfiguration.java:200)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:265)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:126)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:606)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:462)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:691)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:321)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:961)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:950)
	at se.radley.feignproblem.FeignproblemApplication.main(FeignproblemApplication.java:19)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.cloud.netflix.feign.FeignClientFactoryBean]: No default constructor found; nested exception is java.lang.NoSuchMethodException: org.springframework.cloud.netflix.feign.FeignClientFactoryBean.<init>()
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:85)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1086)
	... 24 common frames omitted
Caused by: java.lang.NoSuchMethodException: org.springframework.cloud.netflix.feign.FeignClientFactoryBean.<init>()
	at java.lang.Class.getConstructor0(Class.java:2971)
	at java.lang.Class.getDeclaredConstructor(Class.java:2165)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:80)
	... 25 common frames omitted
```
Why is it trying to do that when (in my code) it clearly has an autowired constructor?

**Comment by spencergibb** [comment]
so far I've traced it to `AbstractBeanFactory.hasInstantiationAwareBeanPostProcessors` being false at the time the `myClient` bean is to be instantiated.  It's some kind of timing issue.

**Comment by spencergibb** [comment]
The other thing I found is the id of the `DefaultListableBeanFactory` is `bootstrap` when it fails, a guid when it succeeds.

**Comment by dsyer** [comment]
OK all that actually makes sense to me because there was a change in Spring Security OAuth2 that prevents eager instantiation of `FactoryBeans` in an auth server using JWT tokens (https://github.com/spring-projects/spring-security-oauth/issues/384). If you upgrade to a snapshot, or use a different `TokenStore`, your app works, so I think we can call it fixed (at least as far as this issue is concerned).

**Comment by leon** [comment]
Awesome guys!
Thanks!

**Comment by leon** [comment]
@dsyer There isn't a snapshot build available :(
http://repo.spring.io/snapshot/org/springframework/security/oauth/spring-security-oauth2/

**Comment by dsyer** [comment]
It's there now.

**Comment by leon** [comment]
Thanks! works like a charm now :)

**Comment by chetak-team** [comment]
Hi, I'm facing the similar issue. Below is the stack trace while deploying to Cloud Foundry. Locally i could able to start the app. Can some one please help me to understand the issue?

2018-01-28T23:02:40.228+05:30 [APP/PROC/WEB/0] [OUT] Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'DynamicsContactClient': FactoryBean threw exception on object creation; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'feignRetryer' defined in org.springframework.cloud.netflix.feign.FeignClientsConfiguration: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [feign.Retryer]: Factory method 'feignRetryer' threw exception; nested exception is java.lang.NoSuchFieldError: NEVER_RETRY

**Comment by ryanjbaxter** [comment]
@chetak-team please open a separate issue
