### ISSUE TITLE
Can't up my Eureka Spring REST service in a Docker container

### ISSUE THREAD

**Issue by ladyy27** [spring-cloud/spring-cloud-netflix#2264]
Hi, my project consists in a REST service, which is registered in Eureka also I use Zuul proxy to manage requests as the below image. It runs perfectly on my computer in local way but when I create a docker container to my service, it doesn't start and I get the follow error: 
* I created a Docker container for each service: Eureka server, Zuul API Gateway, the REST service and my Mysql database
* I get the data of my service from a stored procedure in the database, this conection was tested and it works.
* I start all instances with docker-compose, Eureka and database instances remains up but the REST service instance stops abruptly. Zuul not is implemented yet.

```
matriculas-ms_1  | org.springframework.context.ApplicationContextException: Failed to start bean 'org.springframework.cloud.netflix.eureka.EurekaDiscoveryClientConfiguration'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'scopedTarget.eurekaClient' defined in class path resource [org/springframework/cloud/netflix/eureka/EurekaClientAutoConfiguration$RefreshableEurekaClientConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.netflix.discovery.EurekaClient]: Factory method 'eurekaClient' threw exception; nested exception is java.lang.RuntimeException: Failed to initialize DiscoveryClient!
matriculas-ms_1  | 	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:178) ~[spring-context-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
matriculas-ms_1  | 	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:50) ~[spring-context-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
matriculas-ms_1  | 	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:348) ~[spring-context-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
matriculas-ms_1  | 	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:151) ~[spring-context-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
matriculas-ms_1  | 	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:114) ~[spring-context-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
matriculas-ms_1  | 	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:880) ~[spring-context-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
matriculas-ms_1  | 	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:144) ~[spring-boot-1.5.6.RELEASE.jar!/:1.5.6.RELEASE]
matriculas-ms_1  | 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546) ~[spring-context-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
matriculas-ms_1  | 	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) ~[spring-boot-1.5.6.RELEASE.jar!/:1.5.6.RELEASE]
matriculas-ms_1  | 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693) [spring-boot-1.5.6.RELEASE.jar!/:1.5.6.RELEASE]
matriculas-ms_1  | 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360) [spring-boot-1.5.6.RELEASE.jar!/:1.5.6.RELEASE]
matriculas-ms_1  | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303) [spring-boot-1.5.6.RELEASE.jar!/:1.5.6.RELEASE]
matriculas-ms_1  | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118) [spring-boot-1.5.6.RELEASE.jar!/:1.5.6.RELEASE]
matriculas-ms_1  | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107) [spring-boot-1.5.6.RELEASE.jar!/:1.5.6.RELEASE]
matriculas-ms_1  | 	at tesis.MatriculasMS.MatriculasMsApplication.main(MatriculasMsApplication.java:16) [classes!/:0.0.1-SNAPSHOT]
matriculas-ms_1  | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_111]
matriculas-ms_1  | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_111]
matriculas-ms_1  | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_111]
matriculas-ms_1  | 	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_111]
matriculas-ms_1  | 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [matriculas-service-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
matriculas-ms_1  | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [matriculas-service-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
matriculas-ms_1  | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [matriculas-service-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
matriculas-ms_1  | 	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) [matriculas-service-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
matriculas-ms_1  | Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'scopedTarget.eurekaClient' defined in class path resource [org/springframework/cloud/netflix/eureka/EurekaClientAutoConfiguration$RefreshableEurekaClientConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.netflix.discovery.EurekaClient]: Factory method 'eurekaClient' threw exception; nested exception is java.lang.RuntimeException: Failed to initialize DiscoveryClient!
matriculas-ms_1  | 	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:599) ~[spring-beans-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
matriculas-ms_1  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1173) ~[spring-beans-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
matriculas-ms_1  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1067) ~[spring-beans-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
matriculas-ms_1  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:513) ~[spring-beans-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
matriculas-ms_1  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483) ~[spring-beans-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
matriculas-ms_1  | 	at org.springframework.beans.factory.support.AbstractBeanFactory$2.getObject(AbstractBeanFactory.java:345) ~[spring-beans-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
matriculas-ms_1  | 	at org.springframework.cloud.context.scope.GenericScope$BeanLifecycleWrapper.getBean(GenericScope.java:359) ~[spring-cloud-context-1.1.7.RELEASE.jar!/:1.1.7.RELEASE]
matriculas-ms_1  | 	at org.springframework.cloud.context.scope.GenericScope.get(GenericScope.java:176) ~[spring-cloud-context-1.1.7.RELEASE.jar!/:1.1.7.RELEASE]
matriculas-ms_1  | 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:340) ~[spring-beans-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
matriculas-ms_1  | 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
matriculas-ms_1  | 	at org.springframework.aop.target.SimpleBeanTargetSource.getTarget(SimpleBeanTargetSource.java:35) ~[spring-aop-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
matriculas-ms_1  | 	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:192) ~[spring-aop-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
matriculas-ms_1  | 	at com.sun.proxy.$Proxy87.getApplications(Unknown Source) ~[na:na]
matriculas-ms_1  | 	at org.springframework.cloud.netflix.eureka.EurekaDiscoveryClientConfiguration.maybeInitializeClient(EurekaDiscoveryClientConfiguration.java:120) ~[spring-cloud-netflix-eureka-client-1.2.5.RELEASE.jar!/:1.2.5.RELEASE]
matriculas-ms_1  | 	at org.springframework.cloud.netflix.eureka.EurekaDiscoveryClientConfiguration.start(EurekaDiscoveryClientConfiguration.java:97) ~[spring-cloud-netflix-eureka-client-1.2.5.RELEASE.jar!/:1.2.5.RELEASE]
matriculas-ms_1  | 	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:175) ~[spring-context-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
matriculas-ms_1  | 	... 22 common frames omitted
matriculas-ms_1  | Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.netflix.discovery.EurekaClient]: Factory method 'eurekaClient' threw exception; nested exception is java.lang.RuntimeException: Failed to initialize DiscoveryClient!
matriculas-ms_1  | 	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189) ~[spring-beans-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
matriculas-ms_1  | 	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588) ~[spring-beans-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
matriculas-ms_1  | 	... 37 common frames omitted
matriculas-ms_1  | Caused by: java.lang.RuntimeException: Failed to initialize DiscoveryClient!
matriculas-ms_1  | 	at com.netflix.discovery.DiscoveryClient.<init>(DiscoveryClient.java:441) ~[eureka-client-1.4.12.jar!/:1.4.12]
matriculas-ms_1  | 	at com.netflix.discovery.DiscoveryClient.<init>(DiscoveryClient.java:304) ~[eureka-client-1.4.12.jar!/:1.4.12]
matriculas-ms_1  | 	at org.springframework.cloud.netflix.eureka.CloudEurekaClient.<init>(CloudEurekaClient.java:51) ~[spring-cloud-netflix-eureka-client-1.2.5.RELEASE.jar!/:1.2.5.RELEASE]
matriculas-ms_1  | 	at org.springframework.cloud.netflix.eureka.EurekaClientAutoConfiguration$RefreshableEurekaClientConfiguration.eurekaClient(EurekaClientAutoConfiguration.java:192) ~[spring-cloud-netflix-eureka-client-1.2.5.RELEASE.jar!/:1.2.5.RELEASE]
matriculas-ms_1  | 	at org.springframework.cloud.netflix.eureka.EurekaClientAutoConfiguration$RefreshableEurekaClientConfiguration$$EnhancerBySpringCGLIB$$634e4b12.CGLIB$eurekaClient$0(<generated>) ~[spring-cloud-netflix-eureka-client-1.2.5.RELEASE.jar!/:1.2.5.RELEASE]
matriculas-ms_1  | 	at org.springframework.cloud.netflix.eureka.EurekaClientAutoConfiguration$RefreshableEurekaClientConfiguration$$EnhancerBySpringCGLIB$$634e4b12$$FastClassBySpringCGLIB$$5c5efebf.invoke(<generated>) ~[spring-cloud-netflix-eureka-client-1.2.5.RELEASE.jar!/:1.2.5.RELEASE]
matriculas-ms_1  | 	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228) ~[spring-core-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
matriculas-ms_1  | 	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:358) ~[spring-context-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
matriculas-ms_1  | 	at org.springframework.cloud.netflix.eureka.EurekaClientAutoConfiguration$RefreshableEurekaClientConfiguration$$EnhancerBySpringCGLIB$$634e4b12.eurekaClient(<generated>) ~[spring-cloud-netflix-eureka-client-1.2.5.RELEASE.jar!/:1.2.5.RELEASE]
matriculas-ms_1  | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_111]
matriculas-ms_1  | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_111]
matriculas-ms_1  | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_111]
matriculas-ms_1  | 	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_111]
matriculas-ms_1  | 	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162) ~[spring-beans-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
matriculas-ms_1  | 	... 38 common frames omitted
matriculas-ms_1  | Caused by: java.lang.RuntimeException: Cannot create Jersey client 
matriculas-ms_1  | 	at com.netflix.discovery.shared.transport.jersey.EurekaJerseyClientImpl$EurekaJerseyClientBuilder.build(EurekaJerseyClientImpl.java:174) ~[eureka-client-1.4.12.jar!/:1.4.12]
matriculas-ms_1  | 	at com.netflix.discovery.shared.transport.jersey.JerseyEurekaHttpClientFactory$JerseyEurekaHttpClientFactoryBuilder.buildLegacy(JerseyEurekaHttpClientFactory.java:205) ~[eureka-client-1.4.12.jar!/:1.4.12]
matriculas-ms_1  | 	at com.netflix.discovery.shared.transport.jersey.JerseyEurekaHttpClientFactory$JerseyEurekaHttpClientFactoryBuilder.build(JerseyEurekaHttpClientFactory.java:186) ~[eureka-client-1.4.12.jar!/:1.4.12]
matriculas-ms_1  | 	at com.netflix.discovery.shared.transport.jersey.JerseyEurekaHttpClientFactory.create(JerseyEurekaHttpClientFactory.java:143) ~[eureka-client-1.4.12.jar!/:1.4.12]
matriculas-ms_1  | 	at com.netflix.discovery.shared.transport.jersey.TransportClientFactories.newTransportClientFactory(TransportClientFactories.java:49) ~[eureka-client-1.4.12.jar!/:1.4.12]
matriculas-ms_1  | 	at com.netflix.discovery.DiscoveryClient.scheduleServerEndpointTask(DiscoveryClient.java:477) ~[eureka-client-1.4.12.jar!/:1.4.12]
matriculas-ms_1  | 	at com.netflix.discovery.DiscoveryClient.<init>(DiscoveryClient.java:428) ~[eureka-client-1.4.12.jar!/:1.4.12]
matriculas-ms_1  | 	... 51 common frames omitted
matriculas-ms_1  | Caused by: java.lang.RuntimeException: Cannot create Jersey client
matriculas-ms_1  | 	at com.netflix.discovery.shared.transport.jersey.EurekaJerseyClientImpl.<init>(EurekaJerseyClientImpl.java:60) ~[eureka-client-1.4.12.jar!/:1.4.12]
matriculas-ms_1  | 	at com.netflix.discovery.shared.transport.jersey.EurekaJerseyClientImpl$EurekaJerseyClientBuilder.build(EurekaJerseyClientImpl.java:172) ~[eureka-client-1.4.12.jar!/:1.4.12]
matriculas-ms_1  | 	... 57 common frames omitted
matriculas-ms_1  | Caused by: java.lang.ClassFormatError: Absent Code attribute in method that is not native or abstract in class file javax/mail/MessagingException
matriculas-ms_1  | 	at java.lang.ClassLoader.defineClass1(Native Method) ~[na:1.8.0_111]
matriculas-ms_1  | 	at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[na:1.8.0_111]
matriculas-ms_1  | 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[na:1.8.0_111]
matriculas-ms_1  | 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467) ~[na:1.8.0_111]
matriculas-ms_1  | 	at java.net.URLClassLoader.access$100(URLClassLoader.java:73) ~[na:1.8.0_111]
matriculas-ms_1  | 	at java.net.URLClassLoader$1.run(URLClassLoader.java:368) ~[na:1.8.0_111]
matriculas-ms_1  | 	at java.net.URLClassLoader$1.run(URLClassLoader.java:362) ~[na:1.8.0_111]
matriculas-ms_1  | 	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_111]
matriculas-ms_1  | 	at java.net.URLClassLoader.findClass(URLClassLoader.java:361) ~[na:1.8.0_111]
matriculas-ms_1  | 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_111]
matriculas-ms_1  | 	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:94) ~[matriculas-service-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
matriculas-ms_1  | 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_111]
matriculas-ms_1  | 	at java.lang.Class.getDeclaredMethods0(Native Method) ~[na:1.8.0_111]
matriculas-ms_1  | 	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701) ~[na:1.8.0_111]
matriculas-ms_1  | 	at java.lang.Class.getDeclaredMethods(Class.java:1975) ~[na:1.8.0_111]
matriculas-ms_1  | 	at com.sun.jersey.core.reflection.MethodList.getAllDeclaredMethods(MethodList.java:70) ~[jersey-core-1.19.1.jar!/:1.19.1]
matriculas-ms_1  | 	at com.sun.jersey.core.reflection.MethodList.<init>(MethodList.java:64) ~[jersey-core-1.19.1.jar!/:1.19.1]
matriculas-ms_1  | 	at com.sun.jersey.core.spi.component.ComponentConstructor.getPostConstructMethods(ComponentConstructor.java:132) ~[jersey-core-1.19.1.jar!/:1.19.1]
matriculas-ms_1  | 	at com.sun.jersey.core.spi.component.ComponentConstructor.<init>(ComponentConstructor.java:124) ~[jersey-core-1.19.1.jar!/:1.19.1]
matriculas-ms_1  | 	at com.sun.jersey.core.spi.component.ProviderFactory.__getComponentProvider(ProviderFactory.java:165) ~[jersey-core-1.19.1.jar!/:1.19.1]
matriculas-ms_1  | 	at com.sun.jersey.core.spi.component.ProviderFactory.getComponentProvider(ProviderFactory.java:137) ~[jersey-core-1.19.1.jar!/:1.19.1]
matriculas-ms_1  | 	at com.sun.jersey.core.spi.component.ProviderServices.getComponent(ProviderServices.java:283) ~[jersey-core-1.19.1.jar!/:1.19.1]
matriculas-ms_1  | 	at com.sun.jersey.core.spi.component.ProviderServices.getServices(ProviderServices.java:163) ~[jersey-core-1.19.1.jar!/:1.19.1]
matriculas-ms_1  | 	at com.sun.jersey.core.spi.factory.MessageBodyFactory.initReaders(MessageBodyFactory.java:176) ~[jersey-core-1.19.1.jar!/:1.19.1]
matriculas-ms_1  | 	at com.sun.jersey.core.spi.factory.MessageBodyFactory.init(MessageBodyFactory.java:162) ~[jersey-core-1.19.1.jar!/:1.19.1]
matriculas-ms_1  | 	at com.sun.jersey.api.client.Client.init(Client.java:343) ~[jersey-client-1.19.1.jar!/:1.19.1]
matriculas-ms_1  | 	at com.sun.jersey.api.client.Client.access$000(Client.java:119) ~[jersey-client-1.19.1.jar!/:1.19.1]
matriculas-ms_1  | 	at com.sun.jersey.api.client.Client$1.f(Client.java:192) ~[jersey-client-1.19.1.jar!/:1.19.1]
matriculas-ms_1  | 	at com.sun.jersey.api.client.Client$1.f(Client.java:188) ~[jersey-client-1.19.1.jar!/:1.19.1]
matriculas-ms_1  | 	at com.sun.jersey.spi.inject.Errors.processWithErrors(Errors.java:193) ~[jersey-core-1.19.1.jar!/:1.19.1]
matriculas-ms_1  | 	at com.sun.jersey.api.client.Client.<init>(Client.java:188) ~[jersey-client-1.19.1.jar!/:1.19.1]
matriculas-ms_1  | 	at com.sun.jersey.client.apache4.ApacheHttpClient4.<init>(ApacheHttpClient4.java:151) ~[jersey-apache-client4-1.19.1.jar!/:1.19.1]
matriculas-ms_1  | 	at com.sun.jersey.client.apache4.ApacheHttpClient4.<init>(ApacheHttpClient4.java:137) ~[jersey-apache-client4-1.19.1.jar!/:1.19.1]
matriculas-ms_1  | 	at com.sun.jersey.client.apache4.ApacheHttpClient4.create(ApacheHttpClient4.java:181) ~[jersey-apache-client4-1.19.1.jar!/:1.19.1]
matriculas-ms_1  | 	at com.netflix.discovery.shared.transport.jersey.EurekaJerseyClientImpl.<init>(EurekaJerseyClientImpl.java:52) ~[eureka-client-1.4.12.jar!/:1.4.12]
matriculas-ms_1  | 	... 58 common frames omitted
matriculas-ms_1  | 
respaldos_matriculas-ms_1 exited with code 1
```

Here is the docker-compose.yml
```
version: '3.3'
 services:
  srclbd:
   build: ./srclbd
   ports:
    - "3307:3306"
   expose:
    - "3306"
   volumes:
    - ./srclbd/data:/var/lib/mysql
  eureka:
   build: ./Eureka
   ports:
    - "8761:8761"
   expose:
    - "8761"
  matriculas-ms:
   build: ./matriculas-ms
   ports:
    - "3333:3333"
   expose:
    - "3333"
   depends_on:
    - srclbd
    - eureka
   links:
    - srclbd
    - eureka
   environment:
    - DATABASE_HOST=srclbd
    - EUREKA_HOST=eureka
```

The Dockerfiles:
* Eureka:
`FROM java:8
ADD /target/eureka-0.0.1-SNAPSHOT.jar eureka-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","eureka-0.0.1-SNAPSHOT.jar"]`

* REST service:
`FROM java:8
ADD /target/matriculas-service-0.0.1-SNAPSHOT.jar matriculas-service-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","matriculas-service-0.0.1-SNAPSHOT.jar","-Xdebug -Xrunjdwp:server=y,transport=dt_socket,suspend=n"]`

Here is my project on github:[https://github.com/ladyy27/MS](url)

Which is my error? 
![lady](https://user-images.githubusercontent.com/13395596/30261150-d4493998-9690-11e7-9e4f-475fd909fa16.png)

**Comment by ryanjbaxter** [comment]
The GitHub project link is invalid, can you fix it?

**Comment by ladyy27** [comment]
Sorry, It's true, the link doesn't works but I tried to copy the same link in other window and then works. Thanks. 
[https://github.com/ladyy27/MS](url)

**Comment by ryanjbaxter** [comment]
Is `matriculas-ms` the app with the issue?  I noticed this
https://github.com/ladyy27/MS/blob/master/matriculas-ms/pom.xml#L29

Don't specify the version, let the BOM take care of that for you.  

Also you are using an older version of Spring Cloud.  Could you at least try `Camden.SR7` if not `Dalston.SR3`?

**Comment by ladyy27** [comment]
I changed the version to `spring-cloud-dependencies` already but I have a problem, if I don't specify a version to Eureka, it returns the follow error:
`'dependencies.dependency.version' for org.springframework.cloud:spring-cloud-starter-eureka:jar is missing.`

**Comment by ryanjbaxter** [comment]
When do you see that?  I just removed the `version` property from your POM and the project build fine.

**Comment by ladyy27** [comment]
Mmm I don't know if this is relevant but I run my project on Netbeans 8.2 in Ubuntu 16.04 and also I tried with Lubuntu 14.04. After to try "Clean and Build" and "Build with Dependencies" options, it gives me this output: 

![netbeans](https://user-images.githubusercontent.com/13395596/30291057-2e6c09ee-96f7-11e7-9b5b-0196de17bff5.png)

So, the docker-compose.yml works for you?

**Comment by spencergibb** [comment]
If the build works from the command line, we assume it's a problem with the ide.

**Comment by ladyy27** [comment]
I already tried and the build doesn't work form the command line :/

**Comment by spencergibb** [comment]
What command line did you use?

**Comment by ladyy27** [comment]
`mvn install` and then `mvn clean deploy`. It produced this output:
![error](https://user-images.githubusercontent.com/13395596/30300843-90d889ac-971c-11e7-81c9-73db990ec28a.png)

**Comment by spencergibb** [comment]
What version of maven? We require 3.5.0. using `mvnw` eliminates having the right version.

**Comment by ryanjbaxter** [comment]
To follow up to what @spencergibb said, try `./mvnw clean deploy` instead.

**Comment by ladyy27** [comment]
In fact, I use Maven 3.5.0 and I tried it in other computer (with Kubuntu 16.04) but I still getting the same error, also I tried deleting the `repository` folder in `.m2` to force to download the depedencies again. Could be a problem to access to maven repository? 'cause I connect to internet from the university network, could be a proxy problem?

`utpl@utpl-ThinkCentre-M92p:~/Documentos/tesis/ms_git/MS/mat-servicio$ ./mvnw clean deploy
/home/utpl/Documentos/tesis/ms_git/MS/mat-servicio
[INFO] Scanning for projects...
Downloading: https://repo.maven.apache.org/maven2/org/springframework/boot/spring-boot-starter-parent/1.5.6.RELEASE/spring-boot-starter-parent-1.5.6.RELEASE.pom
Downloaded: https://repo.maven.apache.org/maven2/org/springframework/boot/spring-boot-starter-parent/1.5.6.RELEASE/spring-boot-starter-parent-1.5.6.RELEASE.pom (7.5 kB at 7.1 kB/s)
Downloading: https://repo.maven.apache.org/maven2/org/springframework/boot/spring-boot-dependencies/1.5.6.RELEASE/spring-boot-dependencies-1.5.6.RELEASE.pom
Downloaded: https://repo.maven.apache.org/maven2/org/springframework/boot/spring-boot-dependencies/1.5.6.RELEASE/spring-boot-dependencies-1.5.6.RELEASE.pom (93 kB at 258 kB/s)
Downloading: https://repo.maven.apache.org/maven2/com/fasterxml/jackson/jackson-bom/2.8.9/jackson-bom-2.8.9.pom
Downloaded: https://repo.maven.apache.org/maven2/com/fasterxml/jackson/jackson-bom/2.8.9/jackson-bom-2.8.9.pom (10 kB at 62 kB/s)
Downloading: https://repo.maven.apache.org/maven2/com/fasterxml/jackson/jackson-parent/2.8/jackson-parent-2.8.pom
Downloaded: https://repo.maven.apache.org/maven2/com/fasterxml/jackson/jackson-parent/2.8/jackson-parent-2.8.pom (8.0 kB at 55 kB/s)
Downloading: https://repo.maven.apache.org/maven2/com/fasterxml/oss-parent/27/oss-parent-27.pom
Downloaded: https://repo.maven.apache.org/maven2/com/fasterxml/oss-parent/27/oss-parent-27.pom (20 kB at 125 kB/s)
Downloading: https://repo.maven.apache.org/maven2/org/apache/logging/log4j/log4j-bom/2.7/log4j-bom-2.7.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/logging/log4j/log4j-bom/2.7/log4j-bom-2.7.pom (5.4 kB at 32 kB/s)
Downloading: https://repo.maven.apache.org/maven2/org/apache/apache/9/apache-9.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/apache/9/apache-9.pom (15 kB at 91 kB/s)
Downloading: https://repo.maven.apache.org/maven2/org/springframework/spring-framework-bom/4.3.10.RELEASE/spring-framework-bom-4.3.10.RELEASE.pom
Downloaded: https://repo.maven.apache.org/maven2/org/springframework/spring-framework-bom/4.3.10.RELEASE/spring-framework-bom-4.3.10.RELEASE.pom (5.1 kB at 34 kB/s)
Downloading: https://repo.maven.apache.org/maven2/org/springframework/data/spring-data-releasetrain/Ingalls-SR6/spring-data-releasetrain-Ingalls-SR6.pom
Downloaded: https://repo.maven.apache.org/maven2/org/springframework/data/spring-data-releasetrain/Ingalls-SR6/spring-data-releasetrain-Ingalls-SR6.pom (4.6 kB at 32 kB/s)
Downloading: https://repo.maven.apache.org/maven2/org/springframework/data/build/spring-data-build/1.9.6.RELEASE/spring-data-build-1.9.6.RELEASE.pom
Downloaded: https://repo.maven.apache.org/maven2/org/springframework/data/build/spring-data-build/1.9.6.RELEASE/spring-data-build-1.9.6.RELEASE.pom (6.4 kB at 44 kB/s)
Downloading: https://repo.maven.apache.org/maven2/org/springframework/integration/spring-integration-bom/4.3.11.RELEASE/spring-integration-bom-4.3.11.RELEASE.pom
Downloaded: https://repo.maven.apache.org/maven2/org/springframework/integration/spring-integration-bom/4.3.11.RELEASE/spring-integration-bom-4.3.11.RELEASE.pom (8.5 kB at 57 kB/s)
Downloading: https://repo.maven.apache.org/maven2/org/springframework/security/spring-security-bom/4.2.3.RELEASE/spring-security-bom-4.2.3.RELEASE.pom
Downloaded: https://repo.maven.apache.org/maven2/org/springframework/security/spring-security-bom/4.2.3.RELEASE/spring-security-bom-4.2.3.RELEASE.pom (4.3 kB at 29 kB/s)
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] 'dependencies.dependency.version' for org.springframework.cloud:spring-cloud-starter-eureka:jar is missing. @ line 30, column 21
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project tesis:mat-servicio:0.0.1-SNAPSHOT (/home/utpl/Documentos/tesis/ms_git/MS/mat-servicio/pom.xml) has 1 error
[ERROR]     'dependencies.dependency.version' for org.springframework.cloud:spring-cloud-starter-eureka:jar is missing. @ line 30, column 21
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException`

**Comment by spencergibb** [comment]
Sorry, I'm not going to try and debug building a project in docker when you can build the project outside of docker just fine and copy the jar.

**Comment by ladyy27** [comment]
Finally I solved my error setting up a separated configuration profile to Docker container like this:

```
spring:
 profiles: container
 application:
  name: matriculas-ms
jpa:
 hibernate:
  ddl-auto: none
datasource:
 url: jdbc:mysql://srclbd:3306/srcl?useSSL=false&noAccessToProcedureBodies=true
 username: root
 password: root
 initialize: true
eureka:
 client:
  serviceUrl:
   defaultZone: http://eureka:8761/eureka/
server:
 port: 1111
```
Then, I established this profile in the Dockerfile created to my REST service. So, every time it executes the JAR file, it will with the created profile's configuration.

```
FROM java:8
ADD /target/svcMatriculas.jar svcMatriculas.jar
ENTRYPOINT ["java","-Dspring.profiles.active=container","-jar","svcMatriculas.jar"]
```

Thanks to all of you!
