### ISSUE TITLE
Issue with ResponseEntity during bulk testing using eureka server

### ISSUE THREAD

**Issue by reenolesigues** [spring-cloud/spring-cloud-netflix#2265]
Hi Guys,

Would like to report an intermittent issue I encountered while performing load testing on my eureka services. 
Seems like there are instances wherein the ResponseEntity object is being malformed causing the response status to be malformed. See below for the logs from my calling function:

Exception in thread "main" org.springframework.web.client.ResourceAccessException: I/O error on POST request for "http://phvx001.ph.dev/campaign": Premature EOF; nested exception is java.io.IOException: Premature EOF
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:607)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:557)
	at org.springframework.web.client.RestTemplate.postForEntity(RestTemplate.java:384)
	at homecredit.ph.JsonRequestApplication.main(JsonRequestApplication.java:102)
Caused by: java.io.IOException: Premature EOF
	at sun.net.www.http.ChunkedInputStream.readAheadBlocking(ChunkedInputStream.java:565)
	at sun.net.www.http.ChunkedInputStream.readAhead(ChunkedInputStream.java:609)
	at sun.net.www.http.ChunkedInputStream.read(ChunkedInputStream.java:696)
	at java.io.FilterInputStream.read(FilterInputStream.java:133)
	at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3052)
	at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3046)
	at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3034)
	at java.io.FilterInputStream.read(FilterInputStream.java:83)
	at java.io.PushbackInputStream.read(PushbackInputStream.java:139)
	at org.springframework.web.client.MessageBodyClientHttpResponseWrapper.hasEmptyMessageBody(MessageBodyClientHttpResponseWrapper.java:97)
	at org.springframework.web.client.HttpMessageConverterExtractor.extractData(HttpMessageConverterExtractor.java:82)
	at org.springframework.web.client.RestTemplate$ResponseEntityResponseExtractor.extractData(RestTemplate.java:835)
	at org.springframework.web.client.RestTemplate$ResponseEntityResponseExtractor.extractData(RestTemplate.java:819)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:599)
	... 3 more

This appeared frequently. Issue was resolved when I switched ResponseEntity with the object body instead. Just wondering if you detected this issue already.

Thanks!

**Comment by ryanjbaxter** [comment]
Please learn how to format code on GitHub
https://help.github.com/articles/creating-and-highlighting-code-blocks/

I dont see anything in your issue that indicates it is problem within Spring Cloud.

**Comment by reenolesigues** [comment]
Hi,
Thanks for the info.
Will close this issue for now till I replicate the issue and provide a more detailed explanation of the problem.
