### ISSUE TITLE
Filter exception on Dalston SR3

### ISSUE THREAD

**Issue by karinahaugen** [spring-cloud/spring-cloud-netflix#2268]
We just upgraded spring cloud to Dalston SR3 and Spring boot to 1.5.6.RELEASE. When trying to send a PUT request with form data we get an exception:
```
java.lang.IllegalStateException: Cannot convert form data
        at org.springframework.cloud.netflix.zuul.filters.pre.FormBodyWrapperFilter$FormBodyRequestWrapper.buildContentData(FormBodyWrapperFilter.java:199) ~[spring-cloud-netflix-core-1.3.4.RELEASE.jar!/:1.3.4.RELEASE]
        at org.springframework.cloud.netflix.zuul.filters.pre.FormBodyWrapperFilter$FormBodyRequestWrapper.getContentType(FormBodyWrapperFilter.java:157) ~[spring-cloud-netflix-core-1.3.4.RELEASE.jar!/:1.3.4.RELEASE]
        at javax.servlet.ServletRequestWrapper.getContentType(ServletRequestWrapper.java:135) ~[tomcat-embed-core-8.5.16.jar!/:8.5.16]
        at org.springframework.web.servlet.mvc.condition.ConsumesRequestCondition.getMatchingCondition(ConsumesRequestCondition.java:176) ~[spring-webmvc-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
        at org.springframework.web.servlet.mvc.method.RequestMappingInfo.getMatchingCondition(RequestMappingInfo.java:213) ~[spring-webmvc-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
        at org.springframework.web.servlet.mvc.method.RequestMappingInfoHandlerMapping.getMatchingMapping(RequestMappingInfoHandlerMapping.java:94) ~[spring-webmvc-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
        at org.springframework.web.servlet.mvc.method.RequestMappingInfoHandlerMapping.getMatchingMapping(RequestMappingInfoHandlerMapping.java:58) ~[spring-webmvc-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
        at org.springframework.web.servlet.handler.AbstractHandlerMethodMapping.addMatchingMappings(AbstractHandlerMethodMapping.java:380) ~[spring-webmvc-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
        at org.springframework.web.servlet.handler.AbstractHandlerMethodMapping.lookupHandlerMethod(AbstractHandlerMethodMapping.java:347) ~[spring-webmvc-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
        at org.springframework.web.servlet.handler.AbstractHandlerMethodMapping.getHandlerInternal(AbstractHandlerMethodMapping.java:314) ~[spring-webmvc-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
        at org.springframework.web.servlet.handler.AbstractHandlerMethodMapping.getHandlerInternal(AbstractHandlerMethodMapping.java:61) ~[spring-webmvc-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
        at org.springframework.web.servlet.handler.AbstractHandlerMapping.getHandler(AbstractHandlerMapping.java:352) ~[spring-webmvc-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.getHandler(DispatcherServlet.java:1160) ~[spring-webmvc-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:940) ~[spring-webmvc-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901) ~[spring-webmvc-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970) [spring-webmvc-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
        at org.springframework.web.servlet.FrameworkServlet.doPut(FrameworkServlet.java:883) [spring-webmvc-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:664) [tomcat-embed-core-8.5.16.jar!/:8.5.16]
.....

Caused by: java.lang.NullPointerException: null
        at org.springframework.cloud.netflix.zuul.util.RequestContentDataExtractor.extractFromRequest(RequestContentDataExtractor.java:35) ~[spring-cloud-netflix-core-1.3.4.RELEASE.jar!/:1.3.4.RELEASE]
        at org.springframework.cloud.netflix.zuul.util.RequestContentDataExtractor.extract(RequestContentDataExtractor.java:24) ~[spring-cloud-netflix-core-1.3.4.RELEASE.jar!/:1.3.4.RELEASE]
        at org.springframework.cloud.netflix.zuul.filters.pre.FormBodyWrapperFilter$FormBodyRequestWrapper.buildContentData(FormBodyWrapperFilter.java:187) ~[spring-cloud-netflix-core-1.3.4.RELEASE.jar!/:1.3.4.RELEASE]
```

Any ideas to what we can do to fix this issue?

**Comment by ryanjbaxter** [comment]
Can you provide a sample that reproduces the issue?

**Comment by karinahaugen** [comment]
Added a screenshot from chrome where the PUT request has been sent. As you can see the request has been changed to a POST request, and I guess that's because of zuul?

The request is a standard PUT request from a thymeleaf html file, where we have some form data.
Normal POST request still works, so we can create data. When looking in the POST request there's no "Form data" in the headers. So maybe that's the reason POST still works.

![printscreen](https://user-images.githubusercontent.com/3717709/30345977-80465470-9807-11e7-9e55-556241f3786a.png)

**Comment by spencergibb** [comment]
zuul doesn't change request methods.

**Comment by spencergibb** [comment]
Can you try snapshots, I tried a change here 78e4cb4410f28d0f1d01fdb7f929407ca516494b

**Comment by karinahaugen** [comment]
Sorry, my mistake! But the exception still exists unfortunately.

**Comment by karinahaugen** [comment]
Tried the snapshot and everything works perfect now! When do you expect this to be included in a release?

**Comment by ryanjbaxter** [comment]
We plan on doing a `Dalston.SR4` release soon.  Not sure when exactly that will be.
