### ISSUE TITLE
New token relay pattern: service secured with oauth to call another oauth secured service

### ISSUE THREAD

**Issue by pochadri** [spring-cloud/spring-cloud-netflix#230]
I am configuring on similar lines of the sample project at  https://github.com/dsyer/spring-security-angular/tree/master/oauth2-vanilla

but with another microservice(say resource2) and call it from resource service using RestTemplate(Ribbon is added to dependencies to kick in RibbonClientConfiguration so a loadbalanced client is created). This config does not work  and throws this exception

---
    Caused by: java.lang.IllegalStateException: Unable to locate ILoadBalancer for service: sample-bank
	at org.springframework.cloud.netflix.ribbon.RibbonLoadBalancerClient.getServer(RibbonLoadBalancerClient.java:96) ~[spring-cloud-netflix-core-1.0.0.RC3.jar:1.0.0.RC3]
	at org.springframework.cloud.netflix.ribbon.RibbonLoadBalancerClient.execute(RibbonLoadBalancerClient.java:63) ~[spring-cloud-netflix-core-1.0.0.RC3.jar:1.0.0.RC3]
	at org.springframework.cloud.netflix.ribbon.RibbonInterceptor.intercept(RibbonInterceptor.java:47) ~[spring-cloud-netflix-core-1.0.0.RC3.jar:1.0.0.RC3]
	at org.springframework.http.client.InterceptingClientHttpRequest$RequestExecution.execute(InterceptingClientHttpRequest.java:84) ~[spring-web-4.1.4.RELEASE.jar:4.1.4.RELEASE]
	at org.springframework.http.client.InterceptingClientHttpRequest.executeInternal(InterceptingClientHttpRequest.java:69) ~[spring-web-4.1.4.RELEASE.jar:4.1.4.RELEASE]
	at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:48) ~[spring-web-4.1.4.RELEASE.jar:4.1.4.RELEASE]
	at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:53) ~[spring-web-4.1.4.RELEASE.jar:4.1.4.RELEASE]
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:568) ~[spring-web-4.1.4.RELEASE.jar:4.1.4.RELEASE]
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:529) ~[spring-web-4.1.4.RELEASE.jar:4.1.4.RELEASE]
	at org.springframework.web.client.RestTemplate.postForObject(RestTemplate.java:329) ~[spring-web-4.1.4.RELEASE.jar:4.1.4.RELEASE]

--

do i need to use OAuthRestTemplate and is token passed on to the called service?
I also have the zuulproxy enabled but i do not want to use the proxy for reaching the internal service.

any ideas on how this can be achieved or is there any sample project i can check?

**Comment by dsyer** [comment]
You need an `OAuthRestTemplate` (or the equivalent) to send a token to the remote server. The one that is created for you by the `@RibbonClient` is not an `OAuthRestTemplate`, so we need to address that somehow (maybe in spring-cloud-security).

The stack trace looks irrelevant. It just means your load balancer doesn't have any servers. Are you connected to Eureka, or is the server list hard coded?

**Comment by dsyer** [comment]
See https://github.com/spring-cloud/spring-cloud-security/issues/45 (closing this one as duplicate).
