### ISSUE TITLE
do  I need add zipkin-server to host file

### ISSUE THREAD

**Issue by 13567436138** [spring-cloud/spring-cloud-netflix#2404]
Caused by: java.net.UnknownHostException: zipkin-server
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184) ~[na:1.8.0_31]
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172) ~[na:1.8.0_31]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_31]
	at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_31]
	at java.net.Socket.connect(Socket.java:538) ~[na:1.8.0_31]
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180) ~[na:1.8.0_31]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432) ~[na:1.8.0_31]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527) ~[na:1.8.0_31]
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:211) ~[na:1.8.0_31]
	at sun.net.www.http.HttpClient.New(HttpClient.java:308) ~[na:1.8.0_31]
	at sun.net.www.http.HttpClient.New(HttpClient.java:326) ~[na:1.8.0_31]
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1168) ~[na:1.8.0_31]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1104) ~[na:1.8.0_31]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:998) ~[na:1.8.0_31]
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:932) ~[na:1.8.0_31]
	at org.springframework.http.client.SimpleBufferingClientHttpRequest.executeInternal(SimpleBufferingClientHttpRequest.java:78) ~[spring-web-4.3.11.RELEASE.jar:4.3.11.RELEASE]
	at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:48) ~[spring-web-4.3.11.RELEASE.jar:4.3.11.RELEASE]
	at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:53) ~[spring-web-4.3.11.RELEASE.jar:4.3.11.RELEASE]
	at org.springframework.http.client.InterceptingClientHttpRequest$InterceptingRequestExecution.execute(InterceptingClientHttpRequest.java:99) ~[spring-web-4.3.11.RELEASE.jar:4.3.11.RELEASE]
	at org.springframework.cloud.netflix.metrics.MetricsClientHttpRequestInterceptor.intercept(MetricsClientHttpRequestInterceptor.java:64) ~[spring-cloud-netflix-core-1.3.5.RELEASE.jar:1.3.5.RELEASE]
	at org.springframework.http.client.InterceptingClientHttpRequest$InterceptingRequestExecution.execute(InterceptingClientHttpRequest.java:86) ~[spring-web-4.3.11.RELEASE.jar:4.3.11.RELEASE]
	at org.springframework.http.client.InterceptingClientHttpRequest.executeInternal(InterceptingClientHttpRequest.java:70) ~[spring-web-4.3.11.RELEASE.jar:4.3.11.RELEASE]
	at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:48) ~[spring-web-4.3.11.RELEASE.jar:4.3.11.RELEASE]
	at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:53) ~[spring-web-4.3.11.RELEASE.jar:4.3.11.RELEASE]
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:652) ~[spring-web-4.3.11.RELEASE.jar:4.3.11.RELEASE]
	... 16 common frames omitted

spring.zipkin.service.name=zipkin-server
spring.zipkin.compression.enabled=true
spring.zipkin.enabled=true
spring.zipkin.locator.discovery.enabled=true
spring.sleuth.sampler.percentage=1.0

**Comment by ryanjbaxter** [comment]
Please learn how to [format code on GitHub](https://help.github.com/articles/creating-and-highlighting-code-blocks/).

This question belongs in the Spring Cloud Sleuth project, https://github.com/spring-cloud/spring-cloud-sleuth.
