### ISSUE TITLE
Impossible to set datacenter = Amazon

### ISSUE THREAD

**Issue by radenui** [spring-cloud/spring-cloud-netflix#241]
Hello,

I try to setup eureka server/client on a docker container hosted on an AWS instance.
When I start a simple service with a eureka client using the properties:
```
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    useDnsForFetchingServiceUrls: true
    eurekaServerDNSName: example.int
    eurekaServerPort: 8761
    eurekaServerURLContext: eureka
    region: us-east-1
    preferSameZoneEureka: true
  instance:
    dataCenterInfo:
      name: Amazon
```

My app fails to lauch with this error:
```
2015-03-03 21:38:14.092  INFO 1 --- [           main] .p.EurekaConfigBasedInstanceInfoProvider : Setting initial instance status as: STARTING
2015-03-03 21:38:14.140  WARN 1 --- [           main] ationConfigEmbeddedWebApplicationContext : Exception encountered during context initialization - cancelling refresh attempt

org.springframework.context.ApplicationContextException: Failed to start bean 'org.springframework.cloud.netflix.eureka.EurekaDiscoveryClientConfiguration'; nested exception is java.lang.RuntimeException: Failed to initialize DiscoveryClient!
        at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:176)
        at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:51)
        at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:346)
        at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:149)
        at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:112)
        at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:770)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:140)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:483)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:691)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:321)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:961)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:950)
        at demo.MicroApplication.main(MicroApplication.java:29)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:53)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Failed to initialize DiscoveryClient!
        at com.netflix.discovery.DiscoveryClient.<init>(DiscoveryClient.java:318)
        at com.netflix.discovery.DiscoveryClient.<init>(DiscoveryClient.java:197)
        at com.netflix.discovery.DiscoveryClient.<init>(DiscoveryClient.java:193)
        at com.netflix.discovery.DiscoveryManager.initComponent(DiscoveryManager.java:84)
        at org.springframework.cloud.netflix.eureka.DiscoveryManagerInitializer.init(DiscoveryManagerInitializer.java:38)
        at org.springframework.cloud.netflix.eureka.EurekaDiscoveryClientConfiguration.start(EurekaDiscoveryClientConfiguration.java:122)
        at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:173)
        ... 19 common frames omitted
Caused by: java.lang.ClassCastException: org.springframework.cloud.netflix.eureka.EurekaInstanceConfigBean$IdentifyingDataCenterInfo cannot be cast to com.netflix.appinfo.AmazonInfo
        at com.netflix.discovery.DiscoveryClient.getZone(DiscoveryClient.java:1381)
        at com.netflix.discovery.DiscoveryClient.<init>(DiscoveryClient.java:242)
        ... 25 common frames omitted
```

Am I missing something?

Thanks a lot,

Arthur

**Comment by spencergibb** [comment]
@radenui right now you need to create your own instance of `EurekaInstanceConfigBean` and set `dataCenterInfo` to an `AmazonInfo` instance.

**Comment by radenui** [comment]
Ok, thanks!

**Comment by dsyer** [comment]
You can also use the native Netflix `EurekaClientConfigImpl` (create a `@Bean` of that type).

**Comment by humbargs** [comment]
For documentation purposes, here is what I did to solve the problem.  I tried to follow the instructions under the **Using Eureka on AWS** section [here](http://cloud.spring.io/spring-cloud-netflix/spring-cloud-netflix.html), but he constructor for `EurekaInstanceConfigBean` has been made private.  You have a intialize a few more objects but once you initialize them, it works just fine.

```
    @Bean
    @Profile("aws")
    public EurekaInstanceConfigBean eurekaInstanceConfig() {
        InetUtilsProperties properties = new InetUtilsProperties();
        
        // Just set these as zero length strings
        properties.setDefaultIpAddress("");
        properties.setDefaultHostname("");

        InetUtils inetUtils = new InetUtils(properties);
        EurekaInstanceConfigBean b = new EurekaInstanceConfigBean(inetUtils);
        AmazonInfo info = AmazonInfo.Builder.newBuilder().autoBuild("eureka");
        b.setDataCenterInfo(info);
        return b;
    }
```
