### ISSUE TITLE
NullPointerException in LoadBalancerFeignClient

### ISSUE THREAD

**Issue by akefirad** [spring-cloud/spring-cloud-netflix#2443]
The method `CachingSpringLoadBalancerFactory.create` has:
```java
public FeignLoadBalancer create(String clientName) {
  if (this.cache.containsKey(clientName)) {
    return this.cache.get(clientName);
  }

  // create a new client, cache it, and return it.
}

```
But having `cache` field of type `ConcurrentReferenceHashMap` means `this.cache.get(clientName)` regardless of `this.cache.containsKey(clientName)`. Why not:
```java
public FeignLoadBalancer create(String clientName) {
  FeignLoadBalancer cached = this.cache.get(clientName);
  if (cached != null) {
    return cached;
  }

  // create a new client, cache it, and return it.
}
```

**Comment by spencergibb** [comment]
Can you describe how to recreate the problem?

**Comment by akefirad** [comment]
The `create` method is being used in `LoadBalancerFeignClient`:
```java
@Override
public Response execute(Request request, Request.Options options) throws IOException {
  try {
    URI asUri = URI.create(request.url());
    String clientName = asUri.getHost();
    URI uriWithoutHost = cleanUrl(request.url(), clientName);
    FeignLoadBalancer.RibbonRequest ribbonRequest = new FeignLoadBalancer.RibbonRequest(
        this.delegate, request, uriWithoutHost);

    IClientConfig requestConfig = getClientConfig(options, clientName);
    return this.lbClientFactory.create(clientName).executeWithLoadBalancer(ribbonRequest,
        requestConfig).toResponse();
  }
  catch (ClientException e) {
    // Handle exception
  }
}
```
The `return` line might throw NPE (we're are experiencing it with v1.2.2. Nevertheless the code is the same). Did I answer your question?

**Comment by spencergibb** [comment]
No. I'd like to recreate the problem, so I can write a test and then fix it.

**Comment by akefirad** [comment]
I'm not sure how you want to right a test for this considering the fact that it involves race condition and GC activities. Anyway here's a dirty code we managed to reproduce the scenario once with `-Xmx50m` (please note that  it may or may not fail):
```java
        Map<String, Object> map = new ConcurrentReferenceHashMap<>();
        ExecutorService executor = Executors.newFixedThreadPool(2);

        Future<?> puts = executor.submit(() ->
                IntStream.range(1, Integer.MAX_VALUE)
                        .forEach(value -> map.put("key-" + value, new Object())));

        Future<?> gets = executor.submit(() -> {
            while (!puts.isDone()) {
                IntStream.range(1, Integer.MAX_VALUE)
                        .forEach(value -> {
                            System.out.println("Getting key-" + value);
                            if (map.containsKey("key-" + value)) {
                                Objects.requireNonNull(map.get("key-" + value));
                            }
                        });
            }
        });

        while (!puts.isDone() || !gets.isDone()) {
            if (gets.isDone()) {
                System.out.println("Getting is done!");
                try {
                    gets.get();
                } catch (ExecutionException e) {
                    if (e.getCause() instanceof NullPointerException) {
                        puts.cancel(true);
                        executor.shutdownNow();
                        executor.awaitTermination(1, TimeUnit.SECONDS);
                        throw (NullPointerException) e.getCause();
                    }
                }
            }
            System.out.println("Waiting for the result...");
            Thread.sleep(1000);
        }
    }
```

**Comment by jebeaudet** [comment]
We run into this issue from time to time, good catch with the `ConcurrentReferenceHashMap`. Here's the stacktrace : 
```
java.lang.NullPointerException: null
	at org.springframework.cloud.netflix.feign.ribbon.LoadBalancerFeignClient.execute(LoadBalancerFeignClient.java:63)
	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:97)
	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:76)
	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:103)
```

**Comment by ryanjbaxter** [comment]
Please reopen this issue in the new Spring Cloud OpenFeign project https://github.com/spring-cloud/spring-cloud-openfeign
