### ISSUE TITLE
Zuul: handling of non-standard HTTP statuses

### ISSUE THREAD

**Issue by Toparvion** [spring-cloud/spring-cloud-netflix#2450]
Hi,

We're trying to use Zuul (from `spring-cloud-starter-zuul:1.3.5.RELEASE`) as an edge service for a distributed application where some components (microservices) make use of non-standard HTTP response codes. 

Unfortunately it doesn't work for that case - the edge service fails with 500 error - because of the following code in `org.springframework.cloud.netflix.zuul.filters.route.RibbonRoutingFilter#forward` method:

```java
try {
	ClientHttpResponse response = command.execute();
	this.helper.appendDebug(info, response.getStatusCode().value(), /* <- here's the point*/
			response.getHeaders());
	return response;
}
```
which in case of non-standard HTTP code causes:

```
Caused by: java.lang.IllegalArgumentException: No matching constant for [530]
	at org.springframework.http.HttpStatus.valueOf(HttpStatus.java:497)
	at org.springframework.http.client.AbstractClientHttpResponse.getStatusCode(AbstractClientHttpResponse.java:33)
	at org.springframework.cloud.netflix.zuul.filters.route.RibbonRoutingFilter.forward(RibbonRoutingFilter.java:158)
	at org.springframework.cloud.netflix.zuul.filters.route.RibbonRoutingFilter.run(RibbonRoutingFilter.java:111)
	... 70 common frames omitted
```

In other words, the filter relies on predefined set of common HTTP statuses for debugging purposes (as I can judge by the code) but it breaks the main usage. 

Since the `ProxyRequestHelper#appendDebug` method accepts only `int` for `status` parameter, there is no need to use `ClientHttpResponse#getStatusCode` for retrieving status value. It is enough to use `ClientHttpResponse#getRawStatusCode` method:

```java
	/**
	 * Return the HTTP status code of the response as integer
	 * @return the HTTP status as an integer
	 * @throws IOException in case of I/O errors
	 */
	int getRawStatusCode() throws IOException;
``` 

Can you please suggest is there any other places or cases when using of non-standard HTTP codes may break Zuul behavior?
If there's no, I can offer a trivial Pull Request for fixing this particular issue.

**Comment by ryanjbaxter** [comment]
I can't tell you for sure if there are other places.  You can search through the code.  Obviously you can make the change and then add some tests as well.

**Comment by Toparvion** [comment]
Ok, thank you, I'll try it and then post the link to PR when ready.
