### ISSUE TITLE
Zuul with Java 1.7.0 Update 121 and greater causes java.util.zip.ZipException

### ISSUE THREAD

**Issue by jayhamilton** [spring-cloud/spring-cloud-netflix#2452]
Spring Boot 1.5x with Zuul reverse proxy

Example url passed into Zuul:

- https://xxx.xx.x.x/core/api/endeavour/session?screenInfo=1

Here is the stack trace from Zuul:

```
Caused by: java.lang.reflect.UndeclaredThrowableException: null
  at org.springframework.util.ReflectionUtils.rethrowRuntimeException(ReflectionUtils.java:317) ~[spring-core-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
  at org.springframework.cloud.netflix.zuul.filters.post.SendResponseFilter.run(SendResponseFilter.java:115) ~[spring-cloud-netflix-core-1.3.2.RELEASE.jar!/:1.3.2.RELEASE]
  at com.netflix.zuul.ZuulFilter.runFilter(ZuulFilter.java:112) ~[zuul-core-1.3.0.jar!/:1.3.0]
  at com.netflix.zuul.FilterProcessor.processZuulFilter(FilterProcessor.java:193) ~[zuul-core-1.3.0.jar!/:1.3.0]
 
 ... 64 common frames omitted
 Caused by: java.util.zip.ZipException: invalid code lengths set
  at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:164) ~[na:1.7.0_161]
  at java.util.zip.GZIPInputStream.read(GZIPInputStream.java:116) ~[na:1.7.0_161]
  at java.io.FilterInputStream.read(FilterInputStream.java:107) ~[na:1.7.0_161]
```

**Comment by spencergibb** [comment]
Please learn how to properly [format code and logs](https://help.github.com/articles/creating-and-highlighting-code-blocks/).

Is it specific to that version of java? Can you provide a sample that recreates the issue?

**Comment by jayhamilton** [comment]
It seems to be specific to JDK versions higher than 1.7.0 Update 111. We do not see this behavior with JDK versions lower than and including Update 111.  

I will see if I can easily reproduce this is a very simple environment.

**Comment by jayhamilton** [comment]
Spencer,
we have the following configuration: Angular GUI is sending API requests to ZUUL which then forwards the request to APIs running in the Virgo application container. The Virgo application container uses Tomcat and SpringDM. We are reviewing the following:

1. Virgo/Tomcat is configured to use compression. So we will disable compression to see if there is a change in behavior.
2. We are reviewing the following JDK bug to see if that is related as well: https://bugs.openjdk.java.net/browse/JDK-8189789

**Comment by spencergibb** [comment]
Another simple test would be to use jetty instead of tomcat.

I'm going to close this as it doesn't appear to have anything to do specifically with zuul. Feel free to reopen in there is new evidence.

**Comment by jayhamilton** [comment]
After disablling compression within Tomcat we no longer see the problem. It seems there is a bug in the Oracle JDK for versions between and including  1.7.0 U121 and 1.7.0 update 161.
