### ISSUE TITLE
zuul hystrix use bio to deal request?

### ISSUE THREAD

**Issue by callmeqingzhi** [spring-cloud/spring-cloud-netflix#2459]
this is zuul hystrix's setting:
   hystrix:
  command.default.execution.isolation.thread.timeoutInMilliseconds: 10000
  command.default.circuitBreaker.sleepWindowInMilliseconds: 5000
  command.default.circuitBreaker.requestVolumeThreshold: 20
  command.default.circuitBreaker.errorThresholdPercentage: 50
  threadpool.default.coreSize: 2000
  threadpool.default.keepAliveTimeMinutes: 1
  threadpool.default.maxQueueSize: -1
  threadpool.default.queueSizeRejectionThreshold: 5

and this is server hystrix's setting:
   hystrix:
  command.default.execution.isolation.thread.timeoutInMilliseconds: 3000
  command.default.circuitBreaker.sleepWindowInMilliseconds: 5000
  command.default.circuitBreaker.requestVolumeThreshold: 20
  command.default.circuitBreaker.errorThresholdPercentage: 50
  threadpool.default.coreSize: 10
  threadpool.default.keepAliveTimeMinutes: 1
  threadpool.default.maxQueueSize: -1

when I use zuul to deal requests, it will blocking and fallback, but when I only use server without zuul it's
ok! why?
anyone help me?thx

**Comment by ryanjbaxter** [comment]
Could you please show us the error you are seeing via a stacktrace?

**Comment by callmeqingzhi** [comment]
Caused by: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@2690128f rejected from java.util.concurrent.ThreadPoolExecutor@5623261c[Running, pool size = 10, active threads = 10, queued tasks = 0, completed tasks = 10966]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2047)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:823)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1369)
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
	at com.netflix.hystrix.strategy.concurrency.HystrixContextScheduler$ThreadPoolWorker.schedule(HystrixContextScheduler.java:172)
	at com.netflix.hystrix.strategy.concurrency.HystrixContextScheduler$HystrixContextSchedulerWorker.schedule(HystrixContextScheduler.java:106)
	at rx.internal.operators.OperatorSubscribeOn.call(OperatorSubscribeOn.java:45)
	at rx.internal.operators.OperatorSubscribeOn.call(OperatorSubscribeOn.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	... 113 common frames omitted

**Comment by callmeqingzhi** [comment]
this is zuul's tomcat setting,when setMaxThreads(10), it's ok, but when setMaxThreads(100), zuul will throw exception:
@Component
public class MyTomcatConfig extends TomcatEmbeddedServletContainerFactory
{
    @Override
    protected void customizeConnector(Connector connector)
    {
        super.customizeConnector(connector);
        Http11NioProtocol protocol = (Http11NioProtocol)connector.getProtocolHandler();
        protocol.setMaxConnections(2000);
        protocol.setMaxThreads(10);
    }
}

**Comment by ryanjbaxter** [comment]
The hystrix isolation strategy used with Zuul is Semaphore which might be why it is blocking.

**Comment by spencergibb** [comment]
Closing this due to inactivity. Please re-open if there's more to discuss.
