### ISSUE TITLE
eureka zuul does not work my non-eureka app

### ISSUE THREAD

**Issue by ididy** [spring-cloud/spring-cloud-netflix#2461]
I have a python-flask web app, and registered with eureka using restfull api[https://github.com/Netflix/eureka/wiki/Eureka-REST-operations], and I found it status UP on the eureka web page, but my gateway server(also registered with eureka) can not find it, I call the url <gateway-server-host/myapp-url> and the following response is:
`com.netflix.zuul.exception.ZuulException: Forwarding error
        at org.springframework.cloud.netflix.zuul.filters.route.RibbonRoutingFilter.handleException(RibbonRoutingFilter.java:188)
        at org.springframework.cloud.netflix.zuul.filters.route.RibbonRoutingFilter.forward(RibbonRoutingFilter.java:163)
        at org.springframework.cloud.netflix.zuul.filters.route.RibbonRoutingFilter.run(RibbonRoutingFilter.java:111)`

...

`Caused by: com.netflix.client.ClientException: Load balancer does not have available server for client: test
        at com.netflix.loadbalancer.LoadBalancerContext.getServerFromLoadBalancer(LoadBalancerContext.java:483)
        at com.netflix.loadbalancer.reactive.LoadBalancerCommand$1.call(LoadBalancerCommand.java:184)
        at com.netflix.loadbalancer.reactive.LoadBalancerCommand$1.call(LoadBalancerCommand.java:180)`

any advise for this problem???

**Comment by ryanjbaxter** [comment]
Could be how you are registering it.  It is hard to say without more information.

**Comment by ididy** [comment]
It seems to be non-eureka app cannot be found by the gateway server, I used springcloud app to test my gateway server instead
