### ISSUE TITLE
Feign compression is not working because of missing ApacheHttpClient bean

### ISSUE THREAD

**Issue by gbtec-ingogriebsch** [spring-cloud/spring-cloud-netflix#2462]
As already discussed in #1580 it looks like the Feign compression is not working because the auto configuration preparing the gzip interceptors expects a bean of type ApacheHttpClient which is not available in the application context.

```JSON
"FeignAcceptGzipEncodingAutoConfiguration": {
	"notMatched": [{
		"condition": "OnBeanCondition",
		"message": "@ConditionalOnBean (types: feign.httpclient.ApacheHttpClient; SearchStrategy: all) did not find any beans"
	}
	],
	"matched": [{
		"condition": "OnClassCondition",
		"message": "@ConditionalOnClass found required class 'feign.Feign'; @ConditionalOnMissingClass did not find unwanted class"
	},{
		"condition": "OnPropertyCondition",
		"message": "@ConditionalOnProperty (feign.compression.response.enabled) matched"
	}]
},
"FeignContentGzipEncodingAutoConfiguration": {
	"notMatched": [{
		"condition": "OnBeanCondition",
		"message": "@ConditionalOnBean (types: feign.httpclient.ApacheHttpClient; SearchStrategy: all) did not find any beans"
	}],
	"matched": [{
		"condition": "OnClassCondition",
		"message": "@ConditionalOnClass found required class 'feign.Feign'; @ConditionalOnMissingClass did not find unwanted class"
	},{
		"condition": "OnPropertyCondition",
		"message": "@ConditionalOnProperty (feign.compression.request.enabled) matched"
	}]
}
```

If we add a bean of type ApacheHttpClient to the application context (without configuring the object in any way) the auto configuration is triggering and the interceptors are available (and will probably trigger). But now the call to the server side is broken because of

```DTrace
2017-11-22 09:59:48.277 ERROR 992 --- [io-11111-exec-2] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is feign.RetryableException: spring-cloud-feign-compression-bug-server executing GET http://spring-cloud-feign-compression-bug-server/api/content?size=8192] with root cause

java.net.UnknownHostException: spring-cloud-feign-compression-bug-server
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method) ~[na:1.8.0_92]
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928) ~[na:1.8.0_92]
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323) ~[na:1.8.0_92]
	at java.net.InetAddress.getAllByName0(InetAddress.java:1276) ~[na:1.8.0_92]
	at java.net.InetAddress.getAllByName(InetAddress.java:1192) ~[na:1.8.0_92]
	at java.net.InetAddress.getAllByName(InetAddress.java:1126) ~[na:1.8.0_92]
	at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45) ~[httpclient-4.5.3.jar:4.5.3]
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:112) ~[httpclient-4.5.3.jar:4.5.3]
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:359) ~[httpclient-4.5.3.jar:4.5.3]
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381) ~[httpclient-4.5.3.jar:4.5.3]
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237) ~[httpclient-4.5.3.jar:4.5.3]
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185) ~[httpclient-4.5.3.jar:4.5.3]
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) ~[httpclient-4.5.3.jar:4.5.3]
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111) ~[httpclient-4.5.3.jar:4.5.3]
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[httpclient-4.5.3.jar:4.5.3]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[httpclient-4.5.3.jar:4.5.3]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108) ~[httpclient-4.5.3.jar:4.5.3]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56) ~[httpclient-4.5.3.jar:4.5.3]
	at feign.httpclient.ApacheHttpClient.execute(ApacheHttpClient.java:87) ~[feign-httpclient-9.5.0.jar:na]
	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:97) ~[feign-core-9.5.0.jar:na]
	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:76) ~[feign-core-9.5.0.jar:na]
	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:103) ~[feign-core-9.5.0.jar:na]
	at com.example.demo.$Proxy83.get(Unknown Source) ~[na:na]
	at com.example.demo.ContentService.get(ContentService.java:21) ~[classes/:na]
	at com.example.demo.ContentCtrl.content(ContentCtrl.java:27) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_92]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_92]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_92]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_92]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) ~[spring-web-4.3.12.RELEASE.jar:4.3.12.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133) ~[spring-web-4.3.12.RELEASE.jar:4.3.12.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97) ~[spring-webmvc-4.3.12.RELEASE.jar:4.3.12.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827) ~[spring-webmvc-4.3.12.RELEASE.jar:4.3.12.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738) ~[spring-webmvc-4.3.12.RELEASE.jar:4.3.12.RELEASE]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85) ~[spring-webmvc-4.3.12.RELEASE.jar:4.3.12.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967) ~[spring-webmvc-4.3.12.RELEASE.jar:4.3.12.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901) ~[spring-webmvc-4.3.12.RELEASE.jar:4.3.12.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970) ~[spring-webmvc-4.3.12.RELEASE.jar:4.3.12.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861) ~[spring-webmvc-4.3.12.RELEASE.jar:4.3.12.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635) ~[tomcat-embed-core-8.5.23.jar:8.5.23]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846) ~[spring-webmvc-4.3.12.RELEASE.jar:4.3.12.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) ~[tomcat-embed-core-8.5.23.jar:8.5.23]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[tomcat-embed-core-8.5.23.jar:8.5.23]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.23.jar:8.5.23]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) ~[tomcat-embed-websocket-8.5.23.jar:8.5.23]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.23.jar:8.5.23]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.23.jar:8.5.23]
	at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55) ~[spring-boot-1.5.8.RELEASE.jar:1.5.8.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.3.12.RELEASE.jar:4.3.12.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.23.jar:8.5.23]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.23.jar:8.5.23]
	at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:110) ~[spring-boot-actuator-1.5.8.RELEASE.jar:1.5.8.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.3.12.RELEASE.jar:4.3.12.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.23.jar:8.5.23]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.23.jar:8.5.23]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99) ~[spring-web-4.3.12.RELEASE.jar:4.3.12.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.3.12.RELEASE.jar:4.3.12.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.23.jar:8.5.23]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.23.jar:8.5.23]
	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:108) ~[spring-web-4.3.12.RELEASE.jar:4.3.12.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.3.12.RELEASE.jar:4.3.12.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.23.jar:8.5.23]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.23.jar:8.5.23]
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81) ~[spring-web-4.3.12.RELEASE.jar:4.3.12.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.3.12.RELEASE.jar:4.3.12.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.23.jar:8.5.23]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.23.jar:8.5.23]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197) ~[spring-web-4.3.12.RELEASE.jar:4.3.12.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.3.12.RELEASE.jar:4.3.12.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.23.jar:8.5.23]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.23.jar:8.5.23]
	at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:106) ~[spring-boot-actuator-1.5.8.RELEASE.jar:1.5.8.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.3.12.RELEASE.jar:4.3.12.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.23.jar:8.5.23]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.23.jar:8.5.23]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199) ~[tomcat-embed-core-8.5.23.jar:8.5.23]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat-embed-core-8.5.23.jar:8.5.23]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478) [tomcat-embed-core-8.5.23.jar:8.5.23]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) [tomcat-embed-core-8.5.23.jar:8.5.23]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) [tomcat-embed-core-8.5.23.jar:8.5.23]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) [tomcat-embed-core-8.5.23.jar:8.5.23]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342) [tomcat-embed-core-8.5.23.jar:8.5.23]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803) [tomcat-embed-core-8.5.23.jar:8.5.23]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-embed-core-8.5.23.jar:8.5.23]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868) [tomcat-embed-core-8.5.23.jar:8.5.23]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459) [tomcat-embed-core-8.5.23.jar:8.5.23]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-8.5.23.jar:8.5.23]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_92]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_92]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.5.23.jar:8.5.23]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_92]
```

The project is running under Spring Boot 1.5.8 and Spring Cloud Dalston.SR4. We are using the following dependencies:

```Maven POM
<dependency>
	<groupId>org.springframework.cloud</groupId>
	<artifactId>spring-cloud-starter-eureka</artifactId>
</dependency>
<dependency>
	<groupId>org.springframework.cloud</groupId>
	<artifactId>spring-cloud-starter-feign</artifactId>
</dependency>
<dependency>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-web</artifactId>
</dependency>
<dependency>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-actuator</artifactId>
	<scope>runtime</scope>
</dependency>
```

We don't know if we are missing something that would easily solve the problem. If we have a look at the classpath (through the IDE) we don't find the class ApacheHttpClient. Only after We have added

```Maven POM
<dependency> 
	<groupId>io.github.openfeign</groupId> 
	<artifactId>feign-httpclient</artifactId> 
</dependency>
```

to the project the class is available on the classpath.

We have created to projects which reproduces the behaviour. The current state is reflecting the state that the compression is configured but the auto configuration is not triggered. We have prefixed the comments of the relevant parts with a FIXME (if you want to search for them). If you change/enhance the projects the way we commented you can reproduce the service discovery bug.

 * [server side](https://github.com/gbtec-ingogriebsch/spring-cloud-feign-compression-bug-server)
 * [client side](https://github.com/gbtec-ingogriebsch/spring-cloud-feign-compression-bug-client)

**Comment by ryanjbaxter** [comment]
Sorry I needed to refresh my brain on this issue.  The `ApacheHttpClient` bean will be created in `FeignAutoConfiguration` but only if Ribbon is not used.  When using Ribbon we will use the HTTP client created by Ribbon.  Hence when you are using Eureka Ribbon is going to automatically be on the classpath and therefore the `ApacheHttpClient` bean wont be created.

**Comment by gbtec-ingogriebsch** [comment]
@ryanjbaxter So far understood. You explained what the code is doing. But what does it mean in relation to handle this problem?

Can we do something as long as this problem is not solved? And is there a plan to provide a bugfix for it? Is there for example a possibility inside the GzipEncodingAutoConfiguration's to only expect the ApacheHttpClient bean if Ribbon is not available?

In general it's hard to understand that one cannot use some feign compression because he/she is using some Ribbon/Eureka.

**Comment by spencergibb** [comment]
By default feign uses `HttpURLConnection`. You have to enable apache http client explicitly.

**Comment by spencergibb** [comment]
We default in other places to apache http client, I don't see why we couldn't here.

**Comment by spencergibb** [comment]
Hmm, my bad, there is separate configuration if ribbon is used, and it looks like it is the default

**Comment by spencergibb** [comment]
The gzip autoconfig should also be after `FeignRibbonClientAutoConfiguration`

**Comment by gbtec-ingogriebsch** [comment]
@spencergibb Are your comments related to my answer? Do you give us some hints, what to do? 

Sorry but it is really difficult to follow such thought like comments without context. Therefore it would be really really helpful if you could give some more context so that one who is not living inside that code the whole day is understanding what you are exactly talking about.

**Comment by spencergibb** [comment]
https://github.com/spring-cloud/spring-cloud-netflix/blob/6c52269dc56f2f4fd5012d9ff77c261631bf1a07/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/feign/encoding/FeignAcceptGzipEncodingAutoConfiguration.java#L42

needs to also have `FeignRibbonClientAutoConfiguration`

**Comment by ryanjbaxter** [comment]
Yeah the reason this does not work when using Ribbon is because `FeignAcceptGzipEncodingAutoConfiguration` is not auto configured after `FeignRibbonClientAutoConfiguration` and also because it requires there be an `ApacheHttpClient` bean created as well, which there is not when Ribbon is used.  I will take a look at this and see if we can make it work when Ribbon is used as well.  

@gbtec-ingogriebsch for now you can try and create your own configuration class which returns a `FeignAcceptGzipEncodingInterceptor` bean and that would probably work for your use case.  Let us know.

**Comment by gbtec-ingogriebsch** [comment]
@ryanjbaxter I followed your suggestion and did the following...

````Java
@Configuration
@EnableConfigurationProperties(FeignClientEncodingProperties.class)
@ConditionalOnProperty(value = "feign.compression.response.enabled", matchIfMissing = false)
public class FeignAcceptGzipEncodingConfiguration {

@Bean
public FeignAcceptGzipEncodingInterceptor feignAcceptGzipEncodingInterceptor(FeignClientEncodingProperties properties) {
        return new FeignAcceptGzipEncodingInterceptor(properties) {
        };
    }
}
````

The corresponding configuration look like the following...

````YAML
feign:
  compression:
    request:
      enabled: true
      mime-types:
      - application/json
      min-request-size: 2048
    response:
      enabled: true
````

The other side (running boot app using tomcat) is configured the following way...

````YAML
server:
  port: 0
  tomcat:
    uri-encoding: UTF-8
  compression:
    enabled: true
    mime-types: 
    - application/json
    min-response-size: 2048
````

If I add the configuration classes to the project and configure the Feign compression like shown above the beans are created on startup and triggered if I execute a call through Feign. The problem is that the call results in the following exception:

````DTrace
2017-11-29 21:08:42.069  WARN [biccloud-custom-apigateway,406313c55480f8d9,406313c55480f8d9,true] 10892 --- 
 [io-30000-exec-2] .m.m.a.ExceptionHandlerExceptionResolver : Resolved exception caused by Handler execution: feign.codec.DecodeException: 
 JSON parse error: Illegal character ((CTRL-CHAR, code 31)): 
 only regular white space (\r, \n, \t) is allowed between tokens; 
 nested exception is com.fasterxml.jackson.core.JsonParseException: 
 Illegal character ((CTRL-CHAR, code 31)): only regular white space (\r, \n, \t) is allowed between tokens
 at [Source: java.io.PushbackInputStream@6f37ab7d; line: 1, column: 2]
````

After searching a little bit I stumbled about the following blog entry:
https://jmnarloch.wordpress.com/2015/09/30/spring-cloud-feign-requestresponse-compression/

The blog entry is explaining how to enable compression on Feign. It's also explaining that one is getting the error shown above and is again pointing to the following git page:
https://github.com/jmnarloch/feign-encoding-spring-cloud-starter#know-issues

This page is explaining that - if you face that problem - you need to have an **ApacheHttpClient**!

That's the current state... Looks a little bit like we are spinning in a circle here... Or do I understand something wrong?

**Comment by gbtec-ingogriebsch** [comment]
@ryanjbaxter Would like to ask about the further plan regarding this bug. Has this any priority for you atm? And do you know about another workaround?

**Comment by ryanjbaxter** [comment]
Sorry @gbtec-ingogriebsch this fell off my radar.  I will try and look into it this week.  I need to refresh my brain on what was wrong again.

**Comment by gbtec-ingogriebsch** [comment]
@ryanjbaxter Because I don't know another way, I would like to politely repeat my request about the status of this bug ticket.

**Comment by ryanjbaxter** [comment]
Again sorry for taking so long to get to this but I think I have a solution for you.

In addition to the `FeignAcceptGzipEncodingInterceptor` configuration you added to your app, can you also add the following bean

```
public class CustomApacheHttpClientFactory implements ApacheHttpClientFactory {
    public CustomApacheHttpClientFactory() {
    }

    public HttpClientBuilder createBuilder() {
        return HttpClientBuilder.create().disableCookieManagement().useSystemProperties();
    }
}
```
