### ISSUE TITLE
i can not import spring cloud into eclipse

### ISSUE THREAD

**Issue by ghost** [spring-cloud/spring-cloud-netflix#2502]
```
nresolveable build extension: Plugin org.springframework.cloud:spring-cloud-contract-maven-plugin:1.1.2.RELEASE or one of its dependencies could not be resolved: Failure to find org.springframework.cloud:spring-cloud-netflix-hystrix-contract:jar:1.4.0.RELEASE in https://repo.spring.io/libs-milestone-local was cached in the local repository, resolution will not be reattempted until the update interval of spring-milestones has elapsed or updates are forced -> [Help 2]
org.apache.maven.plugin.PluginManagerException: Plugin org.springframework.cloud:spring-cloud-contract-maven-plugin:1.1.2.RELEASE or one of its dependencies could not be resolved: Failure to find org.springframework.cloud:spring-cloud-netflix-hystrix-contract:jar:1.4.0.RELEASE in https://repo.spring.io/libs-milestone-local was cached in the local repository, resolution will not be reattempted until the update interval of spring-milestones has elapsed or updates are forced
	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.setupExtensionsRealm(DefaultMavenPluginManager.java:848)
	at org.apache.maven.project.DefaultProjectBuildingHelper.createProjectRealm(DefaultProjectBuildingHelper.java:196)
	at org.apache.maven.project.DefaultModelBuildingListener.buildExtensionsAssembled(DefaultModelBuildingListener.java:99)
	at org.apache.maven.model.building.ModelBuildingEventCatapult$1.fire(ModelBuildingEventCatapult.java:44)
	at org.apache.maven.model.building.DefaultModelBuilder.fireEvent(DefaultModelBuilder.java:1348)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:443)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:423)
```

**Comment by ryanjbaxter** [comment]
Please learn how to [format code on GitHub](https://help.github.com/articles/creating-and-highlighting-code-blocks/).

`spring-cloud-netflix-hystrix-contract` is just used by tests and is not part of the build.  Trying building that module separately first and then compiling everything else.

Alternatively you could run `scripts/build.sh`.

**Comment by spencergibb** [comment]
You may need to activate the spring Maven profile as well

**Comment by spencergibb** [comment]
Closing this due to inactivity. Please re-open if there's more to discuss.
