### ISSUE TITLE
WebRequest parameter should by ignored by Feign SpringMvcContract

### ISSUE THREAD

**Issue by tjuchniewicz** [spring-cloud/spring-cloud-netflix#2540]
Currently following interface method:
```java
ResponseEntity<ModelSO> getSubscriptionInformation(
       @RequestBody @ApiParam(name = "request", value = "The body of the request", required = true) 
       ModelSO model, // body 1
       WebRequest webRequest); // body2 ?
```
can't be used as Feign Client:
```
java.lang.IllegalStateException: Method has too many Body parameters: public abstract org.springframework.http.ResponseEntity com.daimler.daivb.vts.snap.SubscriptionInformationSI.getSubscriptionInformation(java.lang.String,java.lang.String,java.lang.String,java.lang.String,com.daimler.daivb.vts.snap.SubscriptionRequestSO,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,org.springframework.web.context.request.WebRequest)
	at feign.Util.checkState(Util.java:128)
	at feign.Contract$BaseContract.parseAndValidateMetadata(Contract.java:114)
	at org.springframework.cloud.netflix.feign.support.SpringMvcContract.parseAndValidateMetadata(SpringMvcContract.java:131)
	at feign.Contract$BaseContract.parseAndValidatateMetadata(Contract.java:64)
	at feign.ReflectiveFeign$ParseHandlersByName.apply(ReflectiveFeign.java:146)
	at feign.ReflectiveFeign.newInstance(ReflectiveFeign.java:53)
	at feign.Feign$Builder.target(Feign.java:209)
	at feign.Feign$Builder.target(Feign.java:205)
```

**Comment by spencergibb** [comment]
That's not how feign works. A client has no knowledge of what a web request is. You shouldn't be sharing server interfaces with clients.

**Comment by tjuchniewicz** [comment]
But we share interfaces with clients...For us this is a common case.
Any idea for improvement?

**Comment by tjuchniewicz** [comment]
Current workaround is to use: `@RequestParam(value = "ignored", required = false) WebRequest request`

**Comment by ryanjbaxter** [comment]
Reopening for the PR above

**Comment by jvstepanova84** [comment]
The same problem with 

```
@Override
    public ResponseEntity<Response> statusBso(@Valid @RequestBody Request request, Errors errors) {
```
where Error is org.springframework.validation.Errors

I can't use Feign with spring validation in controller, because I have error Method has too many Body parameters

**Comment by tjuchniewicz** [comment]
Sorry but I don't work on this PR anymore :-(

**Comment by OlgaMaciaszek** [comment]
@jvstepanova84 Have you tried using the workaround provided by @tjuchniewicz above?

**Comment by XhstormR** [comment]
I have same problem here, we should provide ignore annotation like `@FeignIgnore` to programmatically ignore some method parameter.

**Comment by OlgaMaciaszek** [comment]
@XhstormR Spring Cloud OpenFeign is now in maintenance only mode; we recommend migrating over to [Spring Interface Clients](https://docs.spring.io/spring-framework/reference/integration/rest-clients.html#rest-http-interface) as we do not plan further development there.
