### ISSUE TITLE
use feignClient in afterPropertiesSet will fail

### ISSUE THREAD

**Issue by aftersss** [spring-cloud/spring-cloud-netflix#2553]
We have to init something when using feignClient,  so we just do it in the method `afterPropertiesSet` .

the code is like the following:

```
@Controller
public class IndexCtrl implements InitializingBean {

    //this is an interface annotated with @FeignClient
    @Resource
    private RemoteStockService remoteStockService;

    @Override
    public void afterPropertiesSet() throws Exception {
            remoteStockService.doSomething();
    }
}
```

but this will fail, the stacktrace is like:

```
16:28:25.598 ERROR [main] c.com.duiba.controller.IndexCtrl[IndexCtrl.java:36] -> 
com.netflix.hystrix.exception.HystrixRuntimeException: RemoteStockService#find(long) timed-out and no fallback available.
	at com.netflix.hystrix.AbstractCommand$22.call(AbstractCommand.java:819)
	at com.netflix.hystrix.AbstractCommand$22.call(AbstractCommand.java:804)
	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$4.onError(OperatorOnErrorResumeNextViaFunction.java:140)
	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
	at com.netflix.hystrix.AbstractCommand$DeprecatedOnFallbackHookApplication$1.onError(AbstractCommand.java:1472)
	at com.netflix.hystrix.AbstractCommand$FallbackHookApplication$1.onError(AbstractCommand.java:1397)
	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
	at rx.observers.Subscribers$5.onError(Subscribers.java:230)
	at rx.internal.operators.OnSubscribeThrow.call(OnSubscribeThrow.java:44)
	at rx.internal.operators.OnSubscribeThrow.call(OnSubscribeThrow.java:28)
	at rx.Observable.unsafeSubscribe(Observable.java:10151)
	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:51)
	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
	at rx.Observable.unsafeSubscribe(Observable.java:10151)
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10151)
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10151)
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10151)
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10151)
	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$4.onError(OperatorOnErrorResumeNextViaFunction.java:142)
	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
	at com.netflix.hystrix.AbstractCommand$HystrixObservableTimeoutOperator$1$1.run(AbstractCommand.java:1154)
	at com.netflix.hystrix.strategy.concurrency.HystrixContextRunnable$1.call(HystrixContextRunnable.java:45)
	at com.netflix.hystrix.strategy.concurrency.HystrixContextRunnable$1.call(HystrixContextRunnable.java:41)
	at com.netflix.hystrix.strategy.concurrency.HystrixContextRunnable.run(HystrixContextRunnable.java:61)
	at com.netflix.hystrix.AbstractCommand$HystrixObservableTimeoutOperator$1.tick(AbstractCommand.java:1159)
	at com.netflix.hystrix.util.HystrixTimer$1.run(HystrixTimer.java:99)
	at java.util.concurrent.Executors$RunnableAdapter.call$$$capture(Executors.java:511)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.concurrent.TimeoutException: null
	at com.netflix.hystrix.AbstractCommand.handleTimeoutViaFallback(AbstractCommand.java:997)
	at com.netflix.hystrix.AbstractCommand.access$500(AbstractCommand.java:60)
	at com.netflix.hystrix.AbstractCommand$12.call(AbstractCommand.java:610)
	at com.netflix.hystrix.AbstractCommand$12.call(AbstractCommand.java:601)
	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$4.onError(OperatorOnErrorResumeNextViaFunction.java:140)
```

I debugged it, and I found that the main thread hold a lock, and the hystrix thread wait for the lock which holded by the main thread. the main thread will never release the lock until `IndexCtrl.afterPropertiesSet` success. so the feign invoke just timed out.

`jstack` output is like:

```
"hystrix-stock-service-1@6075" daemon prio=5 tid=0x33 nid=NA waiting for monitor entry
  java.lang.Thread.State: BLOCKED
	 blocks hystrix-stock-service-8@6213
	 blocks hystrix-stock-service-7@6209
	 blocks hystrix-stock-service-6@6205
	 blocks hystrix-stock-service-5@6201
	 blocks hystrix-stock-service-4@6197
	 blocks hystrix-stock-service-3@6192
	 blocks hystrix-stock-service-2@6187
	 waiting for main@1 to release lock on <0x185d> (a java.util.concurrent.ConcurrentHashMap)
	  at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:187)
	  at org.springframework.beans.factory.support.AbstractBeanFactory.isTypeMatch(AbstractBeanFactory.java:486)
	  at org.springframework.beans.factory.support.DefaultListableBeanFactory.doGetBeanNamesForType(DefaultListableBeanFactory.java:432)
	  at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanNamesForType(DefaultListableBeanFactory.java:403)
	  at org.springframework.beans.factory.BeanFactoryUtils.beanNamesForTypeIncludingAncestors(BeanFactoryUtils.java:220)
	  at org.springframework.beans.factory.BeanFactoryUtils.beanNamesForTypeIncludingAncestors(BeanFactoryUtils.java:224)
	  at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1267)
	  at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1101)
	  at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1066)
	  at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:585)
	  at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
	  at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:366)
	  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1264)
	  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:553)
	  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
	  at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	  at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	  - locked <0x18a0> (a java.util.concurrent.ConcurrentHashMap)
	  at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	  at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	  at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761)
	  at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867)
	  at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543)
	  - locked <0x18a1> (a java.lang.Object)
	  at org.springframework.cloud.context.named.NamedContextFactory.createContext(NamedContextFactory.java:116)
	  at org.springframework.cloud.context.named.NamedContextFactory.getContext(NamedContextFactory.java:85)
	  - locked <0x189f> (a java.util.concurrent.ConcurrentHashMap)
	  at org.springframework.cloud.netflix.ribbon.SpringClientFactory.getContext(SpringClientFactory.java:120)
	  at org.springframework.cloud.context.named.NamedContextFactory.getInstance(NamedContextFactory.java:121)
	  at org.springframework.cloud.netflix.ribbon.SpringClientFactory.getInstance(SpringClientFactory.java:110)
	  at org.springframework.cloud.netflix.ribbon.SpringClientFactory.getClientConfig(SpringClientFactory.java:67)
	  at org.springframework.cloud.netflix.feign.ribbon.LoadBalancerFeignClient.getClientConfig(LoadBalancerFeignClient.java:78)
	  at org.springframework.cloud.netflix.feign.ribbon.LoadBalancerFeignClient.execute(LoadBalancerFeignClient.java:62)
	  at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:97)
	  at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:76)
	  at feign.hystrix.HystrixInvocationHandler$1.run(HystrixInvocationHandler.java:108)
	  at com.netflix.hystrix.HystrixCommand$2.call(HystrixCommand.java:302)
	  at com.netflix.hystrix.HystrixCommand$2.call(HystrixCommand.java:298)
	  at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:46)
	  at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
	  at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	  at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	  at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	  at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	  at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	  at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	  at rx.Observable.unsafeSubscribe(Observable.java:10151)
	  at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:51)
	  at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
	  at rx.Observable.unsafeSubscribe(Observable.java:10151)
	  at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
	  at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
	  at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	  at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	  at rx.Observable.unsafeSubscribe(Observable.java:10151)
	  at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
	  at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction$1.call(HystrixContexSchedulerAction.java:56)
	  at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction$1.call(HystrixContexSchedulerAction.java:47)
	  at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction.call(HystrixContexSchedulerAction.java:69)
	  at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	  at java.util.concurrent.Executors$RunnableAdapter.call$$$capture(Executors.java:511)
	  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:-1)
	  at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	  at java.util.concurrent.FutureTask.run(FutureTask.java:-1)
	  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	  at java.lang.Thread.run(Thread.java:745)

"main@1" prio=5 tid=0x1 nid=NA sleeping
  java.lang.Thread.State: TIMED_WAITING
	 blocks hystrix-stock-service-1@6075
	  at java.lang.Thread.sleep(Thread.java:-1)
	  at cn.com.duiba.controller.IndexCtrl.afterPropertiesSet(IndexCtrl.java:30)
	  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1687)
	  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1624)
	  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
	  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
	  at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	  at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	  - locked <0x185d> (a java.util.concurrent.ConcurrentHashMap)
	  at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	  at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	  at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761)
	  at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867)
	  at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543)
	  - locked <0x18a6> (a java.lang.Object)
	  at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
	  at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693)
	  at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360)
	  at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
	  at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118)
	  at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107)
	  at cn.com.duiba.Application.main(Application.java:19)
``` 

I wrote a demo project that can reproduce this bug:

[springCloudBugDemo.zip](https://github.com/spring-cloud/spring-cloud-netflix/files/1562033/springCloudBugDemo.zip)

notice that I setted property:`feign.hystrix.enabled=true` in application.properties, if you remove this property, the bug is disappeared. but we prefer to use hystrix.

**Comment by ryanjbaxter** [comment]
Seems like Hystrix is doing what it should do but I dont understand why you need to call the FeignClient after the bean is created.

**Comment by aftersss** [comment]
I call FeignClient to fetch some data and cache it in memory before Application is started(the cached data will never expire), and when my application is started, we just use the cache to serve requests,  without any call to FeignClient again, to reduce the cost.

**Comment by spencergibb** [comment]
@aftersss unfortunately your project isn't complete (there's no downstream service). You are better off doing work using one of spring boot's application events, rather than `afterPropertiesSet()`. https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-application-events-and-listeners

**Comment by aftersss** [comment]
the project is very simple, you can write a downstream yourself.

I am actually using application events instead, but this bug puzzle some of our developers.

And if I register a eventListener listening `ContextRefreshedEvent`, the eventListener will be trigged two times(one is from the ApplicationContext which contains FeignClient, one is from the main ApplicationContext),  I have to do more work to make sure the initMethod is  trigger only once. I think using `ContextRefreshedEvent` is not very graceful.

**Comment by spencergibb** [comment]
One of statement to check if it's from the current application context isn't graceful?

**Comment by brenuart** [comment]
We also had this issue at multiple occasions - and like you said "this confuses our developers".
Our approach was to rely on `ApplicationStartedEvent` instead.
What do you think ?

**Comment by aftersss** [comment]
`ApplicationStartingEvent`  needs an entry in`META-INF/spring.factories`, It also need some cost to use it. I think `spring.factories` is very good for some framework developers, actually we are using it heavily in ourself's boot framework which is used by each of our `spring-boot` applications, but we don't want to take complexity to application developers.

Go back to the original question,  I think most people will use `afterPropertiesSet()` in this situation, and when they see the exception, they will spend a lot of time debugging it, (just like what I have done). Based on our discussion,  you maybe do not think this is a problem. standing on user's side, I think if you will not support any invocation of `FeignClient` inside `afterPropertiesSet()` (when `feign.hystrix.enabled=true` is setted),  an significative exception should be throwed, to told the user to use another way instead, or maybe some document is needed somewhere.

**Comment by spencergibb** [comment]
Events do not need spring.factories.

**Comment by brenuart** [comment]
I tend to think that `afterProperties()` is not an indication that the application has finished booting and no significant work can be done in that method besides simple initialisation. You should probably wait for `ContextRefreshed` or even better `ApplicationReady`.
