### ISSUE TITLE
Edgware.RELEASE java.lang.NoClassDefFoundError: com/netflix/hystrix/contrib/javanica/aop/aspectj/HystrixCommandAspect

### ISSUE THREAD

**Issue by dcuenot** [spring-cloud/spring-cloud-netflix#2596]
Hello,

I just upgraded to Spring boot 1.5.9 and _Spring Cloud Edgware.RELEASE_ and I got this exception.

```
2017-12-30 01:04:33.293 ERROR [account-service,,,] 21036 --- [           main] o.s.boot.SpringApplication               : Application startup failed

java.lang.NoClassDefFoundError: com/netflix/hystrix/contrib/javanica/aop/aspectj/HystrixCommandAspect
	at java.lang.Class.getDeclaredMethods0(Native Method) ~[na:1.8.0_152]
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701) ~[na:1.8.0_152]
	at java.lang.Class.getDeclaredMethods(Class.java:1975) ~[na:1.8.0_152]
	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:613) ~[spring-core-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:524) ~[spring-core-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:510) ~[spring-core-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.util.ReflectionUtils.getUniqueDeclaredMethods(ReflectionUtils.java:570) ~[spring-core-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.getTypeForFactoryMethod(AbstractAutowireCapableBeanFactory.java:697) ~[spring-beans-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.determineTargetType(AbstractAutowireCapableBeanFactory.java:640) ~[spring-beans-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.predictBeanType(AbstractAutowireCapableBeanFactory.java:609) ~[spring-beans-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.isFactoryBean(AbstractBeanFactory.java:1484) ~[spring-beans-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doGetBeanNamesForType(DefaultListableBeanFactory.java:425) ~[spring-beans-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanNamesForType(DefaultListableBeanFactory.java:395) ~[spring-beans-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.boot.autoconfigure.web.EmbeddedServletContainerAutoConfiguration$BeanPostProcessorsRegistrar.registerSyntheticBeanIfMissing(EmbeddedServletContainerAutoConfiguration.java:148) ~[spring-boot-autoconfigure-1.5.9.RELEASE.jar:1.5.9.RELEASE]
	at org.springframework.boot.autoconfigure.web.EmbeddedServletContainerAutoConfiguration$BeanPostProcessorsRegistrar.registerBeanDefinitions(EmbeddedServletContainerAutoConfiguration.java:137) ~[spring-boot-autoconfigure-1.5.9.RELEASE.jar:1.5.9.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsFromRegistrars(ConfigurationClassBeanDefinitionReader.java:359) ~[spring-context-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForConfigurationClass(ConfigurationClassBeanDefinitionReader.java:143) ~[spring-context-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitions(ConfigurationClassBeanDefinitionReader.java:116) ~[spring-context-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:320) ~[spring-context-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:228) ~[spring-context-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:272) ~[spring-context-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:92) ~[spring-context-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:687) ~[spring-context-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:525) ~[spring-context-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) ~[spring-boot-1.5.9.RELEASE.jar:1.5.9.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693) [spring-boot-1.5.9.RELEASE.jar:1.5.9.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360) [spring-boot-1.5.9.RELEASE.jar:1.5.9.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303) [spring-boot-1.5.9.RELEASE.jar:1.5.9.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118) [spring-boot-1.5.9.RELEASE.jar:1.5.9.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107) [spring-boot-1.5.9.RELEASE.jar:1.5.9.RELEASE]
	at com.demo.account.AccountApplication.main(AccountApplication.java:42) [classes/:na]
Caused by: java.lang.ClassNotFoundException: com.netflix.hystrix.contrib.javanica.aop.aspectj.HystrixCommandAspect
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_152]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_152]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338) ~[na:1.8.0_152]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_152]
	... 31 common frames omitted
```
For information, find below my dependency:tree.

After, in my `pom.xml`, I added this dependency:
        <dependency>
            <groupId>com.netflix.hystrix</groupId>
            <artifactId>hystrix-javanica</artifactId>
        </dependency>

=> This solved my issue, but I think there is small issue in _Spring Cloud Edgware.RELEASE_

GL for fixing!

```
mvnw.cmd -f accounts/pom.xml dependency:tree
        [INFO] Scanning for projects...
        [INFO]
        [INFO] ------------------------------------------------------------------------
        [INFO] Building accounts 1.0.0-SNAPSHOT
        [INFO] ------------------------------------------------------------------------
        [INFO]
        [INFO] --- maven-dependency-plugin:2.10:tree (default-cli) @ accounts ---
        [INFO] com.demo:accounts:jar:1.0.0-SNAPSHOT
        [INFO] +- org.springframework.cloud:spring-cloud-starter-oauth2:jar:1.2.1.RELEASE:compile
        [INFO] |  +- org.springframework.cloud:spring-cloud-starter-security:jar:1.2.1.RELEASE:compile
        [INFO] |  |  \- org.springframework.cloud:spring-cloud-security:jar:1.2.1.RELEASE:compile
        [INFO] |  \- org.springframework.security:spring-security-jwt:jar:1.0.8.RELEASE:compile
        [INFO] |     \- org.bouncycastle:bcpkix-jdk15on:jar:1.56:compile
        [INFO] |        \- org.bouncycastle:bcprov-jdk15on:jar:1.56:compile
        [INFO] +- org.springframework.boot:spring-boot-starter-security:jar:1.5.9.RELEASE:compile
        [INFO] |  +- org.springframework.boot:spring-boot-starter:jar:1.5.9.RELEASE:compile
        [INFO] |  |  +- org.springframework.boot:spring-boot:jar:1.5.9.RELEASE:compile
        [INFO] |  |  +- org.springframework.boot:spring-boot-autoconfigure:jar:1.5.9.RELEASE:compile
        [INFO] |  |  \- org.yaml:snakeyaml:jar:1.17:runtime
        [INFO] |  +- org.springframework:spring-aop:jar:4.3.13.RELEASE:compile
        [INFO] |  +- org.springframework.security:spring-security-config:jar:4.2.3.RELEASE:compile
        [INFO] |  \- org.springframework.security:spring-security-web:jar:4.2.3.RELEASE:compile
        [INFO] |     \- org.springframework:spring-expression:jar:4.3.13.RELEASE:compile
        [INFO] +- org.springframework.security.oauth:spring-security-oauth2:jar:2.0.14.RELEASE:compile
        [INFO] |  +- org.springframework:spring-beans:jar:4.3.13.RELEASE:compile
        [INFO] |  +- org.springframework:spring-core:jar:4.3.13.RELEASE:compile
        [INFO] |  +- org.springframework:spring-context:jar:4.3.13.RELEASE:compile
        [INFO] |  +- org.springframework:spring-webmvc:jar:4.3.13.RELEASE:compile
        [INFO] |  +- org.springframework.security:spring-security-core:jar:4.2.3.RELEASE:compile
        [INFO] |  |  \- aopalliance:aopalliance:jar:1.0:compile
        [INFO] |  +- commons-codec:commons-codec:jar:1.10:compile
        [INFO] |  \- org.codehaus.jackson:jackson-mapper-asl:jar:1.9.13:compile
        [INFO] |     \- org.codehaus.jackson:jackson-core-asl:jar:1.9.13:compile
        [INFO] +- org.springframework.cloud:spring-cloud-starter-feign:jar:1.4.0.RELEASE:compile
        [INFO] |  \- org.springframework.cloud:spring-cloud-starter-openfeign:jar:1.4.0.RELEASE:compile
        [INFO] |     +- io.github.openfeign:feign-core:jar:9.5.0:compile
        [INFO] |     |  \- org.jvnet:animal-sniffer-annotation:jar:1.0:compile
        [INFO] |     +- io.github.openfeign:feign-slf4j:jar:9.5.0:compile
        [INFO] |     +- io.github.openfeign:feign-hystrix:jar:9.5.0:compile
        [INFO] |     +- org.springframework.cloud:spring-cloud-starter-netflix-ribbon:jar:1.4.0.RELEASE:compile
        [INFO] |     |  +- com.netflix.ribbon:ribbon:jar:2.2.4:compile
        [INFO] |     |  |  +- com.netflix.ribbon:ribbon-transport:jar:2.2.4:runtime
        [INFO] |     |  |  |  +- io.reactivex:rxnetty-contexts:jar:0.4.9:runtime
        [INFO] |     |  |  |  \- io.reactivex:rxnetty-servo:jar:0.4.9:runtime
        [INFO] |     |  |  +- javax.inject:javax.inject:jar:1:runtime
        [INFO] |     |  |  \- io.reactivex:rxnetty:jar:0.4.9:runtime
        [INFO] |     |  |     +- io.netty:netty-codec-http:jar:4.0.27.Final:runtime
        [INFO] |     |  |     |  +- io.netty:netty-codec:jar:4.0.27.Final:runtime
        [INFO] |     |  |     |  \- io.netty:netty-handler:jar:4.0.27.Final:runtime
        [INFO] |     |  |     \- io.netty:netty-transport-native-epoll:jar:4.0.27.Final:runtime
        [INFO] |     |  |        +- io.netty:netty-common:jar:4.0.27.Final:runtime
        [INFO] |     |  |        +- io.netty:netty-buffer:jar:4.0.27.Final:runtime
        [INFO] |     |  |        \- io.netty:netty-transport:jar:4.0.27.Final:runtime
        [INFO] |     |  +- com.netflix.ribbon:ribbon-core:jar:2.2.4:compile
        [INFO] |     |  |  \- commons-lang:commons-lang:jar:2.6:compile
        [INFO] |     |  +- com.netflix.ribbon:ribbon-httpclient:jar:2.2.4:compile
        [INFO] |     |  |  +- commons-collections:commons-collections:jar:3.2.2:runtime
        [INFO] |     |  |  \- com.netflix.netflix-commons:netflix-commons-util:jar:0.1.1:runtime
        [INFO] |     |  \- com.netflix.ribbon:ribbon-loadbalancer:jar:2.2.4:compile
        [INFO] |     |     \- com.netflix.netflix-commons:netflix-statistics:jar:0.1.1:runtime
        [INFO] |     \- org.springframework.cloud:spring-cloud-starter-netflix-archaius:jar:1.4.0.RELEASE:compile
        [INFO] |        +- commons-configuration:commons-configuration:jar:1.8:compile
        [INFO] |        \- com.google.guava:guava:jar:18.0:compile
        [INFO] +- org.springframework.cloud:spring-cloud-starter-eureka:jar:1.4.0.RELEASE:compile
        [INFO] |  \- org.springframework.cloud:spring-cloud-starter-netflix-eureka-client:jar:1.4.0.RELEASE:compile
        [INFO] |     +- org.springframework.cloud:spring-cloud-netflix-eureka-client:jar:1.4.0.RELEASE:compile
        [INFO] |     +- com.netflix.eureka:eureka-client:jar:1.7.0:compile
        [INFO] |     |  +- org.codehaus.jettison:jettison:jar:1.3.7:runtime
        [INFO] |     |  |  \- stax:stax-api:jar:1.0.1:runtime
        [INFO] |     |  +- com.netflix.netflix-commons:netflix-eventbus:jar:0.3.0:runtime
        [INFO] |     |  |  +- com.netflix.netflix-commons:netflix-infix:jar:0.3.0:runtime
        [INFO] |     |  |  |  +- commons-jxpath:commons-jxpath:jar:1.3:runtime
        [INFO] |     |  |  |  +- joda-time:joda-time:jar:2.9.9:runtime
        [INFO] |     |  |  |  +- org.antlr:antlr-runtime:jar:3.4:runtime
        [INFO] |     |  |  |  |  +- org.antlr:stringtemplate:jar:3.2.1:runtime
        [INFO] |     |  |  |  |  \- antlr:antlr:jar:2.7.7:runtime
        [INFO] |     |  |  |  \- com.google.code.gson:gson:jar:2.8.2:runtime
        [INFO] |     |  |  \- org.apache.commons:commons-math:jar:2.2:runtime
        [INFO] |     |  +- javax.ws.rs:jsr311-api:jar:1.1.1:runtime
        [INFO] |     |  +- com.netflix.servo:servo-core:jar:0.10.1:runtime
        [INFO] |     |  |  \- com.netflix.servo:servo-internal:jar:0.10.1:runtime
        [INFO] |     |  +- com.sun.jersey:jersey-core:jar:1.19.1:runtime
        [INFO] |     |  +- com.sun.jersey:jersey-client:jar:1.19.1:runtime
        [INFO] |     |  +- com.sun.jersey.contribs:jersey-apache-client4:jar:1.19.1:runtime
        [INFO] |     |  \- com.google.inject:guice:jar:4.1.0:runtime
        [INFO] |     +- com.netflix.eureka:eureka-core:jar:1.7.0:compile
        [INFO] |     |  \- org.codehaus.woodstox:woodstox-core-asl:jar:4.4.1:runtime
        [INFO] |     |     \- javax.xml.stream:stax-api:jar:1.0-2:runtime
        [INFO] |     +- com.netflix.ribbon:ribbon-eureka:jar:2.2.4:compile
        [INFO] |     \- com.thoughtworks.xstream:xstream:jar:1.4.9:compile
        [INFO] |        +- xmlpull:xmlpull:jar:1.1.3.1:compile
        [INFO] |        \- xpp3:xpp3_min:jar:1.1.4c:compile
        [INFO] +- org.springframework.boot:spring-boot-starter-data-mongodb:jar:1.5.9.RELEASE:compile
        [INFO] |  +- org.mongodb:mongodb-driver:jar:3.4.3:compile
        [INFO] |  |  +- org.mongodb:mongodb-driver-core:jar:3.4.3:compile
        [INFO] |  |  \- org.mongodb:bson:jar:3.4.3:compile
        [INFO] |  \- org.springframework.data:spring-data-mongodb:jar:1.10.9.RELEASE:compile
        [INFO] |     +- org.springframework:spring-tx:jar:4.3.13.RELEASE:compile
        [INFO] |     +- org.springframework.data:spring-data-commons:jar:1.13.9.RELEASE:compile
        [INFO] |     \- org.slf4j:jcl-over-slf4j:jar:1.7.25:compile
        [INFO] +- org.springframework.cloud:spring-cloud-starter-bus-amqp:jar:1.3.2.RELEASE:compile
        [INFO] |  +- org.springframework.cloud:spring-cloud-starter-stream-rabbit:jar:1.3.0.RELEASE:compile
        [INFO] |  |  \- org.springframework.cloud:spring-cloud-stream-binder-rabbit:jar:1.3.0.RELEASE:compile
        [INFO] |  |     +- org.springframework.cloud:spring-cloud-stream-binder-rabbit-core:jar:1.3.0.RELEASE:compile
        [INFO] |  |     +- org.springframework.cloud:spring-cloud-stream-codec:jar:1.3.0.RELEASE:compile
        [INFO] |  |     +- org.springframework.boot:spring-boot-starter-amqp:jar:1.5.9.RELEASE:compile
        [INFO] |  |     |  \- org.springframework.amqp:spring-rabbit:jar:1.7.4.RELEASE:compile
        [INFO] |  |     |     +- com.rabbitmq:http-client:jar:1.1.1.RELEASE:compile
        [INFO] |  |     |     +- com.rabbitmq:amqp-client:jar:4.0.3:compile
        [INFO] |  |     |     \- org.springframework.amqp:spring-amqp:jar:1.7.4.RELEASE:compile
        [INFO] |  |     \- org.springframework.integration:spring-integration-amqp:jar:4.3.12.RELEASE:compile
        [INFO] |  \- org.springframework.cloud:spring-cloud-bus:jar:1.3.2.RELEASE:compile
        [INFO] |     +- org.springframework.cloud:spring-cloud-context:jar:1.3.0.RELEASE:compile
        [INFO] |     \- org.springframework.integration:spring-integration-core:jar:4.3.12.RELEASE:compile
        [INFO] +- org.springframework.cloud:spring-cloud-netflix-hystrix-stream:jar:1.4.0.RELEASE:compile
        [INFO] |  +- org.springframework.boot:spring-boot-starter-logging:jar:1.5.9.RELEASE:compile
        [INFO] |  |  +- ch.qos.logback:logback-classic:jar:1.1.11:compile
        [INFO] |  |  +- org.slf4j:jul-to-slf4j:jar:1.7.25:compile
        [INFO] |  |  \- org.slf4j:log4j-over-slf4j:jar:1.7.25:compile
        [INFO] |  +- org.springframework.cloud:spring-cloud-commons:jar:1.3.0.RELEASE:compile
        [INFO] |  |  +- org.springframework.security:spring-security-crypto:jar:4.2.3.RELEASE:compile
        [INFO] |  |  \- org.apache.httpcomponents:httpclient:jar:4.5.3:compile
        [INFO] |  |     \- org.apache.httpcomponents:httpcore:jar:4.4.8:compile
        [INFO] |  +- org.springframework.cloud:spring-cloud-netflix-core:jar:1.4.0.RELEASE:compile
        [INFO] |  +- org.springframework.cloud:spring-cloud-stream:jar:1.3.0.RELEASE:compile
        [INFO] |  |  +- org.springframework.boot:spring-boot-starter-validation:jar:1.5.9.RELEASE:compile
        [INFO] |  |  +- org.springframework:spring-messaging:jar:4.3.13.RELEASE:compile
        [INFO] |  |  +- org.springframework.integration:spring-integration-jmx:jar:4.3.12.RELEASE:compile
        [INFO] |  |  +- org.springframework:spring-tuple:jar:1.0.0.RELEASE:compile
        [INFO] |  |  |  \- com.esotericsoftware:kryo-shaded:jar:3.0.3:compile
        [INFO] |  |  |     \- com.esotericsoftware:minlog:jar:1.3.0:compile
        [INFO] |  |  +- org.springframework.integration:spring-integration-tuple:jar:1.0.0.RELEASE:compile
        [INFO] |  |  \- org.springframework.retry:spring-retry:jar:1.2.1.RELEASE:compile
        [INFO] |  +- com.fasterxml.jackson.core:jackson-databind:jar:2.8.10:compile
        [INFO] |  \- com.netflix.hystrix:hystrix-core:jar:1.5.12:compile
        [INFO] |     +- com.netflix.archaius:archaius-core:jar:0.7.4:compile
        [INFO] |     |  \- com.google.code.findbugs:jsr305:jar:3.0.1:runtime
        [INFO] |     +- io.reactivex:rxjava:jar:1.2.0:compile
        [INFO] |     \- org.hdrhistogram:HdrHistogram:jar:2.1.9:compile
        [INFO] +- de.flapdoodle.embed:de.flapdoodle.embed.mongo:jar:1.50.3:test
        [INFO] |  \- de.flapdoodle.embed:de.flapdoodle.embed.process:jar:1.50.2:test
        [INFO] |     +- commons-io:commons-io:jar:2.4:test
        [INFO] |     +- org.apache.commons:commons-lang3:jar:3.1:test
        [INFO] |     +- net.java.dev.jna:jna:jar:4.2.2:test
        [INFO] |     +- net.java.dev.jna:jna-platform:jar:4.2.2:test
        [INFO] |     \- org.apache.commons:commons-compress:jar:1.10:test
        [INFO] +- com.jayway.jsonpath:json-path:jar:2.2.0:test
        [INFO] |  +- net.minidev:json-smart:jar:2.2.1:test
        [INFO] |  |  \- net.minidev:accessors-smart:jar:1.1:test
        [INFO] |  |     \- org.ow2.asm:asm:jar:5.0.3:test
        [INFO] |  \- org.slf4j:slf4j-api:jar:1.7.25:compile
        [INFO] +- org.springframework.cloud:spring-cloud-starter-config:jar:1.4.0.RELEASE:compile
        [INFO] |  +- org.springframework.cloud:spring-cloud-starter:jar:1.3.0.RELEASE:compile
        [INFO] |  |  \- org.springframework.security:spring-security-rsa:jar:1.0.3.RELEASE:compile
        [INFO] |  \- org.springframework.cloud:spring-cloud-config-client:jar:1.4.0.RELEASE:compile
        [INFO] +- org.springframework.boot:spring-boot-starter-web:jar:1.5.9.RELEASE:compile
        [INFO] |  +- org.springframework.boot:spring-boot-starter-tomcat:jar:1.5.9.RELEASE:compile
        [INFO] |  |  +- org.apache.tomcat.embed:tomcat-embed-core:jar:8.5.23:compile
        [INFO] |  |  |  \- org.apache.tomcat:tomcat-annotations-api:jar:8.5.23:compile
        [INFO] |  |  +- org.apache.tomcat.embed:tomcat-embed-el:jar:8.5.23:compile
        [INFO] |  |  \- org.apache.tomcat.embed:tomcat-embed-websocket:jar:8.5.23:compile
        [INFO] |  +- org.hibernate:hibernate-validator:jar:5.3.6.Final:compile
        [INFO] |  |  +- javax.validation:validation-api:jar:1.1.0.Final:compile
        [INFO] |  |  +- org.jboss.logging:jboss-logging:jar:3.3.1.Final:compile
        [INFO] |  |  \- com.fasterxml:classmate:jar:1.3.4:compile
        [INFO] |  \- org.springframework:spring-web:jar:4.3.13.RELEASE:compile
        [INFO] +- org.springframework.boot:spring-boot-starter-hateoas:jar:1.5.9.RELEASE:compile
        [INFO] |  +- org.springframework.hateoas:spring-hateoas:jar:0.23.0.RELEASE:compile
        [INFO] |  \- org.springframework.plugin:spring-plugin-core:jar:1.2.0.RELEASE:compile
        [INFO] +- org.springframework.boot:spring-boot-starter-actuator:jar:1.5.9.RELEASE:compile
        [INFO] |  \- org.springframework.boot:spring-boot-actuator:jar:1.5.9.RELEASE:compile
        [INFO] +- org.springframework.cloud:spring-cloud-starter-sleuth:jar:1.3.0.RC1:compile
        [INFO] |  +- org.springframework.boot:spring-boot-starter-aop:jar:1.5.9.RELEASE:compile
        [INFO] |  |  \- org.aspectj:aspectjweaver:jar:1.8.13:compile
        [INFO] |  \- org.springframework.cloud:spring-cloud-sleuth-core:jar:1.3.0.RELEASE:compile
        [INFO] |     \- org.aspectj:aspectjrt:jar:1.8.13:compile
        [INFO] +- org.springframework.cloud:spring-cloud-sleuth-zipkin2:jar:1.3.0.RC1:compile
        [INFO] |  +- io.zipkin.zipkin2:zipkin:jar:2.3.1:compile
        [INFO] |  +- io.zipkin.reporter2:zipkin-reporter:jar:2.1.4:compile
        [INFO] |  +- io.zipkin.reporter2:zipkin-sender-kafka11:jar:2.1.4:compile
        [INFO] |  \- io.zipkin.reporter2:zipkin-sender-amqp-client:jar:2.1.4:compile
        [INFO] +- net.logstash.logback:logstash-logback-encoder:jar:4.7:compile
        [INFO] |  \- ch.qos.logback:logback-core:jar:1.1.11:compile
        [INFO] +- com.fasterxml.jackson.dataformat:jackson-dataformat-xml:jar:2.8.10:compile
        [INFO] |  +- com.fasterxml.jackson.core:jackson-core:jar:2.8.10:compile
        [INFO] |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.8.0:compile
        [INFO] |  +- com.fasterxml.jackson.module:jackson-module-jaxb-annotations:jar:2.8.10:compile
        [INFO] |  +- org.codehaus.woodstox:stax2-api:jar:3.1.4:compile
        [INFO] |  \- com.fasterxml.woodstox:woodstox-core:jar:5.0.3:compile
        [INFO] +- org.projectlombok:lombok:jar:1.16.18:compile
        [INFO] \- org.springframework.boot:spring-boot-starter-test:jar:1.5.9.RELEASE:test
        [INFO]    +- org.springframework.boot:spring-boot-test:jar:1.5.9.RELEASE:test
        [INFO]    +- org.springframework.boot:spring-boot-test-autoconfigure:jar:1.5.9.RELEASE:test
        [INFO]    +- junit:junit:jar:4.12:test
        [INFO]    +- org.assertj:assertj-core:jar:2.6.0:test
        [INFO]    +- org.mockito:mockito-core:jar:1.10.19:test
        [INFO]    |  \- org.objenesis:objenesis:jar:2.1:compile
        [INFO]    +- org.hamcrest:hamcrest-core:jar:1.3:test
        [INFO]    +- org.hamcrest:hamcrest-library:jar:1.3:test
        [INFO]    +- org.skyscreamer:jsonassert:jar:1.4.0:test
        [INFO]    |  \- com.vaadin.external.google:android-json:jar:0.0.20131108.vaadin1:test
        [INFO]    \- org.springframework:spring-test:jar:4.3.13.RELEASE:test
```

**Comment by spencergibb** [comment]
Have you included `spring-cloud-starter-netflix-hystrix`?

**Comment by dcuenot** [comment]
Nope :( I forgot this one.
Problem solved! Thanks for your help

**Comment by energister** [comment]
Note that according to the [Edgware release notes](https://github.com/spring-projects/spring-cloud/wiki/Spring-Cloud-Edgware-Release-Notes) `spring-cloud-starter-feign` has been replaced by `spring-cloud-starter-openfeign`

**Comment by energister** [comment]
Looks like the exception occurs because of the `spring-cloud-starter-openfeign` presence among dependencies
