### ISSUE TITLE
Forwarding error/Connection pool issue

### ISSUE THREAD

**Issue by ccit-spence** [spring-cloud/spring-cloud-netflix#262]
Receiving this error from Zuul when trying to access a fairly chatty service (Spring Boot Admin).  I can access the service directly.  Was working fine showed up after a few days and will not work anymore. 

I am seeing this error in the logs of Zuul:

```
2015-03-18 04:34:03.737  WARN 966 --- [http-nio-80-exec-9] o.s.c.n.z.filters.post.SendErrorFilter   : Error during filtering

com.netflix.zuul.exception.ZuulException: Forwarding error
	at org.springframework.cloud.netflix.zuul.filters.route.RibbonRoutingFilter.forward(RibbonRoutingFilter.java:146)
	at org.springframework.cloud.netflix.zuul.filters.route.RibbonRoutingFilter.run(RibbonRoutingFilter.java:110)
	at com.netflix.zuul.ZuulFilter.runFilter(ZuulFilter.java:112)
	at com.netflix.zuul.FilterProcessor.processZuulFilter(FilterProcessor.java:197)
	at com.netflix.zuul.FilterProcessor.runFilters(FilterProcessor.java:161)
	at com.netflix.zuul.FilterProcessor.route(FilterProcessor.java:120)
	at com.netflix.zuul.ZuulRunner.route(ZuulRunner.java:84)
	at com.netflix.zuul.http.ZuulServlet.route(ZuulServlet.java:111)
	at com.netflix.zuul.http.ZuulServlet.service(ZuulServlet.java:77)
	at org.springframework.web.servlet.mvc.ServletWrappingController.handleRequestInternal(ServletWrappingController.java:158)
	at org.springframework.cloud.netflix.zuul.web.ZuulController.handleRequestInternal(ZuulController.java:43)
	at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:146)
	at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:50)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:943)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:877)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:966)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:868)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:644)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:842)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:725)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.springframework.boot.actuate.autoconfigure.EndpointWebMvcAutoConfiguration$ApplicationContextHeaderFilter.doFilterInternal(EndpointWebMvcAutoConfiguration.java:291)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at de.codecentric.boot.admin.web.EndpointCorsFilter.doFilterInternal(EndpointCorsFilter.java:63)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:77)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:102)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.springframework.boot.actuate.autoconfigure.MetricFilterAutoConfiguration$MetricsFilter.doFilterInternal(MetricFilterAutoConfiguration.java:90)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:516)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1086)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:659)
	at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:223)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1558)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1515)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.netflix.hystrix.exception.HystrixRuntimeException: boot-adminRibbonCommand failed and no fallback available.
	at com.netflix.hystrix.AbstractCommand$20.call(AbstractCommand.java:816)
	at com.netflix.hystrix.AbstractCommand$20.call(AbstractCommand.java:798)
	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$1.onError(OperatorOnErrorResumeNextViaFunction.java:77)
	at rx.internal.operators.OperatorDoOnEach$1.onError(OperatorDoOnEach.java:70)
	at rx.internal.operators.OperatorDoOnEach$1.onError(OperatorDoOnEach.java:70)
	at rx.Observable$ThrowObservable$1.call(Observable.java:9058)
	at rx.Observable$ThrowObservable$1.call(Observable.java:9048)
	at rx.Observable.unsafeSubscribe(Observable.java:7304)
	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$1.onError(OperatorOnErrorResumeNextViaFunction.java:78)
	at rx.internal.operators.OperatorMap$1.onError(OperatorMap.java:49)
	at com.netflix.hystrix.HystrixCommand$2.call(HystrixCommand.java:318)
	at com.netflix.hystrix.HystrixCommand$2.call(HystrixCommand.java:310)
	at rx.Observable$1.call(Observable.java:145)
	at rx.Observable$1.call(Observable.java:137)
	at rx.Observable$1.call(Observable.java:145)
	at rx.Observable$1.call(Observable.java:137)
	at rx.Observable$1.call(Observable.java:145)
	at rx.Observable$1.call(Observable.java:137)
	at rx.Observable$1.call(Observable.java:145)
	at rx.Observable$1.call(Observable.java:137)
	at rx.Observable$1.call(Observable.java:145)
	at rx.Observable$1.call(Observable.java:137)
	at rx.Observable$1.call(Observable.java:145)
	at rx.Observable$1.call(Observable.java:137)
	at rx.Observable$1.call(Observable.java:145)
	at rx.Observable$1.call(Observable.java:137)
	at rx.Observable.unsafeSubscribe(Observable.java:7304)
	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$1.onError(OperatorOnErrorResumeNextViaFunction.java:78)
	at rx.internal.operators.OperatorDoOnEach$1.onError(OperatorDoOnEach.java:70)
	at rx.internal.operators.OperatorMap$1.onError(OperatorMap.java:49)
	at com.netflix.hystrix.AbstractCommand$HystrixObservableTimeoutOperator$3.onError(AbstractCommand.java:995)
	at rx.internal.operators.OperatorDoOnEach$1.onError(OperatorDoOnEach.java:70)
	at rx.internal.operators.OperatorDoOnEach$1.onError(OperatorDoOnEach.java:70)
	at rx.Observable$ThrowObservable$1.call(Observable.java:9058)
	at rx.Observable$ThrowObservable$1.call(Observable.java:9048)
	at rx.Observable.unsafeSubscribe(Observable.java:7304)
	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$1.onError(OperatorOnErrorResumeNextViaFunction.java:78)
	at rx.internal.operators.OperatorMap$1.onError(OperatorMap.java:49)
	at com.netflix.hystrix.HystrixCommand$1.call(HystrixCommand.java:301)
	at com.netflix.hystrix.HystrixCommand$1.call(HystrixCommand.java:293)
	at rx.Observable$1.call(Observable.java:145)
	at rx.Observable$1.call(Observable.java:137)
	at rx.Observable$1.call(Observable.java:145)
	at rx.Observable$1.call(Observable.java:137)
	at rx.Observable$1.call(Observable.java:145)
	at rx.Observable$1.call(Observable.java:137)
	at rx.Observable$1.call(Observable.java:145)
	at rx.Observable$1.call(Observable.java:137)
	at rx.Observable$1.call(Observable.java:145)
	at rx.Observable$1.call(Observable.java:137)
	at rx.Observable$1.call(Observable.java:145)
	at rx.Observable$1.call(Observable.java:137)
	at rx.Observable$1.call(Observable.java:145)
	at rx.Observable$1.call(Observable.java:137)
	at rx.Observable$1.call(Observable.java:145)
	at rx.Observable$1.call(Observable.java:137)
	at rx.Observable$1.call(Observable.java:145)
	at rx.Observable$1.call(Observable.java:137)
	at rx.Observable$1.call(Observable.java:145)
	at rx.Observable$1.call(Observable.java:137)
	at rx.Observable$1.call(Observable.java:145)
	at rx.Observable$1.call(Observable.java:137)
	at rx.Observable$1.call(Observable.java:145)
	at rx.Observable$1.call(Observable.java:137)
	at rx.Observable.unsafeSubscribe(Observable.java:7304)
	at com.netflix.hystrix.AbstractCommand$1.call(AbstractCommand.java:388)
	at com.netflix.hystrix.AbstractCommand$1.call(AbstractCommand.java:368)
	at rx.Observable$1.call(Observable.java:145)
	at rx.Observable$1.call(Observable.java:137)
	at rx.Observable$1.call(Observable.java:145)
	at rx.Observable$1.call(Observable.java:137)
	at rx.Observable.unsafeSubscribe(Observable.java:7304)
	at com.netflix.hystrix.AbstractCommand$ObservableCommand$1.call(AbstractCommand.java:1097)
	at com.netflix.hystrix.AbstractCommand$ObservableCommand$1.call(AbstractCommand.java:1093)
	at rx.Observable$1.call(Observable.java:145)
	at rx.Observable$1.call(Observable.java:137)
	at rx.Observable.subscribe(Observable.java:7393)
	at rx.internal.operators.BlockingOperatorToFuture.toFuture(BlockingOperatorToFuture.java:57)
	at rx.observables.BlockingObservable.toFuture(BlockingObservable.java:409)
	at com.netflix.hystrix.HystrixCommand.queue(HystrixCommand.java:385)
	at com.netflix.hystrix.HystrixCommand.execute(HystrixCommand.java:339)
	at org.springframework.cloud.netflix.zuul.filters.route.RibbonRoutingFilter.forward(RibbonRoutingFilter.java:130)
	... 64 common frames omitted
Caused by: com.netflix.client.ClientException: null
	at com.netflix.client.AbstractLoadBalancerAwareClient.executeWithLoadBalancer(AbstractLoadBalancerAwareClient.java:123)
	at com.netflix.client.AbstractLoadBalancerAwareClient.executeWithLoadBalancer(AbstractLoadBalancerAwareClient.java:81)
	at org.springframework.cloud.netflix.zuul.filters.route.RibbonCommand.forward(RibbonCommand.java:129)
	at org.springframework.cloud.netflix.zuul.filters.route.RibbonCommand.run(RibbonCommand.java:103)
	at org.springframework.cloud.netflix.zuul.filters.route.RibbonCommand.run(RibbonCommand.java:48)
	at com.netflix.hystrix.HystrixCommand$1.call(HystrixCommand.java:298)
	... 107 common frames omitted
Caused by: org.apache.http.conn.ConnectionPoolTimeoutException: Timeout waiting for connection from pool
	at org.apache.http.impl.conn.tsccm.ConnPoolByRoute.getEntryBlocking(ConnPoolByRoute.java:412)
	at com.netflix.http4.NamedConnectionPool.getEntryBlocking(NamedConnectionPool.java:141)
	at org.apache.http.impl.conn.tsccm.ConnPoolByRoute$1.getPoolEntry(ConnPoolByRoute.java:298)
	at org.apache.http.impl.conn.tsccm.ThreadSafeClientConnManager$1.getConnection(ThreadSafeClientConnManager.java:238)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:423)
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:863)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:115)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
	at com.sun.jersey.client.apache4.ApacheHttpClient4Handler.handle(ApacheHttpClient4Handler.java:170)
	at com.sun.jersey.api.client.Client.handle(Client.java:648)
	at com.sun.jersey.api.client.WebResource.handle(WebResource.java:680)
	at com.sun.jersey.api.client.WebResource.access$200(WebResource.java:74)
	at com.sun.jersey.api.client.WebResource$Builder.post(WebResource.java:568)
	at com.netflix.niws.client.http.RestClient.execute(RestClient.java:621)
	at com.netflix.niws.client.http.RestClient.execute(RestClient.java:527)
	at com.netflix.niws.client.http.RestClient.execute(RestClient.java:92)
	at com.netflix.client.AbstractLoadBalancerAwareClient$1.call(AbstractLoadBalancerAwareClient.java:109)
	at com.netflix.loadbalancer.reactive.LoadBalancerCommand$3$1.call(LoadBalancerCommand.java:303)
	at com.netflix.loadbalancer.reactive.LoadBalancerCommand$3$1.call(LoadBalancerCommand.java:287)
	at rx.internal.operators.OperatorMap$1.onNext(OperatorMap.java:55)
	at rx.internal.util.ScalarSynchronousObservable$1.call(ScalarSynchronousObservable.java:41)
	at rx.internal.util.ScalarSynchronousObservable$1.call(ScalarSynchronousObservable.java:30)
	at rx.Observable$1.call(Observable.java:145)
	at rx.Observable$1.call(Observable.java:137)
	at rx.Observable$1.call(Observable.java:145)
	at rx.Observable$1.call(Observable.java:137)
	at rx.Observable.unsafeSubscribe(Observable.java:7304)
	at rx.internal.operators.OperatorConcat$ConcatSubscriber.subscribeNext(OperatorConcat.java:163)
	at rx.internal.operators.OperatorConcat$ConcatSubscriber.onNext(OperatorConcat.java:128)
	at rx.internal.operators.OperatorConcat$ConcatSubscriber.onNext(OperatorConcat.java:65)
	at rx.internal.operators.OperatorMap$1.onNext(OperatorMap.java:55)
	at com.netflix.loadbalancer.reactive.LoadBalancerCommand$1.call(LoadBalancerCommand.java:185)
	at com.netflix.loadbalancer.reactive.LoadBalancerCommand$1.call(LoadBalancerCommand.java:180)
	at rx.Observable$1.call(Observable.java:145)
	at rx.Observable$1.call(Observable.java:137)
	at rx.Observable$1.call(Observable.java:145)
	at rx.Observable$1.call(Observable.java:137)
	at rx.Observable.unsafeSubscribe(Observable.java:7304)
	at rx.internal.operators.OperatorRetryWithPredicate$SourceSubscriber$1.call(OperatorRetryWithPredicate.java:112)
	at rx.schedulers.TrampolineScheduler$InnerCurrentThreadScheduler.enqueue(TrampolineScheduler.java:81)
	at rx.schedulers.TrampolineScheduler$InnerCurrentThreadScheduler.schedule(TrampolineScheduler.java:59)
	at rx.internal.operators.OperatorRetryWithPredicate$SourceSubscriber.onNext(OperatorRetryWithPredicate.java:77)
	at rx.internal.operators.OperatorRetryWithPredicate$SourceSubscriber.onNext(OperatorRetryWithPredicate.java:45)
	at rx.internal.util.ScalarSynchronousObservable$1.call(ScalarSynchronousObservable.java:41)
	at rx.internal.util.ScalarSynchronousObservable$1.call(ScalarSynchronousObservable.java:30)
	at rx.Observable$1.call(Observable.java:145)
	at rx.Observable$1.call(Observable.java:137)
	at rx.Observable$1.call(Observable.java:145)
	at rx.Observable$1.call(Observable.java:137)
	at rx.Observable$1.call(Observable.java:145)
	at rx.Observable$1.call(Observable.java:137)
	at rx.Observable.subscribe(Observable.java:7393)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:441)
	at rx.observables.BlockingObservable.single(BlockingObservable.java:340)
	at com.netflix.client.AbstractLoadBalancerAwareClient.executeWithLoadBalancer(AbstractLoadBalancerAwareClient.java:102)
	... 112 common frames omitted
```

**Comment by ccit-spence** [comment]
Side note: restarting the instance that runs Zuul solved the problem.  Could this be a leak of some sort?

**Comment by dsyer** [comment]
Could be a leak, but the stack trace is deep into Netflix and Apache code, so we're going to need more data to pin it down. Try monitoring the `counter.servo.discoveryclient*` values in /metrics.

**Comment by ccit-spence** [comment]
Here is what I see now, will post another snapshot of the values in around 12hrs  Below are the only metrics that are high compared to others.

`counter.servo.discoveryclient-httpclient_release = 3407`
`counter.servo.discoveryclient-httpclient_request = 3407`
`counter.servo.discoveryclient-httpclient_reuse = 3360`

Another high one is this

`counter.servo.boot-admin_release = 31295`
`counter.servo.boot-admin_request = 31295`
`counter.servo.boot-admin_reuse = 30966`

`counter.status.201.boot-admin.star-star = 28905`

**Comment by ccit-spence** [comment]
Latest Stats, all other counters are low.

counter.servo.discoveryclient-httpclient_release = 5529
counter.servo.discoveryclient-httpclient_request = 5529
counter.servo.discoveryclient-httpclient_reuse = 5461

counter.servo.boot-admin_release = 61759
counter.servo.boot-admin_request = 61759
counter.servo.boot-admin_reuse = 61120

counter.status.201.boot-admin.star-star = 58920

**Comment by dsyer** [comment]
That looks pretty normal to me. It would be useful to know what those metrics are when a request fails.

**Comment by ccit-spence** [comment]
Closing this issue since Spring Boot Admin has changed how request are made to the endpoints.  I can't reproduce the problem anymore.

**Comment by agupta1989** [comment]
@ccit-spence Can you share your configuration for zuul ? I mean what was the ```zuul.max.host.connections``` ? FYI I am trying to tackle the solution for the same issue.
