### ISSUE TITLE
Passive health eureka and zuul.

### ISSUE THREAD

**Issue by gmobi-github** [spring-cloud/spring-cloud-netflix#2690]
When two nodes handling request via zuul with ribbon load balancer enabled.
if one fallout system will respond to 
java.net.SocketException: Socket closed

Can I add passive health check so that I can close the node gracefully ?

here is my application.yml
```
info:
  component: Edge Server
  
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

zuul:
  prefix: /api
  routes:
    account: 
      path: /account/**
      serviceId: account-service
    customer: 
      path: /customer/**
      serviceId: customer-service          

ribbon:
  eureka:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:18761/eureka/
    registerWithEureka: false
      
server:
  port: 8765

logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG
```

**Comment by ryanjbaxter** [comment]
Please learn how to [format code on GitHub](https://help.github.com/articles/creating-and-highlighting-code-blocks/).

What has two nodes? Zuul?  Where is the socket timeout coming from?

**Comment by gmobi-github** [comment]
I have below setup.
[GITHUB](https://github.com/piomin/sample-spring-microservices.git)
![image](https://user-images.githubusercontent.com/35562271/35467977-2878a554-033c-11e8-9165-aeb11dcc490d.png)

Now account service has two instances running. 
And I am running load test account service URL http://localhost:8765/api/account/accounts.
if shutdown one instance of account service I will start getting for some time. That means ribbon
still passing request to killed instance, how I can avoid this.

```
java.net.SocketException: Socket closed
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at org.apache.http.impl.io.AbstractSessionInputBuffer.fillBuffer(AbstractSessionInputBuffer.java:158)
	at org.apache.http.impl.io.SocketInputBuffer.fillBuffer(SocketInputBuffer.java:82)
	at org.apache.http.impl.io.AbstractSessionInputBuffer.readLine(AbstractSessionInputBuffer.java:271)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:138)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
	at org.apache.http.impl.AbstractHttpClientConnection.receiveResponseHeader(AbstractHttpClientConnection.java:281)
	at org.apache.http.impl.conn.DefaultClientConnection.receiveResponseHeader(DefaultClientConnection.java:257)
	at org.apache.jmeter.protocol.http.sampler.hc.ManagedClientConnectionImpl.receiveResponseHeader(ManagedClientConnectionImpl.java:199)
	at org.apache.jmeter.protocol.http.sampler.MeasuringConnectionManager$MeasuredConnection.receiveResponseHeader(MeasuringConnectionManager.java:212)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
	at org.apache.http.impl.client.DefaultRequestDirector.tryExecute(DefaultRequestDirector.java:684)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:486)
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:835)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.jmeter.protocol.http.sampler.HTTPHC4Impl.executeRequest(HTTPHC4Impl.java:654)
	at org.apache.jmeter.protocol.http.sampler.HTTPHC4Impl.sample(HTTPHC4Impl.java:413)
	at org.apache.jmeter.protocol.http.sampler.HTTPSamplerProxy.sample(HTTPSamplerProxy.java:74)
	at org.apache.jmeter.protocol.http.sampler.HTTPSamplerBase.sample(HTTPSamplerBase.java:1189)
	at org.apache.jmeter.protocol.http.sampler.HTTPSamplerBase.sample(HTTPSamplerBase.java:1178)
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:491)
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:425)
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:254)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by ryanjbaxter** [comment]
This makes sense because when you shut down an instance of `account service` depending on how the service is "shut down" Eureka will remove the instance from the registry.  However Zuul wont know that the instance has been removed until it refreshed the data from the service discovery service so Zuul will continue to send requests to the removed instance.  If you are using Ribbon in combination with Zuul, which it appears you are, you can configure Ribbon within Zuul to retry failed requests so it will retry any failed request.  You can also use Hystrix fallbacks as the ultimate protection from any failure.

**Comment by gmobi-github** [comment]
Hi Below is my application.yml for gateway service
```
info:
  component: ProGate Service Gateway
  
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

zuul:
  prefix: /asg
  routes:
    progate-business-service: 
      path: /bs/**
      serviceId: progate-business-service
    progate-messaging-service: 
      path: /ms/**
      serviceId: progate-messaging-service          
    progate-reporting-service: 
      path: /rs/**
      serviceId: progate-reporting-service   
ribbon:
  eureka:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:18761}/eureka/
    registerWithEureka: false
      
server:
  port: 8765

logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG
```
I only want to retry socket exception or socket connect-time out. I am using Edgware.RELEASE.
Do I have to add org.springframework.retry:spring-retry dependency to enable it?

**Comment by ryanjbaxter** [comment]
Yes you need to add spring retry as a dependency, it must be on the classpath.  Also set `zuul.retryable` to `true`.  You can then configure the number of times a service will be retried by setting `client.ribbon.MaxAutoRetries`, `client.ribbon.MaxAutoRetriesNextServer`, and `client.ribbon.OkToRetryOnAllOperations`, where `client` is the `serviceId`.

**Comment by gmobi-github** [comment]
All these retry will happen on socket exception or socket connect-time out right? not on client side read timeout right?

**Comment by ryanjbaxter** [comment]
Should happen on socket or read timeouts

**Comment by gmobi-github** [comment]
Can we avoid retry on read timeout  when connection closed by client due high response time of service?

**Comment by ryanjbaxter** [comment]
Possibly, this is something I havent tried yet so I am not 100% sure.  You could try creating a bean of type `LoadBalancedRetryListenerFactory` and return an array of `RetryListener` for your service.  In `RetryListener.onError` you will be passed a `Throwable` which should be the error and the `RetryContext`.  If the error is a read timeout than you should be able to cast the `RetryContext` to an instance of `RetryContextSupport` and call `setExhaustedOnly` which will stop the retries from happening.  Again I havent tried this myself, but it seems like it might work.

**Comment by gmobi-github** [comment]
Okay, I will implement and test, If I have to set read time out. Where I set in my application.yml ?
```
ribbon:
  eureka:
    enabled: true
  ReadTimeout=3000
```

If i set like above will spring boot respect my above config?

**Comment by ryanjbaxter** [comment]
Both configurations are correct as far as setting the `ReadTimeout`, however each one sets other properties as well.

**Comment by spencergibb** [comment]
Closing this due to inactivity. Please re-open if there's more to discuss.

**Comment by shubhanshushukla** [comment]
Hi Ryan,
I have implemented your below suggestion:

`Possibly, this is something I havent tried yet so I am not 100% sure. You could try creating a bean of type LoadBalancedRetryListenerFactory and return an array of RetryListener for your service. In RetryListener.onError you will be passed a Throwable which should be the error and the RetryContext. If the error is a read timeout than you should be able to cast the RetryContext to an instance of RetryContextSupport and call setExhaustedOnly which will stop the retries from happening. Again I havent tried this myself, but it seems like it might work.`

On very first request I am getting error 
` Retry terminated abnormally by interceptor before first attempt`
Here is my RetryListener

```
public class ProGateRetryListener implements RetryListener
{

	@Override
	public <T, E extends Throwable> void close(RetryContext arg0, RetryCallback<T, E> arg1, Throwable arg2)
	{
		// TODO Auto-generated method stub
		
	}

	@Override
	public <T, E extends Throwable> void onError(RetryContext retryContext, RetryCallback<T, E> arg1, Throwable throwable)
	{
		if (retryContext!=null && retryContext instanceof RetryContextSupport)
		{
			((RetryContextSupport)retryContext).setExhaustedOnly();
		}
 		
	}

	@Override
	public <T, E extends Throwable> boolean open(RetryContext arg0, RetryCallback<T, E> arg1)
	{
		// TODO Auto-generated method stub
		return false;
	}

}

```

**Comment by ryanjbaxter** [comment]
What are you trying to accomplish?
