### ISSUE TITLE
NullPointerException PeerRegistry: Eureka Server on JBoss EAP

### ISSUE THREAD

**Issue by MichaelWMerritt** [spring-cloud/spring-cloud-netflix#2694]
Hello, I am having a strange issue with my Eureka server running on JBoss EAP.  Eureka runs and is accessible via browser.  It shows all of my services registered.  However, in my logs I am getting the below listed exception.  My configuration is very simple and also listed below.  I am using the Edgware.RELEASE version.

```
09:10:17,939 ERROR [com.netflix.eureka.registry.PeerAwareInstanceRegistryImpl] (ReplicaAwareInstanceRegistry - RenewalThresholdUpdater) Cannot update renewal threshold: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'eurekaClientConfigBean' defined in class path resource [org/springframework/cloud/netflix/eureka/EurekaClientAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.cloud.netflix.eureka.EurekaClientConfigBean]: Factory method 'eurekaClientConfigBean' threw exception; nested exception is java.lang.NullPointerException
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:599)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1173)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1067)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:513)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1138)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1066)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:835)
	at org.springframework.beans.factory.support.ConstructorResolver.resolvePreparedArguments(ConstructorResolver.java:785)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:415)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1173)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1067)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:513)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
	at org.springframework.beans.factory.support.AbstractBeanFactory$2.getObject(AbstractBeanFactory.java:345)
	at org.springframework.cloud.context.scope.GenericScope$BeanLifecycleWrapper.getBean(GenericScope.java:379)
	at org.springframework.cloud.context.scope.GenericScope.get(GenericScope.java:181)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:340)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.aop.target.SimpleBeanTargetSource.getTarget(SimpleBeanTargetSource.java:35)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:192)
	at com.sun.proxy.$Proxy251.getApplications(Unknown Source)
	at com.netflix.eureka.registry.PeerAwareInstanceRegistryImpl.updateRenewalThreshold(PeerAwareInstanceRegistryImpl.java:523)
	at com.netflix.eureka.registry.PeerAwareInstanceRegistryImpl.access$000(PeerAwareInstanceRegistryImpl.java:92)
	at com.netflix.eureka.registry.PeerAwareInstanceRegistryImpl$2.run(PeerAwareInstanceRegistryImpl.java:194)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.cloud.netflix.eureka.EurekaClientConfigBean]: Factory method 'eurekaClientConfigBean' threw exception; nested exception is java.lang.NullPointerException
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588)
	... 31 more
Caused by: java.lang.NullPointerException
	at io.undertow.servlet.spec.ServletContextImpl.getInitParameterNames(ServletContextImpl.java:379)
	at org.springframework.web.context.support.ServletContextPropertySource.getPropertyNames(ServletContextPropertySource.java:40)
	at org.springframework.core.env.EnumerablePropertySource.containsProperty(EnumerablePropertySource.java:63)
	at org.springframework.core.env.PropertySourcesPropertyResolver.containsProperty(PropertySourcesPropertyResolver.java:51)
	at org.springframework.core.env.AbstractEnvironment.containsProperty(AbstractEnvironment.java:522)
	at org.springframework.boot.bind.RelaxedPropertyResolver.getProperty(RelaxedPropertyResolver.java:83)
	at org.springframework.boot.bind.RelaxedPropertyResolver.getProperty(RelaxedPropertyResolver.java:64)
	at org.springframework.cloud.netflix.eureka.EurekaClientAutoConfiguration.eurekaClientConfigBean(EurekaClientAutoConfiguration.java:116)
	at org.springframework.cloud.netflix.eureka.EurekaClientAutoConfiguration$$EnhancerBySpringCGLIB$$25ab0ce1.CGLIB$eurekaClientConfigBean$4(<generated>)
	at org.springframework.cloud.netflix.eureka.EurekaClientAutoConfiguration$$EnhancerBySpringCGLIB$$25ab0ce1$$FastClassBySpringCGLIB$$e588f1d2.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:358)
	at org.springframework.cloud.netflix.eureka.EurekaClientAutoConfiguration$$EnhancerBySpringCGLIB$$25ab0ce1.eurekaClientConfigBean(<generated>)
	at sun.reflect.GeneratedMethodAccessor2166.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162)
	... 32 more
```

application.properties
```eureka.client.register-with-eureka=false
eureka.server.wait-time-in-ms-when-sync-empty=0
eureka.client.serviceUrl.defaultZone=http://<myUrl>/eureka/eureka
```

**Comment by ryanjbaxter** [comment]
Some of the stacktrace is cut off, could you fix that?

```
at org.springframework.cloud.netflix.eureka.EurekaClientAutoConfiguration.eurekaClientConfigBean(EurekaClientAutoConfigurat
        at org.springframework.cloud.netflix.eureka.EurekaClientAutoConfiguration$$EnhancerBySpringCGLIB$$e3ac8742.CGLIB$eurekaClie
        at org.springframework.cloud.netflix.eureka.EurekaClientAutoConfiguration$$EnhancerBySpringCGLIB$$e3ac8742$$FastClassBySpri
```

**Comment by MichaelWMerritt** [comment]
Sorry about that.  I have updated my initial with the full stack trace.

**Comment by spencergibb** [comment]
I'm not sure this is a spring cloud netflix issue.

```
	at io.undertow.servlet.spec.ServletContextImpl.getInitParameterNames(ServletContextImpl.java:379)
	at org.springframework.web.context.support.ServletContextPropertySource.getPropertyNames(ServletContextPropertySource.java:40)
	at org.springframework.core.env.EnumerablePropertySource.containsProperty(EnumerablePropertySource.java:63)
```

Maybe a spring framework issue? @rstoyanchev thoughts?

**Comment by rstoyanchev** [comment]
@spencergibb seems unlikely. The [Spring class](https://github.com/spring-projects/spring-framework/commits/master/spring-web/src/main/java/org/springframework/web/context/support/ServletContextPropertySource.java) is literally 2 lines of code and the NPE comes from Undertow so I'd suspect an issue there. 

Do we know what line exactly it's on? I can see the number but that doesn't help without looking at the right version of the source. I see an issue referenced [around that line](https://github.com/undertow-io/undertow/blob/d3965f1c080b48dd9232e90365596bc90739df10/servlet/src/main/java/io/undertow/servlet/spec/ServletContextImpl.java#L387-L388) in the latest source.

**Comment by spencergibb** [comment]
@MichaelWMerritt want to submit an undertow issue?

**Comment by MichaelWMerritt** [comment]
Thank you everyone for your input.  @rstoyanchev I don't believe that issue is related as the new source code doesn't match the line numbers and method name of the exception.  I believe I am using an older version of JBoss EAP.  I will investigate further and enter an issue with Undertow if necessary or open a new issue with a clearer question here.

**Comment by rstoyanchev** [comment]
Yes I suspected you probably have an older version of Undertow, but my point was to see the source line that causes the NPE and see if the latest code has that fixed.

**Comment by MichaelWMerritt** [comment]
While this might be an issue with Undertow it appears that I only get this error from my eureka server.  What I mean is that I have multiple Eureka clients deployed but the only eurekaClientConfigBean that fails to instantiate is the Eureka Server instance itself.  Is there a way for me to prevent the Eureka Server from trying to become a client as well?

**Comment by spencergibb** [comment]
@MichaelWMerritt what would you have spring cloud do? This happens in spring core.

**Comment by MichaelWMerritt** [comment]
I'm actually investigating further as I don't believe my last question is relevant.  What I have found is that the error right now starts from EurekaClientAutoConfiguration eurekaClientConfigBean() which uses the RelaxedPropertyResolver.  This is failing.  I am using the 1.4.3 version of the code, but looking at master shows the RelaxedPropertyResolver has been removed.  Is this potentially where the problem is coming from?

**Comment by spencergibb** [comment]
RelaxedPropertyResolver just goes into the spring environment, which in turn queries the servlet init properties. In 2.0 we just skip RelaxedPropertyResolver, the rest is the same.

**Comment by MichaelWMerritt** [comment]
Okay, that makes sense.  I think where I am confused is that the exception states it "Cannot update renewal threshold", however in the eureka UI it shows my thresholds appropriately and refreshes once new clients are registered.  What am I missing here?

**Comment by spencergibb** [comment]
I don't know what you are missing.

**Comment by MichaelWMerritt** [comment]
I meant what am I not understanding about how the thresholds and threshold renewal works.

**Comment by spencergibb** [comment]
Closing this due to inactivity. Please re-open if there's more to discuss.

**Comment by dibyendub** [comment]
Eureka service with a different port has been deployed in Wildfly 12 or Tomcat 8 with no error or exception but while running the eureka in browser gives me blank page. But eureka has been registered as a context root. Can you please help me regarding this.

**Comment by ryanjbaxter** [comment]
@dibyendub please dont comment on unrelated issues.  Typically the problem you are describing has to do with problems in your local environment.  Try clearing you maven repo and trying again.  If you are still having the problem please reach out on Gitter or open another issue.
