### ISSUE TITLE
#2483 causing NPE when no servers available for the load balancer

### ISSUE THREAD

**Issue by lchayoun** [spring-cloud/spring-cloud-netflix#2724]
The NPE is caused by the change in `AbstractRibbonCommand#run` method.
Before this change `this.client.executeWithLoadBalancer(request, config)` was always invoked, handling the case that no servers are available through `LoadBalancerContext#getServerFromLoadBalancer` method.

Stack Trace:
```
Caused by: java.lang.NullPointerException: null
	at org.springframework.cloud.netflix.ribbon.RibbonLoadBalancerClient$RibbonServer.getHost(RibbonLoadBalancerClient.java:169)
	at org.springframework.cloud.netflix.ribbon.apache.RetryableRibbonLoadBalancingHttpClient$1.doWithRetry(RetryableRibbonLoadBalancingHttpClient.java:129)
	at org.springframework.cloud.netflix.ribbon.apache.RetryableRibbonLoadBalancingHttpClient$1.doWithRetry(RetryableRibbonLoadBalancingHttpClient.java:119)
	at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:287)
	at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:180)
	at org.springframework.cloud.netflix.ribbon.apache.RetryableRibbonLoadBalancingHttpClient.executeWithRetry(RetryableRibbonLoadBalancingHttpClient.java:178)
	at org.springframework.cloud.netflix.ribbon.apache.RetryableRibbonLoadBalancingHttpClient.execute(RetryableRibbonLoadBalancingHttpClient.java:152)
	at org.springframework.cloud.netflix.ribbon.apache.RetryableRibbonLoadBalancingHttpClient.execute(RetryableRibbonLoadBalancingHttpClient.java:58)
	at org.springframework.cloud.netflix.zuul.filters.route.support.AbstractRibbonCommand.run(AbstractRibbonCommand.java:185)
	at org.springframework.cloud.netflix.zuul.filters.route.support.AbstractRibbonCommand.run(AbstractRibbonCommand.java:52)
	at com.netflix.hystrix.HystrixCommand$2.call(HystrixCommand.java:302)
	at com.netflix.hystrix.HystrixCommand$2.call(HystrixCommand.java:298)
	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:46)
	... 148 common frames omitted
```

**Comment by ezraroi** [comment]
Before SR2 release train we were getting a nice exception that says that there are no clients for the requested service... now it is NPE in the log :(

**Comment by ryanjbaxter** [comment]
@pway99 ^^^ sounds like an easy fix

**Comment by pway99** [comment]
@ryanjbaxter I will work on that now thanks!
