### ISSUE TITLE
Using Zuul and Ribbon to route to Hosts per Hostname

### ISSUE THREAD

**Issue by sattlerio** [spring-cloud/spring-cloud-netflix#2760]
Hi,

I have a Zuul / Ribbon Application which is deployed in a docker overlay network (which is actual not important for the question.
All hosts in the same docker network are available by there hostname. For example 

`$ ping APPLICATION_XY` 

would work with the name of the service because inside the same network they host_names are mapped to the containers private ip.
In my application config i have the following config:

```
auth:
  ribbon:
    listOfServers: 10.0.160.4:8000 #service_xy
   ServerListRefreshInterval: 15000

test:
  ribbon:
    listOfServers: service_xy:8000
    ServerListRefreshInterval: 15000

zuul:
  routes:
    users:
      path: /auth/**
      sensitiveHeaders: Cookie,Set-Cookie,Authorization
      serviceId: auth
    test:
      path: /test/**
      sensitiveHeaders: Cookie,Set-Cookie,Authorization
      serviceId: test
```

In auth i use the containers private ip and in test i use the name of the docker image ( where the containers has the ip from the hostname)
The route for users is working fine but for test it gives the follwoing errror:
```

	at com.netflix.hystrix.HystrixCommand.execute(HystrixCommand.java:334) ~[hystrix-core-1.5.2.jar!/:1.5.2]
	at org.springframework.cloud.netflix.zuul.filters.route.RibbonRoutingFilter.forward(RibbonRoutingFilter.java:126) ~[spring-cloud-netflix-core-1.1.0.RELEASE.jar!/:1.1.0.RELEASE]
	... 71 common frames omitted
Caused by: com.sun.jersey.api.client.ClientHandlerException: java.lang.IllegalArgumentException: Host name may not be null
	at com.sun.jersey.client.apache4.ApacheHttpClient4Handler.handle(ApacheHttpClient4Handler.java:187) ~[jersey-apache-client4-1.19.1.jar!/:1.19.1]

```

Why is it not possible to use the containers hostname?

Thanks
best

**Comment by legendjaks** [comment]
How are you deploying in the docker swarm? What is the endpoint-mode used? Share the command which is used for deployment. This is really important.

**Comment by spencergibb** [comment]
try a full url `http://service_xy:8000`

**Comment by spencergibb** [comment]
Oh, `service_xy` is not a valid hostname. URL classes in java can't use it.

**Comment by spencergibb** [comment]
Closing this due to inactivity. Please re-open if there's more to discuss.
