### ISSUE TITLE
 after the application is started, it will automatically crash during the running process

### ISSUE THREAD

**Issue by zhangxiangfeng** [spring-cloud/spring-cloud-netflix#2774]
# Question:

  `In the production environment, after the application is started, it will automatically crash during the running process. It is rather urgent and does not know what causes it. The 2.0.0.M2.jar used by eureka,`

### app's gradle:

```
compile 'org.springframework.cloud:spring-cloud-starter-feign:2.0.0.M2'
compile 'org.springframework.cloud:spring-cloud-starter-eureka:2.0.0.M2'
compile group: 'com.netflix.feign', name: 'feign-httpclient', version: '8.18.0'

```

### app's  yml:

```
feign:
  httpclient:
    enabled: true

```

# Log record

```
2018-03-13 14:49:17.547 [Thread-8] [] [X-UID-] INFO  org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext Closing org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@1b083826: startup date [Tue Mar 13 14:42:47 CST 2018]; parent: org.springframework.context.annotation.AnnotationConfigApplicationContext@5ebec15
2018-03-13 14:49:17.548 [Thread-8] [] [X-UID-] INFO  org.springframework.cloud.netflix.eureka.serviceregistry.EurekaServiceRegistry Unregistering application yidao-portal with eureka with status DOWN
2018-03-13 14:49:17.548 [Thread-8] [] [X-UID-] WARN  com.netflix.discovery.DiscoveryClient Saw local status change event StatusChangeEvent [timestamp=1520923757548, current=DOWN, previous=UP]
2018-03-13 14:49:17.549 [DiscoveryClient-InstanceInfoReplicator-0] [] [X-UID-] INFO  com.netflix.discovery.DiscoveryClient DiscoveryClient_YIDAO-PORTAL/172.19.150.216:yidao-portal:10011: registering service...
2018-03-13 14:49:17.551 [Thread-8] [] [X-UID-] INFO  org.springframework.context.support.DefaultLifecycleProcessor Stopping beans in phase 0
2018-03-13 14:49:17.551 [Thread-8] [] [X-UID-] INFO  com.kuaicto.framework.core.CoreLifecycle Application Destroy.
2018-03-13 14:49:17.552 [Thread-8] [] [X-UID-] INFO  org.springframework.jmx.export.annotation.AnnotationMBeanExporter Unregistering JMX-exposed beans on shutdown
2018-03-13 14:49:17.553 [Thread-12] [] [X-UID-] INFO  com.netflix.loadbalancer.PollingServerListUpdater Shutting down the Executor Pool for PollingServerListUpdater
2018-03-13 14:49:17.555 [Thread-8] [] [X-UID-] INFO  org.springframework.jmx.export.annotation.AnnotationMBeanExporter Unregistering JMX-exposed beans
2018-03-13 14:49:17.557 [DiscoveryClient-InstanceInfoReplicator-0] [] [X-UID-] INFO  com.netflix.discovery.DiscoveryClient DiscoveryClient_YIDAO-PORTAL/172.19.150.216:yidao-portal:10011 - registration status: 204
2018-03-13 14:49:18.688 [Thread-8] [] [X-UID-] INFO  com.zaxxer.hikari.HikariDataSource env-prod - Shutdown initiated...
2018-03-13 14:49:18.702 [Thread-8] [] [X-UID-] INFO  com.zaxxer.hikari.HikariDataSource env-prod - Shutdown completed.
2018-03-13 14:49:18.703 [Thread-8] [] [X-UID-] INFO  org.springframework.context.annotation.AnnotationConfigApplicationContext Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@52171ab8: startup date [Tue Mar 13 14:44:32 CST 2018]; parent: org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@1b083826
2018-03-13 14:49:18.705 [Thread-8] [] [X-UID-] INFO  com.netflix.util.concurrent.ShutdownEnabledTimer Shutdown hook removed for: NFLoadBalancer-PingTimer-yidao-user
2018-03-13 14:49:18.705 [Thread-8] [] [X-UID-] INFO  com.netflix.util.concurrent.ShutdownEnabledTimer Exception caught (might be ok if at shutdown)
java.lang.IllegalStateException: Shutdown in progress
        at java.lang.ApplicationShutdownHooks.remove(ApplicationShutdownHooks.java:82)
        at java.lang.Runtime.removeShutdownHook(Runtime.java:239)
        at com.netflix.util.concurrent.ShutdownEnabledTimer.cancel(ShutdownEnabledTimer.java:70)
        at com.netflix.loadbalancer.BaseLoadBalancer.cancelPingTask(BaseLoadBalancer.java:613)
        at com.netflix.loadbalancer.BaseLoadBalancer.shutdown(BaseLoadBalancer.java:864)
        at com.netflix.loadbalancer.DynamicServerListLoadBalancer.shutdown(DynamicServerListLoadBalancer.java:277)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.beans.factory.support.DisposableBeanAdapter.invokeCustomDestroyMethod(DisposableBeanAdapter.java:337)
        at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:271)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:576)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:552)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:953)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:521)
        at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.destroySingletons(FactoryBeanRegistrySupport.java:227)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingletons(DefaultListableBeanFactory.java:960)
        at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1035)
        at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1011)
        at org.springframework.context.support.AbstractApplicationContext.close(AbstractApplicationContext.java:963)
        at org.springframework.cloud.context.named.NamedContextFactory.destroy(NamedContextFactory.java:76)
        at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:256)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:576)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:552)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:953)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:521)
        at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.destroySingletons(FactoryBeanRegistrySupport.java:227)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingletons(DefaultListableBeanFactory.java:960)
        at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1035)
        at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1011)
        at org.springframework.context.support.AbstractApplicationContext$1.run(AbstractApplicationContext.java:933)
2018-03-13 14:49:18.709 [Thread-8] [] [X-UID-] INFO  org.springframework.context.annotation.AnnotationConfigApplicationContext Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@10f5fde4: startup date [Tue Mar 13 14:46:13 CST 2018]; parent: org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@1b083826
2018-03-13 14:49:18.709 [Thread-8] [] [X-UID-] INFO  com.netflix.util.concurrent.ShutdownEnabledTimer Shutdown hook removed for: NFLoadBalancer-PingTimer-yidao-tool
2018-03-13 14:49:18.710 [Thread-8] [] [X-UID-] INFO  com.netflix.util.concurrent.ShutdownEnabledTimer Exception caught (might be ok if at shutdown)
java.lang.IllegalStateException: Shutdown in progress
        at java.lang.ApplicationShutdownHooks.remove(ApplicationShutdownHooks.java:82)
        at java.lang.Runtime.removeShutdownHook(Runtime.java:239)
        at com.netflix.util.concurrent.ShutdownEnabledTimer.cancel(ShutdownEnabledTimer.java:70)
        at com.netflix.loadbalancer.BaseLoadBalancer.cancelPingTask(BaseLoadBalancer.java:613)
        at com.netflix.loadbalancer.BaseLoadBalancer.shutdown(BaseLoadBalancer.java:864)
        at com.netflix.loadbalancer.DynamicServerListLoadBalancer.shutdown(DynamicServerListLoadBalancer.java:277)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.beans.factory.support.DisposableBeanAdapter.invokeCustomDestroyMethod(DisposableBeanAdapter.java:337)
        at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:271)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:576)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:552)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:953)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:521)
        at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.destroySingletons(FactoryBeanRegistrySupport.java:227)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingletons(DefaultListableBeanFactory.java:960)
        at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1035)
        at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1011)
        at org.springframework.context.support.AbstractApplicationContext.close(AbstractApplicationContext.java:963)
        at org.springframework.cloud.context.named.NamedContextFactory.destroy(NamedContextFactory.java:76)
        at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:256)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:576)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:552)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:953)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:521)
        at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.destroySingletons(FactoryBeanRegistrySupport.java:227)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingletons(DefaultListableBeanFactory.java:960)
        at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1035)
        at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1011)
        at org.springframework.context.support.AbstractApplicationContext$1.run(AbstractApplicationContext.java:933)
2018-03-13 14:49:18.711 [Thread-8] [] [X-UID-] INFO  org.springframework.context.annotation.AnnotationConfigApplicationContext Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@466f5e9b: startup date [Tue Mar 13 14:44:33 CST 2018]; parent: org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@1b083826
2018-03-13 14:49:18.711 [Thread-8] [] [X-UID-] INFO  com.netflix.util.concurrent.ShutdownEnabledTimer Shutdown hook removed for: NFLoadBalancer-PingTimer-yidao-ext
2018-03-13 14:49:18.711 [Thread-8] [] [X-UID-] INFO  com.netflix.util.concurrent.ShutdownEnabledTimer Exception caught (might be ok if at shutdown)
java.lang.IllegalStateException: Shutdown in progress
        at java.lang.ApplicationShutdownHooks.remove(ApplicationShutdownHooks.java:82)
        at java.lang.Runtime.removeShutdownHook(Runtime.java:239)
        at com.netflix.util.concurrent.ShutdownEnabledTimer.cancel(ShutdownEnabledTimer.java:70)
        at com.netflix.loadbalancer.BaseLoadBalancer.cancelPingTask(BaseLoadBalancer.java:613)
        at com.netflix.loadbalancer.BaseLoadBalancer.shutdown(BaseLoadBalancer.java:864)
        at com.netflix.loadbalancer.DynamicServerListLoadBalancer.shutdown(DynamicServerListLoadBalancer.java:277)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.beans.factory.support.DisposableBeanAdapter.invokeCustomDestroyMethod(DisposableBeanAdapter.java:337)
        at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:271)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:576)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:552)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:953)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:521)
        at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.destroySingletons(FactoryBeanRegistrySupport.java:227)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingletons(DefaultListableBeanFactory.java:960)
        at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1035)
        at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1011)
        at org.springframework.context.support.AbstractApplicationContext.close(AbstractApplicationContext.java:963)
        at org.springframework.cloud.context.named.NamedContextFactory.destroy(NamedContextFactory.java:76)
        at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:256)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:576)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:552)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:953)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:521)
        at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.destroySingletons(FactoryBeanRegistrySupport.java:227)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingletons(DefaultListableBeanFactory.java:960)
        at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1035)
        at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1011)
        at org.springframework.context.support.AbstractApplicationContext$1.run(AbstractApplicationContext.java:933)
2018-03-13 14:49:18.713 [Thread-8] [] [X-UID-] INFO  org.springframework.context.annotation.AnnotationConfigApplicationContext Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@2dd80673: startup date [Tue Mar 13 14:42:53 CST 2018]; parent: org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@1b083826
2018-03-13 14:49:18.713 [Thread-8] [] [X-UID-] INFO  org.springframework.context.annotation.AnnotationConfigApplicationContext Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@1b7c473a: startup date [Tue Mar 13 14:42:52 CST 2018]; parent: org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@1b083826
2018-03-13 14:49:18.713 [Thread-8] [] [X-UID-] INFO  org.springframework.context.annotation.AnnotationConfigApplicationContext Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@45d2ade3: startup date [Tue Mar 13 14:42:51 CST 2018]; parent: org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@1b083826
2018-03-13 14:49:18.714 [Thread-8] [] [X-UID-] INFO  com.netflix.discovery.DiscoveryClient Shutting down DiscoveryClient ...
2018-03-13 14:49:18.719 [Thread-8] [] [X-UID-] INFO  com.netflix.discovery.DiscoveryClient Unregistering ...
2018-03-13 14:49:18.725 [Thread-8] [] [X-UID-] INFO  com.netflix.discovery.DiscoveryClient DiscoveryClient_YIDAO-PORTAL/172.19.150.216:yidao-portal:10011 - deregister  status: 200
2018-03-13 14:49:18.738 [Thread-8] [] [X-UID-] INFO  com.netflix.discovery.DiscoveryClient Completed shut down of DiscoveryClient
```

**Comment by ryanjbaxter** [comment]
We will need more information to help.

To start with you should be using the Spring Cloud BOM and not importing projects independetly.  See how to include the BOM here http://cloud.spring.io/.  Or you can use start.spring.io to generate your project correctly.  Secondly you should be using the latest Spring Cloud release which is Finchley.M8 if you want to be using the 2.0.x stream and use Boot 2.0.0.  The latest stable Spring Cloud release is Edgware.SR2.  If you fix those two issues and are still experiencing a problem please reopen this issue and provide a project that reproduces the issue.
