### ISSUE TITLE
FeignClient with listOfServers but can't get server instances

### ISSUE THREAD

**Issue by wdyun** [spring-cloud/spring-cloud-netflix#2801]
I am trying to use @FeignClient for the  REST client int application. I want to make use of Ribbon for the load balancing between two instances, but not use Eureka. In the application.yml  configured  the listOfServers like this(also disabe the eureka )
```
client:
  ribbon:
    eureka:
      enabled: false
    listOfServers: server1:8081,server2:8082
```
and the  feign client defines like this:

```
@FeignClient(value = "client")
public interface ClientService {

    @RequestMapping(value = "/api/users", method = RequestMethod.GET)
    public User[] findAllUsers();
}
```

but all i get is the error 'Load balancer does not have available server for client: client',
here is the log:
```
2018-03-29 20:36:49.761  INFO 11046 --- [nio-8085-exec-1] c.n.l.DynamicServerListLoadBalancer      : DynamicServerListLoadBalancer for client client initialized: DynamicServerListLoadBalancer:{NFLoadBalancer:name=client,current list of Servers=[],Load balancer stats=Zone stats: {},Server stats: []}ServerList:org.springframework.cloud.zookeeper.discovery.ZookeeperServerList@2406f836
2018-03-29 20:37:05.492 ERROR 11046 --- [nio-8085-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.RuntimeException: com.netflix.client.ClientException: Load balancer does not have available server for client: client] with root cause

com.netflix.client.ClientException: Load balancer does not have available server for client: client
at com.netflix.loadbalancer.LoadBalancerContext.getServerFromLoadBalancer(LoadBalancerContext.java:483) ~[ribbon-loadbalancer-2.2.4.jar:2.2.4]
	at com.netflix.loadbalancer.reactive.LoadBalancerCommand$1.call(LoadBalancerCommand.java:184) ~[ribbon-loadbalancer-2.2.4.jar:2.2.4]
	at com.netflix.loadbalancer.reactive.LoadBalancerCommand$1.call(LoadBalancerCommand.java:180) ~[ribbon-loadbalancer-2.2.4.jar:2.2.4]
	at rx.Observable.unsafeSubscribe(Observable.java:10151) ~[rxjava-1.2.0.jar:1.2.0]
	at rx.internal.operators.OnSubscribeConcatMap.call(OnSubscribeConcatMap.java:94) ~[rxjava-1.2.0.jar:1.2.0]
	at rx.internal.operators.OnSubscribeConcatMap.call(OnSubscribeConcatMap.java:42) ~[rxjava-1.2.0.jar:1.2.0]
	at rx.Observable.unsafeSubscribe(Observable.java:10151) ~[rxjava-1.2.0.jar:1.2.0]
	at rx.internal.operators.OperatorRetryWithPredicate$SourceSubscriber$1.call(OperatorRetryWithPredicate.java:127) ~[rxjava-1.2.0.jar:1.2.0]
	at rx.internal.schedulers.TrampolineScheduler$InnerCurrentThreadScheduler.enqueue(TrampolineScheduler.java:73) ~[rxjava-1.2.0.jar:1.2.0]
	at rx.internal.schedulers.TrampolineScheduler$InnerCurrentThreadScheduler.schedule(TrampolineScheduler.java:52) ~[rxjava-1.2.0.jar:1.2.0]
	at rx.internal.operators.OperatorRetryWithPredicate$SourceSubscriber.onNext(OperatorRetryWithPredicate.java:79) ~[rxjava-1.2.0.jar:1.2.0]
	at rx.internal.operators.OperatorRetryWithPredicate$SourceSubscriber.onNext(OperatorRetryWithPredicate.java:45) ~[rxjava-1.2.0.jar:1.2.0]
	at rx.internal.util.ScalarSynchronousObservable$WeakSingleProducer.request(ScalarSynchronousObservable.java:276) ~[rxjava-1.2.0.jar:1.2.0]
	at rx.Subscriber.setProducer(Subscriber.java:209) ~[rxjava-1.2.0.jar:1.2.0]
	at rx.internal.util.ScalarSynchronousObservable$JustOnSubscribe.call(ScalarSynchronousObservable.java:138) ~[rxjava-1.2.0.jar:1.2.0]
	at rx.internal.util.ScalarSynchronousObservable$JustOnSubscribe.call(ScalarSynchronousObservable.java:129) ~[rxjava-1.2.0.jar:1.2.0]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48) ~[rxjava-1.2.0.jar:1.2.0]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) ~[rxjava-1.2.0.jar:1.2.0]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48) ~[rxjava-1.2.0.jar:1.2.0]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) ~[rxjava-1.2.0.jar:1.2.0]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48) ~[rxjava-1.2.0.jar:1.2.0]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) ~[rxjava-1.2.0.jar:1.2.0]
	at rx.Observable.subscribe(Observable.java:10247) ~[rxjava-1.2.0.jar:1.2.0]
	at rx.Observable.subscribe(Observable.java:10214) ~[rxjava-1.2.0.jar:1.2.0]
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:444) ~[rxjava-1.2.0.jar:1.2.0]
	at rx.observables.BlockingObservable.single(BlockingObservable.java:341) ~[rxjava-1.2.0.jar:1.2.0]
	at com.netflix.client.AbstractLoadBalancerAwareClient.executeWithLoadBalancer(AbstractLoadBalancerAwareClient.java:112) ~[ribbon-loadbalancer-2.2.4.jar:2.2.4]
	at org.springframework.cloud.netflix.feign.ribbon.LoadBalancerFeignClient.execute(LoadBalancerFeignClient.java:63) ~[spring-cloud-netflix-core-1.4.3.RELEASE.jar:1.4.3.RELEASE]
	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:97) ~[feign-core-9.5.0.jar:na]
	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:76) ~[feign-core-9.5.0.jar:na 
...```

The spring-cloud version is Edgware.SR2

the pom.xml is :
 ```
               <dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-zookeeper-discovery</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-feign</artifactId>
		</dependency>
```
 How the spring cloud component is configured in the Spring Boot application:

```
      @EnableFeignClients
      @SpringBootApplication
      @EnableDiscoveryClient
      public class StorageApplication {

     }
```

**Comment by ryanjbaxter** [comment]
Is Ribbon on the classpath?

**Comment by wdyun** [comment]
Of course here is pom  dependency hierarchy
![image](https://user-images.githubusercontent.com/11865618/38119748-a2aea5ae-33f6-11e8-8730-6dd0b029e28c.png)

**Comment by spencergibb** [comment]
It's `ribbon.eureka.enabled=false`, no `client` prefix. Also `ListOfServers`, capitol L.

**Comment by wdyun** [comment]
@spencergibb I had try 

```
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 4000
  eureka:
    enabled: false
    
client:
  ribbon:
    ListOfServers: server1:8081,server2:8082
```
I got the same error:
```
2018-03-30 10:13:24.644  INFO 12669 --- [nio-8085-exec-1] c.netflix.config.ChainedDynamicProperty  : Flipping property: client.ribbon.ActiveConnectionsLimit to use NEXT property: niws.loadbalancer.availabilityFilteringRule.activeConnectionsLimit = 2147483647
2018-03-30 10:13:24.676  INFO 12669 --- [nio-8085-exec-1] c.netflix.loadbalancer.BaseLoadBalancer  : Client: client instantiated a LoadBalancer: DynamicServerListLoadBalancer:{NFLoadBalancer:name=client,current list of Servers=[],Load balancer stats=Zone stats: {},Server stats: []}ServerList:null
2018-03-30 10:13:24.684  INFO 12669 --- [nio-8085-exec-1] c.n.l.DynamicServerListLoadBalancer      : Using serverListUpdater PollingServerListUpdater
2018-03-30 10:13:24.692  INFO 12669 --- [nio-8085-exec-1] c.n.l.DynamicServerListLoadBalancer      : DynamicServerListLoadBalancer for client client initialized: DynamicServerListLoadBalancer:{NFLoadBalancer:name=client,current list of Servers=[],Load balancer stats=Zone stats: {},Server stats: []}ServerList:org.springframework.cloud.zookeeper.discovery.ZookeeperServerList@6272545e
2018-03-30 10:13:24.873 ERROR 12669 --- [nio-8085-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.RuntimeException: com.netflix.client.ClientException: Load balancer does not have available server for client: client] with root cause

com.netflix.client.ClientException: Load balancer does not have available server for client: client
	at com.netflix.loadbalancer.LoadBalancerContext.getServerFromLoadBalancer(LoadBalancerContext.java:483) ~[ribbon-loadbalancer-2.2.4.jar:2.2.4]
	at com.netflix.loadbalancer.reactive.LoadBalancerCommand$1.call(LoadBalancerCommand.java:184) ~[ribbon-loadbalancer-2.2.4.jar:2.2.4]
	at com.netflix.loadbalancer.reactive.LoadBalancerCommand$1.call(LoadBalancerCommand.java:180) ~[ribbon-loadbalancer-2.2.4.jar:2.2.4]
	at rx.Observable.unsafeSubscribe(Observable.java:10151) ~[rxjava-1.2.0.jar:1.2.0]
	at rx.internal.operators.OnSubscribeConcatMap.call(OnSubscribeConcatMap.java:94) ~[rxjava-1.2.0.jar:1.2.0]
	at rx.internal.operators.OnSubscribeConcatMap.call(OnSubscribeConcatMap.java:42) ~[rxjava-1.2.0.jar:1.2.0]
	at rx.Observable.unsafeSubscribe(Observable.java:10151) ~[rxjava-1.2.0.jar:1.2.0]
```

**Comment by ryanjbaxter** [comment]
If you are not using service discovery, why is Zookeeper on the classpath?  What are you using it for.
Ribbon looks like it is getting the server list from Zookeeper.
`ServerList:org.springframework.cloud.zookeeper.discovery.ZookeeperServerList@2406f836`

**Comment by wdyun** [comment]
I want to use service discovery in my product environment，but in the alpha or dev environment I just want to depend on the service provider‘s(the ‘client’ service in my case)  product environment. And I think this common needs for micro service developer for reliance on the provider's product (I just use  GET api service ).

**Comment by wdyun** [comment]
I want to use service discovery in my product environment，but in the alpha or dev environment I just want to depend on the service provider‘s(the ‘client’ service in my case) product environment. And I think this common needs for micro service developer for reliance on the provider's product (I just use GET api service ).

**Comment by ryanjbaxter** [comment]
Have you tried setting `spring.cloud.zookeeper.dependency.ribbon.enabled=false` in those environments?

**Comment by spencergibb** [comment]
@wdyun 
```
client:
  ribbon:
    NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList
```

will also work.

**Comment by wdyun** [comment]
@spencergibb Sorry for getting back to you late.（We live in different time zones） I have searched the  solution on  stackoverflow  and Google，also I try the configure

```
client:
  ribbon:
    NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList
```

but the FeignClinet  always get  instance list from the Zookeeper  not the configure ‘listOfServers’

**Comment by spencergibb** [comment]
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem? If so, feel free to share and we can reopen.

**Comment by Chococrok** [comment]
Hello,
I have the same exact problem.
I tryed what @wdyun said.
And I tryed with Finchley.SR2, Greenwich.RC1 and Greenwich.RC2.
plz Help
[order-micro-service.tar.gz](https://github.com/spring-cloud/spring-cloud-netflix/files/2826167/order-micro-service.tar.gz)
