### ISSUE TITLE
java.lang.ArrayStoreException on excluding actuator from spring-cloud-starter-zuul

### ISSUE THREAD

**Issue by rashmidusane** [spring-cloud/spring-cloud-netflix#2821]
Hi, 

I am trying to exclude actuator from spring-cloud-starter-zuul like following and getting the error below.

```
<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-zuul</artifactId>
			<version>1.2.6.RELEASE</version>
			<exclusions>
				<exclusion>
					<artifactId>
						spring-boot-starter-actuator
					</artifactId>
					<groupId>org.springframework.boot</groupId>
				</exclusion>
			</exclusions>
</dependency>
```

java.lang.ArrayStoreException: sun.reflect.annotation.TypeNotPresentExceptionProxy
	at sun.reflect.annotation.AnnotationParser.parseClassArray(AnnotationParser.java:724)
	at sun.reflect.annotation.AnnotationParser.parseArray(AnnotationParser.java:531)
	at sun.reflect.annotation.AnnotationParser.parseMemberValue(AnnotationParser.java:355)
	at sun.reflect.annotation.AnnotationParser.parseAnnotation2(AnnotationParser.java:286)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:120)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:72)
	at java.lang.Class.createAnnotationData(Class.java:3521)
	at java.lang.Class.annotationData(Class.java:3510)
	at java.lang.Class.getAnnotations(Class.java:3446)

**Comment by spencergibb** [comment]
Can you upgrade to a newer release, such as Edgware.SR3?

**Comment by rashmidusane** [comment]
Cannot upgrade right now it is conflicting with some other dependencies. Server startup is failing on upgrade.

**Comment by spencergibb** [comment]
It's been 11 months since 1.2 has been updated

**Comment by spencergibb** [comment]
This module has entered [maintenance mode](https://github.com/spring-cloud/spring-cloud-netflix#modules-in-maintenance-mode). This means that the Spring Cloud team will no longer be adding new features to the module. We will fix blocker bugs and security issues, and we will also consider and review small pull requests from the community.
