### ISSUE TITLE
Spring Cloud Netflix Feign content encoding not working

### ISSUE THREAD

**Issue by newguyintown** [spring-cloud/spring-cloud-netflix#2922]
### simple use case: 
I have  client-api which calls server-api using feign for some response and requirement is that client-api wants to get response in gzip format / compressed response from server-api to deal big chunk lod from server-api.

somehow I don't get `Content-Encoding: gzip' in response header until i explicitly set as header filed but when i do that, exception thrown while fetching response object as below.

And Also I know there are many threads in the past but i did not able to find proper solution for this issue rather than just a discussion. 

Please help me out here ...looking for solution :)

### ERROR:
```
com.fasterxml.jackson.core.JsonParseException: Illegal character ((CTRL-CHAR, code 31)): only regular white space (\r, \n, \t) is allowed between tokens
 at [Source: sun.net.www.protocol.http.HttpURLConnection$HttpInputStream@f3ca48b; line: 1, column: 2]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1702)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:558)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._throwInvalidSpace(ParserMinimalBase.java:509)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._skipWSOrEnd(UTF8StreamJsonParser.java:2949)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:731)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3850)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3799)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2924)
```

### Info: 
1) feign command interface
```
    @RequestLine("GET /something)  
    @Headers({"Authorization: {authorizationToken}", "Accept-Encoding: gzip"})
    Response getSomething()
```

2) pom.xml  (showing only dependencies affiliated to this issue )
```
<dependency>
            <groupId>com.github.jmnarloch</groupId>
            <artifactId>feign-encoding-spring-cloud-starter</artifactId>
            <version>1.1.1</version>
</dependency>

<dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>1.5.7.RELEASE</version>
                <type>pom</type>
                <scope>import</scope>
 </dependency>

<dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>Dalston.SR3</version>
                <type>pom</type>
                <scope>import</scope>
</dependency>
```
3) Beans not able to auto configure
```
FeignAcceptGzipEncodingAutoConfiguration:
      Did not match:
         - @ConditionalOnBean (types: feign.httpclient.ApacheHttpClient; SearchStrategy: all) did not find any beans (OnBeanCondition)
      Matched:
         - @ConditionalOnClass found required class 'feign.Feign'; @ConditionalOnMissingClass did not find unwanted class (OnClassCondition)
         - @ConditionalOnProperty (feign.compression.response.enabled) matched (OnPropertyCondition)
FeignContentGzipEncodingAutoConfiguration:
      Did not match:
         - @ConditionalOnBean (types: feign.httpclient.ApacheHttpClient; SearchStrategy: all) did not find any beans (OnBeanCondition)
      Matched:
         - @ConditionalOnClass found required class 'feign.Feign'; @ConditionalOnMissingClass did not find unwanted class (OnClassCondition)
         - @ConditionalOnProperty (feign.compression.request.enabled) matched (OnPropertyCondition)
```

**Comment by spencergibb** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
