### ISSUE TITLE
ArrayStoreException: TypeNotPresentExceptionProxy on adding spring-cloud-starter-netflix-hystrix

### ISSUE THREAD

**Issue by asarkar** [spring-cloud/spring-cloud-netflix#2926]
Using Boot 2.0.2.RELEASE and Cloud Finchley.RC1, I get the following exception:
```
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'requestMappingHandlerMapping' defined in class path resource [org/springframework/boot/autoconfigure/web/servlet/WebMvcAutoConfiguration$EnableWebMvcConfiguration.class]: Invocation of init method failed; nested exception is java.lang.ArrayStoreException: sun.reflect.annotation.TypeNotPresentExceptionProxy
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1706) ~[spring-beans-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:579) ~[spring-beans-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:501) ~[spring-beans-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317) ~[spring-beans-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228) ~[spring-beans-5.0.6.RELEASE.jar:5.0.6.RELEASE]
```

There are several reports of `ArrayStoreException` with various versions of Boot and Cloud. Unfortunately, the JVM doesn't care to tell us what type it was introspecting making it extremely difficult to troubleshoot such problems. A somewhat good discussion is https://github.com/spring-projects/spring-boot/issues/8667

Removing `spring-cloud-starter-netflix-hystrix` dependency from build makes the issue go away; however, that also means I can't use `com.netflix.hystrix.contrib.javanica.annotation.HystrixCommand` annotation in my code.

I don't have a sample app. Generating one from Boot Initializer site doesn't show this problem.

**Comment by ryanjbaxter** [comment]
I believe this is fixed in the Finchley snapshots, can you try those?

**Comment by asarkar** [comment]
Is there a specific ticket that you have in mind? I’m little apprehensive going through the exercise just to try latest code.

**Comment by spencergibb** [comment]
We also have no way to recreate the problem, so there's not much we can do on our side.

**Comment by Hunter-Chen** [comment]
Can't recreate the issue.

**Comment by ryanjbaxter** [comment]
There were a couple of fixes in commons that may have been at the root of this.  https://github.com/spring-cloud/spring-cloud-commons/issues/354

If you try snapshots and it doesnt work than please reopen this
