### ISSUE TITLE
Unresolvable circular reference with eurekae & postgress

### ISSUE THREAD

**Issue by nWidart** [spring-cloud/spring-cloud-netflix#3030]
Hello,

I apologise if this isn't a bug and not the right place to report this.

I've been working on a spring boot 2 project which uses postgres as database, all working fine.
Now, I've been following a course on Pluralsight on spring cloud, which covers Eureka.

I've setup Eureka server and 2 other small microservices with it without issues. These 2 microservices don't connect to any database.

The last part of this would be to use Eureka in the main application (which does connect to postgres).
However, since adding spring cloud netflix dependency, I'm getting the following error (not stacktrace)

``` java
2018-06-26 17:31:51.478 ERROR 8117 --- [ost-startStop-1] o.s.b.web.embedded.tomcat.TomcatStarter  : Error starting Tomcat context. Exception: org.springframework.beans.factory.BeanCreationException. Message: Error creating bean with name 'servletEndpointRegistrar' defined in class path resource [org/springframework/boot/actuate/autoconfigure/endpoint/web/ServletEndpointManagementContextConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.actuate.endpoint.web.ServletEndpointRegistrar]: Factory method 'servletEndpointRegistrar' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'healthEndpoint' defined in class path resource [org/springframework/boot/actuate/autoconfigure/health/HealthEndpointConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.actuate.health.HealthEndpoint]: Factory method 'healthEndpoint' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.boot.actuate.autoconfigure.jdbc.DataSourceHealthIndicatorAutoConfiguration': Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.actuate.autoconfigure.jdbc.DataSourceHealthIndicatorAutoConfiguration$$EnhancerBySpringCGLIB$$8018dd03]: Constructor threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource': Post-processing of FactoryBean's singleton object failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'scopedTarget.dataSource' defined in class path resource [org/springframework/boot/autoconfigure/jdbc/DataSourceConfiguration$Hikari.class]: Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.boot.autoconfigure.jdbc.DataSourceInitializerInvoker': Invocation of init method failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource': Post-processing of FactoryBean's singleton object failed; nested exception is org.springframework.beans.factory.BeanCurrentlyInCreationException: Error creating bean with name 'scopedTarget.dataSource': Requested bean is currently in creation: Is there an unresolvable circular reference?
```

We can see the following flow:

- Error creating bean with name 'healthEndpoint'
- Error creating bean with name 'org.springframework.boot.actuate.autoconfigure.jdbc.DataSourceHealthIndicatorAutoConfiguration
- Error creating bean with name 'dataSource'
- Error creating bean with name 'scopedTarget.dataSource'
- Error creating bean with name 'org.springframework.boot.autoconfigure.jdbc.DataSourceInitializerInvoker'
- Error creating bean with name 'dataSource'
- Error creating bean with name 'scopedTarget.dataSource'

[Here's a private gist containing the `pom.xml`, `application.java` and `application.properties`.](https://gist.github.com/nWidart/1f3a635d6d392afe68d09603c260ed04)

I've tried to replicate the issue on a clean spring boot setup with actuator, web, discovery client, but I'm unable to reproduce the issue.

I'm guessing it must be something stupid, but I'm missing it currently.

Thank you,

**Comment by ryanjbaxter** [comment]
Could you perhaps narrow down the project to its simplest form to reproduce the error and then attach that project as a zip or put it in a git repo and we can look into it?

**Comment by nWidart** [comment]
Hello,

Thanks, I've added the project in a private github repository & added you to it.
I've commented out / deleted files & dependencies that are located on a private nexus repository so that you can still install maven dependencies.

**Comment by nWidart** [comment]
After some more digging around & searching, I came across this comment: https://github.com/spring-cloud/spring-cloud-commons/issues/355#issuecomment-385169003
Which removes the circular dependency error.

However, it now errors with this:

``` java
java.lang.NullPointerException: null
	at org.springframework.cloud.health.RefreshScopeHealthIndicator.doHealthCheck(RefreshScopeHealthIndicator.java:48) ~[spring-cloud-context-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at org.springframework.boot.actuate.health.AbstractHealthIndicator.health(AbstractHealthIndicator.java:84) ~[spring-boot-actuator-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at org.springframework.boot.actuate.health.CompositeHealthIndicator.health(CompositeHealthIndicator.java:68) [spring-boot-actuator-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at org.springframework.boot.actuate.health.HealthEndpoint.health(HealthEndpoint.java:47) [spring-boot-actuator-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:564) ~[na:na]
	at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:223) [spring-core-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.boot.actuate.endpoint.invoke.reflect.ReflectiveOperationInvoker.invoke(ReflectiveOperationInvoker.java:76) [spring-boot-actuator-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at org.springframework.boot.actuate.endpoint.annotation.AbstractDiscoveredOperation.invoke(AbstractDiscoveredOperation.java:61) [spring-boot-actuator-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at org.springframework.boot.actuate.endpoint.jmx.EndpointMBean.invoke(EndpointMBean.java:102) [spring-boot-actuator-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at org.springframework.boot.actuate.endpoint.jmx.EndpointMBean.invoke(EndpointMBean.java:93) [spring-boot-actuator-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at java.management/com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:809) [na:na]
	at java.management/com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801) [na:na]
	at java.management.rmi/javax.management.remote.rmi.RMIConnectionImpl.doOperation(RMIConnectionImpl.java:1466) [na:na]
	at java.management.rmi/javax.management.remote.rmi.RMIConnectionImpl.access$300(RMIConnectionImpl.java:75) [na:na]
	at java.management.rmi/javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(RMIConnectionImpl.java:1307) [na:na]
	at java.management.rmi/javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(RMIConnectionImpl.java:1399) [na:na]
	at java.management.rmi/javax.management.remote.rmi.RMIConnectionImpl.invoke(RMIConnectionImpl.java:827) [na:na]
	at java.base/jdk.internal.reflect.GeneratedMethodAccessor286.invoke(Unknown Source) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:564) ~[na:na]
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:359) [na:na]
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200) [na:na]
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197) [na:na]
	at java.base/java.security.AccessController.doPrivileged(Native Method) [na:na]
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196) [na:na]
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:567) [na:na]
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:800) [na:na]
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:682) [na:na]
	at java.base/java.security.AccessController.doPrivileged(Native Method) [na:na]
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:681) [na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:844) ~[na:na]
```

But the app still boots afterwards.

**Comment by nani2ratna** [comment]
it works in Finchley.RC1 though but not in Finchley.RELEASE

**Comment by ryanjbaxter** [comment]
@nWidart can you post the link to the repo?  I cant find the email right now.

**Comment by nWidart** [comment]
I'm afraid I've deleted the repository in the meantime. The bug seems to be known so I thought it wasn't necessary anymore. 
If you want I can create a new one, however, there are some packages coming from a private nexus repo so it'll likely not install fully.

**Comment by ryanjbaxter** [comment]
Yes we need an app to reproduce the issue.  Lets close this issue and move the conversation to https://github.com/spring-cloud/spring-cloud-commons/issues/384

**Comment by ryanjbaxter** [comment]
If you can reproduce the issue without any Spring Cloud projects on the classpath than we can just use the Boot issue
