### ISSUE TITLE
Eureka replication and registration breaks with HTTP basic authentication

### ISSUE THREAD

**Issue by illingtonFlex** [spring-cloud/spring-cloud-netflix#3035]
Using Finchley.RELEASE

I am attempting to secure my Eureka instances with HTTP basic authentication via Spring Security. The ask is that all connections to Eureka, the console, the endpoints and actuator are all secured via the same credentials, with the password being read from the environment.

I am able to secure the console, but once I log in, I see a Freemarker error (see below).

If I remove the HTTP credentials from the serviceUrl property, the UI error goes away, but nothing can register with Eureka, and replicas are listed as unavailable.

Property with credentials: 
```
eureka.client.serviceUrl.defaultZone=http://username:${PASSWORD}@svcregistry2-dev.myCompany.com:8590/eureka/,http://username:${PASSWORD}@svcregistry1-dev.myCompany.com:8580/eureka/
```

Relevant log lines:

> [2018-06-27 15:04:20.241] -  WARN - [DiscoveryClient-InstanceInfoReplicator-0] [EurekaRegistry_DEV_PEER_1,,,] --- [nfoReplicator-0] c.n.d.s.t.d.RetryableEurekaHttpClient    : Request execution failed with message: java.lang.IllegalArgumentException: Host name may not be null
> [2018-06-27 15:04:20.242] -  WARN - [DiscoveryClient-InstanceInfoReplicator-0] [EurekaRegistry_DEV_PEER_1,,,] --- [nfoReplicator-0] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_EUREKA_SVC_REGISTRY_CLUSTER_DEV/172.16.10.224:EurekaRegistry_DEV_PEER_1:8580 - registration failed Cannot execute request on any known server

> com.netflix.discovery.shared.transport.TransportException: Cannot execute request on any known server
>         at com.netflix.discovery.shared.transport.decorator.RetryableEurekaHttpClient.execute(RetryableEurekaHttpClient.java:112) ~[eureka-client-1.9.2.jar!/:1.9.2]
>         at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.register(EurekaHttpClientDecorator.java:56) ~[eureka-client-1.9.2.jar!/:1.9.2]
>         at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$1.execute(EurekaHttpClientDecorator.java:59) ~[eureka-client-1.9.2.jar!/:1.9.2]
>         at com.netflix.discovery.shared.transport.decorator.SessionedEurekaHttpClient.execute(SessionedEurekaHttpClient.java:77) ~[eureka-client-1.9.2.jar!/:1.9.2]
>         at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.register(EurekaHttpClientDecorator.java:56) ~[eureka-client-1.9.2.jar!/:1.9.2]
>         at com.netflix.discovery.DiscoveryClient.register(DiscoveryClient.java:829) ~[eureka-client-1.9.2.jar!/:1.9.2]
>         at com.netflix.discovery.InstanceInfoReplicator.run(InstanceInfoReplicator.java:121) [eureka-client-1.9.2.jar!/:1.9.2]
>         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_131]
>         at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_131]
>         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_131]
>         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_131]
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_131]
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_131]
>         at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]
> 
> [2018-06-27 15:04:20.242] -  WARN - [DiscoveryClient-InstanceInfoReplicator-0] [EurekaRegistry_DEV_PEER_1,,,] --- [nfoReplicator-0] c.n.discovery.InstanceInfoReplicator     : There was a problem with the instance info replicator
> 

My security config:

    @Configuration
    public static class MyWebSecurityConfigurationAdapter extends WebSecurityConfigurerAdapter {
        protected void configure(HttpSecurity http) throws Exception {
           
           http.antMatcher("/**")
                    .authorizeRequests()
                    .anyRequest().hasRole("ACTUATOR")
                    .and()
                    .httpBasic();
   
           http.csrf().disable();
        }
    }

Security config:

```
spring.security.user.name=username
spring.security.user.roles=ACTUATOR
spring.security.user.password=${PASSWORD}
```

Eureka screen shot:

![image](https://user-images.githubusercontent.com/11623498/41996578-f19523ea-7a1a-11e8-8839-9bccbb10ddca.png)

**Comment by illingtonFlex** [comment]
The problem I was running into was that the password save in the environment contained some characters which are not compatible with url-embedded credentials. I fixed the password and Eureka seems to be working again. I will close this issue.
