### ISSUE TITLE
RetryableRibbonLoadBalancingHttpClient HttpClient & PoolingHttpClientConnectionManager

### ISSUE THREAD

**Issue by tcanavan** [spring-cloud/spring-cloud-netflix#3065]
The exception we are seeing is the following 
```
	at java.net.SocketInputStream.read(SocketInputStream.java:209)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
	at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)
	at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:282)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:138)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:165)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at org.springframework.cloud.netflix.ribbon.apache.RetryableRibbonLoadBalancingHttpClient$1.doWithRetry(RetryableRibbonLoadBalancingHttpClient.java:94)
	at org.springframework.cloud.netflix.ribbon.apache.RetryableRibbonLoadBalancingHttpClient$1.doWithRetry(RetryableRibbonLoadBalancingHttpClient.java:72)
	at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:287)
	at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:164)
	at org.springframework.cloud.netflix.ribbon.apache.RetryableRibbonLoadBalancingHttpClient.executeWithRetry(RetryableRibbonLoadBalancingHttpClient.java:107)
	at org.springframework.cloud.netflix.ribbon.apache.RetryableRibbonLoadBalancingHttpClient.execute(RetryableRibbonLoadBalancingHttpClient.java:72)
	at org.springframework.cloud.netflix.ribbon.apache.RetryableRibbonLoadBalancingHttpClient.execute(RetryableRibbonLoadBalancingHttpClient.java:52)
	at com.netflix.client.AbstractLoadBalancerAwareClient$1.call(AbstractLoadBalancerAwareClient.java:109)
```

Spring retry is been used but in this case I think it has no real affect as 

1. The entry does not seem to be removed from the pool when exception is  thrown. 

2. If another server gets retried it will also get the same error

There use to be an option to check the validity of the connection every time but this no longer works despite the property still existing. It was deemed to be not performant.  The PoolingHttpClientConnectionManager does not seem to be set up for the client thats created in RetryableRibbonLoadBalancingHttpClient which means we cannot use the ValidateAfterInactivity property. The PoolingHttpClientConnectionManager does get setup for the client used im the SimpleRoutingZuulFilter

**Comment by dev-priporov** [comment]
@tcanavan could you please make a simple project to reproduce the issue? Now you didn't write what you do to reproduce that and which versions you use

**Comment by tcanavan** [comment]
@dev-priporov 

Its a only a  question. Why is the RetryableRibbonLoadBalancingHttpClient  not configured with a PoolingHttpClientConnectionManager which would enable us to use the properties like ValidateAfterInactivity  property. 

springBootVersion=1.5.13.RELEASE
springCloudVersion=Dalston.SR5

although I think it applies to all versions since RetryableRibbonLoadBalancingHttpClient was introduced.

**Comment by ryanjbaxter** [comment]
@tcanavan you should be able to provide a bean of type `ApacheHttpClientConnectionManagerFactory` which would return a custom `PoolingHttpClientConnectionManager` and be used by Zuul.
I also suggest you update to at least Edgware.SR4 if not Finchley.RELEASE.
http://cloud.spring.io/spring-cloud-static/Finchley.RELEASE/single/spring-cloud.html#http-clients

**Comment by tcanavan** [comment]
Ok understood from Edgeware.SR4 and above. the RetryableRibbonLoadBalancingHttpClient now accepts the client in the constructor. So we can configure this as you described above. We will do the upgrade this week and let you know how we get on.
