### ISSUE TITLE
Support for feign custom expander

### ISSUE THREAD

**Issue by beku8** [spring-cloud/spring-cloud-netflix#311]
I would like to add custom param expander(as explained [here](https://github.com/Netflix/feign/issues/216)), so I've created my custom expander:
```
@RequestMapping(value="/rest/service?{param}", method=RequestMethod.GET)
	public Map<String, Object> findAll(@Param(value = "param", expander=ParamMapExpander.class) ParamMap param);
```
Following code results in the exception shown below during the start up. Is there any other way to achieve this?
Exception:
```
Exception in thread "main" org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'exampleFeignController': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: com.fm.nd.integration.rest.logistics.ServiceClient com.fm.nd.accounting.rest.ExampleFeignController.serviceClient; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'serviceClient': FactoryBean threw exception on object creation; nested exception is java.lang.NullPointerException
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:334)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1202)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:537)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:303)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:755)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:757)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:480)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:686)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:320)
	at com.fm.nd.accounting.Accounting.main(Accounting.java:30)
Caused by: org.springframework.beans.factory.BeanCreationException: Could not autowire field: com.fm.nd.integration.rest.logistics.ServiceClient com.fm.nd.accounting.rest.ExampleFeignController.serviceClient; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'serviceClient': FactoryBean threw exception on object creation; nested exception is java.lang.NullPointerException
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:561)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:331)
	... 14 more
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'serviceClient': FactoryBean threw exception on object creation; nested exception is java.lang.NullPointerException
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:175)
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.getObjectFromFactoryBean(FactoryBeanRegistrySupport.java:103)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getObjectForBeanInstance(AbstractBeanFactory.java:1517)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:251)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1120)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1044)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:942)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:533)
	... 16 more
Caused by: java.lang.NullPointerException
	at feign.RequestTemplate.allValuesAreNull(RequestTemplate.java:494)
	at feign.RequestTemplate.pullAnyQueriesOutOfUrl(RequestTemplate.java:476)
	at feign.RequestTemplate.append(RequestTemplate.java:207)
	at org.springframework.cloud.netflix.feign.support.SpringMvcContract.processAnnotationOnMethod(SpringMvcContract.java:65)
	at feign.Contract$BaseContract.parseAndValidatateMetadata(Contract.java:62)
	at feign.Contract$BaseContract.parseAndValidatateMetadata(Contract.java:48)
	at feign.ReflectiveFeign$ParseHandlersByName.apply(ReflectiveFeign.java:143)
	at feign.ReflectiveFeign.newInstance(ReflectiveFeign.java:58)
	at feign.Feign$Builder.target(Feign.java:265)
	at feign.Feign$Builder.target(Feign.java:261)
	at org.springframework.cloud.netflix.feign.FeignClientFactoryBean.loadBalance(FeignClientFactoryBean.java:123)
	at org.springframework.cloud.netflix.feign.FeignClientFactoryBean.getObject(FeignClientFactoryBean.java:136)
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:168)
```

**Comment by spencergibb** [comment]
So `@Param`, and hence `expander` is specific to the Feign Default Contract.  You can either create not use the Spring contract (which allows the use of `@RequestMapping`, etc...), or plug into the spring mvc ecosystem by implementing a `HttpMessageConverter`.

**Comment by beku8** [comment]
Is there anything wrong with this approach(using plain ```String```):
```
@RequestMapping(value="/rest/service?{param}", method=RequestMethod.GET)
public Map<String, Object> findAll(@RequestParam("param") String param);
```

Because when I have this inside my ```@FeignClient``` annotated class, it throws:

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'bookingStatusEventListenerImpl': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: com.fm.nd.integration.rest.logistics.ServiceClient com.fm.nd.accounting.crud.event.BookingStatusEventListenerImpl.serviceClient; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'serviceClient': FactoryBean threw exception on object creation; nested exception is java.lang.NullPointerException
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:334)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1202)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:537)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:303)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:755)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:757)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:480)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:686)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:320)
	at com.fm.nd.accounting.Accounting.main(Accounting.java:36)
Caused by: org.springframework.beans.factory.BeanCreationException: Could not autowire field: com.fm.nd.integration.rest.logistics.ServiceClient com.fm.nd.accounting.crud.event.BookingStatusEventListenerImpl.serviceClient; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'serviceClient': FactoryBean threw exception on object creation; nested exception is java.lang.NullPointerException
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:561)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:331)
	... 14 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'serviceClient': FactoryBean threw exception on object creation; nested exception is java.lang.NullPointerException
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:175)
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.getObjectFromFactoryBean(FactoryBeanRegistrySupport.java:103)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getObjectForBeanInstance(AbstractBeanFactory.java:1517)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:251)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1120)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1044)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:942)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:533)
	... 16 common frames omitted
Caused by: java.lang.NullPointerException: null
	at feign.RequestTemplate.allValuesAreNull(RequestTemplate.java:494)
	at feign.RequestTemplate.pullAnyQueriesOutOfUrl(RequestTemplate.java:476)
	at feign.RequestTemplate.append(RequestTemplate.java:207)
	at org.springframework.cloud.netflix.feign.support.SpringMvcContract.processAnnotationOnMethod(SpringMvcContract.java:65)
	at feign.Contract$BaseContract.parseAndValidatateMetadata(Contract.java:62)
	at feign.Contract$BaseContract.parseAndValidatateMetadata(Contract.java:48)
	at feign.ReflectiveFeign$ParseHandlersByName.apply(ReflectiveFeign.java:143)
	at feign.ReflectiveFeign.newInstance(ReflectiveFeign.java:58)
	at feign.Feign$Builder.target(Feign.java:265)
	at feign.Feign$Builder.target(Feign.java:261)
	at org.springframework.cloud.netflix.feign.FeignClientFactoryBean.loadBalance(FeignClientFactoryBean.java:123)
	at org.springframework.cloud.netflix.feign.FeignClientFactoryBean.getObject(FeignClientFactoryBean.java:136)
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:168)
	... 24 common frames omitted

Exception in thread "main" org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'bookingStatusEventListenerImpl': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: com.fm.nd.integration.rest.logistics.ServiceClient com.fm.nd.accounting.crud.event.BookingStatusEventListenerImpl.serviceClient; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'serviceClient': FactoryBean threw exception on object creation; nested exception is java.lang.NullPointerException
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:334)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1202)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:537)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:303)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:755)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:757)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:480)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:686)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:320)
	at com.fm.nd.accounting.Accounting.main(Accounting.java:36)
Caused by: org.springframework.beans.factory.BeanCreationException: Could not autowire field: com.fm.nd.integration.rest.logistics.ServiceClient com.fm.nd.accounting.crud.event.BookingStatusEventListenerImpl.serviceClient; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'serviceClient': FactoryBean threw exception on object creation; nested exception is java.lang.NullPointerException
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:561)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:331)
	... 14 more
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'serviceClient': FactoryBean threw exception on object creation; nested exception is java.lang.NullPointerException
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:175)
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.getObjectFromFactoryBean(FactoryBeanRegistrySupport.java:103)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getObjectForBeanInstance(AbstractBeanFactory.java:1517)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:251)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1120)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1044)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:942)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:533)
	... 16 more
Caused by: java.lang.NullPointerException
	at feign.RequestTemplate.allValuesAreNull(RequestTemplate.java:494)
	at feign.RequestTemplate.pullAnyQueriesOutOfUrl(RequestTemplate.java:476)
	at feign.RequestTemplate.append(RequestTemplate.java:207)
	at org.springframework.cloud.netflix.feign.support.SpringMvcContract.processAnnotationOnMethod(SpringMvcContract.java:65)
	at feign.Contract$BaseContract.parseAndValidatateMetadata(Contract.java:62)
	at feign.Contract$BaseContract.parseAndValidatateMetadata(Contract.java:48)
	at feign.ReflectiveFeign$ParseHandlersByName.apply(ReflectiveFeign.java:143)
	at feign.ReflectiveFeign.newInstance(ReflectiveFeign.java:58)
	at feign.Feign$Builder.target(Feign.java:265)
	at feign.Feign$Builder.target(Feign.java:261)
	at org.springframework.cloud.netflix.feign.FeignClientFactoryBean.loadBalance(FeignClientFactoryBean.java:123)
	at org.springframework.cloud.netflix.feign.FeignClientFactoryBean.getObject(FeignClientFactoryBean.java:136)
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:168)
	... 24 more
```

**Comment by beku8** [comment]
Apparently, there is some validation restrictions on the method annotations & "signatures". Could you give more hints on your answer? Should I write ```HttpMessageConverter<ParamMap>```? Should it implement read or write? What should the Client interface should look like?

**Comment by beku8** [comment]
Ok I think I've figured it out, by extending ```SpringEncoder```.
```
@Override
	public void encode(Object requestBody, RequestTemplate request)
			throws EncodeException {
		if(requestBody instanceof ParamMap){
			ParamMap paramMap = (ParamMap) requestBody;
			
			Map<String,Collection<String>> map = new HashMap<>(request.queries());
			for (String key : paramMap.getMap().keySet()) {
				logger.debug("putting {}", key);
				map.put(key, Arrays.asList(paramMap.getMap().get(key)));
			}
			request.queries(map);
		}
		else{
			super.encode(requestBody, request);
		}
	}

```
and the config is 
```
	@Bean
	@Primary
	public CustomSpringEncoder customSpringEncoder(){
		return new CustomSpringEncoder();
	}
```
