### ISSUE TITLE
java.net.SocketException: Unexpected end of file from server while trying to fetch CONFIG-SERVER using EUREKA in CONFIG-CLIENT

### ISSUE THREAD

**Issue by HimanshubhusanRath** [spring-cloud/spring-cloud-netflix#3121]
1. I am trying to discover a config-server using Eureka and fetch the configurations for my client application.
2. My config-server is running on port **8000** and is registered as a discovery client with Eureka server.
3. I can see the configurations in a browser by using '_http://localhost:8000/student-service/default_' (no profile is set, so 'default' profile).
4. But, when I try to start my client application(student-service), I get the following error:

 ---------------------

2018-08-03 16:24:04.042 ERROR 27650 --- [           main] o.s.boot.SpringApplication               : **Application startup failed**

java.lang.IllegalStateException: Could not locate PropertySource and the fail fast property is set, failing
	at org.springframework.cloud.config.client.ConfigServicePropertySourceLocator.locate(ConfigServicePropertySourceLocator.java:130) ~[spring-cloud-config-client-1.2.3.RELEASE.jar:1.2.3.RELEASE]
	at org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration.initialize(PropertySourceBootstrapConfiguration.java:89) ~[spring-cloud-context-1.1.8.RELEASE.jar:1.1.8.RELEASE]
	at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:633) [spring-boot-1.4.0.RELEASE.jar:1.4.0.RELEASE]
	at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:347) [spring-boot-1.4.0.RELEASE.jar:1.4.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:311) [spring-boot-1.4.0.RELEASE.jar:1.4.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1185) [spring-boot-1.4.0.RELEASE.jar:1.4.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1174) [spring-boot-1.4.0.RELEASE.jar:1.4.0.RELEASE]
	at com.hr.ms.studentservice.main.StudentServiceMainApplication.main(StudentServiceMainApplication.java:18) [classes/:na]
**Caused by: org.springframework.web.client.ResourceAccessException: I/O error on GET request for "http://localhost:8000/student-service/default": Unexpected end of file from server; nested exception is java.net.SocketException: Unexpected end of file from server**
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:633) ~[spring-web-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:580) ~[spring-web-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:498) ~[spring-web-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.cloud.config.client.ConfigServicePropertySourceLocator.getRemoteEnvironment(ConfigServicePropertySourceLocator.java:170) ~[spring-cloud-config-client-1.2.3.RELEASE.jar:1.2.3.RELEASE]
	at org.springframework.cloud.config.client.ConfigServicePropertySourceLocator.locate(ConfigServicePropertySourceLocator.java:91) ~[spring-cloud-config-client-1.2.3.RELEASE.jar:1.2.3.RELEASE]
	... 7 common frames omitted
Caused by: **java.net.SocketException: Unexpected end of file from server**
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:851) ~[na:1.8.0_151]
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678) ~[na:1.8.0_151]
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:848) ~[na:1.8.0_151]
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678) ~[na:1.8.0_151]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1587) ~[na:1.8.0_151]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492) ~[na:1.8.0_151]
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480) ~[na:1.8.0_151]
	at org.springframework.http.client.SimpleBufferingClientHttpRequest.executeInternal(SimpleBufferingClientHttpRequest.java:84) ~[spring-web-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:48) ~[spring-web-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:53) ~[spring-web-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:619) ~[spring-web-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	... 11 common frames omitted

-----------------------

I am using:
- **Spring Boot : 1.4.0.RELEASE
- Spring Cloud : Camden.SR6**

Can somebody please help me ?

**Comment by HimanshubhusanRath** [comment]
The issue is resolved now. 

The port number **8000** was the reason for this issue. After changing the config server port number from **8000** to **8101**, everything is working fine. :)

Don't have any idea what was wrong with 8000 though.
