### ISSUE TITLE
Load balancer does not have available server for client

### ISSUE THREAD

**Issue by bhargodevarya** [spring-cloud/spring-cloud-netflix#3193]
I am evaluating Spring cloud for my current project.
Currently I am trying my hands at eureka with zuul using Spring.

code repo: https://github.com/bhargodevarya/SpringEurekaServer

I created a simple spring boot application that creates an HTTP url that returns some data.
I registered this application in eureka.
I can see that my service is registered properly in the eureka discovery server.
Also, I can see the zuul service registered there.

In my Zuul logs I can see the following:
2018-09-17 00:45:35.690  INFO 23421 --- [nio-8762-exec-1] o.s.c.n.zuul.web.ZuulHandlerMapping      : Mapped URL path [/userservice/**] onto handler of type [class org.springframework.cloud.netflix.zuul.web.ZuulController]

but when it tries to get the information I get the following log:

2018-09-17 00:45:36.266  INFO 23421 --- [nio-8762-exec-1] c.netflix.loadbalancer.BaseLoadBalancer  : Client: **userservice instantiated a LoadBalancer: DynamicServerListLoadBalancer:{NFLoadBalancer:name=userservice,current list of Servers=[],Load balancer stats=Zone stats: {},Server stats: []}ServerList:null**
2018-09-17 00:45:36.279  INFO 23421 --- [nio-8762-exec-1] c.n.l.DynamicServerListLoadBalancer      : Using serverListUpdater PollingServerListUpdater
2018-09-17 00:45:36.291  INFO 23421 --- [nio-8762-exec-1] c.n.l.DynamicServerListLoadBalancer      : DynamicServerListLoadBalancer for **client userservice initialized: DynamicServerListLoadBalancer:{NFLoadBalancer:name=userservice,current list of Servers=[],Load balancer stats=Zone stats: {},Server stats:** []}ServerList:org.springframework.cloud.netflix.ribbon.eureka.DomainExtractingServerList@56e94d19

![image](https://user-images.githubusercontent.com/16055491/45599918-9dd51d00-ba11-11e8-910b-d47831e216b8.png)

but when I hit the url http://localhost:8762/userservice/user/setup in my browser, I get the below exception

com.netflix.zuul.exception.ZuulException: Forwarding error
        at org.springframework.cloud.netflix.zuul.filters.route.RibbonRoutingFilter.handleException(RibbonRoutingFilter.java:189) ~[spring-cloud-netflix-zuul-2.0.1.RELEASE.jar:2.0.1.RELEASE]
        at org.springframework.cloud.netflix.zuul.filters.route.RibbonRoutingFilter.forward(RibbonRoutingFilter.java:164) ~[spring-cloud-netflix-zuul-2.0.1.RELEASE.jar:2.0.1.RELEASE]
        at org.springframework.cloud.netflix.zuul.filters.route.RibbonRoutingFilter.run(RibbonRoutingFilter.java:112) ~[spring-cloud-netflix-zuul-2.0.1.RELEASE.jar:2.0.1.RELEASE]
......
......
Caused by: com.netflix.client.ClientException: Load balancer does not have available server for client: userservice
        at com.netflix.loadbalancer.LoadBalancerContext.getServerFromLoadBalancer(LoadBalancerContext.java:483) ~[ribbon-loadbalancer-2.2.5.jar:2.2.5]

I have given my code repo link above.
Can some one please have a look ?

**Comment by ryanjbaxter** [comment]
Please learn how to [format code on GitHub](https://help.github.com/articles/creating-and-highlighting-code-blocks/).

Your "user service" application does not have `spring.application.name` set.

**Comment by spencergibb** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by bhargodevarya** [comment]
Apologies for the late comment, but what Ryan mentioned fixed my issue. Thanks a lot.
