### ISSUE TITLE
Registe with security error

### ISSUE THREAD

**Issue by zhaijp** [spring-cloud/spring-cloud-netflix#3197]
**My Environment is:**

springboot : <version>2.0.1.RELEASE</version>
springcloud:<version>Finchley.RELEASE</version>

**Eureka Server config:**
logging.level.org.springframework.web=DEBUG
eureka.server.renewal-percent-threshold=0.85
eureka.client.fetchRegistry=true
spring.security.user.name=admin
eureka.server.enable-self-preservation=false
spring.security.user.password=123456
server.port=7890
test.value=test
eureka.client.registerWithEureka=true
spring.application.name=eureka-server
eureka.instance.prefer-ip-address=true

**Eureka Client config:**
.....
eureka.client.serviceUrl.defaultZone=http://admin:123456@192.168.80.71:${server.port}/eureka/

**My Question:**
when the client startup it  registe failed and throw Exception next:

2018-09-19 13:20:18.804  WARN [-,,,] 100652 --- [nfoReplicator-0] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_EUREKA-SERVER/DEMO1:eureka-server:7890 - registration failed Cannot execute request on any known server

com.netflix.discovery.shared.transport.TransportException: Cannot execute request on any known server
	at com.netflix.discovery.shared.transport.decorator.RetryableEurekaHttpClient.execute(RetryableEurekaHttpClient.java:112) ~[eureka-client-1.9.2.jar!/:1.9.2]
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.register(EurekaHttpClientDecorator.java:56) ~[eureka-client-1.9.2.jar!/:1.9.2]
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$1.execute(EurekaHttpClientDecorator.java:59) ~[eureka-client-1.9.2.jar!/:1.9.2]
	at com.netflix.discovery.shared.transport.decorator.SessionedEurekaHttpClient.execute(SessionedEurekaHttpClient.java:77) ~[eureka-client-1.9.2.jar!/:1.9.2]
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.register(EurekaHttpClientDecorator.java:56) ~[eureka-client-1.9.2.jar!/:1.9.2]
	at com.netflix.discovery.DiscoveryClient.register(DiscoveryClient.java:829) ~[eureka-client-1.9.2.jar!/:1.9.2]
	at com.netflix.discovery.InstanceInfoReplicator.run(InstanceInfoReplicator.java:121) [eureka-client-1.9.2.jar!/:1.9.2]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_131]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_131]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_131]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]

**Comment by zhaijp** [comment]
@royclarkson can you help me

**Comment by zhaijp** [comment]
@yuanych 我看你之前也遇到了这个问题，你解决了吗?

**Comment by royclarkson** [comment]
@zhaijp is this using [Spring Cloud Services](https://docs.pivotal.io/spring-cloud-services/2-0/common/index.html)?

**Comment by zhaijp** [comment]
yes is springcloud @royclarkson

**Comment by ryanjbaxter** [comment]
Spring Cloud Services is different than Spring Cloud

**Comment by spencergibb** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
