### ISSUE TITLE
spring cloud  RejectedExecutionException 

### ISSUE THREAD

**Issue by peachyy** [spring-cloud/spring-cloud-netflix#3214]
spring cloud version： Dalston.SR3
springboot version：1.5.7.RELEASE

--------------------------------------------------------------------------

eureka client properties
----------------------------------------------------------------------------------------------

`
eureka.client.healthcheck.enabled=true

eureka.instance.leaseRenewalIntervalInSeconds=10

eureka.instance.leaseExpirationDurationInSeconds=30

eureka.instance.statusPageUrlPath=/info

eureka.instance.healthCheckUrlPath=/health

eureka.instance.prefer-ip-address=true

eureka.instance.instance-id=${spring.cloud.client.ipAddress}:${server.port}

eureka.client.serviceUrl.defaultZone=http://testweb1:8761/eureka/,http://testweb2:8761/eureka/

eureka.client.registry-fetch-interval-seconds=10

spring.cloud.inetutils.ignored-interfaces[0]=docker0

spring.cloud.inetutils.ignored-interfaces[1]=veth.*

`
------------------------------------------------------------------------------------------------------------

09:57:56,778 [INFO ] [XNIO-2 task-13] [AutowiredAnnotationBeanPostProcessor] JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
09:57:56,778 [INFO ] [XNIO-2 task-13] [AutowiredAnnotationBeanPostProcessor] JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
09:57:56,927 [INFO ] [XNIO-2 task-13] [ConfigServicePropertySourceLocator] Fetching config from server at: http://testweb1:8771
09:57:56,927 [INFO ] [XNIO-2 task-13] [ConfigServicePropertySourceLocator] Fetching config from server at: http://testweb1:8771
09:57:57,123 [INFO ] [XNIO-2 task-13] [SpringApplication] No active profile set, falling back to default profiles: default
09:57:57,123 [INFO ] [XNIO-2 task-13] [SpringApplication] No active profile set, falling back to default profiles: default
09:57:57,136 [INFO ] [XNIO-2 task-13] [AutowiredAnnotationBeanPostProcessor] JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
09:57:57,136 [INFO ] [XNIO-2 task-13] [AutowiredAnnotationBeanPostProcessor] JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
09:57:57,178 [INFO ] [XNIO-2 task-13] [SpringApplication] Started application in 0.535 seconds (JVM running for 91.854)
09:57:57,178 [INFO ] [XNIO-2 task-13] [SpringApplication] Started application in 0.535 seconds (JVM running for 91.854)
09:57:57,444 [INFO ] [XNIO-2 task-13] [servlet] jolokia: No access restrictor found, access to any MBean is allowed
09:57:57,466 [INFO ] [XNIO-2 task-13] [servlet] jolokia: Jolokia Discovery MBean registration is skipped because there is already one registered.
09:57:57,554 [INFO ] [XNIO-2 task-13] [DiscoveryClient] Shutting down DiscoveryClient ...
09:57:57,554 [INFO ] [XNIO-2 task-13] [InstanceInfoFactory] Setting initial instance status as: STARTING
09:57:57,554 [INFO ] [XNIO-2 task-13] [InstanceInfoFactory] Setting initial instance status as: STARTING
09:57:57,555 [INFO ] [XNIO-2 task-13] [DiscoveryClient] Unregistering ...
09:57:57,558 [INFO ] [XNIO-2 task-13] [DiscoveryClient] DiscoveryClient_STYLE-APP/192.168.0.222:8766 - deregister status: 200
09:57:57,559 [INFO ] [XNIO-2 task-13] [DiscoveryClient] Completed shut down of DiscoveryClient
09:57:57,560 [INFO ] [XNIO-2 task-13] [DiscoveryClient] Initializing Eureka in region us-east-1
09:57:57,562 [INFO ] [XNIO-2 task-13] [DiscoveryJerseyProvider] Using JSON encoding codec LegacyJacksonJson
09:57:57,562 [INFO ] [XNIO-2 task-13] [DiscoveryJerseyProvider] Using JSON decoding codec LegacyJacksonJson
09:57:57,562 [INFO ] [XNIO-2 task-13] [DiscoveryJerseyProvider] Using XML encoding codec XStreamXml
09:57:57,562 [INFO ] [XNIO-2 task-13] [DiscoveryJerseyProvider] Using XML decoding codec XStreamXml
09:57:57,614 [INFO ] [XNIO-2 task-13] [ConfigClusterResolver] Resolving eureka endpoints via configuration
09:57:57,615 [INFO ] [XNIO-2 task-13] [DiscoveryClient] Disable delta property : false
09:57:57,615 [INFO ] [XNIO-2 task-13] [DiscoveryClient] Single vip registry refresh property : null
09:57:57,615 [INFO ] [XNIO-2 task-13] [DiscoveryClient] Force full registry fetch : false
09:57:57,615 [INFO ] [XNIO-2 task-13] [DiscoveryClient] Application is null : false
09:57:57,615 [INFO ] [XNIO-2 task-13] [DiscoveryClient] Registered Applications size is zero : true
09:57:57,615 [INFO ] [XNIO-2 task-13] [DiscoveryClient] Application version is -1: true
09:57:57,615 [INFO ] [XNIO-2 task-13] [DiscoveryClient] Getting all instance registry info from the eureka server
09:57:57,618 [INFO ] [XNIO-2 task-13] [DiscoveryClient] The response status is 200
09:57:57,618 [INFO ] [XNIO-2 task-13] [DiscoveryClient] Starting heartbeat executor: renew interval is: 10
09:57:57,619 [INFO ] [XNIO-2 task-13] [InstanceInfoReplicator] InstanceInfoReplicator onDemand update allowed rate per min is 4
09:57:57,619 [INFO ] [XNIO-2 task-13] [DiscoveryClient] Discovery Client initialized at timestamp 1538013477619 with initial instances count: 11
09:57:57,619 [INFO ] [XNIO-2 task-13] [EurekaServiceRegistry] Unregistering application style-app with eureka with status DOWN
09:57:57,619 [INFO ] [XNIO-2 task-13] [EurekaServiceRegistry] Unregistering application style-app with eureka with status DOWN
09:57:57,620 [INFO ] [XNIO-2 task-13] [EurekaServiceRegistry] Registering application style-app with eureka with status UP
09:57:57,620 [INFO ] [XNIO-2 task-13] [EurekaServiceRegistry] Registering application style-app with eureka with status UP
09:57:57,620 [WARN ] [XNIO-2 task-13] [DiscoveryClient] Saw local status change event StatusChangeEvent [timestamp=1538013477620, current=UP, previous=DOWN]
09:57:57,620 [INFO ] [DiscoveryClient-InstanceInfoReplicator-0] [DiscoveryClient] DiscoveryClient_STYLE-APP/192.168.0.222:8766: registering service...
09:57:57,621 [ERROR] [XNIO-2 task-13] [GlobalExceptionSupport] Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@571831ff rejected from java.util.concurrent.ScheduledThreadPoolExecutor@1
1bd4e3e[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 6]
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@571831ff rejected from java.util.concurrent.ScheduledThreadPoolExecutor@11bd4e3e[Termin
ated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 6]
at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:326)
at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:533)
at java.util.concurrent.ScheduledThreadPoolExecutor.submit(ScheduledThreadPoolExecutor.java:632)
at com.netflix.discovery.InstanceInfoReplicator.onDemandUpdate(InstanceInfoReplicator.java:77)
at com.netflix.discovery.DiscoveryClient.registerHealthCheck(DiscoveryClient.java:618)
at com.netflix.discovery.DiscoveryClient$$FastClassBySpringCGLIB$$a84c8cb4.invoke(<generated>)
at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:738)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
at org.springframework.cloud.context.config.StandardBeanLifecycleDecorator$2.invoke(StandardBeanLifecycleDecorator.java:85)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:673)
at org.springframework.cloud.netflix.eureka.CloudEurekaClient$$EnhancerBySpringCGLIB$$8cad547a.registerHealthCheck(<generated>)
at org.springframework.cloud.netflix.eureka.serviceregistry.EurekaServiceRegistry.register(EurekaServiceRegistry.java:49)
at org.springframework.cloud.netflix.eureka.serviceregistry.EurekaAutoServiceRegistration.start(EurekaAutoServiceRegistration.java:73)
at org.springframework.cloud.netflix.eureka.EurekaDiscoveryClientConfiguration$EurekaClientConfigurationRefresher.onApplicationEvent(EurekaDiscoveryClientConfiguration.java:79)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:256)
at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:177)
at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:140)
at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:393)
at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:347)
at org.springframework.cloud.context.scope.refresh.RefreshScope.refreshAll(RefreshScope.java:146)
at org.springframework.cloud.context.refresh.ContextRefresher.refresh(ContextRefresher.java:58)
at org.springframework.cloud.endpoint.RefreshEndpoint.refresh(RefreshEndpoint.java:46)
at org.springframework.cloud.endpoint.RefreshEndpoint.invoke(RefreshEndpoint.java:52)
at org.springframework.cloud.endpoint.RefreshEndpoint.invoke(RefreshEndpoint.java:33)
at org.springframework.boot.actuate.endpoint.mvc.AbstractEndpointMvcAdapter.invoke(AbstractEndpointMvcAdapter.java:56)
at org.springframework.boot.actuate.endpoint.mvc.EndpointMvcAdapter.invoke(EndpointMvcAdapter.java:42)
at org.springframework.cloud.endpoint.GenericPostableMvcEndpoint.invoke(GenericPostableMvcEndpoint.java:49)
at sun.reflect.GeneratedMethodAccessor286.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)
at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:85)
at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
at com.hyzh.os.app.config.MyFilter.doFilter(MyFilter.java:55)
at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:110)
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)

**Comment by peachyy** [comment]
已处理
