### ISSUE TITLE
Document The Need To Add JAXB Dependencies When Using JDK 11

### ISSUE THREAD

**Issue by joshlong** [spring-cloud/spring-cloud-netflix#3244]
`@EnableEurekaServer` in `org.springframework.cloud`:`spring-cloud-starter-netflix-eureka-server` requires JAXB which no longer exists on Java 11

 ```
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBContext
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[na:na]
	at java.base/java.lang.Class.forName0(Native Method) ~[na:na]
	at java.base/java.lang.Class.forName(Class.java:398) ~[na:na]
	at java.base/sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:114) ~[na:na]
```

**Comment by ryanjbaxter** [comment]
@joshlong we have to support those that use jdk 11 and those that dont.  For now if you are using JDK 11 you will have to include the jars in your pom.
