### ISSUE TITLE
springcloud Finchley.SR2 创建Eureka server无法启动

### ISSUE THREAD

**Issue by happyqingye** [spring-cloud/spring-cloud-netflix#3285]
创建Eureka server，启动时一直报错，错误提示：
Caused by: java.lang.NullPointerException: null        at com.thoughtworks.xstream.converters.reflection.SunUnsafeReflectionProvider.writeField(SunUnsafeReflectionProvider.java:56) ~[xstream-1.4.10.jar:1.4.10]        at com.thoughtworks.xstream.core.JVM.<clinit>(JVM.java:97) ~[xstream-1.4.10.jar:1.4.10]
--
pom配置：

         <parent>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter-parent</artifactId>
                <version>2.1.0.RELEASE</version>
                <relativePath/> 
        </parent>
......
                <dependency>
                        <groupId>org.springframework.cloud</groupId>
                        <artifactId>spring-cloud-starter-netflix-eureka-server</artifactId>
                </dependency>
.......
        <dependencyManagement>
                <dependencies>
                        <dependency>
                                <groupId>org.springframework.cloud</groupId>
                                <artifactId>spring-cloud-dependencies</artifactId>
                                <version>Finchley.SR2</version>
                                <type>pom</type>
                                <scope>import</scope>
                        </dependency>
                </dependencies>
        </dependencyManagement>

通过调试进行定位，发现依赖的xstream-1.4.10.jar版本存在问题，当type为Test.class时，导致SunLimitedUnsafeReflectionProvider的newInstance(Class type)始终返回null，而null导致了NullPointerException

解决方法：
pom中升级xstream-1.4.10.jar ->xstream-1.4.11.1.jar

备注：官网下载的样例也无法直接执行，存在相同的问题

**Comment by happyqingye** [comment]
升级xstream-1.4.10.jar ->xstream-1.4.11.1.jar
