### ISSUE TITLE
Eureka server on docker in Mac:Cannot find localhost ip

### ISSUE THREAD

**Issue by imyxiao** [spring-cloud/spring-cloud-netflix#3298]
I used to run eureka server on docker, works fine in linux(ubuntu or centos)

eureka server bootstrap.yml:
```yml
eureka:
  environment: ${spring.profiles.active}
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/
```
docker run:
```bash
docker run --name eureka-server --net=host -e "JAVA_OPTS=-Xmx300m" -d docker_image_name
```
when I use mac
```java
2018-12-03 06:26:31.676  INFO 1 --- [           main] c.n.eureka.DefaultEurekaServerContext    [63 ]: Initializing ...
2018-12-03 06:26:31.680  INFO 1 --- [           main] c.n.eureka.cluster.PeerEurekaNodes       [188]: Adding new peer nodes [http://user:password@localhost:8761/eureka/]
2018-12-03 06:26:31.925  INFO 1 --- [           main] c.n.d.provider.DiscoveryJerseyProvider   [70 ]: Using JSON encoding codec LegacyJacksonJson
2018-12-03 06:26:31.926  INFO 1 --- [           main] c.n.d.provider.DiscoveryJerseyProvider   [71 ]: Using JSON decoding codec LegacyJacksonJson
2018-12-03 06:26:31.926  INFO 1 --- [           main] c.n.d.provider.DiscoveryJerseyProvider   [80 ]: Using XML encoding codec XStreamXml
2018-12-03 06:26:31.927  INFO 1 --- [           main] c.n.d.provider.DiscoveryJerseyProvider   [81 ]: Using XML decoding codec XStreamXml
2018-12-03 06:26:32.118  WARN 1 --- [           main] c.n.e.transport.JerseyReplicationClient  [172]: Cannot find localhost ip

java.net.UnknownHostException: linuxkit-025000000001: linuxkit-025000000001: System error
	at java.net.InetAddress.getLocalHost(InetAddress.java:1506)
	at com.netflix.eureka.transport.JerseyReplicationClient.createReplicationClient(JerseyReplicationClient.java:170)
	at com.netflix.eureka.cluster.PeerEurekaNodes.createPeerEurekaNode(PeerEurekaNodes.java:199)
	at com.netflix.eureka.cluster.PeerEurekaNodes.updatePeerEurekaNodes(PeerEurekaNodes.java:190)
	at com.netflix.eureka.cluster.PeerEurekaNodes.start(PeerEurekaNodes.java:88)
	at com.netflix.eureka.DefaultEurekaServerContext.initialize(DefaultEurekaServerContext.java:64)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
```
`/etc/hosts` inside docker container:
```shell
$ docker exec -it eureka-server cat /etc/hosts
127.0.0.1       localhost
::1     localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
```
I can solve the problem by commenting out ` prefer-ip-address: true`.

**Comment by imyxiao** [comment]
i think it docker's problem

**Comment by imyxiao** [comment]
`-net=host` not supported in mac 😭
