### ISSUE TITLE
Weblogic - Error required a bean of type 'com.netflix.discovery.EurekaClient' that could not be found.

### ISSUE THREAD

**Issue by claudineigomes** [spring-cloud/spring-cloud-netflix#3503]
I have putted in Application class:
@EnableDiscoveryClient
@EnableEurekaClient

Error Running in WEBLOGIC:
```
2019-04-15 14:11:02.845 [traceId=:correlationId=:msisdn=]  WARN 14797 --- [ (self-tuning)'] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'instanceDiscovery' defined in org.springframework.cloud.netflix.turbine.TurbineHttpConfiguration$EurekaTurbineConfiguration: Unsatisfied dependency expressed through method 'instanceDiscovery' parameter 1; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.netflix.discovery.EurekaClient' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
2019-04-15 14:11:02.970 [traceId=:correlationId=:msisdn=]  INFO 14797 --- [ (self-tuning)'] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2019-04-15 14:11:03.231 [traceId=:correlationId=:msisdn=] ERROR 14797 --- [ (self-tuning)'] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 1 of method instanceDiscovery in org.springframework.cloud.netflix.turbine.TurbineHttpConfiguration$EurekaTurbineConfiguration required a bean of type 'com.netflix.discovery.EurekaClient' that could not be found.


Action:

Consider defining a bean of type 'com.netflix.discovery.EurekaClient' in your configuration.

<15/04/2019 14h11min03s,SSS COT> <Error> <Deployer> <BEA-149265> <Failure occurred in the execution of deployment request with ID "3903865757582169" for task "83" on [partition-name: DOMAIN]. Error is: "weblogic.application.ModuleException: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.netflix.discovery.EurekaClient' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}"
weblogic.application.ModuleException: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.netflix.discovery.EurekaClient' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
	at weblogic.application.internal.ExtensibleModuleWrapper.start(ExtensibleModuleWrapper.java:140)
	at weblogic.application.internal.flow.ModuleListenerInvoker.start(ModuleListenerInvoker.java:124)
	at weblogic.application.internal.flow.ModuleStateDriver$3.next(ModuleStateDriver.java:233)
	at weblogic.application.internal.flow.ModuleStateDriver$3.next(ModuleStateDriver.java:228)
	at weblogic.application.utils.StateMachineDriver.nextState(StateMachineDriver.java:45)
	Truncated. see log file for complete stacktrace
Caused By: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.netflix.discovery.EurekaClient' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoMatchingBeanFound(DefaultListableBeanFactory.java:1506)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1101)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1062)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:818)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:724)
	Truncated. see log file for complete stacktrace
```

**Comment by spencergibb** [comment]
You don't need both annotations, just one, they are equivalent.

That said, you've not provided versions, dependencies or configuration.

**Comment by spencergibb** [comment]
Please learn how to properly [format code and logs](https://help.github.com/articles/creating-and-highlighting-code-blocks/).

**Comment by claudineigomes** [comment]
My bootstrap.yml
```
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
´´´

Dependencies:
```
<dependency>
	<groupId>org.springframework.cloud</groupId>
	<artifactId>spring-cloud-starter-turbine</artifactId>
	<version>1.4.6.RELEASE</version>
</dependency>

<dependency>
	<groupId>org.springframework.cloud</groupId>
	<artifactId>spring-cloud-starter-netflix-hystrix-dashboard</artifactId>
	<version>2.0.0.RELEASE</version>
</dependency>
´´´

**Comment by spencergibb** [comment]
That is incomplete.

That said, versions 1.x and 2.x of spring cloud are incompatible.

**Comment by claudineigomes** [comment]
I changed to the same version and the error continue:

```
Description:

Parameter 1 of method instanceDiscovery in org.springframework.cloud.netflix.turbine.TurbineHttpConfiguration$EurekaTurbineConfiguration required a bean of type 'com.netflix.discovery.EurekaClient' that could not be found.


Action:

Consider defining a bean of type 'com.netflix.discovery.EurekaClient' in your configuration.
´´´

**Comment by claudineigomes** [comment]
Remembering that this error only happen when i run in WEBLOGIC SERVER 12.2.1.3 :(

**Comment by spencergibb** [comment]
Meaning it doesn't happen when?

**Comment by claudineigomes** [comment]
Doesn't happen when I run in tomcat embed in spring boot ...

**Comment by spencergibb** [comment]
Not sure what I can do there.
