### ISSUE TITLE
HttpTraceFilter bean missing when using Eureka Server

### ISSUE THREAD

**Issue by marcingrzejszczak** [spring-cloud/spring-cloud-netflix#3528]
For latest snapshots, when running the contract samples I started getting

```
[ERROR] org.springframework.cloud.contract.stubrunner.spring.cloud.eureka.StubRunnerSpringCloudEurekaAutoConfigurationSpec  Time elapsed: 4.376 s  <<< ERROR!
org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is org.springframework.boot.web.server.WebServerException: Unable to start embedded Tomcat
    at org.springframework.cloud.contract.stubrunner.spring.cloud.eureka.StubRunnerSpringCloudEurekaAutoConfigurationSpec.setupSpec(StubRunnerSpringCloudEurekaAutoConfigurationSpec.groovy:79)
Caused by: org.springframework.boot.web.server.WebServerException: Unable to start embedded Tomcat
    at org.springframework.cloud.contract.stubrunner.spring.cloud.eureka.StubRunnerSpringCloudEurekaAutoConfigurationSpec.setupSpec(StubRunnerSpringCloudEurekaAutoConfigurationSpec.groovy:79)
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'traceFilterRegistration' defined in class path resource [org/springframework/cloud/netflix/eureka/server/EurekaServerAutoConfiguration.class]: Unsatisfied dependency expressed through method 'traceFilterRegistration' parameter 0; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'javax.servlet.Filter' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Qualifier(value="httpTraceFilter")}
    at org.springframework.cloud.contract.stubrunner.spring.cloud.eureka.StubRunnerSpringCloudEurekaAutoConfigurationSpec.setupSpec(StubRunnerSpringCloudEurekaAutoConfigurationSpec.groovy:79)
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'javax.servlet.Filter' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Qualifier(value="httpTraceFilter")}
    at org.springframework.cloud.contract.stubrunner.spring.cloud.eureka.StubRunnerSpringCloudEurekaAutoConfigurationSpec.setupSpec(StubRunnerSpringCloudEurekaAutoConfigurationSpec.groovy:79)
```

in order to work around this I needed to add a filter with that name:

```
@Configuration
    @EnableAutoConfiguration
    @EnableEurekaServer
    static class EurekaServer {

        @Bean
        Filter httpTraceFilter() {
            return new Filter() {
                @Override
                void init(FilterConfig filterConfig) throws ServletException {

                }

                @Override
                void doFilter(ServletRequest servletRequest, ServletResponse servletResponse, FilterChain filterChain) throws IOException, ServletException {
                    filterChain.doFilter(servletRequest, servletResponse)
                }

                @Override
                void destroy() {

                }
            }
        }


    }
```

**Comment by ztomic** [comment]
I'm having same problem, my workaround:
```java
@ConditionalOnMissingBean
@Bean
public HttpTraceRepository httpTraceRepository() {
  return new InMemoryHttpTraceRepository();
}
```

**Comment by dsyer** [comment]
Should be easy to fix - just add a `@Conditional` to that bean definition that is failing.
