### ISSUE TITLE
Eureka Server not reachable when deployed as war

### ISSUE THREAD

**Issue by gicat** [spring-cloud/spring-cloud-netflix#3567]
Spring Boot **2.1.5.RELEASE**
Spring Cloud **Greenwich.SR1**
Java **8**
Tomcat **apache-tomcat-9.0.20**

Eureka has the following error when deployed as war
```
08:48:58.034 [main] DEBUG o.s.w.s.v.f.FreeMarkerConfigurer - Cannot resolve template loader path [classpath:/templates/] to [java.io.File]: using SpringTemplateLoader as fallback
java.io.FileNotFoundException: class path resource [templates/] cannot be resolved to absolute file path because it does not reside in the file system: jar:file:/D:/Java/apache-tomcat-9.0.20Bis/webapps/eureka-server/WEB-INF/lib/spring-cloud-netflix-eureka-server-2.1.0.RELEASE.jar!/templates/
        at org.springframework.util.ResourceUtils.getFile(ResourceUtils.java:217)
```
After this error the server seems to start correctly, Eureka's home page is reachable.
When I try to start a Zuul server on Tomcat it fails with the following error
```
2019-06-14 08:49:14.230  WARN 21012 --- [           main] c.n.d.s.t.d.RetryableEurekaHttpClient    : Request execution failure with status code 404; retrying on another server if available
2019-06-14 08:49:14.241 ERROR 21012 --- [           main] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_GATEWAY-SERVER/xxxxx.yyyy:gateway-server:8080 - was unable to refresh its cache! status = Cannot execute request on any known server

com.netflix.discovery.shared.transport.TransportException: Cannot execute request on any known server
	at com.netflix.discovery.shared.transport.decorator.RetryableEurekaHttpClient.execute(RetryableEurekaHttpClient.java:112) ~[eureka-client-1.9.8.jar:1.9.8]
```
The same zuul server can connect to a Eureka Server that starts with an executable jar.

I have shared the two services here https://github.com/gicat/spring_cloud_issues
Am I missing some configuration?
Thanks.
Giuseppe

**Comment by spencergibb** [comment]
The first is a `DEBUG` statement and has no bearing.

When you deploy eureka as a war into tomcat, unless you change the context to ROOT, eureka won't be at `http://localhost:8761/eureka/` and you have to update that url in zuul to point at the proper context.

**Comment by gicat** [comment]
Thank you, now it works correctly.
Regards,
Giuseppe
