### ISSUE TITLE
Ribbon - RestTemplate Error

### ISSUE THREAD

**Issue by aivans** [spring-cloud/spring-cloud-netflix#357]
related to  #350 probably

I get this error:
```
Caused by: java.io.IOException: com.sun.jersey.api.client.ClientHandlerException: org.apache.http.client.ClientProtocolException
        at org.springframework.cloud.netflix.ribbon.RibbonClientHttpRequestFactory$RibbonHttpRequest.executeInternal(RibbonClientHttpRequestFactory.java:125) ~[spring-cloud-netflix-core-1.0.3.BUILD-SNAPSHOT.jar:1.0.3.BUILD-SNAPSHOT]
        at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:53) ~[spring-web-4.1.2.RELEASE.jar:4.1.2.RELEASE]
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:568) ~[spring-web-4.1.2.RELEASE.jar:4.1.2.RELEASE]
        ... 122 common frames omitted
Caused by: com.sun.jersey.api.client.ClientHandlerException: org.apache.http.client.ClientProtocolException
        at com.sun.jersey.client.apache4.ApacheHttpClient4Handler.handle(ApacheHttpClient4Handler.java:184) ~[jersey-apache-client4-1.11.jar:1.11]
        at com.sun.jersey.api.client.Client.handle(Client.java:648) ~[jersey-client-1.11.jar:1.11]
        at com.sun.jersey.api.client.WebResource.handle(WebResource.java:670) ~[jersey-client-1.11.jar:1.11]
        at com.sun.jersey.api.client.WebResource.access$200(WebResource.java:74) ~[jersey-client-1.11.jar:1.11]
        at com.sun.jersey.api.client.WebResource$Builder.post(WebResource.java:563) ~[jersey-client-1.11.jar:1.11]
        at com.netflix.niws.client.http.RestClient.execute(RestClient.java:621) ~[ribbon-httpclient-2.0.0.jar:2.0.0]
        at com.netflix.niws.client.http.RestClient.execute(RestClient.java:527) ~[ribbon-httpclient-2.0.0.jar:2.0.0]
        at org.springframework.cloud.netflix.ribbon.RibbonClientHttpRequestFactory$RibbonHttpRequest.executeInternal(RibbonClientHttpRequestFactory.java:122) ~[spring-cloud-netflix-core-1.0.3.BUILD-SNAPSHOT.jar:1.0.3.BUILD-SNAPSHOT]
        ... 124 common frames omitted
Caused by: org.apache.http.client.ClientProtocolException: null
        at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:867) ~[httpclient-4.3.6.jar:4.3.6]
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:115) ~[httpclient-4.3.6.jar:4.3.6]
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57) ~[httpclient-4.3.6.jar:4.3.6]
        at com.sun.jersey.client.apache4.ApacheHttpClient4Handler.handle(ApacheHttpClient4Handler.java:170) ~[jersey-apache-client4-1.11.jar:1.11]
        ... 131 common frames omitted
Caused by: org.apache.http.ProtocolException: Content-Length header already present
        at org.apache.http.protocol.RequestContent.process(RequestContent.java:95) ~[httpcore-4.3.3.jar:4.3.3]
        at org.apache.http.protocol.ImmutableHttpProcessor.process(ImmutableHttpProcessor.java:131) ~[httpcore-4.3.3.jar:4.3.3]
        at org.apache.http.protocol.HttpRequestExecutor.preProcess(HttpRequestExecutor.java:165) ~[httpcore-4.3.3.jar:4.3.3]
        at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:485) ~[httpclient-4.3.6.jar:4.3.6]
        at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:863) ~[httpclient-4.3.6.jar:4.3.6]
        ... 134 common frames omitted
```

I saw that RestTemplate sets the Contet-Length header:
```
				if (httpHeaders.getContentLength() == -1) {
					httpHeaders.setContentLength(0L);
				}
```

HttpCore 4.3.3 (through dependencies) is used and here is the code:
http://grepcode.com/file/repo1.maven.org/maven2/org.apache.httpcomponents/httpcore/4.3.3/org/apache/http/protocol/RequestContent.java#RequestContent
```
                 if (request.containsHeader(HTTP.TRANSFER_ENCODING)) {

                     throw new ProtocolException("Transfer-encoding header already present");

                 }
```

**Comment by aivans** [comment]
More details:

- Request is a POST with null body
- RestTemplate detects that it has no body and adds the ContentLongthe header:
```
			if (!requestEntity.hasBody()) {
				HttpHeaders httpHeaders = httpRequest.getHeaders();
				HttpHeaders requestHeaders = requestEntity.getHeaders();
				if (!requestHeaders.isEmpty()) {
					httpHeaders.putAll(requestHeaders);
				}
				if (httpHeaders.getContentLength() == -1) {
					httpHeaders.setContentLength(0L);
				}
			}
```
- HttpClient complains

**Comment by aivans** [comment]
Hi guys,

does anyone else have the same issue?

**Comment by spencergibb** [comment]
@aivans how are you using `RestTemplate`?  Something like `restTemplate.postForEntity("http://simple/emptypost", null, String.class)`?  Even [curl](http://stackoverflow.com/questions/2885274/post-with-curl-without-sending-data#comment-32877025) requires empty data.  If I change my call to `restTemplate.postForEntity("http://simple/emptypost", "", String.class)`, the test passes.  In other words, post an empty body, not null.

**Comment by spencergibb** [comment]
The only thing we could really do, is in `RibbonClientHttpRequestFactory$RibbonHttpRequest.executeInternal` test if the body is null and remove the content length header which seems hackish to me.

**Comment by aivans** [comment]
@spencergibb  let me try with empty body

**Comment by spencergibb** [comment]
Closed for lack of feedback. Please, reopen if there is something new to add.

**Comment by zhuhw** [comment]
Using an empty body solved my problem! Thanks!

**Comment by aivans** [comment]
Thank you for letting us know.

**Comment by kristofferpeterhansel** [comment]
So. I just ran into this updating to 1.0.3. It seems to be a fairly poor workaround to require empty content since the RestOperations interface specifically states that 'null' is allowed on calls like postForObject.

I don't really know about the responsibility domains at work here. So I don't know if you can fault Spring Web for doing this or not. The code, at least, seem to have a clear mission to buffer the output and make sure the request can be sent un-chunked.

**Comment by qerub** [comment]
I also ran into this today and can confirm what @kristofferpeterhansel added in his edit: the empty string does not work any better than `null`.

**Comment by steve-oakey** [comment]
I have also encountered this problem this week as well. An empty String body will work as long as the `RestTemplate` has no `ClientHttpRequestInterceptor`s. If there is an interceptor, the `RequestExecution` from the `InterceptingClientHttpRequest` in `spring-web` will only copy the body (`byte[]`) if the length is > 0.

We solved (hacked) this by adding a body with a String of "null" (it would have to be just a single byte).

**Comment by tkvangorder** [comment]
We have run into this issue as well. We had already had a modified version of the RibbonHttpRequestFactory and I was able to work around this issue by modifying RibbonRetryHttpRequestFactory.RibbonHttpRequest.addHeaders() method.

@spencergibb How do you feel about making this change? : 

```
		private void addHeaders(HttpHeaders headers) {
			for (String name : headers.keySet()) {
				// apache http RequestContent pukes if there is a body and
				// the dynamic headers are already present
				if (isDynamic(name) && outputStream != null) {
					continue;
				}
				//Don't add content-length if the output stream is null. The RibbonClient does this for us. 
				if (name.equals("Content-Length") && outputStream == null) {
					continue;
				}
				List<String> values = headers.get(name);
				for (String value : values) {
					builder.header(name, value);
				}
			}
		}

```
