### ISSUE TITLE
"java.net.SocketTimeoutException: Read timed out" when using Feign against a Spring Boot application on the same JVM

### ISSUE THREAD

**Issue by alvarosanchez** [spring-cloud/spring-cloud-netflix#358]
I have a Spring Boot application with a REST Repository from Spring Data REST. It's essentially the Persons example from http://spring.io/guides/gs/accessing-data-rest/. I also have Spring Security where the requests get authenticated by decoding a JWT coming from an HTTP Header.

So far so good. If I make a request to any endpoint with a correct JWT, it returns me the correct JSON.

Now, on top of that I wrote the following Feign client:

```groovy
@FeignClient("content-platform")
@RequestMapping("/rest")
interface ContentPlatformClient {

    @RequestMapping(value = "/persons", method = RequestMethod.POST)
    ResponseEntity<Person> createPerson(Person person)

}
```

The specification is:

```groovy
@ContextConfiguration(loader = SpringApplicationContextLoader, classes = TestingContentPlatformApplication)
@WebIntegrationTest
class FooSpec extends Specification {

    @Autowired
    ContentPlatformClient client

    void "it can use Feign"() {
        Person person = new Person(firstName: 'Alvaro', lastName: 'Sanchez')

        when:
        def response = client.createPerson(person)

        then:
        response
    }
}
```

And the `TestingContentPlatformApplication` is:

```groovy
@SpringBootApplication
@EnableFeignClients
@CompileStatic
class TestingContentPlatformApplication extends ContentPlatformApplication {

    static void main(String[] args) {
        SpringApplication.run(TestingContentPlatformApplication, args)
    }

    @Bean
    public RequestInterceptor oauthHeader() {
        String token = generateAccessToken()
        return { RequestTemplate template ->
            template.header("Authorization", "Bearer ${token}")
        } as RequestInterceptor
    }

    @Bean
    Logger.Level logger() {
        Logger.Level.FULL
    }

}
```

I have the Ribbon configuration pointing to `locahost:8080`.

The first part of the output is this:

```
   15:04:46.186 [Test worker] DEBUG o.s.c.n.feign.support.SpringEncoder - Writing [com.odobo.platform.content.domain.Person@60722bbd] using [org.springframework.http.converter.json.MappingJackson2HttpMessageConverter@61469ee0]
    15:04:46.209 [Test worker] DEBUG c.o.p.c.client.ContentPlatformClient - [ContentPlatformClient#createPerson] ---> POST http://content-platform/rest/persons HTTP/1.1
    15:04:46.209 [Test worker] DEBUG c.o.p.c.client.ContentPlatformClient - [ContentPlatformClient#createPerson] Content-Length: 53
    15:04:46.209 [Test worker] DEBUG c.o.p.c.client.ContentPlatformClient - [ContentPlatformClient#createPerson] Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJwcmluY2lwYWwiOiJzYW1wbGUtcHJpbmNpcGFsIiwic3ViIjoic2FtcGxlLWFwcGxpY2F0aW9uIiwiZXhwIjoxNDMyMjk5ODcxLCJyb2xlcyI6WyJST0xFX09ET0JPX0FQUCJdfQ.Nc3tyYb50u5a6AOZDSWY7XFk055D-IBpjxUVDdcvklQ
    15:04:46.209 [Test worker] DEBUG c.o.p.c.client.ContentPlatformClient - [ContentPlatformClient#createPerson] 
    15:04:46.209 [Test worker] DEBUG c.o.p.c.client.ContentPlatformClient - [ContentPlatformClient#createPerson] {"id":null,"firstName":"Alvaro","lastName":"Sanchez"}
    15:04:46.209 [Test worker] DEBUG c.o.p.c.client.ContentPlatformClient - [ContentPlatformClient#createPerson] ---> END HTTP (53-byte body)
    15:04:46.211 [Test worker] INFO  o.s.c.a.AnnotationConfigApplicationContext - Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@7595afdc: startup date [Thu May 21 15:04:46 CEST 2015]; parent: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@750b022a
    15:04:46.290 [Test worker] INFO  o.s.b.f.a.AutowiredAnnotationBeanPostProcessor - JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
    15:04:46.420 [Test worker] INFO  c.n.config.ChainedDynamicProperty - Flipping property: content-platform.ribbon.ActiveConnectionsLimit to use NEXT property: niws.loadbalancer.availabilityFilteringRule.activeConnectionsLimit = 2147483647
    15:04:46.549 [Test worker] INFO  c.n.loadbalancer.BaseLoadBalancer - Client:content-platform instantiated a LoadBalancer:DynamicServerListLoadBalancer:{NFLoadBalancer:name=content-platform,current list of Servers=[],Load balancer stats=Zone stats: {},Server stats: []}ServerList:null
    15:04:46.585 [Test worker] INFO  c.n.config.ChainedDynamicProperty - Flipping property: content-platform.ribbon.ActiveConnectionsLimit to use NEXT property: niws.loadbalancer.availabilityFilteringRule.activeConnectionsLimit = 2147483647
    15:04:46.588 [Test worker] INFO  c.n.l.DynamicServerListLoadBalancer - DynamicServerListLoadBalancer for client content-platform initialized: DynamicServerListLoadBalancer:{NFLoadBalancer:name=content-platform,current list of Servers=[localhost:8080],Load balancer stats=Zone stats: {unknown=[Zone:unknown;	Instance count:1;	Active connections count: 0;	Circuit breaker tripped count: 0;	Active connections per server: 0.0;]
    },Server stats: [[Server:localhost:8080;	Zone:UNKNOWN;	Total Requests:0;	Successive connection failure:0;	Total blackout seconds:0;	Last connection made:Thu Jan 01 01:00:00 CET 1970;	First connection made: Thu Jan 01 01:00:00 CET 1970;	Active Connections:0;	total failure count in last (1000) msecs:0;	average resp time:0.0;	90 percentile resp time:0.0;	95 percentile resp time:0.0;	min resp time:0.0;	max resp time:0.0;	stddev resp time:0.0]
    ]}ServerList:com.netflix.loadbalancer.ConfigurationBasedServerList@41e2f3f2
    15:04:46.842 [Test worker] INFO  c.n.http4.ConnectionPoolCleaner - Initializing ConnectionPoolCleaner for NFHttpClient:content-platform
    15:04:47.268 [Test worker] INFO  c.n.http4.ConnectionPoolCleaner - Initializing ConnectionPoolCleaner for NFHttpClient:content-platform
    15:04:47.555 [pool-4-thread-1] INFO  c.n.config.ChainedDynamicProperty - Flipping property: content-platform.ribbon.ActiveConnectionsLimit to use NEXT property: niws.loadbalancer.availabilityFilteringRule.activeConnectionsLimit = 2147483647
    15:04:47.715 [http-nio-8080-exec-1] INFO  o.a.c.c.C.[Tomcat].[localhost].[/] - Initializing Spring FrameworkServlet 'dispatcherServlet'
    15:04:47.715 [http-nio-8080-exec-1] INFO  o.s.web.servlet.DispatcherServlet - FrameworkServlet 'dispatcherServlet': initialization started
    15:04:47.743 [http-nio-8080-exec-1] INFO  o.s.web.servlet.DispatcherServlet - FrameworkServlet 'dispatcherServlet': initialization completed in 28 ms
    15:04:47.847 [http-nio-8080-exec-1] INFO  o.s.b.a.audit.listener.AuditListener - AuditEvent [timestamp=Thu May 21 15:04:47 CEST 2015, principal=sample-application, type=AUTHENTICATION_SUCCESS, data={details=remoteAddress=127.0.0.1, tokenType=BearertokenValue=<TOKEN>}]
```

But immediately after, the client floods the server with more requests:

```
    15:04:47.874 [http-nio-8080-exec-1] DEBUG o.s.c.n.feign.support.SpringEncoder - Writing [com.odobo.platform.content.domain.Person@27a3b607] using [org.springframework.http.converter.json.MappingJackson2HttpMessageConverter@61469ee0]
    15:04:47.875 [http-nio-8080-exec-1] DEBUG c.o.p.c.client.ContentPlatformClient - [ContentPlatformClient#createPerson] ---> POST http://content-platform/rest/persons HTTP/1.1
    15:04:47.875 [http-nio-8080-exec-1] DEBUG c.o.p.c.client.ContentPlatformClient - [ContentPlatformClient#createPerson] Content-Length: 44
    15:04:47.875 [http-nio-8080-exec-1] DEBUG c.o.p.c.client.ContentPlatformClient - [ContentPlatformClient#createPerson] Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJwcmluY2lwYWwiOiJzYW1wbGUtcHJpbmNpcGFsIiwic3ViIjoic2FtcGxlLWFwcGxpY2F0aW9uIiwiZXhwIjoxNDMyMjk5ODcxLCJyb2xlcyI6WyJST0xFX09ET0JPX0FQUCJdfQ.Nc3tyYb50u5a6AOZDSWY7XFk055D-IBpjxUVDdcvklQ
    15:04:47.875 [http-nio-8080-exec-1] DEBUG c.o.p.c.client.ContentPlatformClient - [ContentPlatformClient#createPerson] 
    15:04:47.875 [http-nio-8080-exec-1] DEBUG c.o.p.c.client.ContentPlatformClient - [ContentPlatformClient#createPerson] {"id":null,"firstName":null,"lastName":null}
    15:04:47.875 [http-nio-8080-exec-1] DEBUG c.o.p.c.client.ContentPlatformClient - [ContentPlatformClient#createPerson] ---> END HTTP (44-byte body)
    15:04:47.888 [http-nio-8080-exec-2] INFO  o.s.b.a.audit.listener.AuditListener - AuditEvent [timestamp=Thu May 21 15:04:47 CEST 2015, principal=sample-application, type=AUTHENTICATION_SUCCESS, data={details=remoteAddress=127.0.0.1, tokenType=BearertokenValue=<TOKEN>}]
```

After a while, all the requests start to fail and the client retries again:

```
    15:05:47.642 [Test worker] DEBUG c.o.p.c.client.ContentPlatformClient - [ContentPlatformClient#createPerson] <--- ERROR SocketTimeoutException: Read timed out (61434ms)
    15:05:47.643 [Test worker] DEBUG c.o.p.c.client.ContentPlatformClient - [ContentPlatformClient#createPerson] java.net.SocketTimeoutException: Read timed out
    	at java.net.SocketInputStream.socketRead0(Native Method)
    	at java.net.SocketInputStream.read(SocketInputStream.java:150)
    	at java.net.SocketInputStream.read(SocketInputStream.java:121)
    	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
    	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
    	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
    	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:703)
    	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:647)
    	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1535)
    	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440)
    	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
    	at feign.Client$Default.convertResponse(Client.java:143)
    	at feign.Client$Default.execute(Client.java:70)
    	at feign.ribbon.LBClient.execute(LBClient.java:69)
    	at feign.ribbon.LBClient.execute(LBClient.java:38)
    	at com.netflix.client.AbstractLoadBalancerAwareClient$1.call(AbstractLoadBalancerAwareClient.java:109)
    	at com.netflix.loadbalancer.reactive.LoadBalancerCommand$3$1.call(LoadBalancerCommand.java:303)
    	at com.netflix.loadbalancer.reactive.LoadBalancerCommand$3$1.call(LoadBalancerCommand.java:287)
    	at rx.internal.operators.OperatorMap$1.onNext(OperatorMap.java:54)
    	at rx.internal.util.ScalarSynchronousObservable$1.call(ScalarSynchronousObservable.java:41)
    	at rx.internal.util.ScalarSynchronousObservable$1.call(ScalarSynchronousObservable.java:30)
    	at rx.Observable$2.call(Observable.java:173)
    	at rx.Observable$2.call(Observable.java:166)
    	at rx.Observable$2.call(Observable.java:173)
    	at rx.Observable$2.call(Observable.java:166)
    	at rx.Observable.unsafeSubscribe(Observable.java:8591)
    	at rx.internal.operators.OperatorConcat$ConcatSubscriber.subscribeNext(OperatorConcat.java:163)
    	at rx.internal.operators.OperatorConcat$ConcatSubscriber.onNext(OperatorConcat.java:128)
    	at rx.internal.operators.OperatorConcat$ConcatSubscriber.onNext(OperatorConcat.java:65)
    	at rx.internal.operators.OperatorMap$1.onNext(OperatorMap.java:54)
    	at com.netflix.loadbalancer.reactive.LoadBalancerCommand$1.call(LoadBalancerCommand.java:185)
    	at com.netflix.loadbalancer.reactive.LoadBalancerCommand$1.call(LoadBalancerCommand.java:180)
    	at rx.Observable$2.call(Observable.java:173)
    	at rx.Observable$2.call(Observable.java:166)
    	at rx.Observable$2.call(Observable.java:173)
    	at rx.Observable$2.call(Observable.java:166)
    	at rx.Observable$2.call(Observable.java:173)
    	at rx.Observable$2.call(Observable.java:166)
    	at rx.Observable$2.call(Observable.java:173)
    	at rx.Observable$2.call(Observable.java:166)
    	at rx.Observable.subscribe(Observable.java:8680)
    	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:452)
    	at rx.observables.BlockingObservable.single(BlockingObservable.java:348)
    	at com.netflix.client.AbstractLoadBalancerAwareClient.executeWithLoadBalancer(AbstractLoadBalancerAwareClient.java:102)
    	at feign.ribbon.RibbonClient.execute(RibbonClient.java:69)
    	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:92)
    	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:71)
    	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:94)
    	at com.sun.proxy.$Proxy117.createPerson(Unknown Source)
    	at com.odobo.platform.content.client.ContentPlatformClient$createPerson.call(Unknown Source)
    	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
    	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:110)
    	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:122)
    	at com.odobo.platform.content.FooSpec.$spock_feature_0_1(FooSpec.groovy:40)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:483)
    	at org.spockframework.util.ReflectionUtil.invokeMethod(ReflectionUtil.java:153)
    	at org.spockframework.runtime.model.MethodInfo.invoke(MethodInfo.java:84)
    	at org.spockframework.runtime.BaseSpecRunner.invokeRaw(BaseSpecRunner.java:480)
    	at org.spockframework.runtime.BaseSpecRunner.invoke(BaseSpecRunner.java:463)
    	at org.spockframework.runtime.BaseSpecRunner.runFeatureMethod(BaseSpecRunner.java:405)
    	at org.spockframework.runtime.BaseSpecRunner.doRunIteration(BaseSpecRunner.java:324)
    	at org.spockframework.runtime.BaseSpecRunner$6.invoke(BaseSpecRunner.java:309)
    	at org.spockframework.runtime.BaseSpecRunner.invokeRaw(BaseSpecRunner.java:480)
    	at org.spockframework.runtime.BaseSpecRunner.invoke(BaseSpecRunner.java:463)
    	at org.spockframework.runtime.BaseSpecRunner.runIteration(BaseSpecRunner.java:288)
    	at org.spockframework.runtime.BaseSpecRunner.initializeAndRunIteration(BaseSpecRunner.java:278)
    	at org.spockframework.runtime.BaseSpecRunner.runSimpleFeature(BaseSpecRunner.java:269)
    	at org.spockframework.runtime.BaseSpecRunner.doRunFeature(BaseSpecRunner.java:263)
    	at org.spockframework.runtime.BaseSpecRunner$5.invoke(BaseSpecRunner.java:246)
    	at org.spockframework.runtime.BaseSpecRunner.invokeRaw(BaseSpecRunner.java:480)
    	at org.spockframework.runtime.BaseSpecRunner.invoke(BaseSpecRunner.java:463)
    	at org.spockframework.runtime.BaseSpecRunner.runFeature(BaseSpecRunner.java:238)
    	at org.spockframework.runtime.BaseSpecRunner.runFeatures(BaseSpecRunner.java:188)
    	at org.spockframework.runtime.BaseSpecRunner.doRunSpec(BaseSpecRunner.java:98)
    	at org.spockframework.runtime.BaseSpecRunner$1.invoke(BaseSpecRunner.java:84)
    	at org.spockframework.runtime.BaseSpecRunner.invokeRaw(BaseSpecRunner.java:480)
    	at org.spockframework.runtime.BaseSpecRunner.invoke(BaseSpecRunner.java:463)
    	at org.spockframework.runtime.BaseSpecRunner.runSpec(BaseSpecRunner.java:76)
    	at org.spockframework.runtime.BaseSpecRunner.run(BaseSpecRunner.java:67)
    	at org.spockframework.runtime.Sputnik.run(Sputnik.java:63)
    	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:86)
    	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:49)
    	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:64)
    	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:50)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:483)
    	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
    	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
    	at org.gradle.messaging.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
    	at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
    	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
    	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:106)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:483)
    	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
    	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
    	at org.gradle.messaging.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:360)
    	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
    	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    	at java.lang.Thread.run(Thread.java:745)

    15:05:47.643 [Test worker] DEBUG c.o.p.c.client.ContentPlatformClient - [ContentPlatformClient#createPerson] <--- END ERROR
    15:05:47.794 [Test worker] DEBUG c.o.p.c.client.ContentPlatformClient - [ContentPlatformClient#createPerson] ---> RETRYING
```

I have tried the following, in all cases, without success:
* Using `feign.*` classes directly (without Spring).
* Using `OkHttpClient`.

However, if I remove the request interceptor, the response is received immediately:

```
    15:12:13.830 [Test worker] DEBUG c.o.p.c.client.ContentPlatformClient - [ContentPlatformClient#createPerson] <--- HTTP/1.1 401 Unauthorized (1204ms)
    15:12:13.830 [Test worker] DEBUG c.o.p.c.client.ContentPlatformClient - [ContentPlatformClient#createPerson] Transfer-Encoding: chunked
    15:12:13.830 [Test worker] DEBUG c.o.p.c.client.ContentPlatformClient - [ContentPlatformClient#createPerson] X-Frame-Options: DENY
    15:12:13.830 [Test worker] DEBUG c.o.p.c.client.ContentPlatformClient - [ContentPlatformClient#createPerson] Cache-Control: no-store
    15:12:13.830 [Test worker] DEBUG c.o.p.c.client.ContentPlatformClient - [ContentPlatformClient#createPerson] Cache-Control: no-cache, no-store, max-age=0, must-revalidate
    15:12:13.830 [Test worker] DEBUG c.o.p.c.client.ContentPlatformClient - [ContentPlatformClient#createPerson] Server: Apache-Coyote/1.1
    15:12:13.830 [Test worker] DEBUG c.o.p.c.client.ContentPlatformClient - [ContentPlatformClient#createPerson] X-Content-Type-Options: nosniff
    15:12:13.830 [Test worker] DEBUG c.o.p.c.client.ContentPlatformClient - [ContentPlatformClient#createPerson] WWW-Authenticate: Bearer realm="platform-content", error="unauthorized", error_description="Full authentication is required to access this resource"
    15:12:13.830 [Test worker] DEBUG c.o.p.c.client.ContentPlatformClient - [ContentPlatformClient#createPerson] Pragma: no-cache
    15:12:13.830 [Test worker] DEBUG c.o.p.c.client.ContentPlatformClient - [ContentPlatformClient#createPerson] Pragma: no-cache
    15:12:13.830 [Test worker] DEBUG c.o.p.c.client.ContentPlatformClient - [ContentPlatformClient#createPerson] Expires: 0
    15:12:13.830 [Test worker] DEBUG c.o.p.c.client.ContentPlatformClient - [ContentPlatformClient#createPerson] X-XSS-Protection: 1; mode=block
    15:12:13.830 [Test worker] DEBUG c.o.p.c.client.ContentPlatformClient - [ContentPlatformClient#createPerson] Date: Thu, 21 May 2015 13:12:13 GMT
    15:12:13.830 [Test worker] DEBUG c.o.p.c.client.ContentPlatformClient - [ContentPlatformClient#createPerson] Content-Type: application/json;charset=UTF-8
    15:12:13.830 [Test worker] DEBUG c.o.p.c.client.ContentPlatformClient - [ContentPlatformClient#createPerson] <--- END HTTP (0-byte body)
```

The last test I have done is spinning up a separately instance of the application on port 8081, and pointing Ribbon there. And the tests runs smoothly (with the header).

There must be something obvious here that I'm missing. Any ideas?

Thanks

**Comment by dsyer** [comment]
I can't see anything obvious. Maybe you could strip it down to a more minimal test case?

**Comment by alvarosanchez** [comment]
I'll try to create a reproducible application.

**Comment by spencergibb** [comment]
Closed for lack of feedback. Please, reopen if there is something new to add.
