### ISSUE TITLE
Intermittent "peer not authenticated" when forwarding route 

### ISSUE THREAD

**Issue by jayguidos** [spring-cloud/spring-cloud-netflix#3595]
I just finished an upgrade to Spring Cloud 2.1.2.RELEASE and OpenJDK 11.0.2

I am getting intermittent SSL handshake errors with "peer not authenticated".  It is always the same route, and seems to happen after a hitting the route for a while followed by a long pause. The route is unchanged and when using my old Zuul installation (Finchley and OpenJDK 8) it still works without problems.

The route is valid, since after getting the error (once) I can send to the route repeatedly with success.  It might be related to SSL caching and timeouts?  I turned on SSL handshake debugging and the handshake seems to proceed and then just.... abort.

I am also getting other timeouts from Zuul occasionally, but after a very only short time interval (like 1 or 2 seconds).  I can't figure out what is timing out or why, but the two problems may be related.  Can you give me any guidance here on how to triage this problem?

The following is a stack trace that Zuul dumps when getting the SSL error:

```
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 2019-07-11T17:15:43.000094Z WARN  o.s.c.n.z.f.p.SendErrorFilter Error during filtering
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | com.netflix.zuul.exception.ZuulException: Forwarding error
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at org.springframework.cloud.netflix.zuul.filters.route.SimpleHostRoutingFilter.handleException(SimpleHostRoutingFilter.java:257)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at org.springframework.cloud.netflix.zuul.filters.route.SimpleHostRoutingFilter.run(SimpleHostRoutingFilter.java:237)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at com.netflix.zuul.ZuulFilter.runFilter(ZuulFilter.java:117)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at com.netflix.zuul.FilterProcessor.processZuulFilter(FilterProcessor.java:193)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at com.netflix.zuul.FilterProcessor.runFilters(FilterProcessor.java:157)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at com.netflix.zuul.FilterProcessor.route(FilterProcessor.java:118)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at com.netflix.zuul.ZuulRunner.route(ZuulRunner.java:96)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at com.netflix.zuul.http.ZuulServlet.route(ZuulServlet.java:116)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at com.netflix.zuul.http.ZuulServlet.service(ZuulServlet.java:81)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at org.springframework.web.servlet.mvc.ServletWrappingController.handleRequestInternal(ServletWrappingController.java:165)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at org.springframework.cloud.netflix.zuul.web.ZuulController.handleRequest(ZuulController.java:45)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:52)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1039)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:897)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:882)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at org.springframework.boot.web.servlet.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:54)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:109)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at org.springframework.boot.actuate.web.trace.servlet.HttpTraceFilter.doFilterInternal(HttpTraceFilter.java:88)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:109)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:320)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:119)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:170)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilterInternal(BasicAuthenticationFilter.java:158)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:109)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at com.bids.http.session.authentication.jwt.JwtAuthenticationFilter.doFilterInternal(JwtAuthenticationFilter.java:61)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:109)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at org.springframework.security.web.csrf.CsrfFilter.doFilterInternal(CsrfFilter.java:100)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:109)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:74)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:109)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:109)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:357)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:270)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:109)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:92)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:109)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:109)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at org.springframework.session.web.http.SessionRepositoryFilter.doFilterInternal(SessionRepositoryFilter.java:151)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at org.springframework.session.web.http.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:85)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.filterAndRecordMetrics(WebMvcMetricsFilter.java:114)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:104)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:109)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:109)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:853)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1587)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at java.base/java.lang.Thread.run(Thread.java:834)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | Caused by: javax.net.ssl.SSLPeerUnverifiedException: peer not authenticated
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at java.base/sun.security.ssl.SSLSessionImpl.getPeerCertificates(SSLSessionImpl.java:526)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.verifyHostname(SSLConnectionSocketFactory.java:504)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:437)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:384)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:374)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:118)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at org.springframework.cloud.netflix.zuul.filters.route.SimpleHostRoutingFilter.forwardRequest(SimpleHostRoutingFilter.java:409)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at org.springframework.cloud.netflix.zuul.filters.route.SimpleHostRoutingFilter.forward(SimpleHostRoutingFilter.java:328)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	at org.springframework.cloud.netflix.zuul.filters.route.SimpleHostRoutingFilter.run(SimpleHostRoutingFilter.java:232)
api-gateway_main.1.icrd8vuz7ice@njodocker06.bidstrading.local    | 	... 110 common frames omitted

```

**Comment by jayguidos** [comment]
This issue didn't get a lot of feedback :) 
For those that may encounter this kind of problem, the issue root cause was many of our services are behind an haproxy instance.  The haproxy was terminating unused connections after 1 minute!  

The SimpleHostRoutingFilter sets up an Apache HTTP client with a connection pool but either the pool was not checking stale connections or the stale check was not reporting terminated sockets. If I set the connection pool to evict connections after 30 seconds of inactivity the problem went away.

I don't know what you could do to improve things here, but I have to admit the reported stack trace details did not offer much of a clue as to the underlying root cause.
