### ISSUE TITLE
How to run multiple instance eureka server with ssl?

### ISSUE THREAD

**Issue by whct1213zhysc** [spring-cloud/spring-cloud-netflix#3601]
- my eureka server config 
```
spring:
  application:
    name: ${EUREKA_APPLICATION_NAME:vlabs-center}
server:
  port: ${SERVER_PORT:8761}
  ssl:
    enabled: true
    key-store: ${SECURITY_KEY:classpath:ummi-dev-local.p12}
    key-store-name: ${SECURITY_KEY_NAME:ummi-dev-local.p12}
    key-store-password: ${SECURITY_KEY_PASSWORD:ummi123}
    key-store-type: ${SECURITY_KEY_TYPE:PKCS12}
    key-alias: ${SECURITY_KEY_ALIAS:ivhummi}
eureka:
  instance:
    hostname: ${EUREKA_HOST_NAME:vlabs-center}
    appname: ${spring.application.name}
    #prefer-ip-address: true
    #instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
  server:
    enable-self-preservation: ${SELF_PRESERVATION:false}
    eviction-interval-timer-in-ms: 1000
    responseCacheUpdateInvervalMs: 1000
  client:
    register-with-eureka: ${BOOL_REGISTER:false}
    fetchRegistry: ${BOOL_FETCH:false}
    serviceUrl:
      defaultZone: ${EUREKA_URL_LIST:https://vlabs-center:8761/eureka/}
```
- when i run multiple instance eureka server with ssl , it's hava error :
```
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:397) ~[na:1.8.0_212]
        at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:302) ~[na:1.8.0_212]
        at sun.security.validator.Validator.validate(Validator.java:262) ~[na:1.8.0_212]
        at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324) ~[na:1.8.0_212]
        at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229) ~[na:1.8.0_212]
        at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124) ~[na:1.8.0_212]
        at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1621) ~[na:1.8.0_212]
        ... 30 common frames omitted
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141) ~[na:1.8.0_212]
        at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126) ~[na:1.8.0_212]
        at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280) ~[na:1.8.0_212]
        at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:392) ~[na:1.8.0_212]
        ... 36 common frames omitted
```

**Comment by spencergibb** [comment]
This is a duplicate

**Comment by whct1213zhysc** [comment]
@spencergibb 
How to set my configuration?
because i run multiple instance eureka server, when a eureka server  registering to another eureka server  will prompt for the above error message

**Comment by spencergibb** [comment]
Maybe it's not a duplicate. Can you clarify what you mean by running multiple it doesn't work?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
