### ISSUE TITLE
Calling microservice using feign client from Zuul gateway filter

### ISSUE THREAD

**Issue by nirmalmedicare** [spring-cloud/spring-cloud-netflix#3644]
I have a validation service which needs to be called before every request, and if the validation fails I want to return the result from gateway itselh,so I am trying to call it using feign-client from my Zuul gateway filter. It is giving me some exception and not able to make the call

I have tried creating a proxy of my service to be called and enabled it as a fegin client.

Run method of my Zuul filter. This filter is of type "pre"
  @Autowired
    private ValidationServiceProxy proxy;

        public Object run()  {

            try {

            RequestContext ctx = RequestContext.getCurrentContext();

            HttpServletRequest request =ctx.getRequest();

        ctx.addZuulRequestHeader("interaction_id", "1000");

        String responseEntity= proxy.test(request);

        logger.info("Response"+responseEntity);

    }catch (Exception e) {
        e.printStackTrace();
    }
    return null;

}
My validation service proxy code

    @FeignClient(name="validation-service")
    public interface ValidationServiceProxy {

    @GetMapping("/api/v1/test")
    public String test(HttpServletRequest httpServletRequest);

        }
My controller code on the validation service.

      @GetMapping(value = "/test")
  @Consumes(MediaType.APPLICATION_FORM_URLENCODED)
  @Produces(MediaType.TEXT_PLAIN)
  public ResponseEntity<String> test(HttpServletRequest httpServletRequest) {

    String result = "Hello World";

    return ResponseEntity.ok().body(result);

}

    feign.codec.EncodeException: Could not write JSON: It is illegal to call this method if the current request is not in asynchronous mode (i.e. isAsyncStarted() returns false); nested exception is com.fasterxml.jackson.databind.JsonMappingException: It is illegal to call this method if the current request is not in asynchronous mode (i.e. isAsyncStarted() returns false) (through reference chain: org.springframework.cloud.netflix.zuul.filters.pre.Servlet30RequestWrapper["request"]->org.apache.catalina.connector.RequestFacade["asyncContext"])
        at feign.ReflectiveFeign$BuildEncodedTemplateFromArgs.resolve(ReflectiveFeign.java:376)
        at feign.ReflectiveFeign$BuildTemplateByResolvingArgs.create(ReflectiveFeign.java:224)
        at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:74)
        at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:103)
        at com.sun.proxy.$Proxy162.test(Unknown Source)
        at com.in28minutes.microservices.netflixzuulapigatewayserver.ZuulLoggingFilter.run(ZuulLoggingFilter.java:48)
        at com.netflix.zuul.ZuulFilter.runFilter(ZuulFilter.java:117)
        at com.netflix.zuul.FilterProcessor.processZuulFilter(FilterProcessor.java:193)
        at com.netflix.zuul.FilterProcessor.runFilters(FilterProcessor.java:157)
        at com.netflix.zuul.FilterProcessor.preRoute(FilterProcessor.java:133)
        at com.netflix.zuul.ZuulRunner.preRoute(ZuulRunner.java:105)
        at com.netflix.zuul.http.ZuulServlet.preRoute(ZuulServlet.java:125)
        at com.netflix.zuul.http.ZuulServlet.service(ZuulServlet.java:74)
        at org.springframework.web.servlet.mvc.ServletWrappingController.handleRequestInternal(ServletWrappingController.java:165)
        at org.springframework.cloud.netflix.zuul.web.ZuulController.handleRequest(ZuulController.java:45)
        at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:52)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1039)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:897)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:634)

**Comment by spencergibb** [comment]
Is that the full exception? It looks like that is a jackson error, what can we do about that?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
