### ISSUE TITLE
Hystrix Actuator endpoint is hardcoded

### ISSUE THREAD

**Issue by jaredpetersen** [spring-cloud/spring-cloud-netflix#3705]
**Describe the bug**
Actuator changed the endpoints to be prefixed with `/actuator` when they upgraded to Spring Boot 2. However, they also allowed developers to specify a custom prefix via a `management.endpoints.base-path` configuration so that it's possible to maintain the same endpoints before the upgrade.

When Spring Cloud Netflix was upgraded to deal with the new Actuator endpoints, one hardcoded path was replaced with another. Here's the [issue](https://github.com/spring-cloud/spring-cloud-netflix/issues/2784) and the corresponding [commit](https://github.com/spring-cloud/spring-cloud-netflix/commit/9b1d3b36fd09c7d7aadf472827575d96fa0d7a41).

This may be an issue with other Actuator endpoints as well.

Spring Cloud Netflix should be able to handle custom base path endpoints for Actuator.

Using Spring Boot 2.1.10.RELEASE and Spring Cloud Greenwich.SR2.

**Sample**
See commit for hardcoded hysterix endpoints.

As a result of this hardcoding, the InstanceMonitor cannot find the correct endpoint (IP address redacted):

```
2019-12-09 18:12:03,007 [InstanceMonitor] INFO  c.n.t.m.instance.InstanceMonitor - Removing monitor from StatsEventConsole: XXX.XX.XX.XXX:XXXXX default
2019-12-09 18:12:02,991 [InstanceMonitor] WARN  c.n.t.m.instance.InstanceMonitor - Stopping InstanceMonitor for: XXX.XX.XX.XXX:XXXXX default
com.netflix.turbine.monitor.instance.InstanceMonitor$MisconfiguredHostException: [{"timestamp":"2019-12-09T18:12:02.985+0000","status":404,"error":"Not Found","message":"Not Found","path":"/actuator/hystrix.stream"}]
	at com.netflix.turbine.monitor.instance.InstanceMonitor.init(InstanceMonitor.java:318)
	at com.netflix.turbine.monitor.instance.InstanceMonitor.access$100(InstanceMonitor.java:103)
	at com.netflix.turbine.monitor.instance.InstanceMonitor$2.call(InstanceMonitor.java:235)
	at com.netflix.turbine.monitor.instance.InstanceMonitor$2.call(InstanceMonitor.java:229)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by spencergibb** [comment]
Try setting `turbine.instanceUrlSuffix`.

This module has entered [maintenance mode](https://github.com/spring-cloud/spring-cloud-netflix#modules-in-maintenance-mode). This means that the Spring Cloud team will no longer be adding new features to the module. We will fix blocker bugs and security issues, and we will also consider and review small pull requests from the community.

**Comment by jaredpetersen** [comment]
That definitely worked. Just set `turbine.instanceUrlSuffix` to `hystrix.stream`. Guess I didn't read the code closely enough 😓 

Thanks for the quick response. Been looking for a solution all morning.
