### ISSUE TITLE
my application has run three days agao, but tody , my app get a process error,about eureka shut down

### ISSUE THREAD

**Issue by Boonearbear** [spring-cloud/spring-cloud-netflix#3807]
**Describe the bug**
my application has run three days agao, but tody , my app get a process error,about eureka shut down,check my app log , analysis ， another app to use  service  intercate to get my data,so my app down.

**log**
05-Jun-2020 08:47:48.334 INFO [Thread-14] org.apache.coyote.AbstractProtocol.pause Pausing ProtocolHandler ["http-nio-8081"]
2020-06-05 08:47:48.336  INFO 24990 --- [      Thread-12] ationConfigEmbeddedWebApplicationContext : Closing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@250ddab3: startup date [Tue Jun 02 01:07:12 CST 2020]; parent: org.springframework.context.annotation.AnnotationConfigApplicationContext@715c4648
2020-06-05 08:47:48.336 INFO  org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext Line:984 - Closing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@250ddab3: startup date [Tue Jun 02 01:07:12 CST 2020]; parent: org.springframework.context.annotation.AnnotationConfigApplicationContext@715c4648
2020-06-05 08:47:48.338  INFO 24990 --- [      Thread-12] o.s.c.n.e.s.EurekaServiceRegistry        : Unregistering application wygl-service-basics with eureka with status DOWN
2020-06-05 08:47:48.338 INFO  org.springframework.cloud.netflix.eureka.serviceregistry.EurekaServiceRegistry Line:64  - Unregistering application wygl-service-basics with eureka with status DOWN
2020-06-05 08:47:48.338  WARN 24990 --- [      Thread-12] com.netflix.discovery.DiscoveryClient    : Saw local status change event StatusChangeEvent [timestamp=1591318068338, current=DOWN, previous=UP]
2020-06-05 08:47:48.338 WARN  com.netflix.discovery.DiscoveryClient Line:1291 - Saw local status change event StatusChangeEvent [timestamp=1591318068338, current=DOWN, previous=UP]
2020-06-05 08:47:48.339  INFO 24990 --- [nfoReplicator-0] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_WYGL-SERVICE-BASICS/172.18.213.105:wygl-service-basics:8081: registering service...
2020-06-05 08:47:48.339  INFO 24990 --- [      Thread-12] s.c.a.AnnotationConfigApplicationContext : Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@a5d4d72: startup date [Tue Jun 02 01:07:45 CST 2020]; parent: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@250ddab3
2020-06-05 08:47:48.339 INFO  com.netflix.discovery.DiscoveryClient Line:804 - DiscoveryClient_WYGL-SERVICE-BASICS/172.18.213.105:wygl-service-basics:8081: registering service...
2020-06-05 08:47:48.339 INFO  org.springframework.context.annotation.AnnotationConfigApplicationContext Line:984 - Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@a5d4d72: startup date [Tue Jun 02 01:07:45 CST 2020]; parent: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@250ddab3
2020-06-05 08:47:48.355  INFO 24990 --- [nfoReplicator-0] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_WYGL-SERVICE-BASICS/172.18.213.105:wygl-service-basics:8081 - registration status: 204
2020-06-05 08:47:48.355 INFO  com.netflix.discovery.DiscoveryClient Line:813 - DiscoveryClient_WYGL-SERVICE-BASICS/172.18.213.105:wygl-service-basics:8081 - registration status: 204
2020-06-05 08:47:48.356  INFO 24990 --- [      Thread-12] o.s.c.support.DefaultLifecycleProcessor  : Stopping beans in phase 2147483647
2020-06-05 08:47:48.356 INFO  org.springframework.context.support.DefaultLifecycleProcessor Line:360 - Stopping beans in phase 2147483647
2020-06-05 08:47:48.377  INFO 24990 --- [      Thread-12] o.s.a.r.l.SimpleMessageListenerContainer : Waiting for workers to finish.
2020-06-05 08:47:48.377 INFO  org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer Line:937 - Waiting for workers to finish.
05-Jun-2020 08:47:48.386 INFO [Thread-14] org.apache.coyote.AbstractProtocol.pause Pausing ProtocolHandler ["ajp-nio-8019"]
05-Jun-2020 08:47:48.436 INFO [Thread-14] org.apache.catalina.core.StandardService.stopInternal Stopping service [Catalina]
2020-06-05 08:47:48.933  INFO 24990 --- [      Thread-12] o.s.a.r.l.SimpleMessageListenerContainer : Successfully waited for workers to finish.
2020-06-05 08:47:48.933 INFO  org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer Line:940 - Successfully waited for workers to finish.
2020-06-05 08:47:48.934  INFO 24990 --- [      Thread-12] o.s.c.support.DefaultLifecycleProcessor  : Stopping beans in phase 2147482647
2020-06-05 08:47:48.934 INFO  org.springframework.context.support.DefaultLifecycleProcessor Line:360 - Stopping beans in phase 2147482647
2020-06-05 08:47:48.937  INFO 24990 --- [      Thread-12] o.s.a.r.l.SimpleMessageListenerContainer : Waiting for workers to finish.
2020-06-05 08:47:48.937 INFO  org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer Line:937 - Waiting for workers to finish.
2020-06-05 08:47:49.897  INFO 24990 --- [      Thread-12] o.s.a.r.l.SimpleMessageListenerContainer : Successfully waited for workers to finish.
2020-06-05 08:47:49.897 INFO  org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer Line:940 - Successfully waited for workers to finish.
2020-06-05 08:47:49.897  INFO 24990 --- [      Thread-12] o.s.i.a.i.AmqpInboundChannelAdapter      : stopped inbound.springCloudBus.anonymous.clNQ3CkjQm67HjKZrjiztg
2020-06-05 08:47:49.897 INFO  org.springframework.integration.amqp.inbound.AmqpInboundChannelAdapter Line:137 - stopped inbound.springCloudBus.anonymous.clNQ3CkjQm67HjKZrjiztg
2020-06-05 08:47:49.898  INFO 24990 --- [      Thread-12] o.s.c.support.DefaultLifecycleProcessor  : Stopping beans in phase 0
2020-06-05 08:47:49.898 INFO  org.springframework.context.support.DefaultLifecycleProcessor Line:360 - Stopping beans in phase 0
2020-06-05 08:47:49.899  INFO 24990 --- [      Thread-12] o.s.i.endpoint.EventDrivenConsumer       : Removing {logging-channel-adapter:_org.springframework.integration.errorLogger} as a subscriber to the 'errorChannel' channel
2020-06-05 08:47:49.899 INFO  org.springframework.integration.endpoint.EventDrivenConsumer Line:108 - Removing {logging-channel-adapter:_org.springframework.integration.errorLogger} as a subscriber to the 'errorChannel' channel
2020-06-05 08:47:49.899  INFO 24990 --- [      Thread-12] o.s.i.channel.PublishSubscribeChannel    : Channel 'wygl-service-basics:8081.errorChannel' has 0 subscriber(s).
2020-06-05 08:47:49.899 INFO  org.springframework.integration.channel.PublishSubscribeChannel Line:81  - Channel 'wygl-service-basics:8081.errorChannel' has 0 subscriber(s).
2020-06-05 08:47:49.899  INFO 24990 --- [      Thread-12] o.s.i.endpoint.EventDrivenConsumer       : stopped _org.springframework.integration.errorLogger
2020-06-05 08:47:49.899 INFO  org.springframework.integration.endpoint.EventDrivenConsumer Line:154 - stopped _org.springframework.integration.errorLogger
2020-06-05 08:47:49.899  INFO 24990 --- [      Thread-12] o.s.c.support.DefaultLifecycleProcessor  : Stopping beans in phase -2147482648
2020-06-05 08:47:49.899 INFO  org.springframework.context.support.DefaultLifecycleProcessor Line:360 - Stopping beans in phase -2147482648
2020-06-05 08:47:49.902  INFO 24990 --- [      Thread-12] o.s.s.c.ThreadPoolTaskScheduler          : Shutting down ExecutorService 'taskScheduler'
2020-06-05 08:47:49.902 INFO  org.springframework.scheduling.concurrent.ThreadPoolTaskScheduler Line:203 - Shutting down ExecutorService 'taskScheduler'
2020-06-05 08:47:49.902  INFO 24990 --- [      Thread-12] o.s.i.monitor.IntegrationMBeanExporter   : Unregistering JMX-exposed beans on shutdown
2020-06-05 08:47:49.902 INFO  org.springframework.integration.monitor.IntegrationMBeanExporter Line:449 - Unregistering JMX-exposed beans on shutdown
2020-06-05 08:47:49.903  INFO 24990 --- [      Thread-12] o.s.i.monitor.IntegrationMBeanExporter   : Unregistering JMX-exposed beans
2020-06-05 08:47:49.903 INFO  org.springframework.integration.monitor.IntegrationMBeanExporter Line:243 - Unregistering JMX-exposed beans
2020-06-05 08:47:49.903  INFO 24990 --- [      Thread-12] o.s.i.monitor.IntegrationMBeanExporter   : Summary on shutdown: springCloudBusOutput
2020-06-05 08:47:49.903 INFO  org.springframework.integration.monitor.IntegrationMBeanExporter Line:375 - Summary on shutdown: springCloudBusOutput
2020-06-05 08:47:49.903  INFO 24990 --- [      Thread-12] o.s.i.monitor.IntegrationMBeanExporter   : Summary on shutdown: errorChannel
2020-06-05 08:47:49.903 INFO  org.springframework.integration.monitor.IntegrationMBeanExporter Line:375 - Summary on shutdown: errorChannel
2020-06-05 08:47:49.903  INFO 24990 --- [      Thread-12] o.s.i.monitor.IntegrationMBeanExporter   : Summary on shutdown: springCloudBusInput
2020-06-05 08:47:49.903 INFO  org.springframework.integration.monitor.IntegrationMBeanExporter Line:375 - Summary on shutdown: springCloudBusInput
2020-06-05 08:47:49.903  INFO 24990 --- [      Thread-12] o.s.i.monitor.IntegrationMBeanExporter   : Summary on shutdown: nullChannel
2020-06-05 08:47:49.903 INFO  org.springframework.integration.monitor.IntegrationMBeanExporter Line:375 - Summary on shutdown: nullChannel
2020-06-05 08:47:49.903  INFO 24990 --- [      Thread-12] o.s.i.monitor.IntegrationMBeanExporter   : Summary on shutdown: _org.springframework.integration.errorLogger.handler
2020-06-05 08:47:49.903 INFO  org.springframework.integration.monitor.IntegrationMBeanExporter Line:378 - Summary on shutdown: _org.springframework.integration.errorLogger.handler
2020-06-05 08:47:49.903  INFO 24990 --- [      Thread-12] o.s.j.e.a.AnnotationMBeanExporter        : Unregistering JMX-exposed beans on shutdown
2020-06-05 08:47:49.903 INFO  org.springframework.jmx.export.annotation.AnnotationMBeanExporter Line:449 - Unregistering JMX-exposed beans on shutdown
2020-06-05 08:47:49.903  INFO 24990 --- [      Thread-12] o.s.j.e.a.AnnotationMBeanExporter        : Unregistering JMX-exposed beans
2020-06-05 08:47:49.903 INFO  org.springframework.jmx.export.annotation.AnnotationMBeanExporter Line:243 - Unregistering JMX-exposed beans
2020-06-05 08:47:49.923  INFO 24990 --- [      Thread-12] s.c.a.AnnotationConfigApplicationContext : Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@4f4a930f: startup date [Tue Jun 02 02:00:59 CST 2020]; parent: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@250ddab3
2020-06-05 08:47:49.923 INFO  org.springframework.context.annotation.AnnotationConfigApplicationContext Line:984 - Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@4f4a930f: startup date [Tue Jun 02 02:00:59 CST 2020]; parent: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@250ddab3
2020-06-05 08:47:49.929  WARN 24990 --- [      Thread-12] s.c.a.AnnotationConfigApplicationContext : Exception thrown from ApplicationListener handling ContextClosedEvent

org.springframework.beans.factory.BeanCreationNotAllowedException: Error creating bean with name 'eurekaAutoServiceRegistration': Singleton bean creation not allowed while singletons of this factory are in destruction (Do not request a bean from a BeanFactory in a destroy method implementation!)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:216)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:308)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1080)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.getTargetBean(ApplicationListenerMethodAdapter.java:283)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:253)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:177)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:140)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:393)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:399)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:347)
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:991)
	at org.springframework.context.support.AbstractApplicationContext.close(AbstractApplicationContext.java:958)
	at org.springframework.cloud.context.named.NamedContextFactory.destroy(NamedContextFactory.java:76)
	at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:272)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:583)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:555)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:959)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:516)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingletons(DefaultListableBeanFactory.java:966)
	at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1032)
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1008)
	at org.springframework.context.support.AbstractApplicationContext$2.run(AbstractApplicationContext.java:929)

*****  quetiosn **********
1. witch problem cause my app down.
2,how to prevent this.
[Uploading app logs .txt…]()

**Comment by spencergibb** [comment]
spring cloud doesn't shut down applications

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
