### ISSUE TITLE
Getting error with Spring Boot 2.4.0

### ISSUE THREAD

**Issue by SledgeHammer01** [spring-cloud/spring-cloud-netflix#3930]
Using Spring Boot 2.4.0 and spring-cloud-starter-netflix-eureka-server 2.2.6.RELEASE, I get the following error on startup... works fine if I roll back to 2.3.6.RELEASE for Spring Boot.

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'configurationPropertiesBeans' defined in class path resource [org/springframework/cloud/autoconfigure/ConfigurationPropertiesRebinderAutoConfiguration.class]: Post-processing of merged bean definition failed; nested exception is java.lang.IllegalStateException: Failed to introspect Class [org.springframework.cloud.context.properties.ConfigurationPropertiesBeans] from ClassLoader [jdk.internal.loader.ClassLoaders$AppClassLoader@77556fd]

Caused by: java.lang.IllegalStateException: Failed to introspect Class [org.springframework.cloud.context.properties.ConfigurationPropertiesBeans] from ClassLoader [jdk.internal.loader.ClassLoaders$AppClassLoader@77556fd]

Caused by: java.lang.ClassNotFoundException: org.springframework.boot.context.properties.ConfigurationBeanFactoryMetadata
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[na:na]
```

**Comment by spencergibb** [comment]
Spring Cloud Hoxton is not compatible with boot 2.4.x

**Comment by spencergibb** [comment]
See https://github.com/spring-cloud/spring-cloud-release/milestones for the compatible release schedule for spring cloud 2020.0
