### ISSUE TITLE
Zuul original ServletRequest not passed to RequestDispatcher

### ISSUE THREAD

**Issue by andreasevers** [spring-cloud/spring-cloud-netflix#397]
Hi,

When an upstream microservice throws an exception, Zuul fails in processing this error:

>{"exceptionType":"ZuulException","message":"Filter threw Exception","stackTrace":"com.netflix.zuul.exception.ZuulException: Filter threw Exception
	at com.netflix.zuul.FilterProcessor.processZuulFilter(FilterProcessor.java:231)
	at com.netflix.zuul.FilterProcessor.runFilters(FilterProcessor.java:161)
	at com.netflix.zuul.FilterProcessor.postRoute(FilterProcessor.java:92)
	at com.netflix.zuul.ZuulRunner.postRoute(ZuulRunner.java:75)
	at com.netflix.zuul.http.ZuulServlet.postRoute(ZuulServlet.java:102)
	at com.netflix.zuul.http.ZuulServlet.service(ZuulServlet.java:84)
	at org.springframework.web.servlet.mvc.ServletWrappingController.handleRequestInternal(ServletWrappingController.java:158)
	at org.springframework.cloud.netflix.zuul.web.ZuulController.handleRequestInternal(ZuulController.java:43)
	at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:146)
	at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:50)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:966)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:857)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:734)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:842)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:847)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:295)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
	at org.springframework.boot.actuate.autoconfigure.EndpointWebMvcAutoConfiguration$ApplicationContextHeaderFilter.doFilterInternal(EndpointWebMvcAutoConfiguration.java:291)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
	at de.codecentric.boot.admin.web.EndpointCorsFilter.doFilterInternal(EndpointCorsFilter.java:63)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:77)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
	at com.pxs.gateway.SimpleCorsFilter.doFilter(SimpleCorsFilter.java:76)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
	at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:102)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:85)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
	at org.springframework.boot.actuate.autoconfigure.MetricFilterAutoConfiguration$MetricsFilter.doFilterInternal(MetricFilterAutoConfiguration.java:90)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
	at org.springframework.boot.context.web.ErrorPageFilter.doFilter(ErrorPageFilter.java:113)
	at org.springframework.boot.context.web.ErrorPageFilter.access$000(ErrorPageFilter.java:59)
	at org.springframework.boot.context.web.ErrorPageFilter$1.doFilterInternal(ErrorPageFilter.java:88)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.boot.context.web.ErrorPageFilter.doFilter(ErrorPageFilter.java:106)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:231)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:149)
	at org.jboss.modcluster.container.jbossweb.JBossWebContext$RequestListenerValve.event(JBossWebContext.java:91)
	at org.jboss.modcluster.container.jbossweb.JBossWebContext$RequestListenerValve.invoke(JBossWebContext.java:72)
	at org.jboss.as.web.security.SecurityContextAssociationValve.invoke(SecurityContextAssociationValve.java:169)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:145)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:97)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:102)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:344)
	at org.apache.coyote.ajp.AjpProcessor.process(AjpProcessor.java:490)
	at org.apache.coyote.ajp.AjpProtocol$AjpConnectionHandler.process(AjpProtocol.java:420)
	at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:926)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.UndeclaredThrowableException
	at org.springframework.util.ReflectionUtils.rethrowRuntimeException(ReflectionUtils.java:302)
	at org.springframework.cloud.netflix.zuul.filters.post.SendErrorFilter.run(SendErrorFilter.java:79)
	at com.netflix.zuul.ZuulFilter.runFilter(ZuulFilter.java:112)
	at com.netflix.zuul.FilterProcessor.processZuulFilter(FilterProcessor.java:197)
	... 65 more
**Caused by: javax.servlet.ServletException: JBWEB000239: Original SevletRequest or wrapped original ServletRequest not passed to RequestDispatcher in violation of SRV.8.2 and SRV.14.2.5.1**
	at org.apache.catalina.core.ApplicationDispatcher.checkSameObjects(ApplicationDispatcher.java:1129)
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:505)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:482)
	at org.springframework.cloud.netflix.zuul.filters.post.SendErrorFilter.run(SendErrorFilter.java:74)
	... 67 more
"}

This could be JBoss related.

Could it be that Zuul uses its own wrapper classes implementing the interface rather than the javax.servlet.http ones?

This could mean that you cannot pass then to RequestDispatcher.forward(), because the Servlet specification says that you must pass the original request/response or javax.servlet.http.HttpServlet.

**Comment by spencergibb** [comment]
Zuul does use wrapper classes.  I'm not aware of "the Servlet specification says that you must pass the original request/response or javax.servlet.http.HttpServlet" to `forward()`. JEE provides wrappers `javax.servlet.http.HttpServletRequestWrapper`.

According to the docs "The request and response parameters must be either the same objects as were passed to the calling servlet's service method or be subclasses of the ServletRequestWrapper or ServletResponseWrapper classes that wrap them."  It explicitly supports wrappers.

**Comment by andreasevers** [comment]
Oh right....

I got the notion of no wrappers allowed from a similar issue in RestEasy: https://issues.jboss.org/browse/RESTEASY-745

I'm now investigating why the objects are not the same. I'll get back to you once I find out!

**Comment by andreasevers** [comment]
I have found the reason why the request and response objects are not the same on JBoss:

The equals check has a while loop to go through the HttpServletRequestWrappers until it gets the actual request. However, in doing this, it expects the Wrappers to extend from the JEE ServletRequestWrapper.

The standard JEE HttpServletRequestWrapper does this like so:
    public class HttpServletRequestWrapper extends ServletRequestWrapper implements HttpServletRequest {
However, in Zuul the HttpServletRequestWrapper doesn't extend from anything:
    public class HttpServletRequestWrapper implements HttpServletRequest {...}
And this is what makes the equals check fail, because it doesn't treat Zuul's wrapper as an official JEE wrapper:

```
        while (!same) {
            if (originalRequest.equals(dispatchedRequest)) {
                same = true;
            }
            if (!same && ***dispatchedRequest instanceof ServletRequestWrapper***) {
                dispatchedRequest =
                    ((ServletRequestWrapper) dispatchedRequest).getRequest();
            } else {
                break;
            }
        }
```
As the Zuul wrapper is not an instance of the standard ServletRequestWrapper, the wrapper is not inspected and the actual request inside is not retrieved. This results in mismatching objects and the whole flow breaks.

The possible solution I see here is to have the Zuul wrapper extend from the javax.servlet.ServletRequestWrapper, if possible.

For now I will try to work around this by implementing my own SendErrorFilter and passing the RequestFacades to the forward method instead of the wrapper. Same for responses.

**Comment by spencergibb** [comment]
Thanks for all the research.  Let me know what you find.

**Comment by andreasevers** [comment]
No problem :)

The temporary (dirty) workaround which does the trick is this:

Override SendErrorFilter with our own and added the following section in the run() method:

```
if (dispatcher != null) {
				ctx.set(SEND_ERROR_FILTER_RAN, true);
				if (!ctx.getResponse().isCommitted()) {
					/**
					 * TEMPORARY FIX FOR
					 * https://github.com/spring-cloud/spring-cloud
					 * -netflix/issues/397
					 */
					Field requestField = ReflectionUtils.findField(HttpServletRequestWrapper.class, "req", HttpServletRequest.class);
					Assert.notNull(requestField, "HttpServletRequestWrapper.req field not found");
					requestField.setAccessible(true);
					HttpServletRequest request = (HttpServletRequest) ReflectionUtils.getField(requestField, ((HttpServletRequestWrapper) ctx.getRequest()).getRequest());

					dispatcher.forward(request, ((HttpServletResponseWrapper) ctx.getResponse()).getResponse());
				}
			}
```

I don't like to keep this in our codebase, so if the suggestion I proposed in my previous comment could be possible, then I could remove this hack.

So could extending the com.netflix.zuul.http.HttpServletRequestWrapper from javax.servlet.ServletRequestWrapper be a possibility?

**Comment by spencergibb** [comment]
@andreasevers it seems like this needs to be fixed in zuul, as that is where `HttpServletRequestWrapper` lives, correct? Sorry for the delay in responding.

**Comment by spencergibb** [comment]
Closing for lack of feedback.
