### ISSUE TITLE
how to configure Eureka server running on https instead of http

### ISSUE THREAD

**Issue by todzheng** [spring-cloud/spring-cloud-netflix#404]
I tried to create a Eureka server, and config it with ssl support, but server would not start: anything I need to config to specify the Replica node URL, which might be the issue?
```
Finished initializing remote region registries. All known remote regions: []
2015-06-16 15:20:45.247  INFO 2433 --- [       Thread-3] com.netflix.eureka.EurekaBootStrap       : Replica node URL:  http://localhost:8761/eureka/
2015-06-16 15:20:45.248  INFO 2433 --- [       Thread-3] e.s.EurekaServerInitializerConfiguration : Started Eureka Server

2015-06-16 15:21:38.974 ERROR 2433 --- [nio-8761-exec-3] c.n.eureka.resources.StatusResource      : Could not determine if the replica is available 

java.lang.NullPointerException: null
	at com.netflix.eureka.resources.StatusResource.isReplicaAvailable(StatusResource.java:90)
	at com.netflix.eureka.resources.StatusResource.getStatusInfo(StatusResource.java:70)
	at org.springframework.cloud.netflix.eureka.server.EurekaController.status(EurekaController.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
```

**Comment by todzheng** [comment]
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0

spring:
  application:
    name: eureka

**Comment by spencergibb** [comment]
I'm not sure that NPE is actually causing any problems.  We see it from time to time and have been unable to fix it.

**Comment by todzheng** [comment]
but my server is not able to come up somehow, because it is trying to find replica node with http://localhost:8761/eureka instead of https://localhost:8761/eureka

**Comment by brenuart** [comment]
The exception is thrown because of the UI - it doesn't interfere with the normal Eureka operations.

Basically, your Eureka server doesn't recognise itself as being `http://localhost:8761/eureka/` which is the default `eureka.client.serviceUrl` value if none is explicitly set in your config.

The server takes its identity from `eureka.instance.hostname` which by default resolves to the hostname or your machine (if not explicitly set otherwise in your config).

Result: if your hostname is `myhostname`, a `serviceUrl=http://localhost:8761...` points to a different machine... which Eureka interpret as being a peer it should replicate with.

You can get rid of that exception by adding the following in your config:

    server.port: 8761
    eureka.instance.hostname: localhost
    eureka.client.serviceUrl.defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

The exception should disappear...
