### ISSUE TITLE
eureka-client1.10.14  rejected from java.util.concurrent.ThreadPoolExecutor

### ISSUE THREAD

**Issue by Sunywdev** [spring-cloud/spring-cloud-netflix#4069]
I used the eureka-client1.10.14 version in SpringCloud2020.3. There are some WARN logs recently. I put the detailed information below. Is it because my thread pool is not enough?  looking forward to the reply;

WARN c.n.discovery.TimedSupervisorTask -task supervisor rejected the task
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@4bbc4fb3 rejected from java.util.concurrent.ThreadPoolExecutor@6577728a[Running, pool size = 2, active threads = 2, queued tasks = 0, completed tasks = 19838]
        at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
        at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
        at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1379)
        at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
        at com.netflix.discovery.TimedSupervisorTask.run(TimedSupervisorTask.java:66)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by OlgaMaciaszek** [comment]
Hello, @Sunywdev, the `2020.x` line is no longer supported. Please upgrade to `2021.x` and verify if the issue persists.

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
