### ISSUE TITLE
HttpRequest coming as null resulting in java.lang.IllegalStateException: request not parsed while accessing requestHeaders

### ISSUE THREAD

**Issue by jakshay21** [spring-cloud/spring-cloud-netflix#4071]
Running reactor-netty-http:1.0.2 resulting in below error. Any suggestions?
Access logs are enabled - System.setProperty("reactor.netty.http.server.accessLogEnabled", "true")

```
[logLevel=ERROR] -- 2022-01-27 09:10:20,462 -0800 -- reactor-http-epoll-14              reactor.netty.transport.ServerTransport -- [id: 0x2a948acc, L:/10.187.155.25:40018 ! R:/17.8.71.183:34978] onUncaughtException(SimpleConnection{channel=[id: 0x2a948acc, L:/10.187.155.25:40018 ! R:/17.8.71.183:34978]})
java.lang.IllegalStateException: request not parsed
    at reactor.netty.http.server.HttpServerOperations.requestHeaders(HttpServerOperations.java:368) ~[reactor-netty-http-1.0.2.jar!/:1.0.2]
    at reactor.netty.http.server.HttpServerOperations.<init>(HttpServerOperations.java:156) ~[reactor-netty-http-1.0.2.jar!/:1.0.2]
    at reactor.netty.http.server.HttpServerOperations$FailedHttpServerRequest.<init>(HttpServerOperations.java:769) ~[reactor-netty-http-1.0.2.jar!/:1.0.2]
    at reactor.netty.http.server.HttpServerOperations.sendDecodingFailures(HttpServerOperations.java:647) ~[reactor-netty-http-1.0.2.jar!/:1.0.2]
    at reactor.netty.http.server.HttpTrafficHandler.sendDecodingFailures(HttpTrafficHandler.java:257) ~[reactor-netty-http-1.0.2.jar!/:1.0.2]
    at reactor.netty.http.server.HttpTrafficHandler.channelRead(HttpTrafficHandler.java:217) ~[reactor-netty-http-1.0.2.jar!/:1.0.2]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.55.Final.jar!/:4.1.55.Final]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.55.Final.jar!/:4.1.55.Final]
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.55.Final.jar!/:4.1.55.Final]
    at reactor.netty.http.server.logging.AccessLogHandlerH1.channelRead(AccessLogHandlerH1.java:57) [reactor-netty-http-1.0.2.jar!/:1.0.2]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.55.Final.jar!/:4.1.55.Final]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.55.Final.jar!/:4.1.55.Final]
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.55.Final.jar!/:4.1.55.Final]
    at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436) [netty-transport-4.1.55.Final.jar!/:4.1.55.Final]
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) [netty-codec-4.1.55.Final.jar!/:4.1.55.Final]
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) [netty-codec-4.1.55.Final.jar!/:4.1.55.Final]
    at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251) [netty-transport-4.1.55.Final.jar!/:4.1.55.Final]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.55.Final.jar!/:4.1.55.Final]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.55.Final.jar!/:4.1.55.Final]
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.55.Final.jar!/:4.1.55.Final]
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.55.Final.jar!/:4.1.55.Final]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.55.Final.jar!/:4.1.55.Final]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.55.Final.jar!/:4.1.55.Final]
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.55.Final.jar!/:4.1.55.Final]
    at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795) [netty-transport-native-epoll-4.1.55.Final-linux-x86_64.jar!/:4.1.55.Final]
    at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480) [netty-transport-native-epoll-4.1.55.Final-linux-x86_64.jar!/:4.1.55.Final]
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) [netty-transport-native-epoll-4.1.55.Final-linux-x86_64.jar!/:4.1.55.Final]
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-common-4.1.55.Final.jar!/:4.1.55.Final]
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.55.Final.jar!/:4.1.55.Final]
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.55.Final.jar!/:4.1.55.Final]
    at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by jakshay21** [comment]
Closing as the request doesn't belongs to this package.
