### ISSUE TITLE
c.netflix.discovery.TimedSupervisorTask

### ISSUE THREAD

**Issue by mamin1976** [spring-cloud/spring-cloud-netflix#4093]
**Describe the bug**
Gateway service uses full CPU and generate error:
 WARN 1 --- [scoveryClient-1] c.netflix.discovery.TimedSupervisorTask  : task supervisor timed out

java.util.concurrent.TimeoutException: null
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204) ~[na:na]
	at com.netflix.discovery.TimedSupervisorTask.run(TimedSupervisorTask.java:68) ~[eureka-client-1.10.17.jar!/:1.10.17]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]

**Comment by davidsoles** [comment]
Hello,
I am having the same error.
```
2022-05-18 13:24:44.296  WARN 1 --- [scoveryClient-0] c.netflix.discovery.TimedSupervisorTask  : task supervisor timed out

java.util.concurrent.TimeoutException: null
	at java.base/java.util.concurrent.FutureTask.get(Unknown Source) ~[na:na]
	at com.netflix.discovery.TimedSupervisorTask.run(TimedSupervisorTask.java:68) ~[eureka-client-1.10.17.jar:1.10.17]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
	at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
```
The configuration is the following:
- Eureka Server with Spring Boot 2.6.6 and Spring Cloud Version 2021.0.1
- Eureka Client with Spring Boot 2.6.7 and Spring Cloud Version 2021.0.2
- Both with Java 17.

`application.properties` file in the client:
```
eureka.client.service-url.defaultZone=http://10.200.14.54:8761/eureka
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
```
There are multiple versions of Eureka Clients among many other microservices and the behaviour is the same, a lot of flickering, connect and disconnect multiple times making the whole system unstable 😭

**Comment by ishivesh** [comment]
Any updates here, facing the same issue :(

**Comment by OlgaMaciaszek** [comment]
Judging by the stack trace, the issue is pertinent to https://github.com/Netflix/eureka repo and not the Spring Cloud Netflix Eureka integration that we provide, so the issue should be opened in that repo.
