### ISSUE TITLE
Apps don't re-register after server restarts

### ISSUE THREAD

**Issue by bchilcott** [spring-cloud/spring-cloud-netflix#4153]
This may be a duplicate of #26, but that seemed to be some kind of authentication issue and I don't believe this is. Client apps start fine and connect to the server, but upon killing and restarting the server, none of them re-connect.

Client logs:
```
2023-01-06T03:53:46.208Z  WARN 37592 --- [tbeatExecutor-0] c.n.d.s.t.d.RetryableEurekaHttpClient    : Request execution failed with message: Error while extracting response for type [class com.netflix.appinfo.InstanceInfo] and content type [application/json]
2023-01-06T03:53:46.208Z ERROR 37592 --- [tbeatExecutor-0] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_BOASUI/PC.mshome.net:BOASUI - was unable to send heartbeat!

com.netflix.discovery.shared.transport.TransportException: Cannot execute request on any known server
	at com.netflix.discovery.shared.transport.decorator.RetryableEurekaHttpClient.execute(RetryableEurekaHttpClient.java:112) ~[eureka-client-2.0.0.jar:2.0.0]
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.sendHeartBeat(EurekaHttpClientDecorator.java:89) ~[eureka-client-2.0.0.jar:2.0.0]
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$3.execute(EurekaHttpClientDecorator.java:92) ~[eureka-client-2.0.0.jar:2.0.0]
	at com.netflix.discovery.shared.transport.decorator.SessionedEurekaHttpClient.execute(SessionedEurekaHttpClient.java:77) ~[eureka-client-2.0.0.jar:2.0.0]
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.sendHeartBeat(EurekaHttpClientDecorator.java:89) ~[eureka-client-2.0.0.jar:2.0.0]
	at com.netflix.discovery.DiscoveryClient.renew(DiscoveryClient.java:837) ~[eureka-client-2.0.0.jar:2.0.0]
	at com.netflix.discovery.DiscoveryClient$HeartbeatThread.run(DiscoveryClient.java:1401) ~[eureka-client-2.0.0.jar:2.0.0]
```

There doesn't appear to be any log acknowledging this attempt on the server.  I have both client and server configured with the default options - no additions in any application.yml.

This repo reproduces the issue:
https://github.com/bchilcott/eureka-reconnect-issue-demo

**Comment by eroaespinosa** [comment]
Same problem

**Comment by th-turk** [comment]
Same problem

**Comment by bchilcott** [comment]
Created a minimal project that reproduces the issue [here](https://github.com/bchilcott/eureka-reconnect-issue-demo).

**Comment by th-turk** [comment]
@bchilcott   
 Have you checked related solution at #4145 for server side ? 
that fixed issue for me. Error handling for client side restTemplate is missing as i saw. when empiting the content to bypass cleint side error eureka able to renew the lease.

**Comment by GilbertHG** [comment]
any solution for this?

**Comment by th-turk** [comment]
> any solution for this?
@GilbertHG 

You can add one end poitm to your Eureak server tp bypass the error content then it iwll work but keep follow the permanent solution

``` Java
@RestController
static class CustomErrorController implements ErrorController {

	private static final String ERROR_MAPPING = "/error";

	@RequestMapping(ERROR_MAPPING)
	public ResponseEntity<Void> error() {
		return ResponseEntity.notFound().build();
	}
	
}
```

**Comment by spencergibb** [comment]
Duplicates #4153

**Comment by bchilcott** [comment]
> Duplicates #4153

Am I missing something..? This is #4153.

**Comment by spencergibb** [comment]
typo sorry
