### ISSUE TITLE
400 error when Eureka discovery client attempts to register Spring Boot 2.7.5 service with service registry

### ISSUE THREAD

**Issue by SachinPratapSingh889** [spring-cloud/spring-cloud-netflix#4280]
Eureka-client(application.properties) -
![image](https://github.com/spring-cloud/spring-cloud-netflix/assets/91151248/37620312-d436-4878-832e-cdaef9c11dea)
Eureka-server(application.properties)-
![image](https://github.com/spring-cloud/spring-cloud-netflix/assets/91151248/7fcd2db0-fb8e-4e6c-a2a2-f948c1ed1f47)
Pom.xml(client)
![image](https://github.com/spring-cloud/spring-cloud-netflix/assets/91151248/10e9c895-1492-4663-acc2-314994a951fe)
Spring cloud version
![image](https://github.com/spring-cloud/spring-cloud-netflix/assets/91151248/01dcd45c-6d00-4fc1-96ff-d90bf66482b3)
Spring Boot Version-
2.7.5
I am not getting my client register on eureka server running on port 8761, below is the console 
2024-05-05 03:40:59.527  INFO 18384 --- [           main] c.n.discovery.InstanceInfoReplicator     : InstanceInfoReplicator onDemand update allowed rate per min is 4
2024-05-05 03:40:59.534  INFO 18384 --- [           main] com.netflix.discovery.DiscoveryClient    : Discovery Client initialized at timestamp 1714860659533 with initial instances count: 0
2024-05-05 03:40:59.536  INFO 18384 --- [           main] o.s.c.n.e.s.EurekaServiceRegistry        : Registering application CUSTOMER                          with eureka with status UP
2024-05-05 03:40:59.537  INFO 18384 --- [           main] com.netflix.discovery.DiscoveryClient    : Saw local status change event StatusChangeEvent [timestamp=1714860659537, current=UP, previous=STARTING]
2024-05-05 03:40:59.539  INFO 18384 --- [nfoReplicator-0] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_CUSTOMER                         /Sachin.mshome.net:Customer                         :8081: registering service...
2024-05-05 03:40:59.576  INFO 18384 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8081 (http) with context path ''
2024-05-05 03:40:59.577  INFO 18384 --- [           main] .s.c.n.e.s.EurekaAutoServiceRegistration : Updating port to 8081
2024-05-05 03:40:59.595  WARN 18384 --- [nfoReplicator-0] c.n.d.s.t.d.RetryableEurekaHttpClient    : Request execution failure with status code 400; retrying on another server if available
2024-05-05 03:40:59.601  WARN 18384 --- [nfoReplicator-0] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_CUSTOMER                         /Sachin.mshome.net:Customer                         :8081 - registration failed Cannot execute request on any known server

com.netflix.discovery.shared.transport.TransportException: Cannot execute request on any known server
	at com.netflix.discovery.shared.transport.decorator.RetryableEurekaHttpClient.execute(RetryableEurekaHttpClient.java:112) ~[eureka-client-1.10.17.jar:1.10.17]
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.register(EurekaHttpClientDecorator.java:56) ~[eureka-client-1.10.17.jar:1.10.17]
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$1.execute(EurekaHttpClientDecorator.java:59) ~[eureka-client-1.10.17.jar:1.10.17]
	at com.netflix.discovery.shared.transport.decorator.SessionedEurekaHttpClient.execute(SessionedEurekaHttpClient.java:77) ~[eureka-client-1.10.17.jar:1.10.17]
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.register(EurekaHttpClientDecorator.java:56) ~[eureka-client-1.10.17.jar:1.10.17]
	at com.netflix.discovery.DiscoveryClient.register(DiscoveryClient.java:876) ~[eureka-client-1.10.17.jar:1.10.17]
	at com.netflix.discovery.InstanceInfoReplicator.run(InstanceInfoReplicator.java:121) ~[eureka-client-1.10.17.jar:1.10.17]
	at com.netflix.discovery.InstanceInfoReplicator$1.run(InstanceInfoReplicator.java:101) ~[eureka-client-1.10.17.jar:1.10.17]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2024-05-05 03:40:59.601  WARN 18384 --- [nfoReplicator-0] c.n.discovery.InstanceInfoReplicator     : There was a problem with the instance info replicator

com.netflix.discovery.shared.transport.TransportException: Cannot execute request on any known server
	at com.netflix.discovery.shared.transport.decorator.RetryableEurekaHttpClient.execute(RetryableEurekaHttpClient.java:112) ~[eureka-client-1.10.17.jar:1.10.17]
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.register(EurekaHttpClientDecorator.java:56) ~[eureka-client-1.10.17.jar:1.10.17]
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$1.execute(EurekaHttpClientDecorator.java:59) ~[eureka-client-1.10.17.jar:1.10.17]
	at com.netflix.discovery.shared.transport.decorator.SessionedEurekaHttpClient.execute(SessionedEurekaHttpClient.java:77) ~[eureka-client-1.10.17.jar:1.10.17]
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.register(EurekaHttpClientDecorator.java:56) ~[eureka-client-1.10.17.jar:1.10.17]
	at com.netflix.discovery.DiscoveryClient.register(DiscoveryClient.java:876) ~[eureka-client-1.10.17.jar:1.10.17]
	at com.netflix.discovery.InstanceInfoReplicator.run(InstanceInfoReplicator.java:121) ~[eureka-client-1.10.17.jar:1.10.17]
	at com.netflix.discovery.InstanceInfoReplicator$1.run(InstanceInfoReplicator.java:101) ~[eureka-client-1.10.17.jar:1.10.17]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2024-05-05 03:40:59.682  INFO 18384 --- [           main] c.m.customer.CustomerApplication         : Started CustomerApplication in 6.224 seconds (JVM running for 6.609)

**Comment by OlgaMaciaszek** [comment]
Hello @SachinPratapSingh889, the only GA version of Spring Cloud that is currently under OSS support is 2023.0.x, for example Spring Cloud `2023.0.1` used with Boot `3.2.5`. Please verify if your issue persists after upgrading to this version. If yes, please provide more details of the issue including expected result, actual result and a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve) that reproduces the issue.

**Comment by SachinPratapSingh889** [comment]
In my application.properties , 
I was using spring.jpa.ddl-auto=update instead of spring.jpa.hibernate.ddl-auto=update.
This change resolved the issue.

Thanks,
Sachin
