### ISSUE TITLE
After Installing CERBOT SSL certificate using NGINX web server, Unable the microservices to register with eureka server earlier it was working. 

### ISSUE THREAD

**Issue by hariramsaini** [spring-cloud/spring-cloud-netflix#4387]
I setup eureka server along with micro services using docker-compose and it was working fine. Today i installed CERBOT SSL certificate for NGINX Server after that apigateway and other micro services are not able to register with eureka server.

Apigateway Logs:

```
apigateway    | 2024-12-09T07:14:28.346Z  INFO 1 --- [           main] o.s.c.g.r.RouteDefinitionRouteLocator    : Loaded RoutePredicateFactory [Before]
apigateway    | 2024-12-09T07:14:28.347Z  INFO 1 --- [           main] o.s.c.g.r.RouteDefinitionRouteLocator    : Loaded RoutePredicateFactory [Between]
apigateway    | 2024-12-09T07:14:28.348Z  INFO 1 --- [           main] o.s.c.g.r.RouteDefinitionRouteLocator    : Loaded RoutePredicateFactory [Cookie]
apigateway    | 2024-12-09T07:14:28.349Z  INFO 1 --- [           main] o.s.c.g.r.RouteDefinitionRouteLocator    : Loaded RoutePredicateFactory [Header]
apigateway    | 2024-12-09T07:14:28.349Z  INFO 1 --- [           main] o.s.c.g.r.RouteDefinitionRouteLocator    : Loaded RoutePredicateFactory [Host]
apigateway    | 2024-12-09T07:14:28.349Z  INFO 1 --- [           main] o.s.c.g.r.RouteDefinitionRouteLocator    : Loaded RoutePredicateFactory [Method]
apigateway    | 2024-12-09T07:14:28.350Z  INFO 1 --- [           main] o.s.c.g.r.RouteDefinitionRouteLocator    : Loaded RoutePredicateFactory [Path]
apigateway    | 2024-12-09T07:14:28.350Z  INFO 1 --- [           main] o.s.c.g.r.RouteDefinitionRouteLocator    : Loaded RoutePredicateFactory [Query]
apigateway    | 2024-12-09T07:14:28.353Z  INFO 1 --- [           main] o.s.c.g.r.RouteDefinitionRouteLocator    : Loaded RoutePredicateFactory [ReadBody]
apigateway    | 2024-12-09T07:14:28.354Z  INFO 1 --- [           main] o.s.c.g.r.RouteDefinitionRouteLocator    : Loaded RoutePredicateFactory [RemoteAddr]
apigateway    | 2024-12-09T07:14:28.355Z  INFO 1 --- [           main] o.s.c.g.r.RouteDefinitionRouteLocator    : Loaded RoutePredicateFactory [XForwardedRemoteAddr]
apigateway    | 2024-12-09T07:14:28.356Z  INFO 1 --- [           main] o.s.c.g.r.RouteDefinitionRouteLocator    : Loaded RoutePredicateFactory [Weight]
apigateway    | 2024-12-09T07:14:28.356Z  INFO 1 --- [           main] o.s.c.g.r.RouteDefinitionRouteLocator    : Loaded RoutePredicateFactory [CloudFoundryRouteService]
apigateway    | 2024-12-09T07:14:29.289Z  INFO 1 --- [           main] DiscoveryClientOptionalArgsConfiguration : Eureka HTTP Client uses RestTemplate.
apigateway    | 2024-12-09T07:14:29.583Z  WARN 1 --- [           main] iguration$LoadBalancerCaffeineWarnLogger : Spring Cloud LoadBalancer is currently working with the default cache. While this cache implementation is useful for development and tests, it's recommended to use Caffeine cache in production.You can switch to using Caffeine cache, by adding it and org.springframework.cache.caffeine.CaffeineCacheManager to the classpath.
apigateway    | 2024-12-09T07:14:29.679Z  INFO 1 --- [           main] o.s.c.n.eureka.InstanceInfoFactory       : Setting initial instance status as: STARTING
apigateway    | 2024-12-09T07:14:30.136Z  INFO 1 --- [           main] com.netflix.discovery.DiscoveryClient    : Initializing Eureka in region us-east-1
apigateway    | 2024-12-09T07:14:30.162Z  INFO 1 --- [           main] c.n.d.s.r.aws.ConfigClusterResolver      : Resolving eureka endpoints via configuration
apigateway    | 2024-12-09T07:14:30.252Z  INFO 1 --- [           main] com.netflix.discovery.DiscoveryClient    : Disable delta property : false
apigateway    | 2024-12-09T07:14:30.252Z  INFO 1 --- [           main] com.netflix.discovery.DiscoveryClient    : Single vip registry refresh property : null
apigateway    | 2024-12-09T07:14:30.252Z  INFO 1 --- [           main] com.netflix.discovery.DiscoveryClient    : Force full registry fetch : false
apigateway    | 2024-12-09T07:14:30.253Z  INFO 1 --- [           main] com.netflix.discovery.DiscoveryClient    : Application is null : false
apigateway    | 2024-12-09T07:14:30.256Z  INFO 1 --- [           main] com.netflix.discovery.DiscoveryClient    : Registered Applications size is zero : true
apigateway    | 2024-12-09T07:14:30.257Z  INFO 1 --- [           main] com.netflix.discovery.DiscoveryClient    : Application version is -1: true
apigateway    | 2024-12-09T07:14:30.259Z  INFO 1 --- [           main] com.netflix.discovery.DiscoveryClient    : Getting all instance registry info from the eureka server
apigateway    | 2024-12-09T07:16:46.757Z  INFO 1 --- [           main] c.n.d.s.t.d.RedirectingEurekaHttpClient  : Request execution error. endpoint=DefaultEndpoint{ serviceUrl='http://15.235.199.11:8761/ServiceDiscovery/eureka/}, exception=I/O error on GET request for "http://15.235.199.11:8761/ServiceDiscovery/eureka/apps/": Connect to http://15.235.199.11:8761 [/15.235.199.11] failed: Connection timed out stacktrace=org.springframework.web.client.ResourceAccessException: I/O error on GET request for "http://15.235.199.11:8761/ServiceDiscovery/eureka/apps/": Connect to http://15.235.199.11:8761 [/15.235.199.11] failed: Connection timed out
apigateway    |         at org.springframework.web.client.RestTemplate.createResourceAccessException(RestTemplate.java:888)
apigateway    |         at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:868)
apigateway    |         at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:764)
apigateway    |         at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:646)
apigateway    |         at org.springframework.cloud.netflix.eureka.http.RestTemplateEurekaHttpClient.getApplicationsInternal(RestTemplateEurekaHttpClient.java:149)
apigateway    |         at org.springframework.cloud.netflix.eureka.http.RestTemplateEurekaHttpClient.getApplications(RestTemplateEurekaHttpClient.java:139)
apigateway    |         at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$6.execute(EurekaHttpClientDecorator.java:137)
apigateway    |         at com.netflix.discovery.shared.transport.decorator.RedirectingEurekaHttpClient.executeOnNewServer(RedirectingEurekaHttpClient.java:121)
apigateway    |         at com.netflix.discovery.shared.transport.decorator.RedirectingEurekaHttpClient.execute(RedirectingEurekaHttpClient.java:80)
apigateway    |         at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.getApplications(EurekaHttpClientDecorator.java:134)
apigateway    |         at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$6.execute(EurekaHttpClientDecorator.java:137)
apigateway    |         at com.netflix.discovery.shared.transport.decorator.RetryableEurekaHttpClient.execute(RetryableEurekaHttpClient.java:120)
apigateway    |         at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.getApplications(EurekaHttpClientDecorator.java:134)
apigateway    |         at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$6.execute(EurekaHttpClientDecorator.java:137)
apigateway    |         at com.netflix.discovery.shared.transport.decorator.SessionedEurekaHttpClient.execute(SessionedEurekaHttpClient.java:77)
apigateway    |         at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.getApplications(EurekaHttpClientDecorator.java:134)
apigateway    |         at com.netflix.discovery.DiscoveryClient.getAndStoreFullRegistry(DiscoveryClient.java:1045)
apigateway    |         at com.netflix.discovery.DiscoveryClient.fetchRegistry(DiscoveryClient.java:958)
apigateway    |         at com.netflix.discovery.DiscoveryClient.<init>(DiscoveryClient.java:396)
apigateway    |         at com.netflix.discovery.DiscoveryClient.<init>(DiscoveryClient.java:247)
apigateway    |         at com.netflix.discovery.DiscoveryClient.<init>(DiscoveryClient.java:242)
apigateway    |         at org.springframework.cloud.netflix.eureka.CloudEurekaClient.<init>(CloudEurekaClient.java:68)
apigateway    |         at org.springframework.cloud.netflix.eureka.EurekaClientAutoConfiguration$RefreshableEurekaClientConfiguration.eurekaClient(EurekaClientAutoConfiguration.java:320)
apigateway    |         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
apigateway    |         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
apigateway    |         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
apigateway    |         at java.base/java.lang.reflect.Method.invoke(Method.java:569)
apigateway    |         at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:139)
apigateway    |         at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:650)
apigateway    |         at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:642)
apigateway    |         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1332)
apigateway    |         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1162)
apigateway    |         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:560)
apigateway    |         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520)
apigateway    |         at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$1(AbstractBeanFactory.java:364)
apigateway    |         at org.springframework.cloud.context.scope.GenericScope$BeanLifecycleWrapper.getBean(GenericScope.java:375)
apigateway    |         at org.springframework.cloud.context.scope.GenericScope.get(GenericScope.java:179)
apigateway    |         at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:361)
apigateway    |         at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
apigateway    |         at org.springframework.aop.target.SimpleBeanTargetSource.getTarget(SimpleBeanTargetSource.java:35)
apigateway    |         at org.springframework.cloud.netflix.eureka.serviceregistry.EurekaRegistration.getTargetObject(EurekaRegistration.java:128)
apigateway    |         at org.springframework.cloud.netflix.eureka.serviceregistry.EurekaRegistration.getEurekaClient(EurekaRegistration.java:116)
apigateway    |         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
apigateway    |         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
apigateway    |         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
apigateway    |         at java.base/java.lang.reflect.Method.invoke(Method.java:569)
apigateway    |         at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:281)
apigateway    |         at org.springframework.cloud.context.scope.GenericScope$LockedScopedProxyFactoryBean.invoke(GenericScope.java:482)
apigateway    |         at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
apigateway    |         at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:751)
apigateway    |         at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:703)
apigateway    |         at org.springframework.cloud.netflix.eureka.serviceregistry.EurekaRegistration$$SpringCGLIB$$0.getEurekaClient(<generated>)
apigateway    |         at org.springframework.cloud.netflix.eureka.serviceregistry.EurekaServiceRegistry.maybeInitializeClient(EurekaServiceRegistry.java:54)
apigateway    |         at org.springframework.cloud.netflix.eureka.serviceregistry.EurekaServiceRegistry.register(EurekaServiceRegistry.java:38)
apigateway    |         at org.springframework.cloud.netflix.eureka.serviceregistry.EurekaAutoServiceRegistration.start(EurekaAutoServiceRegistration.java:83)
apigateway    |         at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:179)
apigateway    |         at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:357)
apigateway    |         at java.base/java.lang.Iterable.forEach(Iterable.java:75)
apigateway    |         at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:156)
apigateway    |         at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:124)
apigateway    |         at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:966)
apigateway    |         at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:619)
apigateway    |         at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:66)
apigateway    |         at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:738)
apigateway    |         at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:440)
apigateway    |         at org.springframework.boot.SpringApplication.run(SpringApplication.java:316)
apigateway    |         at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)
apigateway    |         at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295)
apigateway    |         at com.narayanfintech.ApiGateway.main(ApiGateway.java:11)
apigateway    |         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
apigateway    |         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
apigateway    |         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
apigateway    |         at java.base/java.lang.reflect.Method.invoke(Method.java:569)
apigateway    |         at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
apigateway    |         at org.springframework.boot.loader.Launcher.launch(Launcher.java:95)
apigateway    |         at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
apigateway    |         at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)
apigateway    | Caused by: org.apache.hc.client5.http.ConnectTimeoutException: Connect to http://15.235.199.11:8761 [/15.235.199.11] failed: Connection timed out
apigateway    |         at org.apache.hc.client5.http.ConnectExceptionSupport.createConnectTimeoutException(ConnectExceptionSupport.java:52)
apigateway    |         at org.apache.hc.client5.http.ConnectExceptionSupport.enhance(ConnectExceptionSupport.java:74)
apigateway    |         at org.apache.hc.client5.http.impl.io.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:195)
apigateway    |         at org.apache.hc.client5.http.impl.io.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:447)
apigateway    |         at org.apache.hc.client5.http.impl.classic.InternalExecRuntime.connectEndpoint(InternalExecRuntime.java:162)
apigateway    |         at org.apache.hc.client5.http.impl.classic.InternalExecRuntime.connectEndpoint(InternalExecRuntime.java:172)
apigateway    |         at org.apache.hc.client5.http.impl.classic.ConnectExec.execute(ConnectExec.java:142)
apigateway    |         at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
apigateway    |         at org.apache.hc.client5.http.impl.classic.ProtocolExec.execute(ProtocolExec.java:192)
apigateway    |         at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
apigateway    |         at org.apache.hc.client5.http.impl.classic.HttpRequestRetryExec.execute(HttpRequestRetryExec.java:96)
apigateway    |         at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
apigateway    |         at org.apache.hc.client5.http.impl.classic.ContentCompressionExec.execute(ContentCompressionExec.java:152)
apigateway    |         at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
apigateway    |         at org.apache.hc.client5.http.impl.classic.RedirectExec.execute(RedirectExec.java:115)
apigateway    |         at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
apigateway    |         at org.apache.hc.client5.http.impl.classic.InternalHttpClient.doExecute(InternalHttpClient.java:170)
apigateway    |         at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:106)
apigateway    |         at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:55)
apigateway    |         at org.springframework.http.client.HttpComponentsClientHttpRequest.executeInternal(HttpComponentsClientHttpRequest.java:93)
apigateway    |         at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:48)
apigateway    |         at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:66)
apigateway    |         at org.springframework.http.client.InterceptingClientHttpRequest$InterceptingRequestExecution.execute(InterceptingClientHttpRequest.java:101)
apigateway    |         at org.springframework.cloud.netflix.eureka.http.RestTemplateTransportClientFactory.lambda$restTemplate$0(RestTemplateTransportClientFactory.java:143)
apigateway    |         at org.springframework.http.client.InterceptingClientHttpRequest$InterceptingRequestExecution.execute(InterceptingClientHttpRequest.java:87)
apigateway    |         at org.springframework.http.client.InterceptingClientHttpRequest.executeInternal(InterceptingClientHttpRequest.java:71)
apigateway    |         at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:48)
apigateway    |         at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:66)
apigateway    |         at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:862)
apigateway    |         ... 75 more
apigateway    | Caused by: java.net.ConnectException: Connection timed out
apigateway    |         at java.base/sun.nio.ch.Net.pollConnect(Native Method)
apigateway    |         at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
apigateway    |         at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:554)
apigateway    |         at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:602)
apigateway    |         at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
apigateway    |         at java.base/java.net.Socket.connect(Socket.java:633)
apigateway    |         at org.apache.hc.client5.http.socket.PlainConnectionSocketFactory.lambda$connectSocket$0(PlainConnectionSocketFactory.java:85)
apigateway    |         at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
apigateway    |         at org.apache.hc.client5.http.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:84)
apigateway    |         at org.apache.hc.client5.http.socket.ConnectionSocketFactory.connectSocket(ConnectionSocketFactory.java:113)
apigateway    |         at org.apache.hc.client5.http.impl.io.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:181)
apigateway    |         ... 101 more
apigateway    |
apigateway    | 2024-12-09T07:16:46.759Z  WARN 1 --- [           main] c.n.d.s.t.d.RetryableEurekaHttpClient    : Request execution failed with message: I/O error on GET request for "http://15.235.199.11:8761/ServiceDiscovery/eureka/apps/": Connect to http://15.235.199.11:8761 [/15.235.199.11] failed: Connection timed out
apigateway    | 2024-12-09T07:16:46.770Z  INFO 1 --- [           main] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_APIGATEWAY/172.20.0.3:apigateway:9001 - was unable to refresh its cache! This periodic background refresh will be retried in 30 seconds. status = Cannot execute request on any known server stacktrace = com.netflix.discovery.shared.transport.TransportException: Cannot execute request on any known server
apigateway    |         at com.netflix.discovery.shared.transport.decorator.RetryableEurekaHttpClient.execute(RetryableEurekaHttpClient.java:112)
apigateway    |         at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.getApplications(EurekaHttpClientDecorator.java:134)
apigateway    |         at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$6.execute(EurekaHttpClientDecorator.java:137)
apigateway    |         at com.netflix.discovery.shared.transport.decorator.SessionedEurekaHttpClient.execute(SessionedEurekaHttpClient.java:77)
apigateway    |         at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.getApplications(EurekaHttpClientDecorator.java:134)
apigateway    |         at com.netflix.discovery.DiscoveryClient.getAndStoreFullRegistry(DiscoveryClient.java:1045)
apigateway    |         at com.netflix.discovery.DiscoveryClient.fetchRegistry(DiscoveryClient.java:958)
apigateway    |         at com.netflix.discovery.DiscoveryClient.<init>(DiscoveryClient.java:396)
apigateway    |         at com.netflix.discovery.DiscoveryClient.<init>(DiscoveryClient.java:247)
apigateway    |         at com.netflix.discovery.DiscoveryClient.<init>(DiscoveryClient.java:242)
apigateway    |         at org.springframework.cloud.netflix.eureka.CloudEurekaClient.<init>(CloudEurekaClient.java:68)
apigateway    |         at org.springframework.cloud.netflix.eureka.EurekaClientAutoConfiguration$RefreshableEurekaClientConfiguration.eurekaClient(EurekaClientAutoConfiguration.java:320)
apigateway    |         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
apigateway    |         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
apigateway    |         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
apigateway    |         at java.base/java.lang.reflect.Method.invoke(Method.java:569)
apigateway    |         at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:139)
apigateway    |         at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:650)
apigateway    |         at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:642)
apigateway    |         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1332)
apigateway    |         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1162)
apigateway    |         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:560)
apigateway    |         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520)
apigateway    |         at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$1(AbstractBeanFactory.java:364)
apigateway    |         at org.springframework.cloud.context.scope.GenericScope$BeanLifecycleWrapper.getBean(GenericScope.java:375)
apigateway    |         at org.springframework.cloud.context.scope.GenericScope.get(GenericScope.java:179)
apigateway    |         at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:361)
apigateway    |         at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
apigateway    |         at org.springframework.aop.target.SimpleBeanTargetSource.getTarget(SimpleBeanTargetSource.java:35)
apigateway    |         at org.springframework.cloud.netflix.eureka.serviceregistry.EurekaRegistration.getTargetObject(EurekaRegistration.java:128)
apigateway    |         at org.springframework.cloud.netflix.eureka.serviceregistry.EurekaRegistration.getEurekaClient(EurekaRegistration.java:116)
apigateway    |         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
apigateway    |         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
apigateway    |         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
apigateway    |         at java.base/java.lang.reflect.Method.invoke(Method.java:569)
apigateway    |         at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:281)
apigateway    |         at org.springframework.cloud.context.scope.GenericScope$LockedScopedProxyFactoryBean.invoke(GenericScope.java:482)
apigateway    |         at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
apigateway    |         at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:751)
apigateway    |         at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:703)
apigateway    |         at org.springframework.cloud.netflix.eureka.serviceregistry.EurekaRegistration$$SpringCGLIB$$0.getEurekaClient(<generated>)
apigateway    |         at org.springframework.cloud.netflix.eureka.serviceregistry.EurekaServiceRegistry.maybeInitializeClient(EurekaServiceRegistry.java:54)
apigateway    |         at org.springframework.cloud.netflix.eureka.serviceregistry.EurekaServiceRegistry.register(EurekaServiceRegistry.java:38)
apigateway    |         at org.springframework.cloud.netflix.eureka.serviceregistry.EurekaAutoServiceRegistration.start(EurekaAutoServiceRegistration.java:83)
apigateway    |         at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:179)
apigateway    |         at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:357)
apigateway    |         at java.base/java.lang.Iterable.forEach(Iterable.java:75)
apigateway    |         at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:156)
apigateway    |         at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:124)
apigateway    |         at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:966)
apigateway    |         at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:619)
apigateway    |         at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:66)
apigateway    |         at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:738)
apigateway    |         at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:440)
apigateway    |         at org.springframework.boot.SpringApplication.run(SpringApplication.java:316)
apigateway    |         at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)
apigateway    |         at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295)
apigateway    |         at com.narayanfintech.ApiGateway.main(ApiGateway.java:11)
apigateway    |         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
apigateway    |         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
apigateway    |         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
apigateway    |         at java.base/java.lang.reflect.Method.invoke(Method.java:569)
apigateway    |         at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
apigateway    |         at org.springframework.boot.loader.Launcher.launch(Launcher.java:95)
apigateway    |         at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
apigateway    |         at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)
apigateway    |
```

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
