### ISSUE TITLE
Failed to instantiate [com.netflix.appinfo.ApplicationInfoManager]: Factory method 'eurekaApplicationInfoManager' threw exception

### ISSUE THREAD

**Issue by gangadharkasturi** [spring-cloud/spring-cloud-netflix#4392]
**Describe the bug**

Trying to deploy Spring Cloud Gateway to AWS fargate. The build is working fine in local env, dev server but not in AWS Fargate. Please fix the issue.

Using JDK 17 and Spring Boot 3.1.2, Spring Cloud 2022.0.2 versions.

Logs:

```
1734432268120,Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
1734432268161,"2024-12-17T16:14:28.153+05:30 ERROR [apigateway-service,,] 1 --- [           main] o.s.boot.SpringApplication               : Application run failed"
1734432268161,org.springframework.context.ApplicationContextException: Failed to start bean 'eurekaAutoServiceRegistration'
1734432268161,  at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:182) ~[spring-context-6.0.11.jar!/:6.0.11]
1734432268161,  at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:357) ~[spring-context-6.0.11.jar!/:6.0.11]
1734432268161,  at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[na:na]
1734432268161,  at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:156) ~[spring-context-6.0.11.jar!/:6.0.11]
1734432268161,  at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:124) ~[spring-context-6.0.11.jar!/:6.0.11]
1734432268161,  at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:958) ~[spring-context-6.0.11.jar!/:6.0.11]
1734432268161,  at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:611) ~[spring-context-6.0.11.jar!/:6.0.11]
1734432268161,  at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:66) ~[spring-boot-3.1.2.jar!/:3.1.2]
1734432268161,  at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:734) ~[spring-boot-3.1.2.jar!/:3.1.2]
1734432268161,  at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:436) ~[spring-boot-3.1.2.jar!/:3.1.2]
1734432268161,  at org.springframework.boot.SpringApplication.run(SpringApplication.java:312) ~[spring-boot-3.1.2.jar!/:3.1.2]
1734432268161,  at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306) ~[spring-boot-3.1.2.jar!/:3.1.2]
1734432268161,  at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295) ~[spring-boot-3.1.2.jar!/:3.1.2]
1734432268161,  at com.example.ApigatewayApplication.main(ApigatewayApplication.java:25) ~[classes!/:13.0.3-SNAPSHOT]
1734432268161,  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
1734432268161,  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
1734432268161,  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
1734432268161,  at java.base/java.lang.reflect.Method.invoke(Method.java:569) ~[na:na]
1734432268161,  at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[CloudExample-exec.jar:13.0.3-SNAPSHOT]
1734432268161,  at org.springframework.boot.loader.Launcher.launch(Launcher.java:95) ~[CloudExample-exec.jar:13.0.3-SNAPSHOT]
1734432268161,  at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[CloudExample-exec.jar:13.0.3-SNAPSHOT]
1734432268161,  at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65) ~[CloudExample-exec.jar:13.0.3-SNAPSHOT]
1734432268161,"Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'scopedTarget.eurekaApplicationInfoManager' defined in class path resource [org/springframework/cloud/netflix/eureka/EurekaClientAutoConfiguration$RefreshableEurekaClientConfiguration.class]: Failed to instantiate [com.netflix.appinfo.ApplicationInfoManager]: Factory method 'eurekaApplicationInfoManager' threw exception with message: Cannot invoke ""java.lang.CharSequence.toString()"" because ""replacement"" is null"
1734432268161,  at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:659) ~[spring-beans-6.0.11.jar!/:6.0.11]
1734432268161,  at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:647) ~[spring-beans-6.0.11.jar!/:6.0.11]
1734432268161,  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1332) ~[spring-beans-6.0.11.jar!/:6.0.11]
1734432268161,  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1162) ~[spring-beans-6.0.11.jar!/:6.0.11]
1734432268161,  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:560) ~[spring-beans-6.0.11.jar!/:6.0.11]
1734432268161,  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520) ~[spring-beans-6.0.11.jar!/:6.0.11]
1734432268161,  at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$1(AbstractBeanFactory.java:365) ~[spring-beans-6.0.11.jar!/:6.0.11]
1734432268161,  at org.springframework.cloud.context.scope.GenericScope$BeanLifecycleWrapper.getBean(GenericScope.java:375) ~[spring-cloud-context-4.0.2.jar!/:4.0.2]
1734432268161,  at org.springframework.cloud.context.scope.GenericScope.get(GenericScope.java:179) ~[spring-cloud-context-4.0.2.jar!/:4.0.2]
1734432268161,  at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:362) ~[spring-beans-6.0.11.jar!/:6.0.11]
1734432268161,  at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[spring-beans-6.0.11.jar!/:6.0.11]
1734432268161,  at org.springframework.aop.target.SimpleBeanTargetSource.getTarget(SimpleBeanTargetSource.java:35) ~[spring-aop-6.0.11.jar!/:6.0.11]
1734432268161,  at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:692) ~[spring-aop-6.0.11.jar!/:6.0.11]
1734432268161,  at com.netflix.appinfo.ApplicationInfoManager$$SpringCGLIB$$0.getInfo(<generated>) ~[eureka-client-2.0.0.jar!/:2.0.0]
1734432268161,  at org.springframework.cloud.netflix.eureka.serviceregistry.EurekaServiceRegistry.maybeInitializeClient(EurekaServiceRegistry.java:53) ~[spring-cloud-netflix-eureka-client-4.0.1.jar!/:4.0.1]
1734432268161,  at org.springframework.cloud.netflix.eureka.serviceregistry.EurekaServiceRegistry.register(EurekaServiceRegistry.java:38) ~[spring-cloud-netflix-eureka-client-4.0.1.jar!/:4.0.1]
1734432268161,  at org.springframework.cloud.netflix.eureka.serviceregistry.EurekaAutoServiceRegistration.start(EurekaAutoServiceRegistration.java:83) ~[spring-cloud-netflix-eureka-client-4.0.1.jar!/:4.0.1]
1734432268161,  at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:179) ~[spring-context-6.0.11.jar!/:6.0.11]
1734432268161,  ... 21 common frames omitted
1734432268161,"Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.netflix.appinfo.ApplicationInfoManager]: Factory method 'eurekaApplicationInfoManager' threw exception with message: Cannot invoke ""java.lang.CharSequence.toString()"" because ""replacement"" is null"
1734432268161,  at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:171) ~[spring-beans-6.0.11.jar!/:6.0.11]
1734432268161,  at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:655) ~[spring-beans-6.0.11.jar!/:6.0.11]
1734432268161,  ... 38 common frames omitted
1734432268161,"Caused by: java.lang.NullPointerException: Cannot invoke ""java.lang.CharSequence.toString()"" because ""replacement"" is null"
1734432268161,  at java.base/java.lang.String.replace(String.java:2961) ~[na:na]
1734432268161,  at com.netflix.appinfo.InstanceInfo$Builder.setStatusPageUrl(InstanceInfo.java:623) ~[eureka-client-2.0.0.jar!/:2.0.0]
1734432268161,  at org.springframework.cloud.netflix.eureka.InstanceInfoFactory.create(InstanceInfoFactory.java:58) ~[spring-cloud-netflix-eureka-client-4.0.1.jar!/:4.0.1]
1734432268161,  at org.springframework.cloud.netflix.eureka.EurekaClientAutoConfiguration$RefreshableEurekaClientConfiguration.eurekaApplicationInfoManager(EurekaClientAutoConfiguration.java:331) ~[spring-cloud-netflix-eureka-client-4.0.1.jar!/:4.0.1]
1734432268161,  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
1734432268161,  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
1734432268161,  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
1734432268161,  at java.base/java.lang.reflect.Method.invoke(Method.java:569) ~[na:na]
1734432268161,  at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:139) ~[spring-beans-6.0.11.jar!/:6.0.11]
1734432268161,  ... 39 common frames omitted
```

[https://stackoverflow.com/questions/79288684/error-creating-bean-with-name-scopedtarget-eurekaapplicationinfomanager](https://stackoverflow.com/questions/79288684/error-creating-bean-with-name-scopedtarget-eurekaapplicationinfomanager)

**Comment by OlgaMaciaszek** [comment]
Hello, @gangadharkasturi, thanks for creating the issue. Spring Cloud `2022.0.x` has been out of OSS support for over a year now. Please upgrade to Spring Cloud `2023.0.x` or `2024.0.x` and verify.

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.
