### ISSUE TITLE
Feign generic clients

### ISSUE THREAD

**Issue by jmnarloch** [spring-cloud/spring-cloud-netflix#457]
Since the update of Feign to version 8.6.0 now it's possible to have whole interface hierarchies used as a clients.

I was trying to facilitate this idea in a form:
```
public interface CrudClient<T> {      

    @RequestMapping(method = RequestMethod.POST, value = "/") 
    long save(T entity);      

    @RequestMapping(method = RequestMethod.PUT, value = "/{id}")     
    void update(@PathVariable("id") long id, T entity);      

    @RequestMapping(method = RequestMethod.GET, value = "/{id}")     
    T get(@PathVariable("id") long id);     

    @RequestMapping(method = RequestMethod.DELETE, value = "/{id}")     
    void delete(@PathVariable("id") long id); 
}
```

The only problem with this approach is that you will have to alter the specific paths for the concreate clients. The only supported way at the moment is to specify the explicit url like. 'http://localhost/users'

But it would be awaseome if it would be possible to do that with enabled Eureka discovery and Ribbon load balancing. Through one of the possible syntaxes:
```
@FeignClient("localapp/users")
public interface UsersClient extends CrudClient<User> {
  }
```
or
```
@FeignClient("localapp")
 @RequestMapping(value = "/users") 
public interface UsersClient extends CrudClient<User> {
  }
```

**Comment by jmnarloch** [comment]
The second example has funny implication, becouse it registers a handler within Spring MVC, so proably extending the @FeignClient functionality would be better.

**Comment by spencergibb** [comment]
We have supported `@RequestMapping` on the interface since 38e25f390f93d133aab2d21f43769ee57d1b1778.  Adding `@RequestMapping` shouldn't automatically register a bean since it doesn't have a "parent annotation" of `@Component`, like `@Controller` does.  If you are seeing that problem, please open an issue specifically for that.  Thanks!

**Comment by jmnarloch** [comment]
Just as fallow up. I might wrongly interpreted the result, but this test proves something different I think: https://github.com/jmnarloch/spring-cloud-netflix/commit/2d24bf630e57f6aec012983b4465c8cc8875dea7

As long the feign client is annotated with @RequestMapping(value = "/") the test is going to fail with:

```
Caused by: java.lang.IllegalStateException: Ambiguous mapping. Cannot map 'feignHttpClientTests$UserClient' method 
public abstract T org.springframework.cloud.netflix.feign.valid.FeignHttpClientTests$CrudClient.get(long)
to {[/users/{id}],methods=[GET]}: There is already 'feignHttpClientTests.Application' bean method
public java.lang.Object org.springframework.cloud.netflix.feign.valid.FeignHttpClientTests$Application.get(long) mapped.
	at org.springframework.web.servlet.handler.AbstractHandlerMethodMapping$MappingRegistry.assertUniqueMethodMapping(AbstractHandlerMethodMapping.java:565)
	at org.springframework.web.servlet.handler.AbstractHandlerMethodMapping$MappingRegistry.register(AbstractHandlerMethodMapping.java:529)
	at org.springframework.web.servlet.handler.AbstractHandlerMethodMapping.registerHandlerMethod(AbstractHandlerMethodMapping.java:252)
	at org.springframework.web.servlet.handler.AbstractHandlerMethodMapping.detectHandlerMethods(AbstractHandlerMethodMapping.java:223)
	at org.springframework.web.servlet.handler.AbstractHandlerMethodMapping.initHandlerMethods(AbstractHandlerMethodMapping.java:183)
	at org.springframework.web.servlet.handler.AbstractHandlerMethodMapping.afterPropertiesSet(AbstractHandlerMethodMapping.java:164)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping.afterPropertiesSet(RequestMappingHandlerMapping.java:134)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1637)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1574)
	... 44 more
```

I consider this as a kind of edge case and this is not something important to me, just interesting finding.

**Comment by spencergibb** [comment]
@jmnarloch [here are](https://github.com/spring-projects/spring-framework/blob/master/spring-webmvc/src/main/java/org/springframework/web/servlet/mvc/method/annotation/RequestMappingHandlerMapping.java#L178-L181) the offending lines.  So it's 
```
if  `@Controller` || `@RequestMapping`
```
Why don't you open a new issue as a bug since this was a feature request.

**Comment by jmnarloch** [comment]
You mean to open an issue in Spring Framework, right?

**Comment by spencergibb** [comment]
@jmnarloch no, here.  That feignclients are registered as mvc controllers if they put `@RequestMapping` on the class.
