### ISSUE TITLE
Bad status on discovery client log

### ISSUE THREAD

**Issue by ljramones** [spring-cloud/spring-cloud-netflix#47]
I am noticing that I get a `RuntimeException: Bad status: 500` every 5 or so minutes in my logs.  The test service I created does seem to connect but this is filling up my logs.
Any idea why this should be happening?
Here is a trace:

```
2014-10-23 18:06:52.767  INFO 75065 --- [pool-3-thread-1] com.netflix.discovery.DiscoveryClient    : Finished a call to service url http://localhost:8761/v2/ and url path apps/delta with status code 200.
2014-10-23 18:06:52.770  INFO 75065 --- [pool-3-thread-1] com.netflix.discovery.DiscoveryClient    : Completed cache refresh task for discovery. All Apps hash code is Local region apps hashcode: UP_1_, is fetching remote regions? false 
2014-10-23 18:06:55.061  INFO 75065 --- [pool-2-thread-1] com.netflix.discovery.DiscoveryClient    : Finished a call to service url http://localhost:8761/v2/ and url path apps/TESTSERVICE1/127.0.0.1 with status code 500.
2014-10-23 18:06:55.061  WARN 75065 --- [pool-2-thread-1] com.netflix.discovery.DiscoveryClient    : Action: Renew  => returned status of 500 from http://localhost:8761/v2/apps/TESTSERVICE1/127.0.0.1
2014-10-23 18:06:55.062 ERROR 75065 --- [pool-2-thread-1] com.netflix.discovery.DiscoveryClient    : Can't get a response from http://localhost:8761/v2/apps/TESTSERVICE1/127.0.0.1
Can't contact any eureka nodes - possibly a security group issue?

java.lang.RuntimeException: Bad status: 500
    at com.netflix.discovery.DiscoveryClient.makeRemoteCall(DiscoveryClient.java:1114)
    at com.netflix.discovery.DiscoveryClient.makeRemoteCall(DiscoveryClient.java:1019)
    at com.netflix.discovery.DiscoveryClient.access$400(DiscoveryClient.java:108)
    at com.netflix.discovery.DiscoveryClient$HeartbeatThread.run(DiscoveryClient.java:1528)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)

2014-10-23 18:06:55.062 ERROR 75065 --- [pool-2-thread-1] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_TESTSERVICE1/127.0.0.1 - was unable to send heartbeat!

java.lang.RuntimeException: Bad status: 500
    at com.netflix.discovery.DiscoveryClient.makeRemoteCall(DiscoveryClient.java:1114)
    at com.netflix.discovery.DiscoveryClient.makeRemoteCall(DiscoveryClient.java:1019)
    at com.netflix.discovery.DiscoveryClient.access$400(DiscoveryClient.java:108)
    at com.netflix.discovery.DiscoveryClient$HeartbeatThread.run(DiscoveryClient.java:1528)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)

2014-10-23 18:07:05.072  INFO 75065 --- [pool-2-thread-1] com.netflix.discovery.DiscoveryClient    : Finished a call to service url http://localhost:8761/v2/ and url path apps/TESTSERVICE1/127.0.0.1 with status code 404.
2014-10-23 18:07:05.072  INFO 75065 --- [pool-2-thread-1] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_TESTSERVICE1/127.0.0.1 - Re-registering apps/TESTSERVICE1
2014-10-23 18:07:05.072  INFO 75065 --- [pool-2-thread-1] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_TESTSERVICE1/127.0.0.1: registering service...
2014-10-23 18:07:05.079  INFO 75065 --- [pool-2-thread-1] com.netflix.discovery.DiscoveryClient    : Finished a call to service url http://localhost:8761/v2/ and url path apps/TESTSERVICE1 with status code 204.
2014-10-23 18:07:05.080  INFO 75065 --- [pool-2-thread-1] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_TESTSERVICE1/127.0.0.1 - registration status: 204
2014-10-23 18:07:15.088  INFO 75065 --- [pool-2-thread-1] com.netflix.discovery.DiscoveryClient    : Finished a call to service url http://localhost:8761/v2/ and url path apps/TESTSERVICE1/127.0.0.1 with status code 200.
2014-10-23 18:07:22.777  INFO 75065 --- [pool-3-thread-1] com.netflix.discovery.DiscoveryClient    : Finished a call to service url http://localhost:8761/v2/ and url path apps/delta with status code 200.
2014-10-23 18:07:22.779  INFO 75065 --- [pool-3-thread-1] com.netflix.discovery.DiscoveryClient    : Completed cache refresh task for discovery. All Apps hash code is Local region apps hashcode: UP_1_, is fetching remote regions? false 
2014-10-23 18:07:25.096  INFO 75065 --- [pool-2-thread-1] com.netflix.discovery.DiscoveryClient    : Finished a call to service url http://localhost:8761/v2/ and url path apps/TESTSERVICE1/127.0.0.1 with status code 200.
```

**Comment by kennyk65** [comment]
@larry13767 - Did you ever determine what the cause of this was?

I get something similar, except it is a 404, and Boot logs it as an ERROR:

    2015-04-20 20:39:15.366 ERROR 87609 --- [pool-7-thread-1] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_BOOTSTRAP/Ken-Krueger-MacBook-Pro.local - was unable to refresh its cache!     status = Bad status: 404

    java.lang.RuntimeException: Bad status: 404
 	at com.netflix.discovery.DiscoveryClient.makeRemoteCall(DiscoveryClient.java:1155)
	at com.netflix.discovery.DiscoveryClient.makeRemoteCall(DiscoveryClient.java:1060)
	at com.netflix.discovery.DiscoveryClient.getAndStoreFullRegistry(DiscoveryClient.java:835)
	at com.netflix.discovery.DiscoveryClient.fetchRegistry(DiscoveryClient.java:746)
	at com.netflix.discovery.DiscoveryClient.access$1400(DiscoveryClient.java:105)
	at com.netflix.discovery.DiscoveryClient$CacheRefreshThread.run(DiscoveryClient.java:1723)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

It doesn't seem to be harmful except it fills the logs.  I have 3 instances intercommunicating, and they seem to be ok other than this log activity.

**Comment by kennyk65** [comment]
Never mind, I discovered my problem.  I had left the trailing "/" off of the default zone.  User headspace error:

    eureka:
      client:
        serviceUrl:
          defaultZone: http://localhost:8013/eureka/
