### ISSUE TITLE
spring-cloud-starter-eureka contains incorrect version of ribbon-httpclient

### ISSUE THREAD

**Issue by Klaxon77** [spring-cloud/spring-cloud-netflix#480]
`Spring-cloud-starter-eureka` contains incorrect version of `ribbon-httpclient`. This causes NoSuchFieldError while creating ribbon RestClient:
```
java.lang.NoSuchFieldError: ReceiveBuffferSize
	at com.netflix.niws.client.http.RestClient.apacheHttpClientSpecificInitialization(RestClient.java:283)
	at org.springframework.cloud.netflix.ribbon.RibbonClientConfiguration$OverrideRestClient.apacheHttpClientSpecificInitialization(RibbonClientConfiguration.java:147)
	at com.netflix.niws.client.http.RestClient.initWithNiwsConfig(RestClient.java:163)
	at org.springframework.cloud.netflix.ribbon.RibbonClientConfiguration$OverrideRestClient.<init>(RibbonClientConfiguration.java:141)
	at org.springframework.cloud.netflix.ribbon.RibbonClientConfiguration.ribbonRestClient(RibbonClientConfiguration.java:104)
	at org.springframework.cloud.netflix.ribbon.RibbonClientConfiguration$$EnhancerBySpringCGLIB$$733272c7.CGLIB$ribbonRestClient$7(<generated>)
	at org.springframework.cloud.netflix.ribbon.RibbonClientConfiguration$$EnhancerBySpringCGLIB$$733272c7$$FastClassBySpringCGLIB$$40d291aa.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:309)
	at org.springframework.cloud.netflix.ribbon.RibbonClientConfiguration$$EnhancerBySpringCGLIB$$733272c7.ribbonRestClient(<generated>)
```

### Cause:
Wrong version of  ribbon-httpclient which is transitive dependency from `spring-cloud-starter-eureka` (1.0.3.RELEASE). All transitive dependencies for ribbon are of version **2.0.0**, but **ribbon-httpclient** is of version **2.0-RC9**.

### Workaround
Because of this problem we need to set version for ribbon-httpclient explicitely in our project, and it's easy to forget about it.

### My application
My dependencies in maven look like:
```
    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
            <version>1.2.5.RELEASE</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-eureka</artifactId>
            <version>1.0.3.RELEASE</version>
        </dependency>
        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
        </dependency>
    </dependencies>
```

And code:
```
@SpringBootApplication
@EnableEurekaClient
public class EurekaClientApplication {
    public static void main(String[] args) {
        SpringApplication.run(EurekaClientApplication.class, args);
    }

    @RestController
    public static class PingController {

        @Autowired
        private RestTemplate eurekaRestTemplate;

        @RequestMapping("/ping")
        public String ping() {
            return "{ ping: ok }";
        }

        @RequestMapping("/pingByEureka")
        public String pingByEureka() {
            return eurekaRestTemplate.getForObject("http://eureka-client/ping", String.class);
        }
    }
}
```
After endpoint `/pingByEureka` is invoked - restTemplate configured with ribbon is created and we get previously mentioned exception.

**Comment by spencergibb** [comment]
What is the parent of your pom?  Or are you importing the BOM?  Wondering if one of those will fix your issue.

You should have
```
	<parent>
		<groupId>org.springframework.cloud</groupId>
		<artifactId>spring-cloud-starter-parent</artifactId>
		<version>Angel.SR3</version>
	</parent>
```

or 
```
	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-starter-parent</artifactId>
				<version>Angel.SR3</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>
```

**Comment by Klaxon77** [comment]
Hello @spencergibb. 
Solution with including **spring-cloud-starter-parent**, as described above works fine.

But what if I already have another parent pom? And don't want to include a BOM, because it will break my other transitive dependencies?

Is there a chance this issue will be fixed in next version of spring-cloud-starter-eureka?

**Comment by spencergibb** [comment]
Should be fixed in the next version already:
```
[INFO] +- com.netflix.ribbon:ribbon-httpclient:jar:2.1.0:compile
```

**Comment by Klaxon77** [comment]
Thank you.

**Comment by spencergibb** [comment]
Is this still a problem with `Brixton.M1`?

**Comment by spencergibb** [comment]
Closing due to lack of requested feedback. If you'd like us to reopen the issue, please comment with the required information.
