### ISSUE TITLE
Can't use Spring security with @FeignClient

### ISSUE THREAD

**Issue by zhsyourai** [spring-cloud/spring-cloud-netflix#503]
When I use Spring security and @FeignClient together:
```java
@FeignClient("base-server")
public interface BaseServerClient {
    @RequestMapping(value = "/find", method = RequestMethod.GET)
    School find(@RequestParam("Id") long Id);
}
```
And

```java
@Autowired
private BaseServerClient baseServerClient;
...
baseServerClient.find();
```
It throw

```java
java.lang.NullPointerException: null
	at feign.ribbon.LoadBalancingTarget.apply(LoadBalancingTarget.java:95) ~[feign-ribbon-8.7.1.jar:8.7.1]
	at feign.SynchronousMethodHandler.targetRequest(SynchronousMethodHandler.java:141) ~[feign-core-8.7.1.jar:8.7.1]
	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:83) ~[feign-core-8.7.1.jar:8.7.1]
	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:71) ~[feign-core-8.7.1.jar:8.7.1]
	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:94) ~[feign-core-8.7.1.jar:8.7.1]
	at com.sun.proxy.$Proxy121.find(Unknown Source) ~[na:na]
```

And I found ribbonClient is null

```java
	protected <T> T loadBalance(Feign.Builder builder, Class<T> type, String schemeName) {
		builder.logger(new Slf4jLogger(type)); // TODO: how to have choice here?
		if (this.ribbonClient != null) {
			return builder.client(this.ribbonClient).target(type, schemeName);
		}
		else {
			return builder.target(LoadBalancingTarget.create(type, schemeName));
		}
	}
```

But when I remove Spring security from my project, It is work.
I think this is a autoconfig problem.

This is a demo to reproduce the problem https://github.com/zhsyourai/demoFeign

**Comment by spencergibb** [comment]
Closing as duplicate of #441
