### ISSUE TITLE
Zuul forwarding error in Undertow

### ISSUE THREAD

**Issue by jmnarloch** [spring-cloud/spring-cloud-netflix#524]
Hi, 

I have an interesting Zuul exception (in version 1.0.1)  with Undertow 1.2.9. In order to reproduce this start any Zuul proxy application with configured route for service id, but disconnected from Eureka.
So that Ribbon would not be able to lookup the service address.

Sample config:
```
zuul:
  ignoredServices: '*'
  retryable: true
  routes:
    api:
      path: /api/v1/**
      serviceId: invoices
```
What is going to happen is that Ribbon will throw an exception:
```
com.netflix.client.ClientException: Load balancer does not have available server for client: rest-service
	com.netflix.loadbalancer.LoadBalancerContext.getServerFromLoadBalancer(LoadBalancerContext.java:468)
	com.netflix.loadbalancer.reactive.LoadBalancerCommand$1.call(LoadBalancerCommand.java:184)
	com.netflix.loadbalancer.reactive.LoadBalancerCommand$1.call(LoadBalancerCommand.java:180)
	rx.Observable$1.call(Observable.java:144)
	rx.Observable$1.call(Observable.java:136)
	rx.Observable$1.call(Observable.java:144)
	rx.Observable$1.call(Observable.java:136)
	rx.Observable.unsafeSubscribe(Observable.java:7531)
```

This works fine in Tomcat, the error is propagated to the client with HTTP 500 status code. But in Undertow this does not work the same and causes an error.

```
com.netflix.zuul.exception.ZuulException: Filter threw Exception
	at com.netflix.zuul.FilterProcessor.processZuulFilter(FilterProcessor.java:231)
	at com.netflix.zuul.FilterProcessor.runFilters(FilterProcessor.java:161)
	at com.netflix.zuul.FilterProcessor.postRoute(FilterProcessor.java:92)
	at com.netflix.zuul.ZuulRunner.postRoute(ZuulRunner.java:75)
	at com.netflix.zuul.http.ZuulServlet.postRoute(ZuulServlet.java:102)
	at com.netflix.zuul.http.ZuulServlet.service(ZuulServlet.java:84)
	at org.springframework.web.servlet.mvc.ServletWrappingController.handleRequestInternal(ServletWrappingController.java:158)
	at org.springframework.cloud.netflix.zuul.web.ZuulController.handleRequestInternal(ZuulController.java:43)
	at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:147)
	at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:50)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:86)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:130)
	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:172)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:199)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:774)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: UT010023: Request org.springframework.cloud.netflix.zuul.filters.pre.Servlet30RequestWrapper@a16ed1b was not original or a wrapper
	at io.undertow.servlet.spec.RequestDispatcherImpl.forwardImpl(RequestDispatcherImpl.java:138)
	at io.undertow.servlet.spec.RequestDispatcherImpl.forward(RequestDispatcherImpl.java:108)
	at org.springframework.cloud.netflix.zuul.filters.post.SendErrorFilter.run(SendErrorFilter.java:74)
	at com.netflix.zuul.ZuulFilter.runFilter(ZuulFilter.java:112)
	at com.netflix.zuul.FilterProcessor.processZuulFilter(FilterProcessor.java:197)
	... 99 common frames omitted

```

Generally the error thrown by Undertow 
```
Caused by: java.lang.IllegalArgumentException: UT010023: Request org.springframework.cloud.netflix.zuul.filters.pre.Servlet30RequestWrapper@a16ed1b was not original or a wrapper 
```
Is hiding the original exception thrown from Ribbon and the worse thing is that it causes the ZuulFilter to proceed as there were no error and return 200 HTTP Success response without any payload.

![zuul_forwarding_error_undertow](https://cloud.githubusercontent.com/assets/1581045/9757326/2f678c32-56e0-11e5-83a4-7625c628f683.png)

**Comment by jmnarloch** [comment]
I was doing one thing wrong I haven't set the allow-non-standard-wrappers property to true (default is false) that you would normally set for Widfly in xml file. 
https://docs.jboss.org/author/display/WFLY9/Undertow+%28web%29+subsystem+configuration

In Spring Boot you need to add factory been instead:
```
@Bean
    public UndertowEmbeddedServletContainerFactory embeddedServletContainerFactory() {
        UndertowEmbeddedServletContainerFactory factory = new UndertowEmbeddedServletContainerFactory();
        factory.addDeploymentInfoCustomizers(new UndertowDeploymentInfoCustomizer() {
            @Override
            public void customize(DeploymentInfo deploymentInfo) {
                deploymentInfo.setAllowNonStandardWrappers(true);
            }
        });
        return factory;
    }
```

Unfortunetly this does not fix my problem though, I still have response 200 - SUCCESS instead of error from Zuul

**Comment by jmnarloch** [comment]
Closing the issue, this was only my fault and not fully configured Undertow. Besides the above property you need to register error handler in servlet context upart from any that you might have in Spring.

**Comment by jmnarloch** [comment]
On the other hand @spencergibb @dsyer don't you think that Zuul should come with autoconfiguration for Undertow that would at least set allowNonStandardWrappers to true? In other case that would "eat" any Zuul forwarding exceptions.

**Comment by alwinmark** [comment]
I think at least the status code should be unlike 200. As we had Akamai in front of our application this Bug leads to broken assets, because Akamai refetched it's assets and zuul returned 200 with an empty page...
