### ISSUE TITLE
Spring cloud config server with ssl discoverable through http instead of https

### ISSUE THREAD

**Issue by ruchakulkarni** [spring-cloud/spring-cloud-netflix#532]
I have set up a config server with basic authentication and SSL enabled. It has following properties in application.yml

    server:  
     port: 8888  
     ssl:  
       key-store: keystore.p12  
       key-store-password: keypass
       keyStoreType: PKCS12
       keyAlias: tomcat
and following eureka instance properties:

    eureka:
      environment: DEVLOCAL
      client:
        enabled: true
        region: ${eureka.region:us-west-1}
        registryFetchIntervalSeconds: 30
        instanceInfoReplicationIntervalSeconds: 30
        initialInstanceInfoReplicationIntervalSeconds: 40
        eurekaServiceUrlPollIntervalSeconds: 300
        eurekaConnectionIdleTimeoutSeconds: 30
        heartbeatExecutorThreadPoolSize: 2
        heartbeatExecutorExponentialBackOffBound: 10
        cacheRefreshExecutorThreadPoolSize: 2
        cacheRefreshExecutorExponentialBackOffBound: 10
        serviceUrl:
          defaultZone: http://127.0.0.1:8761/eureka/
      instance:
        statusPageUrl: https://localhost:${server.port}/info
        securePort: ${server.port}
        securePortEnabled: true
        nonSecurePortEnabled: false
        secureVirtualHostName: ${spring.application.name}
        appname: ${spring.application.name}
        leaseRenewalIntervalInSeconds: 10
        metadataMap:
          securePort: ${server.port}

Also, I am running a spring cloud discovery service locally that is able to discover my config server. Since I have overridden my eureka.instance.statusPageUrl, I am able to see the info of my config server on the discovery service.

Now, I created a sample service that depends on config server and wants to discover the config server through the discovery service. But the discovery service gives "**http**://localhost:8888/" as the url for config server, whereas it should have given "**https**://localhost:8888/". Why doesn't the discovery service recognize that my config server is using **https** and not **http**?

**Comment by dsyer** [comment]
What version of Spring Cloud components are you using? Try with `Brixton.BUILD-SNAPSHOT` and see if you get the same behaviour.

**Comment by jacquesboucher** [comment]
`com.netflix.appinfo.InstanceInfo` seems to hardcode the protocol to http:

```java
        public Builder setHomePageUrl(String relativeUrl, String explicitUrl) {
            String hostNameInterpolationExpression = "${" + namespace + "hostname}";
            if (explicitUrl != null) {
                result.homePageUrl = explicitUrl.replace(
                        hostNameInterpolationExpression, result.hostName);
            } else if (relativeUrl != null) {
                result.homePageUrl = HTTP_PROTOCOL + result.hostName + COLON
                + result.port + relativeUrl;
            }
            return this;
        }
```

An easy workaround is to update your spring config application(.yml) by specifying the `homePageUrl`:

```
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 15
    leaseExpirationDurationInSeconds: 20
    statusPageUrlPath: /admin/info
    healthCheckUrlPath: /admin/health
    hostname: ${vcap.application.uris[0]:localhost}
    securePort: ${application_secure_port:${server.port}}
    securePortEnabled: ${secure_port_enabled:true}
    nonSecurePortEnabled: false 
    homePageUrl: https://${eureka.instance.hostname}:${eureka.instance.securePort}/
```

Our application had the same issue where it would give the following error when trying to lookup Spring Config via Eureka:

```
Caused by: org.springframework.web.client.ResourceAccessException: I/O error on GET request for "http://localhost:8762/myapp/default":Unexpected end of file from server; nested exception is java.net.SocketException: Unexpected end of file from server
```

By setting the `homePageUrl`, the `ConfigClientProperties` will use this information when asked by `ConfigServicePropertySourceLocator.getRemoteEnvironment`.


I've tired with `Brixton.M3`, but I get `NoClassDefFoundError org/springframework/cloud/stream/binder/Binder` when running the application.

These are the dependencies used:
```gradle
dependencyManagement {
  imports {
    mavenBom 'org.springframework.cloud:spring-cloud-starter-parent:Brixton.M3'
  }
}

dependencies {
  compile 'org.springframework.cloud:spring-cloud-starter-config'
  compile 'org.springframework.cloud:spring-cloud-config-server'
  compile ("org.springframework.cloud:spring-cloud-starter-eureka") {
    exclude module: "servlet-api"
  }
  
  compile("org.springframework.boot:spring-boot-starter-web") {
    exclude module: "spring-boot-starter-tomcat"
  }
  
  compile "org.springframework.boot:spring-boot-starter-jetty"
  compile "org.springframework.boot:spring-boot-starter-actuator"
  
}
```

The stacktrace is the following:
```
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:53)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: Could not evaluate condition on org.springframework.cloud.netflix.eureka.EurekaClientAutoConfiguration#eurekaClientConfigBean due to internal class not found. This can happen if you are @ComponentScanning a springframework package (e.g. if you put a @ComponentScan in the default package by mistake)
        at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:53)
        at org.springframework.context.annotation.ConditionEvaluator.shouldSkip(ConditionEvaluator.java:102)
        at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForBeanMethod(ConfigurationClassBeanDefinitionReader.java:178)
        at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForConfigurationClass(ConfigurationClassBeanDefinitionReader.java:140)
        at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitions(ConfigurationClassBeanDefinitionReader.java:116)
        at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:333)
        at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:243)
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:273)
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:98)
        at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:677)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:519)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:752)
        at org.springframework.boot.SpringApplication.doRun(SpringApplication.java:347)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:295)
        at org.oneplatform.commons.framework.springboot.StartupHelper.launch(StartupHelper.java:55)
        at org.oneplatform.cloud.config.Application.startup(Application.java:49)
        at org.oneplatform.cloud.config.Application.main(Application.java:61)
        ... 6 more
Caused by: java.lang.NoClassDefFoundError: org/springframework/cloud/stream/binder/Binder
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2693)
        at java.lang.Class.getDeclaredMethods(Class.java:1967)
        at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:609)
        at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:521)
        at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:507)
        at org.springframework.util.ReflectionUtils.getUniqueDeclaredMethods(ReflectionUtils.java:567)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.getTypeForFactoryMethod(AbstractAutowireCapableBeanFactory.java:683)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.determineTargetType(AbstractAutowireCapableBeanFactory.java:627)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.predictBeanType(AbstractAutowireCapableBeanFactory.java:597)
        at org.springframework.beans.factory.support.AbstractBeanFactory.isFactoryBean(AbstractBeanFactory.java:1445)
        at org.springframework.beans.factory.support.AbstractBeanFactory.isFactoryBean(AbstractBeanFactory.java:975)
        at org.springframework.boot.autoconfigure.condition.BeanTypeRegistry$OptimizedBeanTypeRegistry.addBeanTypeForNonAliasDefinition(BeanTypeRegistry.java:289)
        at org.springframework.boot.autoconfigure.condition.BeanTypeRegistry$OptimizedBeanTypeRegistry.addBeanType(BeanTypeRegistry.java:278)
        at org.springframework.boot.autoconfigure.condition.BeanTypeRegistry$OptimizedBeanTypeRegistry.getNamesForType(BeanTypeRegistry.java:259)
        at org.springframework.boot.autoconfigure.condition.OnBeanCondition.collectBeanNamesForType(OnBeanCondition.java:182)
        at org.springframework.boot.autoconfigure.condition.OnBeanCondition.getBeanNamesForType(OnBeanCondition.java:171)
        at org.springframework.boot.autoconfigure.condition.OnBeanCondition.getMatchingBeans(OnBeanCondition.java:139)
        at org.springframework.boot.autoconfigure.condition.OnBeanCondition.getMatchOutcome(OnBeanCondition.java:113)
        at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:47)
        ... 23 more
Caused by: java.lang.ClassNotFoundException: org.springframework.cloud.stream.binder.Binder
        at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at org.springframework.boot.loader.LaunchedURLClassLoader.doLoadClass(LaunchedURLClassLoader.java:170)
        at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:136)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 43 more
2015-12-08 10:19:53.789  INFO 6784 --- [       Thread-2] s.c.a.AnnotationConfigApplicationContext : Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@ca10cf0: startup date [Tue Dec 08 10:19:47 EST 2015]; root of context hierarchy
```
The annotation on the Spring Boot app were:

```
@SpringBootApplication
@EnableConfigServer
@EnableEurekaClient
```
Changed to:

```
@Configuration
@EnableAutoConfiguration
@EnableConfigServer
@EnableEurekaClient
```
But same exception as above when starting up the Spring boot based config app.  Changing the BOM to `Angel.SR4`, the application starts up fine (but the app that tries to lookup spring config via eureka fails as it uses http instead of https).

Using `Brixton.BUILD-SNAPSHOT` results in unresolved dependencies:

```
           https://artifactory.oneplatform.org/artifactory/libs-release/org/springframework/cloud/spring-cloud-starter-parent/Brixton.BUILD-SNAPSHOT/spring-cloud-starter-parent-Brixton.BUILD-SNAPSHOT.pom
        Required by:
            org.oneplatform:oneplatform-cloud-config:1.0.0
   > Could not resolve all dependencies for configuration 'detachedConfiguration1'.
      > Could not find org.springframework.cloud:spring-cloud-starter-parent:Brixton.BUILD-SNAPSHOT.
        Searched in the following locations:
            https://jcenter.bintray.com/org/springframework/cloud/spring-cloud-starter-parent/Brixton.BUILD-SNAPSHOT/maven-metadata.xml
            https://jcenter.bintray.com/org/springframework/cloud/spring-cloud-starter-parent/Brixton.BUILD-SNAPSHOT/spring-cloud-starter-parent-Brixton.BUILD-SNAPSHOT.pom
            https://jcenter.bintray.com/org/springframework/cloud/spring-cloud-starter-parent/Brixton.BUILD-SNAPSHOT/spring-cloud-starter-parent-Brixton.BUILD-SNAPSHOT.pom
            file:/C:/Users/boucherj/.m2/repository/org/springframework/cloud/spring-cloud-starter-parent/Brixton.BUILD-SNAPSHOT/maven-metadata.xml
            file:/C:/Users/boucherj/.m2/repository/org/springframework/cloud/spring-cloud-starter-parent/Brixton.BUILD-SNAPSHOT/spring-cloud-starter-parent-Brixton.BUILD-SNAPSHOT.pom
            file:/C:/Users/boucherj/.m2/repository/org/springframework/cloud/spring-cloud-starter-parent/Brixton.BUILD-SNAPSHOT/spring-cloud-starter-parent-Brixton.BUILD-SNAPSHOT.pom
            https://artifactory.oneplatform.org/artifactory/libs-release/org/springframework/cloud/spring-cloud-starter-parent/Brixton.BUILD-SNAPSHOT/maven-metadata.xml
            https://artifactory.oneplatform.org/artifactory/libs-release/org/springframework/cloud/spring-cloud-starter-parent/Brixton.BUILD-SNAPSHOT/spring-cloud-starter-parent-Brixton.BUILD-SNAPSHOT.pom
            https://artifactory.oneplatform.org/artifactory/libs-release/org/springframework/cloud/spring-cloud-starter-parent/Brixton.BUILD-SNAPSHOT/spring-cloud-starter-parent-Brixton.BUILD-SNAPSHOT.pom
        Required by:
            org.oneplatform:oneplatform-cloud-config:1.0.0
```

Sorry, haven't dig more as the workaround is good enough for now on our side.

**Comment by dsyer** [comment]
I think this is working as designed (once you get the dependencies ironed out). There's a section in the user guide about how to register a secure app, and I don't think there's anything different here.
