### ISSUE TITLE
Servo errors on shutdown

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-netflix#571]
```
2015-10-02 11:43:36.817  WARN 3726 --- [       Thread-2] c.netflix.servo.jmx.JmxMonitorRegistry   : Unable to un-register Monitor:MonitorConfig{name=eurekaClient.registry.lastUpdateSec_00480, tags=class=org.springframework.cloud.netflix.eureka.CloudEurekaClient,GAUGE, policy=DefaultPublishingPolicy}
javax.management.InstanceNotFoundException: com.netflix.servo:name=eurekaClient.registry.lastUpdateSec_00480,class=org.springframework.cloud.netflix.eureka.CloudEurekaClient,type=GAUGE
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getMBean(DefaultMBeanServerInterceptor.java:1095) ~[na:1.8.0_05]
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.exclusiveUnregisterMBean(DefaultMBeanServerInterceptor.java:427) ~[na:1.8.0_05]
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.unregisterMBean(DefaultMBeanServerInterceptor.java:415) ~[na:1.8.0_05]
	at com.sun.jmx.mbeanserver.JmxMBeanServer.unregisterMBean(JmxMBeanServer.java:546) ~[na:1.8.0_05]
	at com.netflix.servo.jmx.JmxMonitorRegistry.unregister(JmxMonitorRegistry.java:125) ~[servo-core-0.9.4.jar!/:0.9.4]
	at com.netflix.servo.DefaultMonitorRegistry.unregister(DefaultMonitorRegistry.java:143) [servo-core-0.9.4.jar!/:0.9.4]
	at com.netflix.discovery.util.ThresholdLevelsMetric.shutdown(ThresholdLevelsMetric.java:84) [51bf1a45b0f6ffe5f4d2f84eaeb40b87b7ec5587-eureka-client-1.2.5.jar:1.2.5]
	at com.netflix.discovery.DiscoveryClient.shutdown(DiscoveryClient.java:869) [51bf1a45b0f6ffe5f4d2f84eaeb40b87b7ec5587-eureka-client-1.2.5.jar:1.2.5]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_05]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_05]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_05]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0_05]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:354) [spring-beans-4.2.1.RELEASE.jar!/:4.2.1.RELEASE]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeDestroyMethods(InitDestroyAnnotationBeanPostProcessor.java:319) [spring-beans-4.2.1.RELEASE.jar!/:4.2.1.RELEASE]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeDestruction(InitDestroyAnnotationBeanPostProcessor.java:153) [spring-beans-4.2.1.RELEASE.jar!/:4.2.1.RELEASE]
	at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:242) [spring-beans-4.2.1.RELEASE.jar!/:4.2.1.RELEASE]
	at org.springframework.beans.factory.support.DisposableBeanAdapter.run(DisposableBeanAdapter.java:235) [spring-beans-4.2.1.RELEASE.jar!/:4.2.1.RELEASE]
	at org.springframework.cloud.context.config.StandardBeanLifecycleDecorator$1.run(StandardBeanLifecycleDecorator.java:62) [spring-cloud-context-1.1.0.BUILD-SNAPSHOT.jar!/:1.1.0.BUILD-SNAPSHOT]
	at org.springframework.cloud.context.scope.GenericScope$BeanLifecycleWrapper.destroy(GenericScope.java:338) [spring-cloud-context-1.1.0.BUILD-SNAPSHOT.jar!/:1.1.0.BUILD-SNAPSHOT]
	at org.springframework.cloud.context.scope.GenericScope.destroy(GenericScope.java:126) [spring-cloud-context-1.1.0.BUILD-SNAPSHOT.jar!/:1.1.0.BUILD-SNAPSHOT]
	at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:261) [spring-beans-4.2.1.RELEASE.jar!/:4.2.1.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:578) [spring-beans-4.2.1.RELEASE.jar!/:4.2.1.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:554) [spring-beans-4.2.1.RELEASE.jar!/:4.2.1.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:925) [spring-beans-4.2.1.RELEASE.jar!/:4.2.1.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:523) [spring-beans-4.2.1.RELEASE.jar!/:4.2.1.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingletons(DefaultListableBeanFactory.java:932) [spring-beans-4.2.1.RELEASE.jar!/:4.2.1.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:997) [spring-context-4.2.1.RELEASE.jar!/:4.2.1.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:973) [spring-context-4.2.1.RELEASE.jar!/:4.2.1.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.doClose(EmbeddedWebApplicationContext.java:150) [spring-boot-1.3.0.BUILD-SNAPSHOT.jar!/:1.3.0.BUILD-SNAPSHOT]
	at org.springframework.context.support.AbstractApplicationContext.close(AbstractApplicationContext.java:925) [spring-context-4.2.1.RELEASE.jar!/:4.2.1.RELEASE]
	at org.springframework.boot.builder.ParentContextCloserApplicationListener$ContextCloserListener.onApplicationEvent(ParentContextCloserApplicationListener.java:102) [spring-boot-1.3.0.BUILD-SNAPSHOT.jar!/:1.3.0.BUILD-SNAPSHOT]
	at org.springframework.boot.builder.ParentContextCloserApplicationListener$ContextCloserListener.onApplicationEvent(ParentContextCloserApplicationListener.java:86) [spring-boot-1.3.0.BUILD-SNAPSHOT.jar!/:1.3.0.BUILD-SNAPSHOT]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:163) [spring-context-4.2.1.RELEASE.jar!/:4.2.1.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:136) [spring-context-4.2.1.RELEASE.jar!/:4.2.1.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:380) [spring-context-4.2.1.RELEASE.jar!/:4.2.1.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:334) [spring-context-4.2.1.RELEASE.jar!/:4.2.1.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:958) [spring-context-4.2.1.RELEASE.jar!/:4.2.1.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext$1.run(AbstractApplicationContext.java:893) [spring-context-4.2.1.RELEASE.jar!/:4.2.1.RELEASE]
```

**Comment by brenuart** [comment]
May be related to https://github.com/Netflix/eureka/issues/638

**Comment by spencergibb** [comment]
We have the fix from https://github.com/Netflix/eureka/pull/639 in spring-cloud-netflix now. Wonder if I just need to recompile my config server.

**Comment by spencergibb** [comment]
See https://github.com/Netflix/eureka/issues/704

**Comment by ccit-spence** [comment]
Looks like I am having the same issue with ```Spring Boot 1.3.0.RC1``` ```Brixton.M2```

```
2015-11-15 02:27:14.647  WARN 75431 --- [       Thread-1] c.netflix.servo.jmx.JmxMonitorRegistry   : Unable to un-register Monitor:MonitorConfig{name=eurekaClient.registry.lastUpdateSec_00480, tags=class=org.springframework.cloud.netflix.eureka.CloudEurekaClient,GAUGE, policy=DefaultPublishingPolicy}
javax.management.InstanceNotFoundException: com.netflix.servo:name=eurekaClient.registry.lastUpdateSec_00480,class=org.springframework.cloud.netflix.eureka.CloudEurekaClient,type=GAUGE
```

**Comment by brenuart** [comment]
Cannot reproduce the problem with `Brixton.M3`

**Comment by cforce** [comment]
I still have the problem on Brixton.M3
```java
javax.management.InstanceNotFoundException: com.netflix.servo:name=eurekaClient.resolver.lastLoadTimestamp,class=AsyncResolver,id=bootstrap,level=INFO,type=GAUGE
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getMBean(DefaultMBeanServerInterceptor.java:1095) ~[na:1.8.0_11]
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.exclusiveUnregisterMBean(DefaultMBeanServerInterceptor.java:427) ~[na:1.8.0_11]
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.unregisterMBean(DefaultMBeanServerInterceptor.java:415) ~[na:1.8.0_11]
	at com.sun.jmx.mbeanserver.JmxMBeanServer.unregisterMBean(JmxMBeanServer.java:546) ~[na:1.8.0_11]
	at com.netflix.servo.jmx.JmxMonitorRegistry.unregister(JmxMonitorRegistry.java:125) ~[servo-core-0.10.0.jar:0.10.0]
	at com.netflix.servo.DefaultMonitorRegistry.unregister(DefaultMonitorRegistry.java:143) [servo-core-0.10.0.jar:0.10.0]
	at com.netflix.servo.monitor.Monitors.unregisterObject(Monitors.java:197) [servo-core-0.10.0.jar:0.10.0]
	at com.netflix.discovery.shared.resolver.AsyncResolver.shutdown(AsyncResolver.java:136) [eureka-client-1.3.4.jar:1.3.4]
	at com.netflix.discovery.DiscoveryClient$EurekaTransport.shutdown(DiscoveryClient.java:259) [eureka-client-1.3.4.jar:1.3.4]
	at com.netflix.discovery.DiscoveryClient.shutdown(DiscoveryClient.java:962) [eureka-client-1.3.4.jar:1.3.4]
	at org.springframework.cloud.netflix.config.DiscoveryClientConfigServiceAutoConfiguration.init(DiscoveryClientConfigServiceAutoConfiguration.java:52) [spring-cloud-netflix-core-1.1.0.M3.jar:1.1.0.M3]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_11]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_11]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_11]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0_11]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:354) [spring-beans-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:305) [spring-beans-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:133) [spring-beans-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:408) [spring-beans-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1570) [spring-beans-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545) [spring-beans-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482) [spring-beans-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) [spring-beans-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) [spring-beans-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) [spring-beans-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) [spring-beans-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:772) [spring-beans-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:839) [spring-context-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:538) [spring-context-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118) [spring-boot-1.3.1.RELEASE.jar:1.3.1.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:764) [spring-boot-1.3.1.RELEASE.jar:1.3.1.RELEASE]
	at org.springframework.boot.SpringApplication.doRun(SpringApplication.java:357) [spring-boot-1.3.1.RELEASE.jar:1.3.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:305) [spring-boot-1.3.1.RELEASE.jar:1.3.1.RELEASE]
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:134) [spring-boot-1.3.1.RELEASE.jar:1.3.1.RELEASE]

**Comment by dinkarthakur** [comment]
I also have same problem on Brixton.M4

**Comment by spencergibb** [comment]
Closing this due to inactivity. Please re-open if there's more to discuss.
