### ISSUE TITLE
ClassNotFoundException: com.netflix.eureka.converters.EntityBodyConverter

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-netflix#60]
The missing class is in the eureka-client jar.  I have to restart eureka.

	[2014-11-06 10:45:22.259] boot - 99614  WARN [Finalizer] --- JmxMonitorRegistry: Unable to un-register Monitor:MonitorConfig{name=Discovery-PeerNodeClient-localhost, tags=class=NamedConnectionPool, policy=DefaultPublishingPolicy}
	javax.management.InstanceNotFoundException: com.netflix.servo:name=Discovery-PeerNodeClient-localhost_Reuse,class=NamedConnectionPool,type=COUNTER,id=Discovery-PeerNodeClient-localhost
		at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getMBean(DefaultMBeanServerInterceptor.java:1095)
		at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.exclusiveUnregisterMBean(DefaultMBeanServerInterceptor.java:427)
		at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.unregisterMBean(DefaultMBeanServerInterceptor.java:415)
		at com.sun.jmx.mbeanserver.JmxMBeanServer.unregisterMBean(JmxMBeanServer.java:546)
		at com.netflix.servo.jmx.JmxMonitorRegistry.unregister(JmxMonitorRegistry.java:123)
		at com.netflix.servo.DefaultMonitorRegistry.unregister(DefaultMonitorRegistry.java:143)
		at com.netflix.servo.monitor.Monitors.unregisterObject(Monitors.java:199)
		at com.netflix.http4.NamedConnectionPool.shutdown(NamedConnectionPool.java:188)
		at org.apache.http.impl.conn.tsccm.ThreadSafeClientConnManager.shutdown(ThreadSafeClientConnManager.java:293)
		at org.apache.http.impl.conn.tsccm.ThreadSafeClientConnManager.finalize(ThreadSafeClientConnManager.java:165)
		at java.lang.ref.Finalizer.invokeFinalizeMethod(Native Method)
		at java.lang.ref.Finalizer.runFinalizer(Finalizer.java:101)
		at java.lang.ref.Finalizer.access$100(Finalizer.java:32)
		at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:190)
	2014-11-06 10:52:04.761] boot - 99614 ERROR [http-nio-8761-exec-8] --- DiscoveryJerseyProvider: Error creating a serializer.
	java.lang.ClassNotFoundException: com.netflix.eureka.converters.EntityBodyConverter
		at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
		at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
		at java.security.AccessController.doPrivileged(Native Method)
		at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
		at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
		at java.lang.Class.forName0(Native Method)
		at java.lang.Class.forName(Class.java:190)
		at com.netflix.discovery.provider.DiscoveryJerseyProvider.getSerializer(DiscoveryJerseyProvider.java:207)
		at com.netflix.discovery.provider.DiscoveryJerseyProvider.writeTo(DiscoveryJerseyProvider.java:152)
		at com.sun.jersey.spi.container.ContainerResponse.write(ContainerResponse.java:306)
		at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1448)
		at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1360)
		at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1350)
		at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:416)
		at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:538)
		at com.sun.jersey.spi.container.servlet.ServletContainer.doFilter(ServletContainer.java:910)
		at com.sun.jersey.spi.container.servlet.ServletContainer.doFilter(ServletContainer.java:858)
		at com.sun.jersey.spi.container.servlet.ServletContainer.doFilter(ServletContainer.java:812)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
		at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:101)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
		at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:101)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
		at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:748)
		at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:486)
		at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:411)
		at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:338)
		at org.springframework.web.servlet.view.InternalResourceView.renderMergedOutputModel(InternalResourceView.java:209)
		at org.springframework.web.servlet.view.AbstractView.render(AbstractView.java:267)
		at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1221)
		at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1005)
		at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:952)
		at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:870)
		at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:961)
		at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:852)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:620)
		at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:837)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
		at org.springframework.boot.actuate.autoconfigure.EndpointWebMvcAutoConfiguration$ApplicationContextHeaderFilter.doFilterInternal(EndpointWebMvcAutoConfiguration.java:280)
		at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
		at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:77)
		at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
		at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:110)
		at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
		at org.springframework.boot.actuate.autoconfigure.MetricFilterAutoConfiguration$MetricsFilter.doFilterInternal(MetricFilterAutoConfiguration.java:90)
		at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
		at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1070)
		at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1736)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1695)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.lang.Thread.run(Thread.java:744)
	[2014-11-06 10:52:04.764] boot - 99614 ERROR [http-nio-8761-exec-8] --- DiscoveryJerseyProvider: No serializer available for serializable class: class com.netflix.eureka.util.StatusInfo, serialization will fail.

**Comment by spencergibb** [comment]
@wgorder I was able to run your `acme-ui` and `api-gateway` project successfully with `./gradlew :bootRun`

**Comment by wgorder** [comment]
I'll try it again

**Comment by spencergibb** [comment]
@wgorder ping

**Comment by wgorder** [comment]
Sorry @spencergibb  I forgot I had this one to test.  Everything looks good now for me as well.  Guess we can close this.

**Comment by ash1425** [comment]
Sorry to comment on this old bug - I am getting same class-loader issue when trying with "gradle bootRun" but it runs when running "java -jar". I am trying to run simple plain Eureka Server in standalone mode. My source code is at https://github.com/ash1425/EurekaServer. 

stacktrace - 

2015-05-30 21:14:11.231  WARN 632 --- [       Thread-3] c.n.eureka.PeerAwareInstanceRegistry     : The replica size seems to be empty. Check the route 53 DNS Registry
2015-05-30 21:14:11.338  INFO 632 --- [           main] s.b.c.e.t.TomcatEmbeddedServletContainer : Tomcat started on port(s): 8761 (http)
2015-05-30 21:14:11.340  INFO 632 --- [           main] EurekaServer.EurekaServerApplication     : Started EurekaServerApplication in 7.653 seconds (JVM running for 8.03)
2015-05-30 21:14:53.930  INFO 632 --- [nio-8761-exec-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring FrameworkServlet 'dispatcherServlet'
2015-05-30 21:14:53.930  INFO 632 --- [nio-8761-exec-1] o.s.web.servlet.DispatcherServlet        : FrameworkServlet 'dispatcherServlet': initialization started
2015-05-30 21:14:53.942  INFO 632 --- [nio-8761-exec-1] o.s.web.servlet.DispatcherServlet        : FrameworkServlet 'dispatcherServlet': initialization completed in 11 ms
2015-05-30 21:14:54.019 ERROR 632 --- [nio-8761-exec-1] c.n.d.provider.DiscoveryJerseyProvider   : Error creating a serializer.

java.lang.ClassNotFoundException: com.netflix.eureka.converters.EntityBodyConverter
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:195)
	at com.netflix.discovery.provider.DiscoveryJerseyProvider.getSerializer(DiscoveryJerseyProvider.java:207)
	at com.netflix.discovery.provider.DiscoveryJerseyProvider.writeTo(DiscoveryJerseyProvider.java:152)

**Comment by cforce** [comment]
same here with "mvn spring-boot:run" it git the problems as soon as i try to access the Eureka Dashboard

**Comment by dsyer** [comment]
Apparently it works fine for others. What versions of Spring Cloud and Spring Boot did you use? Maybe a sample project would help the diagnose what you are doing differently?

**Comment by securew2** [comment]
I ran into the same issue experimenting with deployment of a eureka war in wildfly. It works fine deploying via mv spring-boot:run, but in wildfly it showed the above error. 

I did some digging around and found this:

https://github.com/Netflix/eureka/commit/539ea4b4f4fa43061f90c836d759ddf7e733ebf8

Unfortunatly for me, simply upgrading to the latest package caused a bunch of other errors

**Comment by securew2** [comment]
I ran into the same issue experimenting with deployment of a eureka war in wildfly. It works fine deploying via mv spring-boot:run, but in wildfly it showed the above error. 

I did some digging around and found this:

https://github.com/Netflix/eureka/commit/539ea4b4f4fa43061f90c836d759ddf7e733ebf8

Unfortunatly for me, simply upgrading to the latest package caused a bunch of other errors

**Comment by wxlund** [comment]
I know this is a close issue but I'm having the same problem.  I'm working within STS with gradle and when I launch as a Spring Boot app I get the same stack trace.  When I ./gradlew assemble and run with java -jar it works fine.  Should I open a new issue or would you consider this the same issue?

**Comment by dsyer** [comment]
Please do open a new issue and attach a link to your code.
