### ISSUE TITLE
Zuul failed to communicate with Eureka Server

### ISSUE THREAD

**Issue by xjiaoyang** [spring-cloud/spring-cloud-netflix#602]
I'm using `spring.cloud.netflix version:1.0.3.RELEASED`, `spring-cloud-starter-pararent:Angel.SR3`,
recently i'v got problems seting up eureka and load balance server(Zuul).
I started Eureka Server on 8761, application.yml like this:
```java
server:
  port: 8761

eureka:
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 10
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
```
Eureka server started with no warnings/errors.

when i started my load balance server,it cannot communicate with Eureka server, console prints like this:
```java

2015-10-16 14:26:17.496  WARN 26995 --- [           main] com.netflix.discovery.DiscoveryClient    : Action: Refresh  => returned status of 401 from http://localhost:8761/eureka/apps/
2015-10-16 14:26:17.504 ERROR 26995 --- [           main] com.netflix.discovery.DiscoveryClient    : Can't get a response from http://localhost:8761/eureka/apps/
Can't contact any eureka nodes - possibly a security group issue?

java.lang.RuntimeException: Bad status: 401
	at com.netflix.discovery.DiscoveryClient.makeRemoteCall(DiscoveryClient.java:1155)
	at com.netflix.discovery.DiscoveryClient.makeRemoteCall(DiscoveryClient.java:1060)
	at com.netflix.discovery.DiscoveryClient.getAndStoreFullRegistry(DiscoveryClient.java:835)
	at com.netflix.discovery.DiscoveryClient.fetchRegistry(DiscoveryClient.java:746)
	at com.netflix.discovery.DiscoveryClient.<init>(DiscoveryClient.java:320)
	at com.netflix.discovery.DiscoveryClient.<init>(DiscoveryClient.java:197)
	at com.netflix.discovery.DiscoveryClient.<init>(DiscoveryClient.java:193)
	at com.netflix.discovery.DiscoveryManager.initComponent(DiscoveryManager.java:84)
	at org.springframework.cloud.netflix.eureka.DiscoveryManagerInitializer.init(DiscoveryManagerInitializer.java:39)
	at org.springframework.cloud.netflix.eureka.EurekaDiscoveryClientConfiguration.start(EurekaDiscoveryClientConfiguration.java:129)
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:173)
	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:51)
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:346)
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:149)
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:112)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:770)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:140)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:483)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:686)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:320)
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:139)
	at io.docsign.cloud.LoadBalanceApplication.main(LoadBalanceApplication.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
```
and periodly prints like this:

```java
2015-10-16 14:30:47.619  INFO 26995 --- [pool-5-thread-1] com.netflix.discovery.DiscoveryClient    : Disable delta property : false
2015-10-16 14:30:47.619  INFO 26995 --- [pool-5-thread-1] com.netflix.discovery.DiscoveryClient    : Single vip registry refresh property : null
2015-10-16 14:30:47.619  INFO 26995 --- [pool-5-thread-1] com.netflix.discovery.DiscoveryClient    : Force full registry fetch : false
2015-10-16 14:30:47.619  INFO 26995 --- [pool-5-thread-1] com.netflix.discovery.DiscoveryClient    : Application is null : false
2015-10-16 14:30:47.619  INFO 26995 --- [pool-5-thread-1] com.netflix.discovery.DiscoveryClient    : Registered Applications size is zero : true
2015-10-16 14:30:47.619  INFO 26995 --- [pool-5-thread-1] com.netflix.discovery.DiscoveryClient    : Application version is -1: true
2015-10-16 14:30:47.624  WARN 26995 --- [pool-5-thread-1] com.netflix.discovery.DiscoveryClient    : Action: Refresh  => returned status of 401 from http://localhost:8761/eureka/apps/
2015-10-16 14:30:47.624  WARN 26995 --- [pool-4-thread-1] com.netflix.discovery.DiscoveryClient    : Action: Renew  => returned status of 401 from http://localhost:8761/eureka/apps/LOAD-BALANCE-SERVICE/WB.local
2015-10-16 14:30:47.625 ERROR 26995 --- [pool-5-thread-1] com.netflix.discovery.DiscoveryClient    : Can't get a response from http://localhost:8761/eureka/apps/
Can't contact any eureka nodes - possibly a security group issue?

java.lang.RuntimeException: Bad status: 401
	at com.netflix.discovery.DiscoveryClient.makeRemoteCall(DiscoveryClient.java:1155)
	at com.netflix.discovery.DiscoveryClient.makeRemoteCall(DiscoveryClient.java:1060)
	at com.netflix.discovery.DiscoveryClient.getAndStoreFullRegistry(DiscoveryClient.java:835)
	at com.netflix.discovery.DiscoveryClient.fetchRegistry(DiscoveryClient.java:746)
	at com.netflix.discovery.DiscoveryClient.access$1400(DiscoveryClient.java:105)
	at com.netflix.discovery.DiscoveryClient$CacheRefreshThread.run(DiscoveryClient.java:1723)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

2015-10-16 14:30:47.625 ERROR 26995 --- [pool-4-thread-1] com.netflix.discovery.DiscoveryClient    : Can't get a response from http://localhost:8761/eureka/apps/LOAD-BALANCE-SERVICE/WB.local
Can't contact any eureka nodes - possibly a security group issue?

java.lang.RuntimeException: Bad status: 401
	at com.netflix.discovery.DiscoveryClient.makeRemoteCall(DiscoveryClient.java:1155)
	at com.netflix.discovery.DiscoveryClient.makeRemoteCall(DiscoveryClient.java:1060)
	at com.netflix.discovery.DiscoveryClient.access$500(DiscoveryClient.java:105)
	at com.netflix.discovery.DiscoveryClient$HeartbeatThread.run(DiscoveryClient.java:1583)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

2015-10-16 14:30:47.625 ERROR 26995 --- [pool-5-thread-1] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_LOAD-BALANCE-SERVICE/WB.local - was unable to refresh its cache! status = Bad status: 401

java.lang.RuntimeException: Bad status: 401
	at com.netflix.discovery.DiscoveryClient.makeRemoteCall(DiscoveryClient.java:1155)
	at com.netflix.discovery.DiscoveryClient.makeRemoteCall(DiscoveryClient.java:1060)
	at com.netflix.discovery.DiscoveryClient.getAndStoreFullRegistry(DiscoveryClient.java:835)
	at com.netflix.discovery.DiscoveryClient.fetchRegistry(DiscoveryClient.java:746)
	at com.netflix.discovery.DiscoveryClient.access$1400(DiscoveryClient.java:105)
	at com.netflix.discovery.DiscoveryClient$CacheRefreshThread.run(DiscoveryClient.java:1723)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

2015-10-16 14:30:47.625 ERROR 26995 --- [pool-4-thread-1] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_LOAD-BALANCE-SERVICE/WB.local - was unable to send heartbeat!

java.lang.RuntimeException: Bad status: 401
	at com.netflix.discovery.DiscoveryClient.makeRemoteCall(DiscoveryClient.java:1155)
	at com.netflix.discovery.DiscoveryClient.makeRemoteCall(DiscoveryClient.java:1060)
	at com.netflix.discovery.DiscoveryClient.access$500(DiscoveryClient.java:105)
	at com.netflix.discovery.DiscoveryClient$HeartbeatThread.run(DiscoveryClient.java:1583)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
i do not know i configured wrong or what.

**Comment by xjiaoyang** [comment]
Here is my load banlance sever application.yml
```java
info:
  component: load-balance-service

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

zuul:
  ignoredServices: "*"
  routes:
    load-balance-service:
      path: /load-balance-service

server:
  port: 8765

eureka:
  password: password
  region: default
  name: cloud-discorver-server-master
  preferSameZone: true
  serviceUrl:
    default: http://localhost:8761/eureka
```

**Comment by xjiaoyang** [comment]
i found a solution, remove this from the parent project pom
```xml
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-security</artifactId>
        </dependency>
```

but there is another problem : HOW TO PROTECT EUREKA SERVER?
usully in my project i use username-password mechanism, any suggestions?

**Comment by Writtscher** [comment]
Usually you do not want to spread authentication state across your microservices but have an authorization server that holds the "user session". Your eureka server is just another microservice in your landscape and asks the authorization server whether the user is authenticated or not. This process is called single sign on. As soon as any of your service communicates with other services (with eureka) it passes an authentication token and the other service  asks the authorization server wether the token is valid or not.

You can find good examples out there. Have a look at https://github.com/spring-cloud-samples/sso to and https://github.com/spring-cloud-samples/authserver. This should give you an idea how to authenticate in your landscape.

**Comment by spencergibb** [comment]
@xjiaoyang you can secure it using spring-security and basic auth. Then in your clients you can do something like:
```
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password@localhost:8761/eureka/
```
