### ISSUE TITLE
Seeing a class not found in eureka server

### ISSUE THREAD

**Issue by EvilJinious1** [spring-cloud/spring-cloud-netflix#614]
Hi

I updated our eureka service instance to 1.3.0M5 and started seeing this exception thrown when a service joins 

(java.lang.NoClassDefFoundError: Could not initialize class com.netflix.eureka.util.AwsAsgUtil)
```
2015-10-23 14:30:33.668 ERROR 18166 --- [nio-8761-exec-8] c.s.j.spi.container.ContainerResponse    : The exception contained within MappableContainerException could not be mapped to a response, re-throwing to the HTTP container
java.lang.NoClassDefFoundError: Could not initialize class com.netflix.eureka.util.AwsAsgUtil
	at com.netflix.eureka.AbstractInstanceRegistry.getOverriddenInstanceStatus(AbstractInstanceRegistry.java:1268) ~[eureka-core-1.2.5.jar:1.2.5]
	at com.netflix.eureka.AbstractInstanceRegistry.register(AbstractInstanceRegistry.java:223) ~[eureka-core-1.2.5.jar:1.2.5]
	at com.netflix.eureka.PeerAwareInstanceRegistryImpl.register(PeerAwareInstanceRegistryImpl.java:389) ~[eureka-core-1.2.5.jar:1.2.5]
	at com.netflix.eureka.PeerAwareInstanceRegistryImpl$$FastClassBySpringCGLIB$$421051c2.invoke(<generated>) ~[spring-core-4.2.2.RELEASE.jar!/:1.2.5]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.2.2.RELEASE.jar!/:4.2.2.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:717) ~[spring-aop-4.2.2.RELEASE.jar!/:4.2.2.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) ~[spring-aop-4.2.2.RELEASE.jar!/:4.2.2.RELEASE]
	at org.springframework.cloud.netflix.eureka.server.EurekaServerInitializerConfiguration$RegistryInstanceProxyInitializer$TrafficOpener.invoke(EurekaServerInitializerConfiguration.java:266) ~[spring-cloud-netflix-eureka-server-1.1.0.BUILD-SNAPSHOT.jar!/:1.1.0.BUILD-SNAPSHOT]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.2.2.RELEASE.jar!/:4.2.2.RELEASE]
	at org.springframework.cloud.netflix.eureka.server.advice.PiggybackMethodInterceptor.invoke(PiggybackMethodInterceptor.java:41) ~[spring-cloud-netflix-eureka-server-1.1.0.BUILD-SNAPSHOT.jar!/:1.1.0.BUILD-SNAPSHOT]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.2.2.RELEASE.jar!/:4.2.2.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:653) ~[spring-aop-4.2.2.RELEASE.jar!/:4.2.2.RELEASE]
	at com.netflix.eureka.PeerAwareInstanceRegistryImpl$$EnhancerBySpringCGLIB$$db1c0127.register(<generated>) ~[spring-core-4.2.2.RELEASE.jar!/:1.2.5]
	at com.netflix.eureka.resources.ApplicationResource.addInstance(ApplicationResource.java:143) ~[eureka-core-1.2.5.jar:1.2.5]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0_25]
	at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60) ~[jersey-server-1.19.jar!/:1.19]
	at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$VoidOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:167) ~[jersey-server-1.19.jar!/:1.19]

```

**Comment by spencergibb** [comment]
1.3.0M5 is a version of spring-boot. Looks like you upgraded to 1.1.0.BUILD-SNAPSHOT. 1.1.0.M2 is also out now. Can you confirm you are still having this problem? If so, please provide a build file or project to replicate.

**Comment by spencergibb** [comment]
Closing for lack of feedback.
