### ISSUE TITLE
NPE at ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:94)

### ISSUE THREAD

**Issue by kemitix** [spring-cloud/spring-cloud-netflix#626]
Using spring-cloud-starter-feign:1.0.3.RELEASE.

Call to feigned method throws NPE in client at ReflectiveFeign.java at line 94.

    return dispatch.get(method).invoke(args);

Debugging shows that the `dispatch` Map has zero entries causing `get(method)` to return null.

    Caused by: java.lang.NullPointerException: null
	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:94)
	at com.sun.proxy.$Proxy52.getXcriDocument(Unknown Source)
	at uk.ac.fife.xcri.writer.XcriWriter.run(XcriWriter.java:61)
	at uk.ac.fife.xcri.writer.XcriWriter.start(XcriWriter.java:84)
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:173)

I'm calling the feigned method from a phase 1 `SmartLifecycle` implementation.

    2015-11-03 13:41:59.792  INFO 11268 --- [           main] o.s.c.support.DefaultLifecycleProcessor  : Starting beans in phase 0
    2015-11-03 13:41:59.824  INFO 11268 --- [           main] o.s.c.support.DefaultLifecycleProcessor  : Starting beans in phase 1
    2015-11-03 13:41:59.842  WARN 11268 --- [           main] s.c.a.AnnotationConfigApplicationContext : Exception encountered during context initialization - cancelling refresh attempt
    org.springframework.context.ApplicationContextException: Failed to start bean 'xcriWriter'; nested exception is java.lang.NullPointerException

Invocation:

    @Autowired
    private XcriClient xcriService;

    final String xcriDocument = xcriService.getXcriDocument();

XcriClient:

    @FeignClient("xcri-service")
    public interface XcriClient extends XcriServiceAPI {}

XcriServiceAPI:

    public interface XcriServiceAPI {
        @RequestMapping(method = RequestMethod.GET, value = "/get")
        String getXcriDocument();
    }

Using the urls listed in my localhost:8761/eureka/apps I can fetch the /get endpoint of my service as expected in my browser.

**Comment by spencergibb** [comment]
Duplicates #599, waiting for a 1.0.4 release.

**Comment by JuliusMischok** [comment]
I'm facing the same issue with 1.0.4.RELEASE, Stacktrace is the same:

    java.lang.NullPointerException: null
	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:94)
	at com.sun.proxy.$Proxy70.hello(Unknown Source)
        ...

`spring-cloud-starter`, `spring-cloud-starter-eureka-server`, `spring-cloud-starter-feign` are included with 1.0.4.RELEASE.

**Comment by spencergibb** [comment]
@JuliusMischok can you open a new issue rather than commenting on a closed duplicate and perhaps provide some way to duplicate it?
