### ISSUE TITLE
zuul.ignoreLocalService fails with exception

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-netflix#652]
http://stackoverflow.com/questions/33782873/zuul-and-consul-integration-issue
```
Caused by: java.lang.IllegalStateException: Unable to locate service in consul agent: edge-server-8456
	at org.springframework.cloud.consul.discovery.ConsulDiscoveryClient.getLocalServiceInstance(ConsulDiscoveryClient.java:67) ~[spring-cloud-consul-discovery-1.0.0.M4.jar:1.0.0.M4]
	at org.springframework.cloud.netflix.zuul.filters.ProxyRouteLocator.<init>(ProxyRouteLocator.java:70) ~[spring-cloud-netflix-core-1.1.0.M3.jar:1.1.0.M3]
	at org.springframework.cloud.netflix.zuul.ZuulProxyConfiguration.routeLocator(ZuulProxyConfiguration.java:77) ~[spring-cloud-netflix-core-1.1.0.M3.jar:1.1.0.M3]
```

https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/zuul/filters/ProxyRouteLocator.java#L69

Setting `zuul.ignoreLocalService: false` will work around it.

**Comment by spencergibb** [comment]
I'm actually thinking that spring-cloud-consul shouldn't fail in `getLocalServiceInstance` if it isn't registered yet.

**Comment by spencergibb** [comment]
Closing in favor of https://github.com/spring-cloud/spring-cloud-consul/issues/112
