### ISSUE TITLE
@ConditionalOnMissingBean annotations must specify at least one bean (type, name or annotation)

### ISSUE THREAD

**Issue by LutzStrobel** [spring-cloud/spring-cloud-netflix#654]
We want to upgrade to spring-cloud:Angel:SR4 and get the following error starting a micro service:

```
Exception in thread "main" java.lang.IllegalStateException: Error processing condition on org.springframework.cloud.netflix.feign.ribbon.FeignRibbonClientAutoConfiguration.feignRibbonClient
...
Caused by: java.lang.IllegalArgumentException: @ConditionalOnMissingBean annotations must specify at least one bean (type, name or annotation)
	at org.springframework.util.Assert.isTrue(Assert.java:65)
	at org.springframework.boot.autoconfigure.condition.OnBeanCondition$BeanSearchSpec.<init>(OnBeanCondition.java:232)
	at org.springframework.boot.autoconfigure.condition.OnBeanCondition.getMatchOutcome(OnBeanCondition.java:93)
```

Angel.SR4 ships with spring-boot:1.2.6.RELEASE and the OnBeanCondition code validates if the current annotation has a bean specified.
What can we do to avoid this behavior?

Thanx Lutz

**Comment by spencergibb** [comment]
Can you provide a sample so I can reproduce it?

**Comment by LutzStrobel** [comment]
The spring boot app consists of a simple application class which consumes a remote micro service. Hope it helps analyzing.

```
@Configuration
@ComponentScan
@EnableAutoConfiguration
@EnableEurekaClient
@RestController
public class App {

    @Autowired
    KnowledgeManagementService knowledgeManagementService;



    @RequestMapping("/")
    public String home() {
        try {
            law.smart.micro.knowledge.management.model.Set single = knowledgeManagementService.getById("135d34a7-df8c-4036-bff4-f29c5527169f");
        } catch (Exception e) {
            e.printStackTrace();
        }
        return "Hello world";
    }

    public static void main(String[] args) {
        new SpringApplicationBuilder(App.class).web(true).run(args);
    }

}
```

This is a minimal pom to reproduce the problem. I suppose that it results from the feign dependencies. But wiithout those deps I get exception claiming that the feign decoder could not be found.

```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>de.lstrobel.ms</groupId>
  <artifactId>consumer</artifactId>
  <version>1.0-SNAPSHOT</version>
  <packaging>jar</packaging>

  <name>consumer</name>
  <url>http://maven.apache.org</url>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>

  <dependencyManagement>
    <dependencies>

      <dependency>
        <groupId>org.springframework.cloud</groupId>
        <artifactId>spring-cloud-starter-parent</artifactId>
        <version>Angel.SR4</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>

    </dependencies>
  </dependencyManagement>

  <dependencies>
    <dependency>
      <groupId>law.smart.micro</groupId>
      <artifactId>knowledge-management-api</artifactId>
      <version>4.1.0</version>
    </dependency>

    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter</artifactId>
    </dependency>

    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-starter</artifactId>
    </dependency>

    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-starter-eureka</artifactId>
    </dependency>

    <dependency>
      <groupId>com.netflix.feign</groupId>
      <artifactId>feign-core</artifactId>
    </dependency>

    <dependency>
      <groupId>com.netflix.feign</groupId>
      <artifactId>feign-slf4j</artifactId>
    </dependency>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>3.8.1</version>
      <scope>test</scope>
    </dependency>

  </dependencies>
</project>
```

**Comment by spencergibb** [comment]
Why do you have?
```
    <dependency>
      <groupId>com.netflix.feign</groupId>
      <artifactId>feign-core</artifactId>
    </dependency>

    <dependency>
      <groupId>com.netflix.feign</groupId>
      <artifactId>feign-slf4j</artifactId>
    </dependency>
```

**Comment by spencergibb** [comment]
If I remove those the error goes away.

**Comment by LutzStrobel** [comment]
As I noted above, the dependencies are required because I get exceptions like "Caused by: java.lang.ClassNotFoundException: feign.Logger" and others without the deps at startup time.

I have simplyfied the consumer project to exclude any local dependencies.

```
  <dependencyManagement>
    <dependencies>

      <dependency>
        <groupId>org.springframework.cloud</groupId>
        <artifactId>spring-cloud-starter-parent</artifactId>
        <version>Angel.SR4</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>

    </dependencies>
  </dependencyManagement>

  <dependencies>
    <dependency>
      <groupId>de.lstrobel.ms</groupId>
      <artifactId>ms-producer-api</artifactId>
      <version>1.0-SNAPSHOT</version>
    </dependency>

    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter</artifactId>
    </dependency>

    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-starter-eureka</artifactId>
    </dependency>

    <!--<dependency>-->
      <!--<groupId>com.netflix.feign</groupId>-->
      <!--<artifactId>feign-core</artifactId>-->
    <!--</dependency>-->

    <!--<dependency>-->
      <!--<groupId>com.netflix.feign</groupId>-->
      <!--<artifactId>feign-slf4j</artifactId>-->
    <!--</dependency>-->

  </dependencies>

```

The App class is now as follows:

```
@Configuration
@ComponentScan
@EnableAutoConfiguration
@EnableEurekaClient
@EnableFeignClients(basePackages = {"de.lstrobel.ms"})
@RestController
public class App {

    @Autowired
    Producer producer;


    @RequestMapping("/")
    public String home() {
         return "Hello world";
    }

    public static void main(String[] args) {
        new SpringApplicationBuilder(App.class).web(true).run(args);
    }

}

```

The Producer is the remote interface to be accessed via a feign ribbon client from the maven dependency "ms-producer-api".

```
@FeignClient("ms-producer")
public interface Producer {
    @RequestMapping(method = RequestMethod.GET, value = "/hello/{name}")
    String hello(@PathVariable(value = "name") String name);
}
```

If I start the consumer app without the com.netflix.feign dependencies I get exceptions like:
```
Caused by: java.lang.ClassNotFoundException: feign.Logger
```
 and other (decoder).
If I start the consumer app with the com.netflix.feign dependencies I get the exceptions like
```
Caused by: java.lang.IllegalArgumentException: @ConditionalOnMissingBean annotations must specify at least one bean (type, name or annotation)
```

**Comment by spencergibb** [comment]
to use feign you need to include `spring-cloud-starter-feign`
