### ISSUE TITLE
NPE in RibbonApacheHttpResponse.getInputStream when issuing a PATCH request to spring data rest resource

### ISSUE THREAD

**Issue by snussbaumer** [spring-cloud/spring-cloud-netflix#687]
I need to be able to issue PATCH requests through a ZuulProxy and was glad it is possible since https://github.com/spring-cloud/spring-cloud-netflix/issues/412. Unfortunately I had an NPE when trying the new classes.

Setup : 
 - a spring data rest microservice exposing a @RepositoryRestResource, for example `/users`
 - an @EnableZuulProxy microservice with the following bean : 
```java
@Bean
public HttpClientRibbonCommandFactory ribbonCommandFactory(SpringClientFactory clientFactory) {
    return new HttpClientRibbonCommandFactory(clientFactory);
}
```

If I issue a PATCH request directly to the data microservice everything works fine. If I issue the same PATCH request through the Zuul Proxy I get the NullPointerException : 

```
java.lang.NullPointerException: null
run_1 | 	at org.springframework.cloud.netflix.ribbon.apache.RibbonApacheHttpResponse.getInputStream(RibbonApacheHttpResponse.java:126) ~[spring-cloud-netflix-core-1.1.0.BUILD-SNAPSHOT.jar:1.1.0.BUILD-SNAPSHOT]
run_1 | 	at org.springframework.cloud.netflix.ribbon.RibbonHttpResponse.getBody(RibbonHttpResponse.java:49) ~[spring-cloud-netflix-core-1.1.0.BUILD-SNAPSHOT.jar:1.1.0.BUILD-SNAPSHOT]
run_1 | 	at org.springframework.cloud.netflix.zuul.filters.route.RibbonRoutingFilter.setResponse(RibbonRoutingFilter.java:164) ~[spring-cloud-netflix-core-1.1.0.BUILD-SNAPSHOT.jar:1.1.0.BUILD-SNAPSHOT]
run_1 | 	at org.springframework.cloud.netflix.zuul.filters.route.RibbonRoutingFilter.run(RibbonRoutingFilter.java:77) ~[spring-cloud-netflix-core-1.1.0.BUILD-SNAPSHOT.jar:1.1.0.BUILD-SNAPSHOT]
```

There is a workaround with the following code in the data microservice : 

```java
public class RestConfiguration extends RepositoryRestMvcConfiguration {
    @Override
    protected void configureRepositoryRestConfiguration(RepositoryRestConfiguration config) {
        config.setReturnBodyOnUpdate(true);
    }
}
```

The default value for `returnBodyOnUpdate` is `false`, and when issuing a patch in this configuration there is no body that is returned, only an HTTP 204 No Content. Setting the value to true returns the modified resource.

I was expecting the same problem with a POST (which doesn't return a body by default either), but it's not the case.

**Comment by snussbaumer** [comment]
I've just checked the latest build and can see no NPE on my setup anymore :smiley: 

Many thanks !
