### ISSUE TITLE
Spring Boot 1.3 @FeignClient Error with @RequestBody

### ISSUE THREAD

**Issue by mike-boddin** [spring-cloud/spring-cloud-netflix#689]
I upgraded a working project from spring boot 1.2.x to 1.3.
Now I get this error on startup:
```
java.lang.NullPointerException: null
	at org.springframework.cloud.netflix.feign.support.SpringMvcContract.processAnnotationsOnParameter(SpringMvcContract.java:160)
	at feign.Contract$BaseContract.parseAndValidateMetadata(Contract.java:104)
	at org.springframework.cloud.netflix.feign.support.SpringMvcContract.parseAndValidateMetadata(SpringMvcContract.java:71)
	at feign.Contract$BaseContract.parseAndValidatateMetadata(Contract.java:61)
	at feign.hystrix.HystrixDelegatingContract.parseAndValidatateMetadata(HystrixDelegatingContract.java:24)
	at feign.ReflectiveFeign$ParseHandlersByName.apply(ReflectiveFeign.java:137)
	at feign.ReflectiveFeign.newInstance(ReflectiveFeign.java:55)
	at feign.Feign$Builder.target(Feign.java:179)
	at feign.Feign$Builder.target(Feign.java:175)
	at org.springframework.cloud.netflix.feign.FeignClientFactoryBean.loadBalance(FeignClientFactoryBean.java:126)
	at org.springframework.cloud.netflix.feign.FeignClientFactoryBean.getObject(FeignClientFactoryBean.java:143)
	at ...
```

The problematic part of my application is the following FeignClient:
```java
@FeignClient("feign.sample")
@RequestMapping("/feign")
public interface SampleFeignClient
{
    @RequestMapping(value = "/test", method = RequestMethod.POST)
    public String testAction(@RequestBody String string);

}
```

When I remove the ``@RequestBody String string`` part everything works fine.
Is there anything wrong with the processing of the ``@RequestBody`` annotation?

extract from the dependency-tree:
``|  +- org.springframework.cloud:spring-cloud-netflix-core:jar:1.1.0.M3:compile``

**Comment by mike-boddin** [comment]
@tknowak maybe this is related to your problem here: https://github.com/spring-cloud/spring-cloud-netflix/issues/672#issuecomment-161218335

**Comment by Koizumi85** [comment]
I had this Exception too yesterday and also solved it with removing the @RequestBody.
I looked at the code where the Exception is thrown and how it was in 1.2.
It seems in 1.2 the @RequestBody was simply ignored because there wasn't an if-clause matching it. In 1.3 the code takes an "AnnotationProcessor" from an Map and calls a function on it. And there isn't a processor for @RequestBody in the map.
I think a null check on the annotationProcessor in this method would ensure the same behaviour as in 1.2, or?

**Comment by tknowak** [comment]
@mike-boddin yep, removing @RequestBody helps also in my problem in #672 
Thanks!

**Comment by dsyer** [comment]
I added a null check. So you *can* actually use a POST with `@RequestBody` right (the test doesn't cover that at an integration test level)?
