### ISSUE TITLE
eureka+feign:local feign client with eureka gradle:bootRun always read timeout  from service

### ISSUE THREAD

**Issue by Dreampie** [spring-cloud/spring-cloud-netflix#714]
My service DiscoveryClient  read timeout from service.user-api-provider read from user-service-provider  with feign

service with eureka-server https://github.com/Dreampie/cloud-service 
feign client with eureka-server    https://github.com/Dreampie/cloud-api
eureka-server and config-server  https://github.com/Dreampie/cloud-server

```
//eureka service in 192.168.60.41
USER-API-PROVIDER	n/a (2)	(2)	UP (2) - 127.0.0.1:user-api-provider:10001 , 172.17.0.8:user-api-provider:10001
USER-SERVICE-PROVIDER	n/a (1)	(1)	UP (1) - 172.17.0.7:user-service-provider:9001

//local client 127.0.0.1
DiscoveryClient_USER-API-PROVIDER/127.0.0.1:user-api-provider:10001 - registration status: 204
```
172.17.0.8:user-api-provider:10001  call back was ok,use docker run start it.
127.0.0.1:user-api-provider:10001 read time out,use gradle bootRun start it.

```
2015-12-14 10:01:56.866  INFO 4686 --- [pool-6-thread-1] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_USER-API-PROVIDER/127.0.0.1:user-api-provider:10001 - Re-registering apps/USER-API-PROVIDER
2015-12-14 10:01:56.866  INFO 4686 --- [pool-6-thread-1] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_USER-API-PROVIDER/127.0.0.1:user-api-provider:10001: registering service...
2015-12-14 10:01:57.216  INFO 4686 --- [pool-6-thread-1] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_USER-API-PROVIDER/127.0.0.1:user-api-provider:10001 - registration status: 204
2015-12-14 10:02:26.836  INFO 4686 --- [scoveryClient-2] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_USER-API-PROVIDER/127.0.0.1:user-api-provider:10001 - retransmit instance info with status UP
2015-12-14 10:02:26.836  INFO 4686 --- [scoveryClient-2] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_USER-API-PROVIDER/127.0.0.1:user-api-provider:10001: registering service...
2015-12-14 10:02:26.905  INFO 4686 --- [scoveryClient-2] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_USER-API-PROVIDER/127.0.0.1:user-api-provider:10001 - registration status: 204
2015-12-14 10:02:27.303  INFO 4686 --- [pool-6-thread-1] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_USER-API-PROVIDER/127.0.0.1:user-api-provider:10001 - Re-registering apps/USER-API-PROVIDER
2015-12-14 10:02:27.303  INFO 4686 --- [pool-6-thread-1] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_USER-API-PROVIDER/127.0.0.1:user-api-provider:10001: registering service...
2015-12-14 10:02:27.326  INFO 4686 --- [pool-6-thread-1] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_USER-API-PROVIDER/127.0.0.1:user-api-provider:10001 - registration status: 204
2015-12-14 10:13:35.504  INFO 4686 --- [io-10001-exec-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring FrameworkServlet 'dispatcherServlet'
2015-12-14 10:13:35.504  INFO 4686 --- [io-10001-exec-1] o.s.web.servlet.DispatcherServlet        : FrameworkServlet 'dispatcherServlet': initialization started
2015-12-14 10:13:35.525  INFO 4686 --- [io-10001-exec-1] o.s.web.servlet.DispatcherServlet        : FrameworkServlet 'dispatcherServlet': initialization completed in 21 ms
2015-12-14 10:13:35.571  INFO 4686 --- [io-10001-exec-1] s.c.a.AnnotationConfigApplicationContext : Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@70aeb8dd: startup date [Mon Dec 14 10:13:35 CST 2015]; parent: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@2a2bb0eb
2015-12-14 10:13:35.607  INFO 4686 --- [io-10001-exec-1] f.a.AutowiredAnnotationBeanPostProcessor : JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
2015-12-14 10:13:35.805  INFO 4686 --- [io-10001-exec-1] c.netflix.config.ChainedDynamicProperty  : Flipping property: user-service-provider.ribbon.ActiveConnectionsLimit to use NEXT property: niws.loadbalancer.availabilityFilteringRule.activeConnectionsLimit = 2147483647
2015-12-14 10:13:35.930  INFO 4686 --- [io-10001-exec-1] c.netflix.loadbalancer.BaseLoadBalancer  : Client:user-service-provider instantiated a LoadBalancer:DynamicServerListLoadBalancer:{NFLoadBalancer:name=user-service-provider,current list of Servers=[],Load balancer stats=Zone stats: {},Server stats: []}ServerList:null
2015-12-14 10:13:35.981  INFO 4686 --- [io-10001-exec-1] c.netflix.config.ChainedDynamicProperty  : Flipping property: user-service-provider.ribbon.ActiveConnectionsLimit to use NEXT property: niws.loadbalancer.availabilityFilteringRule.activeConnectionsLimit = 2147483647
2015-12-14 10:13:35.985  INFO 4686 --- [io-10001-exec-1] c.n.l.DynamicServerListLoadBalancer      : DynamicServerListLoadBalancer for client user-service-provider initialized: DynamicServerListLoadBalancer:{NFLoadBalancer:name=user-service-provider,current list of Servers=[user-service-provider:9001],Load balancer stats=Zone stats: {defaultzone=[Zone:defaultzone;	Instance count:1;	Active connections count: 0;	Circuit breaker tripped count: 0;	Active connections per server: 0.0;]
},Server stats: [[Server:user-service-provider:9001;	Zone:defaultZone;	Total Requests:0;	Successive connection failure:0;	Total blackout seconds:0;	Last connection made:Thu Jan 01 08:00:00 CST 1970;	First connection made: Thu Jan 01 08:00:00 CST 1970;	Active Connections:0;	total failure count in last (1000) msecs:0;	average resp time:0.0;	90 percentile resp time:0.0;	95 percentile resp time:0.0;	min resp time:0.0;	max resp time:0.0;	stddev resp time:0.0]
]}ServerList:org.springframework.cloud.netflix.ribbon.eureka.DomainExtractingServerList@32bcf800
2015-12-14 10:13:36.178  INFO 4686 --- [io-10001-exec-1] com.netflix.http4.ConnectionPoolCleaner  : Initializing ConnectionPoolCleaner for NFHttpClient:user-service-provider
2015-12-14 10:13:36.339  INFO 4686 --- [io-10001-exec-1] com.netflix.http4.ConnectionPoolCleaner  : Initializing ConnectionPoolCleaner for NFHttpClient:user-service-provider
2015-12-14 10:13:36.940  INFO 4686 --- [pool-9-thread-1] c.netflix.config.ChainedDynamicProperty  : Flipping property: user-service-provider.ribbon.ActiveConnectionsLimit to use NEXT property: niws.loadbalancer.availabilityFilteringRule.activeConnectionsLimit = 2147483647
2015-12-14 10:14:27.883 ERROR 4686 --- [io-10001-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is feign.RetryableException: connect timed out executing GET http://user-service-provider/users/566a44b6e4b06feec17ff9f9] with root cause

java.net.SocketTimeoutException: connect timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:345)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
	at sun.net.www.http.HttpClient.New(HttpClient.java:308)
	at sun.net.www.http.HttpClient.New(HttpClient.java:326)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1168)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1104)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:998)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:932)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1512)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at feign.Client$Default.convertResponse(Client.java:143)
	at feign.Client$Default.execute(Client.java:70)
	at feign.ribbon.LBClient.execute(LBClient.java:69)
	at feign.ribbon.LBClient.execute(LBClient.java:38)
	at com.netflix.client.AbstractLoadBalancerAwareClient$1.call(AbstractLoadBalancerAwareClient.java:109)
	at com.netflix.loadbalancer.reactive.LoadBalancerCommand$3$1.call(LoadBalancerCommand.java:303)
	at com.netflix.loadbalancer.reactive.LoadBalancerCommand$3$1.call(LoadBalancerCommand.java:287)
	at rx.internal.operators.OperatorMap$1.onNext(OperatorMap.java:54)
	at rx.internal.util.ScalarSynchronousObservable$1.call(ScalarSynchronousObservable.java:41)
	at rx.internal.util.ScalarSynchronousObservable$1.call(ScalarSynchronousObservable.java:30)
	at rx.Observable$2.call(Observable.java:173)
	at rx.Observable$2.call(Observable.java:166)
	at rx.Observable$2.call(Observable.java:173)
	at rx.Observable$2.call(Observable.java:166)
	at rx.Observable.unsafeSubscribe(Observable.java:8591)
	at rx.internal.operators.OperatorConcat$ConcatSubscriber.subscribeNext(OperatorConcat.java:163)
	at rx.internal.operators.OperatorConcat$ConcatSubscriber.onNext(OperatorConcat.java:128)
	at rx.internal.operators.OperatorConcat$ConcatSubscriber.onNext(OperatorConcat.java:65)
	at rx.internal.operators.OperatorMap$1.onNext(OperatorMap.java:54)
	at com.netflix.loadbalancer.reactive.LoadBalancerCommand$1.call(LoadBalancerCommand.java:185)
	at com.netflix.loadbalancer.reactive.LoadBalancerCommand$1.call(LoadBalancerCommand.java:180)
	at rx.Observable$2.call(Observable.java:173)
	at rx.Observable$2.call(Observable.java:166)
	at rx.Observable$2.call(Observable.java:173)
	at rx.Observable$2.call(Observable.java:166)
	at rx.Observable$2.call(Observable.java:173)
	at rx.Observable$2.call(Observable.java:166)
	at rx.Observable$2.call(Observable.java:173)
	at rx.Observable$2.call(Observable.java:166)
	at rx.Observable.subscribe(Observable.java:8680)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:452)
	at rx.observables.BlockingObservable.single(BlockingObservable.java:348)
	at com.netflix.client.AbstractLoadBalancerAwareClient.executeWithLoadBalancer(AbstractLoadBalancerAwareClient.java:102)
	at feign.ribbon.RibbonClient.execute(RibbonClient.java:69)
	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:92)
	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:71)
	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:94)
	at com.sun.proxy.$Proxy74.findById(Unknown Source)
	at cn.dreampie.api.user.controller.UserController.findById(UserController.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:137)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:776)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:705)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:966)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:857)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:618)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:842)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:725)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.springframework.boot.actuate.autoconfigure.EndpointWebMvcAutoConfiguration$ApplicationContextHeaderFilter.doFilterInternal(EndpointWebMvcAutoConfiguration.java:291)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:77)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:102)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:85)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.springframework.boot.actuate.autoconfigure.MetricFilterAutoConfiguration$MetricsFilter.doFilterInternal(MetricFilterAutoConfiguration.java:90)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:516)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1086)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:659)
	at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:223)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1558)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1515)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by spencergibb** [comment]
Does this work when running an executable jar or running the `main` from an IDE?

**Comment by spencergibb** [comment]
Closing for lack of feedback.
