### ISSUE TITLE
Occasional 500 errors： c.netflix.eureka.cluster.PeerEurekaNode  : PeerEurekaNode

### ISSUE THREAD

**Issue by Dreampie** [spring-cloud/spring-cloud-netflix#729]
```
2015-12-17 04:01:03.846 ERROR 1 --- [artbeat-process] c.netflix.eureka.cluster.PeerEurekaNode  : PeerEurekaNode: http://user:eureka@192.168.60.41:8761/eureka/apps/: USER-SERVICE-PROVIDER/172.17.0.7:user-service-provider:9001:Heartbeat

com.sun.jersey.api.client.ClientHandlerException: java.net.SocketTimeoutException: Read timed out
	at com.sun.jersey.client.apache4.ApacheHttpClient4Handler.handle(ApacheHttpClient4Handler.java:184)
	at com.netflix.discovery.EurekaIdentityHeaderFilter.handle(EurekaIdentityHeaderFilter.java:28)
	at com.sun.jersey.api.client.Client.handle(Client.java:648)
	at com.sun.jersey.api.client.WebResource.handle(WebResource.java:680)
	at com.sun.jersey.api.client.WebResource.access$200(WebResource.java:74)
	at com.sun.jersey.api.client.WebResource$Builder.put(WebResource.java:527)
	at com.netflix.eureka.cluster.PeerEurekaNode.sendHeartBeat(PeerEurekaNode.java:510)
	at com.netflix.eureka.cluster.PeerEurekaNode.access$400(PeerEurekaNode.java:72)
	at com.netflix.eureka.cluster.PeerEurekaNode$3.execute(PeerEurekaNode.java:275)
	at com.netflix.eureka.cluster.PeerEurekaNode$6.executeSingle(PeerEurekaNode.java:992)
	at com.netflix.eureka.cluster.PeerEurekaNode$6.process(PeerEurekaNode.java:844)
	at com.netflix.logging.messaging.MessageBatcher$ProcessMessages.run(MessageBatcher.java:410)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:170)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at org.apache.http.impl.io.AbstractSessionInputBuffer.fillBuffer(AbstractSessionInputBuffer.java:160)
	at org.apache.http.impl.io.SocketInputBuffer.fillBuffer(SocketInputBuffer.java:84)
	at org.apache.http.impl.io.AbstractSessionInputBuffer.readLine(AbstractSessionInputBuffer.java:273)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:140)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:260)
	at org.apache.http.impl.AbstractHttpClientConnection.receiveResponseHeader(AbstractHttpClientConnection.java:283)
	at org.apache.http.impl.conn.DefaultClientConnection.receiveResponseHeader(DefaultClientConnection.java:251)
	at org.apache.http.impl.conn.AbstractClientConnAdapter.receiveResponseHeader(AbstractClientConnAdapter.java:223)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:271)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:123)
	at org.apache.http.impl.client.DefaultRequestDirector.tryExecute(DefaultRequestDirector.java:685)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:487)
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:863)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:115)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
	at com.sun.jersey.client.apache4.ApacheHttpClient4Handler.handle(ApacheHttpClient4Handler.java:170)
	... 14 common frames omitted
```

**Comment by spencergibb** [comment]
Have you setup eureka for peering?

**Comment by spencergibb** [comment]
Closing for lack of feedback.

**Comment by andysworkshop** [comment]
In `Brixton.M5` this bug was caused by the following property:

    eureka.client.eurekaConnectionIdleTimeoutSeconds = 30

The problem was that `com.netflix.discovery.DiscoveryClient` was using a `EurekaJerseyClientBuilder` to build the client [without converting seconds to milliseconds](https://github.com/Netflix/eureka/blob/v1.3.6/eureka-client/src/main/java/com/netflix/discovery/DiscoveryClient.java#L434) with the result that the connection would be almost instantly timed out, something that was very likely to happen during all the process stress that happens during startup.

The `DiscoveryClient` class looks to have been refactored since then. Can anyone confirm that this bug was fixed in the refacforing and whether it's fixed in `Brixton.RC1` ? @spencergibb I guess...

**Comment by spencergibb** [comment]
The netflix code has moved around, but it's doing the same thing as before. Have you submitted an issue to netflix?

**Comment by andysworkshop** [comment]
Not yet. It's been bothering me for a while but I only had time to track it down this afternoon. I'll upgrade one of our services to Brixton.RC1 tomorrow and see if it's still there.

**Comment by spencergibb** [comment]
My guess is that is. The workaround is the put milli's there.

**Comment by andysworkshop** [comment]
OK, ignore everything I said. There was no bug in any version of the Netflix code. What threw me was that their method parameter is named `delayMs` but it's not passed as millis, it's seconds and they then use `delayMs` later with a qualifier of `TimeUnit.SECONDS` which I missed. Confusing, but correct. My search for those strange occasional read timeouts goes on.

**Comment by sellers** [comment]
@andysworkshop have you found any interesting tidbits regarding a timeout with the heartbeat?

**Comment by vseguin** [comment]
@sellers @andysworkshop From what i read in the code, it seems that in the method `scheduleServerEndpointTask`, it creates a `JerseyEurekaHttpClientFactory` and does the same erroneous conversion:

> 

        JerseyEurekaHttpClientFactoryBuilder clientBuilder = newBuilder()
                .withAdditionalFilters(additionalFilters)
                .withMyInstanceInfo(myInstanceInfo)
                .withUserAgent("Java-EurekaClient")
                .withClientAccept(EurekaAccept.fromString(clientConfig.getClientDataAccept()))
                .withAllowRedirect(clientConfig.allowRedirects())
                .withConnectionTimeout(clientConfig.getEurekaServerConnectTimeoutSeconds() * 1000)
                .withReadTimeout(clientConfig.getEurekaServerReadTimeoutSeconds() * 1000)
                .withMaxConnectionsPerHost(clientConfig.getEurekaServerTotalConnectionsPerHost())
                .withMaxTotalConnections(clientConfig.getEurekaServerTotalConnections())
                .withConnectionIdleTimeout(clientConfig.getEurekaConnectionIdleTimeoutSeconds())
                .withEncoder(clientConfig.getEncoderName())
                .withDecoder(clientConfig.getDecoderName(), clientConfig.getClientDataAccept())
                .withClientIdentity(clientIdentity);
