### ISSUE TITLE
The same class name of two @FeignClient in different packages，can't @Autowired

### ISSUE THREAD

**Issue by Dreampie** [spring-cloud/spring-cloud-netflix#790]
```java
//package1
@FeignClient("notice-service-provider")
public interface TypeService {
}

//package2
@FeignClient("log-service-provider")
public interface TypeService {
}
```

if use `@Autowired` TypeService typeService;//anyone always got error
```java
2016-01-26 10:50:32.617  INFO 23938 --- [           main] o.s.b.f.s.DefaultListableBeanFactory     : Overriding bean definition for bean 'typeService' with a different definition: replacing [Generic bean: class [org.springframework.cloud.netflix.feign.FeignClientFactoryBean]; scope=; abstract=false; lazyInit=false; autowireMode=2; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null] with [Generic bean: class [org.springframework.cloud.netflix.feign.FeignClientFactoryBean]; scope=; abstract=false; lazyInit=false; autowireMode=2; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null]
```

```java
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [package1.TypeService] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoSuchBeanDefinitionException(DefaultListableBeanFactory.java:1373) ~[spring-beans-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1119) ~[spring-beans-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1014) ~[spring-beans-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:545) ~[spring-beans-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	... 53 common frames omitted
```
![image](https://cloud.githubusercontent.com/assets/3667080/12571517/02c8b912-c41d-11e5-8090-089b09380c19.png)

**Comment by Dreampie** [comment]
1.1.0.M4 will contains this?

**Comment by dsyer** [comment]
1.1.0.M4 is already out. This change is in snapshots.

**Comment by Dreampie** [comment]
thanks
