### ISSUE TITLE
Exception writing metrics to atlas

### ISSUE THREAD

**Issue by andysworkshop** [spring-cloud/spring-cloud-netflix#798]
I'm using zuul and some microservices configured to write metrics to atlas. I'm using Brixton M4. Both zuul and the microservices throw an exception that appears to repeat infinitely when processing the response from atlas. My configuration is pretty vanilla as per the available docs with no custom code written by myself (only automatic metrics are being submitted).

Here's the exception and a little previous debug logging context. Any/all configuration and more logging available if you need it, please ask.

    2016-01-28 10:35:30.224 DEBUG 5529 --- [task-scheduler-4] org.apache.http.wire                     :  << "HTTP/1.1 202 Accepted[\r][\n]"
    2016-01-28 10:35:30.224 DEBUG 5529 --- [task-scheduler-4] org.apache.http.wire                     :  << "Server: spray-can/1.3.2[\r][\n]"
    2016-01-28 10:35:30.224 DEBUG 5529 --- [task-scheduler-4] org.apache.http.wire                     :  << "Date: Thu, 28 Jan 2016 10:35:30 GMT[\r][\n]"
    2016-01-28 10:35:30.224 DEBUG 5529 --- [task-scheduler-4] org.apache.http.wire                     :  << "Content-Type: text/plain; charset=UTF-8[\r][\n]"
    2016-01-28 10:35:30.224 DEBUG 5529 --- [task-scheduler-4] org.apache.http.wire                     :  << "Content-Length: 1284[\r][\n]"
    2016-01-28 10:35:30.225 DEBUG 5529 --- [task-scheduler-4] org.apache.http.wire                     :  << "[\r][\n]"
    2016-01-28 10:35:30.225 DEBUG 5529 --- [task-scheduler-4] o.a.h.impl.conn.DefaultClientConnection  : Receiving response: HTTP/1.1 202 Accepted
    2016-01-28 10:35:30.225 DEBUG 5529 --- [task-scheduler-4] org.apache.http.headers                  : << HTTP/1.1 202 Accepted
    2016-01-28 10:35:30.225 DEBUG 5529 --- [task-scheduler-4] org.apache.http.headers                  : << Server: spray-can/1.3.2
    2016-01-28 10:35:30.225 DEBUG 5529 --- [task-scheduler-4] org.apache.http.headers                  : << Date: Thu, 28 Jan 2016 10:35:30 GMT
    2016-01-28 10:35:30.225 DEBUG 5529 --- [task-scheduler-4] org.apache.http.headers                  : << Content-Type: text/plain; charset=UTF-8
    2016-01-28 10:35:30.225 DEBUG 5529 --- [task-scheduler-4] org.apache.http.headers                  : << Content-Length: 1284
    2016-01-28 10:35:30.225 DEBUG 5529 --- [task-scheduler-4] com.netflix.http4.NFHttpClient           : Connection can be kept alive indefinitely
    2016-01-28 10:35:30.225 DEBUG 5529 --- [task-scheduler-4] org.apache.http.wire                     :  << "{"type":"partial","message":["value too long: name = [hystrix.HystrixCommand.RibbonCommand.myservice1.propertyValue_circuitBreakerErrorThresholdPercentage] (100 > 80)","value too long: name = [hystrix.HystrixCommand.RibbonCommand.myservice1.propertyValue_metricsRollingStatisticalWindowInMilliseconds] (107 > 80)","value too long: name = [hystrix.HystrixCommand.RibbonCommand.myservice1.propertyValue_executionIsolationThreadTimeoutInMilliseconds] (107 > 80)","value too long: name = [hystrix.HystrixCommand.RibbonCommand.myservice1.propertyValue_fallbackIsolationSemaphoreMaxConcurrentRequests] (109 > 80)","value too long: name = [hystrix.HystrixCommand.RibbonCommand.myservice1.propertyValue_circuitBreakerSleepWindowInMilliseconds] (101 > 80)","value too long: name = [hystrix.HystrixCommand.RibbonCommand.myservice1.propertyValue_executionIsolationSemaphoreMaxConcurrentRequests] (110 > 80)","value too long: name = [hystrix.HystrixCommand.RibbonCommand.myservice1.propertyValue_executionTimeoutInMilliseconds] (92 > 80)","value too long: name = [hystrix.HystrixCommand.RibbonCommand.myservice1.propertyValue_circuitBreakerRequestVolumeThreshold] (98 > 80)","value too long: name = [hystrix.HystrixCommand.RibbonCommand.myservice1.rollingMaxConcurrentExecutionCount] (82 > 80)"]}"
    2016-01-28 10:35:30.225 DEBUG 5529 --- [task-scheduler-4] o.s.web.client.RestTemplate              : POST request for "http://atlas/api/v1/publish" resulted in 202 (ACCEPTED)
    2016-01-28 10:35:30.225 DEBUG 5529 --- [task-scheduler-4] c.n.http4.MonitoredConnectionManager     : Released connection is reusable.
    2016-01-28 10:35:30.225 DEBUG 5529 --- [task-scheduler-4] com.netflix.http4.NamedConnectionPool    : Releasing connection [{}->http://localhost:7101][null]
    2016-01-28 10:35:30.225 DEBUG 5529 --- [task-scheduler-4] com.netflix.http4.NamedConnectionPool    : Pooling connection [{}->http://localhost:7101][null]; keep alive indefinitely
    2016-01-28 10:35:30.225 DEBUG 5529 --- [task-scheduler-4] com.netflix.http4.NamedConnectionPool    : Notifying no-one, there are no waiting threads
    2016-01-28 10:35:30.227 ERROR 5529 --- [task-scheduler-4] o.s.c.n.m.atlas.AtlasMetricObserver      : Failed to write metrics to atlas

    org.springframework.web.client.RestClientException: Could not extract response: no suitable HttpMessageConverter found for response type [interface java.util.Map] and content type [text/plain;charset=UTF-8]
            at org.springframework.web.client.HttpMessageConverterExtractor.extractData(HttpMessageConverterExtractor.java:109) ~[spring-web-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
            at org.springframework.web.client.RestTemplate$ResponseEntityResponseExtractor.extractData(RestTemplate.java:835) ~[spring-web-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
            at org.springframework.web.client.RestTemplate$ResponseEntityResponseExtractor.extractData(RestTemplate.java:819) ~[spring-web-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
            at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:599) ~[spring-web-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
            at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:557) ~[spring-web-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
            at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:475) ~[spring-web-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
            at org.springframework.cloud.netflix.metrics.atlas.AtlasMetricObserver.sendMetricsBatch(AtlasMetricObserver.java:148) [spring-cloud-netflix-core-1.1.0.M4.jar!/:1.1.0.M4]
            at org.springframework.cloud.netflix.metrics.atlas.AtlasMetricObserver.update(AtlasMetricObserver.java:126) [spring-cloud-netflix-core-1.1.0.M4.jar!/:1.1.0.M4]
            at org.springframework.cloud.netflix.metrics.atlas.AtlasExporter.export(AtlasExporter.java:35) [spring-cloud-netflix-core-1.1.0.M4.jar!/:1.1.0.M4]
            at org.springframework.boot.actuate.metrics.export.MetricExporters$ExportRunner.run(MetricExporters.java:112) [spring-boot-actuator-1.3.1.RELEASE.jar!/:1.3.1.RELEASE]
            at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_66]
            at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_66]
            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_66]
            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_66]
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_66]
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_66]
            at java.lang.Thread.run(Thread.java:745) [na:1.8.0_66]

**Comment by dsyer** [comment]
Your Atlas server looks like it is barfing on metric names. Does it have a configurable setting for the maximum length? Ping @jkschneider.

**Comment by spencergibb** [comment]
ping @jkschneider

**Comment by andysworkshop** [comment]
An update from us. We've upgraded to Spring Cloud Brixton RC1 and Atlas 1.4.6. We see that on some of our test builds everything seems to work fine. In this good case Atlas is returning `200 OK` in response to the `POST` requests and the response content length is zero.

On another test build with the same versions we see the original error. The error is triggered because Atlas is returning `202 Accepted` instead of `200 OK` and also returns some json content with a `Content-Type` header of `text/plain`. This triggers the failure inside spring because the REST template is expecting to be able to create a `Map` class and has no `HttpMessageConverter` registered that can transform `text/plain` into a `Map`. Which is to be expected.

So the questions now are; what causes Atlas to return `202 Accepted`, is that an expected case and why does it return `text/plain` instead of `application/json` when the content is json?

**Comment by jkschneider** [comment]
@andysworkshop From [this test](https://github.com/Netflix/atlas/blob/729a87825e3023b576a16ce7d099c996649cd81d/atlas-webapi/src/test/scala/com/netflix/atlas/webapi/PublishApiSuite.scala#L105) and [this test](https://github.com/Netflix/atlas/blob/729a87825e3023b576a16ce7d099c996649cd81d/atlas-webapi/src/test/scala/com/netflix/atlas/webapi/PublishApiSuite.scala#L177), it appears that you will only receive a 202 in the event of a partial failure to process the metric. Does the response body contain any information that would indicate why the publish partially failed?

**Comment by andysworkshop** [comment]
I pulled the response body out of the debugger. Yes it's very informative:

    {
      "type": "partial",
      "message": ["value too long: name = [response.eureka.apps.TESTAPPS-SRV001.OURHOSTNAME01.uk.xy.com:testapps-srv001:25530] (82 > 80)",
        "value too long: name = [response.eureka.apps.TESTAPPS-SRV001.OURHOSTNAME01.uk.xy.com:testapps-srv001:15530] (82 > 80)"
      ]
    }

So I had a look around the source code and found this in [reference.conf](https://github.com/Netflix/atlas/blob/master/atlas-webapi/src/main/resources/reference.conf):

        {
          class = "com.netflix.atlas.core.validation.ValueLengthRule"
          min-length = 1
          max-length = 80
        },

Copying that into the same section in the `memory.conf` file used to launch atlas and increasing `max-length` to 100 seemed to make the problem go away.

Have I caused any unintended consequences by increasing that value?

To the Spring team: presumably there are other possible scenarios in which Atlas will return json as text/plain. Is there a workaround for the framework not being able to handle that or are you looking to Atlas to report the correct content type (I get from the source code that they use text/plain so that browsers are likely to render it)

**Comment by winterer** [comment]
Is there any progress on this issue yet?

I'm facing a similiar problem when using special characters in a Spring MVC request mapping (e.g. a regular expression). Spring Actuator's `MetricsFilter` uses the best matching pattern (`HandlerMapping.BEST_MATCHING_PATTERN_ATTRIBUTE`) as metric name when reporting a MVC request. This metric name ends up as name tag value when the metrics are reported to Atlas - which does not accept other characters than `[a-zA-Z._-]` (or so) by default.

**Comment by spencergibb** [comment]
ping @jkschneider

**Comment by jkschneider** [comment]
With a locally running version of Atlas 1.4.6, this quick integration test proves out the original issue:

```java
@Test
public void tooLongMetricSent() {
	RestTemplate restTemplate = new RestTemplate();

	AtlasMetricObserverConfigBean config = new AtlasMetricObserverConfigBean();
	config.setBatchSize(2);
	config.setUri("http://localhost:7101/");

	AtlasMetricObserver obs = new AtlasMetricObserver(config, restTemplate, BasicTagList.EMPTY);
	
	List<Metric> metrics = generateMetrics(1); // some good metrics
	
	metrics.add(new Metric(new MonitorConfig.Builder("aSupercalifragilisticexpialidociousReallyQuiteAtrociousMetricNameButSoundsPrecocious").build(),
			System.currentTimeMillis(), 1)); // a bad metric (value too long)
	
	obs.update(metrics);
}
```

**Comment by jkschneider** [comment]
[Atlas 1.4.7](https://github.com/Netflix/atlas/wiki/Getting-Started) fixes the content-type on partial failure (HTTP 202) responses, and #1314 logs the partial failure reasons.
