### ISSUE TITLE
NullPointerException with Grails

### ISSUE THREAD

**Issue by todoubaba** [spring-cloud/spring-cloud-netflix#803]
When using zuul in grails 3.1.0, NPE is thrown:
```
java.lang.NullPointerException: null
	at org.springframework.cloud.netflix.metrics.DefaultMetricsTagProvider.httpRequestTags(DefaultMetricsTagProvider.java:64) ~[spring-cloud-netflix-core-1.1.0.M4.jar:1.1.0.M4]
	at org.springframework.cloud.netflix.metrics.MetricsHandlerInterceptor.recordMetric(MetricsHandlerInterceptor.java:85) ~[spring-cloud-netflix-core-1.1.0.M4.jar:1.1.0.M4]
	at org.springframework.cloud.netflix.metrics.MetricsHandlerInterceptor.afterCompletion(MetricsHandlerInterceptor.java:72) ~[spring-cloud-netflix-core-1.1.0.M4.jar:1.1.0.M4]
	at org.springframework.web.servlet.HandlerExecutionChain.triggerAfterCompletion(HandlerExecutionChain.java:170) ~[spring-webmvc-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1045) [spring-webmvc-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:971) [spring-webmvc-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893) [spring-webmvc-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:969) [spring-webmvc-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:860) [spring-webmvc-4.2.4.RELEASE.jar:4.2.4.RELEASE]
```
It seems that grails does not set the `BEST_MATCHING_PATTERN_ATTRIBUTE` in request.
Code at https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/metrics/DefaultMetricsTagProvider.java#L64 should check whether `request
				.getAttribute(HandlerMapping.BEST_MATCHING_PATTERN_ATTRIBUTE)` is null.

**Comment by dsyer** [comment]
That code is only reachable from a `HandlerInterceptor` so it can only be coming from a Spring `DispatcherServlet`. If Grails is not setting that attribute it probably needs to get fixed there, I would think. We can probably do something defensive here in the meantime.

**Comment by todoubaba** [comment]
Thank you for the quick fix :+1:

**Comment by drse** [comment]
Running into same issue with grails `3.1.0.RC1` and `spring-cloud-netflix:1.1.0.M5`. Seems `uri` is still null after `request.getPathInfo();` and requires another null check.
