### ISSUE TITLE
Basic auth for Eureka clients broken on Brixton.BUILD-SNAPSHOT

### ISSUE THREAD

**Issue by jordanjennings** [spring-cloud/spring-cloud-netflix#849]
Eureka clients don't seem to be respecting basic auth starting within the last day. My configuration looks like:

```
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:password@dev-eureka.company.com:80/eureka/
```

At startup (and every time the application tries to connect to eureka) I get a stack trace like:

```
2016-02-23 18:23:15.844  WARN 16612 --- [nfoReplicator-0] c.n.discovery.InstanceInfoReplicator     : There was a problem with the instance info replicator

com.netflix.discovery.shared.transport.TransportException: Cannot execute request on any known server
	at com.netflix.discovery.shared.transport.decorator.RetryableEurekaHttpClient.execute(RetryableEurekaHttpClient.java:111) ~[eureka-client-1.4.1.jar:1.4.1]
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.register(EurekaHttpClientDecorator.java:56) ~[eureka-client-1.4.1.jar:1.4.1]
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$1.execute(EurekaHttpClientDecorator.java:59) ~[eureka-client-1.4.1.jar:1.4.1]
	at com.netflix.discovery.shared.transport.decorator.SessionedEurekaHttpClient.execute(SessionedEurekaHttpClient.java:77) ~[eureka-client-1.4.1.jar:1.4.1]
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.register(EurekaHttpClientDecorator.java:56) ~[eureka-client-1.4.1.jar:1.4.1]
	at com.netflix.discovery.DiscoveryClient.register(DiscoveryClient.java:771) ~[eureka-client-1.4.1.jar:1.4.1]
	at com.netflix.discovery.InstanceInfoReplicator.run(InstanceInfoReplicator.java:103) ~[eureka-client-1.4.1.jar:1.4.1]
	at com.netflix.discovery.InstanceInfoReplicator$1.run(InstanceInfoReplicator.java:87) [eureka-client-1.4.1.jar:1.4.1]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_60]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_60]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_60]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_60]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_60]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_60]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_60]

```

When I debug the code, I can see that the call to Eureka is returning a 401. So somewhere along the way the credentials are being lost. If I revert to Brixton.M4 then it starts working again.

**Comment by dsyer** [comment]
This is going to be a major headache because netflix have completely re-written the eureka client and it is dropping all information from the service URL authority (i.e. host, port and credentials) except the host and port.

**Comment by jordanjennings** [comment]
Awesome, thanks for getting it taken care of so quickly!
