### ISSUE TITLE
Cannot inject DiscoveryClient

### ISSUE THREAD

**Issue by spolnik** [spring-cloud/spring-cloud-netflix#863]
Project to reproduce:
https://github.com/spolnik/trading-office/tree/eureka_client_discovery_client_issue

command to run: `./gradlew :allocation-enricher:bootRun`
```
Caused by: java.lang.NullPointerException: null
	at com.netflix.discovery.DiscoveryClient$$FastClassBySpringCGLIB$$a84c8cb4.invoke(<generated>) ~[eureka-client-1.1.147.jar:1.1.147]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:720) ~[spring-aop-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) ~[spring-aop-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.aop.support.DelegatingIntroductionInterceptor.doProceed(DelegatingIntroductionInterceptor.java:133) ~[spring-aop-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.aop.support.DelegatingIntroductionInterceptor.invoke(DelegatingIntroductionInterceptor.java:121) ~[spring-aop-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:655) ~[spring-aop-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at com.netflix.discovery.DiscoveryClient$$EnhancerBySpringCGLIB$$e53baf99.getInstancesByVipAddress(<generated>) ~[eureka-client-1.1.147.jar:1.1.147]
	at org.springframework.cloud.netflix.eureka.EurekaDiscoveryClient.getInstances(EurekaDiscoveryClient.java:85) ~[spring-cloud-netflix-core-1.0.7.RELEASE.jar:1.0.7.RELEASE]
	at com.trading.AllocationEnricherApplication.counterpartyApi(AllocationEnricherApplication.java:56) [main/:na]
	at com.trading.AllocationEnricherApplication$$EnhancerBySpringCGLIB$$a9505b1b.CGLIB$counterpartyApi$4(<generated>) ~[main/:na]
	at com.trading.AllocationEnricherApplication$$EnhancerBySpringCGLIB$$a9505b1b$$FastClassBySpringCGLIB$$a89d3806.invoke(<generated>) ~[main/:na]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228) ~[spring-core-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:355) ~[spring-context-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at com.trading.AllocationEnricherApplication$$EnhancerBySpringCGLIB$$a9505b1b.counterpartyApi(<generated>) ~[main/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_60]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_60]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_60]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_60]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162) ~[spring-beans-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	... 47 common frames omitted

2016-03-01 19:50:08.351  WARN 14667 --- [           main] o.s.boot.SpringApplication               : Error handling failed (Error creating bean with name 'org.springframework.cloud.netflix.eureka.EurekaDiscoveryClientConfiguration': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.springframework.cloud.netflix.eureka.EurekaInstanceConfigBean org.springframework.cloud.netflix.eureka.EurekaDiscoveryClientConfiguration.instanceConfig; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'eurekaInstanceConfigBean' defined in class path resource [org/springframework/cloud/netflix/eureka/EurekaClientAutoConfiguration.class]: Initialization of bean failed; nested exception is java.lang.IllegalStateException: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@10a9d961 has not been refreshed yet)
2016-03-01 19:50:08.353  INFO 14667 --- [       Thread-1] s.c.a.AnnotationConfigApplicationContext : Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@3d121db3: startup date [Tue Mar 01 19:50:04 CET 2016]; root of context hierarchy
:allocation-enricher:bootRun FAILED
```

**Comment by spencergibb** [comment]
A couple of things. Spring Boot 1.3.x and Spring Cloud Angel.x is use at your own risk. Angel specifically supports Boot 1.2.x. 

2nd, in `AllocationEnricherApplication` you are trying to use Eureka before it is initialized. There are two ways to do what you are wanting: 1) inject the `RestTemplate` created by Spring Cloud and wired with ribbon into `CounterpartyApiClient` and do `restTemplate.getForObject("http://COUNTERPARTY-SERVICE/api/exchange/mic/%s, Exchange.class);` or 2) inject a `LoadBalancerClient` and call `choose("COUNTERPARTY-SERVICE")` in `CounterpartyApiClient`.

**Comment by spolnik** [comment]
Hey,
after switching to Brixton.M5 && using approach number 1) (Injecting RestTemplate) everything works nicely!

Thank you a lot for help with that
