### ISSUE TITLE
Ribbon client errors never handled?

### ISSUE THREAD

**Issue by OrangeDog** [spring-cloud/spring-cloud-netflix#940]
As far as I can tell, a `@LoadBalanced RestTemplate` never feeds back any error information to the load balancer, making most of the Ribbon features unusable.

Circuit breakers are never tripped, `AvailabilityFilteringRule` (the default) and `RetryRule` are essentially useless - behaving exactly the same as `RoundRobinRule`, and the monitors' stats are never updated.
I can't see that response time stats are ever updated either, making `WeightedResponseTimeRule` likewise identical to `RoundRobinRule`.

The only location where there's currently an opportunity to get this information is `RibbonHttpRequest.executeInternal`, but that just passes back out to generic `RestTemplate` code that has no ribbon knowledge.
The `RestClient` does have an `HttpClientLoadBalancerErrorHandler` as a retry handler, but this is never called either.
In fact none of the `noteX` methods in `LoadBalancerContext` are ever called in any circumstances I can find.

These are the sort of exceptions I expect to be interacting with the load balancers:
```
org.springframework.web.client.ResourceAccessException: I/O error on POST request for "https://ribbon-client":com.sun.jersey.api.client.ClientHandlerException: org.apache.http.conn.HttpHostConnectException: Connect to localhost:7443 [localhost/127.0.0.1] failed: Connection refused: connect; nested exception is java.io.IOException: com.sun.jersey.api.client.ClientHandlerException: org.apache.http.conn.HttpHostConnectException: Connect to localhost:7443 [localhost/127.0.0.1] failed: Connection refused: connect
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:607) ~[spring-web-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:572) ~[spring-web-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:523) ~[spring-web-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at MyController ~[classes/:na]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:648) [tomcat-embed-core-8.0.28.jar:8.0.28]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846) [spring-webmvc-4.2.3.RELEASE.jar:4.2.3.RELEASE]
    ... 102 frames omitted
Caused by: java.io.IOException: com.sun.jersey.api.client.ClientHandlerException: org.apache.http.conn.HttpHostConnectException: Connect to localhost:7443 [localhost/127.0.0.1] failed: Connection refused: connect
	at org.springframework.cloud.netflix.ribbon.RibbonClientHttpRequestFactory$RibbonHttpRequest.executeInternal(RibbonClientHttpRequestFactory.java:125) ~[spring-cloud-netflix-core-1.0.7.RELEASE.jar:1.0.7.RELEASE]
	at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:53) ~[spring-web-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.http.client.InterceptingClientHttpRequest$RequestExecution.execute(InterceptingClientHttpRequest.java:94) ~[spring-web-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at MyAuthenticator.intercept ~[classes/:na]
	at org.springframework.http.client.InterceptingClientHttpRequest$RequestExecution.execute(InterceptingClientHttpRequest.java:84) ~[spring-web-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.http.client.InterceptingClientHttpRequest.executeInternal(InterceptingClientHttpRequest.java:69) ~[spring-web-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:48) ~[spring-web-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:53) ~[spring-web-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:596) ~[spring-web-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	... 127 common frames omitted
Caused by: com.sun.jersey.api.client.ClientHandlerException: org.apache.http.conn.HttpHostConnectException: Connect to localhost:7443 [localhost/127.0.0.1] failed: Connection refused: connect
	at com.sun.jersey.client.apache4.ApacheHttpClient4Handler.handle(ApacheHttpClient4Handler.java:184) ~[jersey-apache-client4-1.11.jar:1.11]
	at com.sun.jersey.api.client.Client.handle(Client.java:648) ~[jersey-client-1.13.jar:1.13]
	at com.sun.jersey.api.client.WebResource.handle(WebResource.java:680) ~[jersey-client-1.13.jar:1.13]
	at com.sun.jersey.api.client.WebResource.access$200(WebResource.java:74) ~[jersey-client-1.13.jar:1.13]
	at com.sun.jersey.api.client.WebResource$Builder.post(WebResource.java:568) ~[jersey-client-1.13.jar:1.13]
	at com.netflix.niws.client.http.RestClient.execute(RestClient.java:621) ~[ribbon-httpclient-2.0.0.jar:2.0.0]
	at com.netflix.niws.client.http.RestClient.execute(RestClient.java:527) ~[ribbon-httpclient-2.0.0.jar:2.0.0]
	at org.springframework.cloud.netflix.ribbon.RibbonClientHttpRequestFactory$RibbonHttpRequest.executeInternal(RibbonClientHttpRequestFactory.java:122) ~[spring-cloud-netflix-core-1.0.7.RELEASE.jar:1.0.7.RELEASE]
	... 135 common frames omitted
Caused by: org.apache.http.conn.HttpHostConnectException: Connect to localhost:7443 [localhost/127.0.0.1] failed: Connection refused: connect
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:151) ~[httpclient-4.5.1.jar:4.5.1]
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353) ~[httpclient-4.5.1.jar:4.5.1]
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380) ~[httpclient-4.5.1.jar:4.5.1]
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236) ~[httpclient-4.5.1.jar:4.5.1]
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184) ~[httpclient-4.5.1.jar:4.5.1]
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88) ~[httpclient-4.5.1.jar:4.5.1]
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[httpclient-4.5.1.jar:4.5.1]
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184) ~[httpclient-4.5.1.jar:4.5.1]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:117) ~[httpclient-4.5.1.jar:4.5.1]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55) ~[httpclient-4.5.1.jar:4.5.1]
	at com.sun.jersey.client.apache4.ApacheHttpClient4Handler.handle(ApacheHttpClient4Handler.java:170) ~[jersey-apache-client4-1.11.jar:1.11]
	... 142 common frames omitted
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method) ~[na:1.8.0_65]
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:85) ~[na:1.8.0_65]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[na:1.8.0_65]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_65]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_65]
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172) ~[na:1.8.0_65]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_65]
	at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_65]
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:337) ~[httpclient-4.5.1.jar:4.5.1]
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:134) ~[httpclient-4.5.1.jar:4.5.1]
	... 152 common frames omitted
```

Perhaps I've missed something in my config?
The Apache HttpClient is configured and shared with other (non-balanced) components elsewhere.

```
  @RibbonClient(name = "ribbon-client", configuration = CoreRibbonConfig.class)
  public static class CoreRibbonConfig {

    @Bean
    public IClientConfig ribbonClientConfig() {
      IClientConfig config = new DefaultClientConfigImpl();
      config.loadProperties("ribbon-client");
      return config;
    }

    @Bean
    public ILoadBalancer ribbonLoadBalancer(IClientConfig config) {
      AbstractLoadBalancerRule rule = new AvailabilityFilteringRule();
      rule.initWithNiwsConfig(config);

      AbstractServerList<Server> serverList = new ConfigurationBasedServerList();
      serverList.initWithNiwsConfig(config);

      return LoadBalancerBuilder.newBuilder()
          .withClientConfig(config)
          .withPing(new NoOpPing())
          .withRule(rule)
          .buildFixedServerListLoadBalancer(serverList.getInitialListOfServers());
    }

    @Bean
    @SuppressWarnings("deprecation")
    public RestClient ribbonRestClient(IClientConfig config, ILoadBalancer loadBalancer, HttpClient httpClient) {
      RestClient client = new RestClient(config);
      client.setJerseyClient(new ApacheHttpClient4(new ApacheHttpClient4Handler(httpClient, null, false)));
      client.setLoadBalancer(loadBalancer);
      Monitors.registerObject("Client_" + client.getClientName(), client);
      return client;
    }

  }
```

**Comment by tkvangorder** [comment]
The load balanced RestTemplate only uses the ribbon configuration for picking a server. It does not (yet) use Ribbon's retry mechanism. See https://github.com/spring-cloud/spring-cloud-netflix/issues/648 for details.

I can save you some time because I have been down this road.

We ended up overriding Spring Cloud's RibbonClientHttpRequestFactory to serve up a modified version of the RibbonHttpRequest that uses "executeWithLoadBalancer". I can verify that this does use Ribbon's retry mechanisms. I am hoping to get another pull request together for this issue along with integration tests that exercise the retry mechanism. 

A secondary issue you are likely to run into is there was  not an easy way to change the RetryHandler in the RibbonClientConfiguriation. This too has been addressed by the Spring Team (thanks Spencer!) via this issue: https://github.com/spring-cloud/spring-cloud-netflix/issues/931

This fix will allow you to specify the AvailabilityFilteringRule (or you might want to use BestAvailableRule) for your client. The BestAvailableRule will pick servers based on lowest concurrent connections and it skips servers that are in circuit breaker state. Hope that helps you! There was not a lot of documentation on the retry stuff and most of this was learned by trial an error.

**Comment by OrangeDog** [comment]
Closing as duplicate.

**Comment by OrangeDog** [comment]
I see that v1.1.0 calls `RibbonStatsRecorder.recordStats` in `RibbonHttpRequest`.

Is that going to allow `AvailabilityFilteringRule` and `WeightedResponseTimeRule` to work?
I assume it will still have no effect on retry logic.

**Comment by OrangeDog** [comment]
I see that v1.1.0 calls `RibbonStatsRecorder.recordStats` in `RibbonHttpRequest`.
That makes `AvailabilityFilteringRule` and `WeightedResponseTimeRule` (and servo stats) work, but not `RetryRule`.
